#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(59)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
a->printPretty();
std::cout << (a->remove(305)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
a->printPretty();
*a=*c;
std::cout << (a->insert(18)) << std::endl;
*a=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
d->printPretty();
std::cout << (e->insert(244)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
*e=*a;
std::cout << (b->insert(129)) << std::endl;
*c=*e;
std::cout << (b->insert(129)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
*c=*d;
b->printPretty();
*d=*b;
std::cout << (d->insert(129)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (c->insert(75)) << std::endl;
d->printPretty();
std::cout << (d->insert(129)) << std::endl;
d->printPretty();
e->printPretty();
e->printPretty();
std::cout << (d->insert(129)) << std::endl;
e->printPretty();
std::cout << (c->insert(341)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
std::cout << (d->remove(437)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
d->printPretty();
std::cout << (b->remove(218)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
*b=*e;
*a=*e;
std::cout << (e->insert(241)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
*d=*d;
*e=*b;
std::cout << (b->insert(158)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
e->printPretty();
std::cout << (c->insert(75)) << std::endl;
d->printPretty();
std::cout << (a->insert(499)) << std::endl;
std::cout << (a->insert(218)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (a->insert(331)) << std::endl;
*b=*e;
std::cout << (c->insert(200)) << std::endl;
*d=*a;
std::cout << (b->insert(73)) << std::endl;
std::cout << (d->remove(324)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
*c=*c;
std::cout << (e->insert(129)) << std::endl;
b->printPretty();
std::cout << (c->remove(129)) << std::endl;
*b=*b;
*a=*a;
std::cout << (b->insert(129)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (b->insert(296)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (b->insert(317)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(299)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (c->remove(354)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
std::cout << (c->remove(223)) << std::endl;
std::cout << (d->remove(499)) << std::endl;
e->printPretty();
std::cout << (e->remove(416)) << std::endl;
b->printPretty();
*d=*d;
e->printPretty();
a->printPretty();
std::cout << (b->insert(493)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (b->remove(218)) << std::endl;
*a=*d;
std::cout << (c->insert(229)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
e->printPretty();
std::cout << (e->insert(129)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
std::cout << (b->insert(288)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (b->remove(307)) << std::endl;
b->printPretty();
std::cout << (e->insert(295)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(288)) << std::endl;
e->printPretty();
std::cout << (c->insert(151)) << std::endl;
std::cout << (b->remove(212)) << std::endl;
std::cout << (b->remove(490)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
*c=*d;
std::cout << (a->insert(37)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
c->printPretty();
std::cout << (d->insert(232)) << std::endl;
*e=*b;
std::cout << (b->remove(425)) << std::endl;
*c=*c;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (b->insert(288)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
std::cout << (a->remove(331)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
e->printPretty();
*b=*d;
std::cout << (c->insert(276)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (c->remove(238)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
std::cout << (b->remove(232)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
c->printPretty();
std::cout << (b->remove(216)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(65)) << std::endl;
std::cout << (e->remove(137)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (b->insert(421)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(330)) << std::endl;
*c=*a;
std::cout << (a->remove(37)) << std::endl;
*d=*c;
std::cout << (b->insert(421)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
*e=*e;
std::cout << (b->remove(266)) << std::endl;
*c=*c;
std::cout << (c->remove(129)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (b->remove(214)) << std::endl;
d->printPretty();
std::cout << (b->insert(493)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
e->printPretty();
std::cout << (a->insert(218)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
b->printPretty();
std::cout << (c->insert(357)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
std::cout << (d->remove(120)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
b->printPretty();
std::cout << (a->remove(218)) << std::endl;
c->printPretty();
std::cout << (b->remove(46)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
std::cout << (d->insert(157)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
*b=*b;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
*b=*a;
std::cout << (b->insert(465)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
std::cout << (d->remove(274)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
c->printPretty();
std::cout << (a->remove(129)) << std::endl;
a->printPretty();
std::cout << (b->remove(465)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (d->remove(465)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
*e=*e;
e->printPretty();
d->printPretty();
*c=*c;
std::cout << (e->remove(425)) << std::endl;
e->printPretty();
std::cout << (b->remove(129)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
*e=*b;
std::cout << (d->remove(129)) << std::endl;
std::cout << (a->insert(240)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (a->insert(240)) << std::endl;
*d=*d;
std::cout << (c->insert(357)) << std::endl;
d->printPretty();
a->printPretty();
d->printPretty();
std::cout << (b->remove(306)) << std::endl;
std::cout << (e->insert(442)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
std::cout << (a->insert(351)) << std::endl;
*b=*d;
*a=*d;
std::cout << (b->remove(330)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (e->insert(306)) << std::endl;
std::cout << (e->insert(35)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
*d=*b;
std::cout << (c->insert(195)) << std::endl;
b->printPretty();
std::cout << (c->remove(101)) << std::endl;
*b=*e;
std::cout << (a->remove(328)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
c->printPretty();
std::cout << (e->remove(156)) << std::endl;
a->printPretty();
std::cout << (d->remove(258)) << std::endl;
*a=*a;
std::cout << (b->remove(164)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (d->remove(346)) << std::endl;
std::cout << (a->remove(366)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
d->printPretty();
std::cout << (e->insert(41)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
c->printPretty();
std::cout << (e->insert(192)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
*e=*d;
std::cout << (a->remove(338)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (c->insert(37)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
c->printPretty();
std::cout << (e->insert(37)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
*e=*c;
*a=*a;
std::cout << (b->remove(399)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
a->printPretty();
std::cout << (b->insert(35)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (b->remove(221)) << std::endl;
c->printPretty();
std::cout << (e->insert(479)) << std::endl;
*c=*e;
*e=*c;
std::cout << (b->remove(55)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
e->printPretty();
std::cout << (c->insert(451)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (d->remove(295)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->insert(230)) << std::endl;
std::cout << (d->insert(369)) << std::endl;
e->printPretty();
a->printPretty();
c->printPretty();
std::cout << (e->insert(479)) << std::endl;
*d=*b;
std::cout << (b->insert(297)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (d->insert(14)) << std::endl;
*c=*a;
std::cout << (d->insert(179)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
b->printPretty();
std::cout << (c->insert(14)) << std::endl;
*d=*b;
std::cout << (c->remove(451)) << std::endl;
c->printPretty();
std::cout << (d->remove(357)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
std::cout << (e->insert(37)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (e->insert(218)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
std::cout << (a->remove(452)) << std::endl;
std::cout << (c->insert(37)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
c->printPretty();
std::cout << (d->remove(218)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
*d=*d;
std::cout << (a->remove(149)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->remove(124)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
e->printPretty();
std::cout << (e->insert(14)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
b->printPretty();
std::cout << (a->remove(357)) << std::endl;
*b=*b;
std::cout << (d->insert(394)) << std::endl;
b->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
std::cout << (e->remove(263)) << std::endl;
d->printPretty();
c->printPretty();
*a=*d;
std::cout << (a->insert(297)) << std::endl;
std::cout << (a->remove(42)) << std::endl;
*c=*e;
std::cout << (b->remove(357)) << std::endl;
*e=*b;
std::cout << (b->remove(392)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
*c=*d;
std::cout << (d->remove(113)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
*e=*d;
*e=*d;
std::cout << (c->remove(385)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
*e=*d;
std::cout << (b->insert(144)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
d->printPretty();
std::cout << (a->insert(351)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
a->printPretty();
std::cout << (e->insert(398)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (d->remove(429)) << std::endl;
std::cout << (c->insert(316)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
e->printPretty();
c->printPretty();
b->printPretty();
std::cout << (c->remove(394)) << std::endl;
std::cout << (c->insert(37)) << std::endl;
*c=*d;
std::cout << (a->remove(470)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
std::cout << (e->insert(37)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
e->printPretty();
std::cout << (d->insert(207)) << std::endl;
std::cout << (d->remove(401)) << std::endl;
std::cout << (d->remove(23)) << std::endl;
*a=*a;
*b=*c;
std::cout << (c->insert(268)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
b->printPretty();
std::cout << (d->remove(328)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
b->printPretty();
std::cout << (d->insert(8)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
*e=*e;
std::cout << (d->remove(451)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (d->remove(436)) << std::endl;
std::cout << (c->insert(325)) << std::endl;
*a=*d;
std::cout << (e->insert(135)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (e->insert(297)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(297)) << std::endl;
std::cout << (c->insert(37)) << std::endl;
*a=*e;
std::cout << (b->insert(417)) << std::endl;
b->printPretty();
*a=*e;
*d=*d;
std::cout << (d->remove(27)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
e->printPretty();
std::cout << (d->insert(193)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(241)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
b->printPretty();
std::cout << (a->remove(451)) << std::endl;
*c=*b;
std::cout << (b->insert(14)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (d->remove(14)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
*e=*d;
c->printPretty();
d->printPretty();
e->printPretty();
std::cout << (b->remove(310)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (d->insert(259)) << std::endl;
std::cout << (c->remove(181)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
b->printPretty();
std::cout << (c->insert(269)) << std::endl;
std::cout << (b->insert(342)) << std::endl;
d->printPretty();
std::cout << (a->insert(37)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
a->printPretty();
std::cout << (d->insert(255)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
c->printPretty();
std::cout << (c->remove(227)) << std::endl;
std::cout << (c->insert(451)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (e->insert(193)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
std::cout << (b->insert(297)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
*d=*a;
std::cout << (d->insert(370)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
*b=*c;
b->printPretty();
*b=*e;
std::cout << (a->remove(37)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (d->insert(125)) << std::endl;
*c=*c;
std::cout << (e->insert(238)) << std::endl;
d->printPretty();
b->printPretty();
c->printPretty();
e->printPretty();
std::cout << (d->insert(269)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (a->insert(227)) << std::endl;
b->printPretty();
std::cout << (d->insert(101)) << std::endl;
*a=*d;
b->printPretty();
*a=*d;
std::cout << (c->insert(135)) << std::endl;
std::cout << (a->remove(267)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
std::cout << (d->remove(141)) << std::endl;
a->printPretty();
std::cout << (d->insert(125)) << std::endl;
*e=*d;
std::cout << (b->insert(193)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
d->printPretty();
std::cout << (c->insert(451)) << std::endl;
*b=*e;
std::cout << (b->remove(411)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
*c=*a;
std::cout << (c->remove(37)) << std::endl;
*b=*d;
std::cout << (c->remove(296)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
d->printPretty();
std::cout << (b->remove(135)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (d->insert(269)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (d->insert(405)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->insert(37)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
*b=*c;
std::cout << (b->remove(125)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
*a=*a;
*b=*c;
b->printPretty();
std::cout << (c->insert(451)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
a->printPretty();
std::cout << (d->remove(134)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (a->remove(275)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (d->remove(279)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
c->printPretty();
d->printPretty();
*a=*e;
std::cout << (d->insert(221)) << std::endl;
*d=*e;
std::cout << (b->insert(296)) << std::endl;
std::cout << (d->insert(26)) << std::endl;
std::cout << (a->insert(323)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
c->printPretty();
std::cout << (a->insert(269)) << std::endl;
std::cout << (b->remove(135)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
e->printPretty();
std::cout << (d->remove(26)) << std::endl;
std::cout << (d->remove(336)) << std::endl;
*a=*d;
std::cout << (e->remove(203)) << std::endl;
b->printPretty();
*d=*a;
*d=*a;
std::cout << (e->remove(235)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
c->printPretty();
std::cout << (b->remove(101)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
std::cout << (a->remove(371)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (c->remove(154)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
c->printPretty();
std::cout << (c->insert(83)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->insert(135)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (e->remove(86)) << std::endl;
*a=*c;
b->printPretty();
a->printPretty();
d->printPretty();
std::cout << (e->insert(125)) << std::endl;
std::cout << (d->insert(288)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
*d=*e;
*e=*c;
std::cout << (e->insert(463)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (d->insert(288)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (d->insert(135)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
d->printPretty();
std::cout << (b->remove(283)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
*c=*c;
*c=*d;
std::cout << (a->remove(83)) << std::endl;
*e=*b;
std::cout << (b->remove(101)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
std::cout << (c->insert(457)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
d->printPretty();
std::cout << (d->remove(310)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
*b=*d;
std::cout << (a->remove(157)) << std::endl;
std::cout << (a->remove(233)) << std::endl;
d->printPretty();
std::cout << (c->remove(308)) << std::endl;
std::cout << (a->insert(349)) << std::endl;
d->printPretty();
std::cout << (a->remove(349)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
return 0;
}
