#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(160)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(47)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
a->printPretty();
std::cout << (b->remove(226)) << std::endl;
e->printPretty();
std::cout << (a->remove(136)) << std::endl;
c->printPretty();
e->printPretty();
d->printPretty();
b->printPretty();
*e=*d;
*c=*c;
*d=*b;
std::cout << (c->remove(332)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
*c=*b;
*e=*d;
std::cout << (e->remove(421)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
*a=*b;
std::cout << (d->insert(462)) << std::endl;
d->printPretty();
std::cout << (b->remove(465)) << std::endl;
*c=*b;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (e->remove(365)) << std::endl;
*e=*a;
std::cout << (d->insert(462)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
*b=*c;
std::cout << (a->insert(7)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
e->printPretty();
std::cout << (c->remove(291)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (a->remove(146)) << std::endl;
*d=*c;
std::cout << (a->remove(7)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
c->printPretty();
std::cout << (d->insert(481)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
*c=*a;
std::cout << (e->remove(331)) << std::endl;
*e=*e;
std::cout << (c->remove(275)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
d->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
*a=*b;
std::cout << (a->insert(406)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
b->printPretty();
std::cout << (d->insert(481)) << std::endl;
*e=*e;
std::cout << (a->remove(406)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (d->remove(122)) << std::endl;
*b=*e;
std::cout << (e->insert(237)) << std::endl;
a->printPretty();
std::cout << (a->insert(497)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(96)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
*c=*d;
*d=*b;
std::cout << (d->remove(96)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (d->insert(192)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (d->remove(192)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (e->remove(63)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
e->printPretty();
std::cout << (a->remove(154)) << std::endl;
e->printPretty();
e->printPretty();
d->printPretty();
std::cout << (b->remove(96)) << std::endl;
std::cout << (b->insert(185)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
c->printPretty();
std::cout << (e->remove(416)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
*a=*c;
b->printPretty();
c->printPretty();
std::cout << (a->insert(163)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
std::cout << (e->insert(497)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
*d=*e;
std::cout << (b->insert(197)) << std::endl;
e->printPretty();
std::cout << (c->remove(17)) << std::endl;
d->printPretty();
std::cout << (e->remove(497)) << std::endl;
*e=*c;
std::cout << (a->insert(394)) << std::endl;
a->printPretty();
std::cout << (e->remove(295)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
c->printPretty();
*c=*d;
*b=*e;
std::cout << (c->insert(280)) << std::endl;
d->printPretty();
std::cout << (a->insert(394)) << std::endl;
*d=*a;
std::cout << (c->remove(354)) << std::endl;
std::cout << (c->insert(497)) << std::endl;
c->printPretty();
std::cout << (d->insert(390)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (d->insert(163)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
std::cout << (d->insert(135)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->insert(75)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
d->printPretty();
std::cout << (b->insert(25)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(284)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (d->remove(9)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
*a=*c;
std::cout << (b->remove(147)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (d->remove(323)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->remove(204)) << std::endl;
*e=*d;
std::cout << (e->insert(390)) << std::endl;
*e=*d;
std::cout << (c->insert(497)) << std::endl;
*e=*e;
std::cout << (b->insert(46)) << std::endl;
*d=*b;
std::cout << (e->remove(135)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (b->remove(1)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
std::cout << (b->insert(470)) << std::endl;
c->printPretty();
std::cout << (d->remove(220)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (c->remove(497)) << std::endl;
c->printPretty();
std::cout << (a->insert(497)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
*e=*a;
*b=*c;
std::cout << (b->remove(286)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (c->insert(334)) << std::endl;
*e=*a;
std::cout << (a->insert(73)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
b->printPretty();
std::cout << (e->remove(73)) << std::endl;
*c=*d;
*e=*b;
std::cout << (b->remove(472)) << std::endl;
std::cout << (b->remove(473)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
std::cout << (c->insert(413)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
*d=*a;
std::cout << (d->insert(467)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
*e=*b;
std::cout << (c->insert(413)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
*c=*d;
std::cout << (a->remove(73)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
a->printPretty();
std::cout << (d->remove(292)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
e->printPretty();
*b=*b;
std::cout << (b->insert(188)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
*e=*b;
*e=*a;
std::cout << (c->insert(73)) << std::endl;
std::cout << (d->insert(248)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
b->printPretty();
std::cout << (b->insert(188)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
*e=*d;
std::cout << (d->remove(49)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
*c=*e;
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
*d=*a;
std::cout << (e->remove(153)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (d->remove(324)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
*b=*b;
std::cout << (b->insert(473)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
*b=*d;
std::cout << (c->remove(324)) << std::endl;
a->printPretty();
b->printPretty();
*c=*c;
std::cout << (b->insert(37)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (b->insert(37)) << std::endl;
std::cout << (b->insert(43)) << std::endl;
e->printPretty();
std::cout << (b->remove(61)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
*b=*a;
std::cout << (b->insert(292)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
*b=*a;
a->printPretty();
*c=*b;
*c=*d;
c->printPretty();
std::cout << (c->insert(88)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (b->insert(41)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
*c=*e;
std::cout << (b->insert(388)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (d->remove(90)) << std::endl;
b->printPretty();
std::cout << (d->remove(168)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
std::cout << (d->insert(437)) << std::endl;
*c=*a;
std::cout << (b->remove(274)) << std::endl;
*b=*a;
b->printPretty();
e->printPretty();
std::cout << (a->remove(266)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
c->printPretty();
std::cout << (e->insert(145)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
*e=*e;
std::cout << (a->remove(4)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (e->remove(134)) << std::endl;
b->printPretty();
std::cout << (c->remove(41)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
c->printPretty();
std::cout << (b->remove(41)) << std::endl;
std::cout << (d->remove(437)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(277)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
*c=*a;
*b=*a;
*a=*b;
std::cout << (b->remove(434)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
e->printPretty();
std::cout << (a->remove(427)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
a->printPretty();
std::cout << (c->remove(302)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
c->printPretty();
std::cout << (c->insert(421)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (e->insert(461)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
d->printPretty();
std::cout << (c->remove(421)) << std::endl;
c->printPretty();
std::cout << (b->insert(255)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
std::cout << (d->remove(202)) << std::endl;
*e=*e;
std::cout << (b->insert(255)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
*b=*c;
std::cout << (e->insert(236)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(120)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(455)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (c->insert(466)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
c->printPretty();
*a=*b;
d->printPretty();
*c=*c;
a->printPretty();
std::cout << (a->remove(120)) << std::endl;
b->printPretty();
std::cout << (b->insert(120)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
e->printPretty();
std::cout << (d->insert(478)) << std::endl;
std::cout << (c->remove(244)) << std::endl;
c->printPretty();
std::cout << (d->remove(442)) << std::endl;
*c=*a;
*c=*d;
std::cout << (c->insert(478)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
*b=*a;
*e=*c;
*d=*a;
*c=*b;
*d=*e;
std::cout << (b->insert(402)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
d->printPretty();
std::cout << (b->insert(457)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
*a=*b;
std::cout << (b->insert(33)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(457)) << std::endl;
e->printPretty();
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
*c=*e;
std::cout << (d->insert(173)) << std::endl;
e->printPretty();
std::cout << (c->remove(455)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
*b=*b;
std::cout << (a->insert(116)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
*d=*c;
std::cout << (d->remove(58)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
e->printPretty();
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
*a=*b;
std::cout << (b->insert(100)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (a->remove(457)) << std::endl;
*a=*d;
d->printPretty();
*a=*a;
a->printPretty();
*e=*e;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->insert(324)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
c->printPretty();
std::cout << (d->remove(259)) << std::endl;
*a=*b;
*b=*a;
std::cout << (c->remove(177)) << std::endl;
a->printPretty();
std::cout << (c->insert(160)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
a->printPretty();
std::cout << (c->remove(136)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
std::cout << (a->insert(16)) << std::endl;
*c=*a;
a->printPretty();
*a=*a;
std::cout << (d->remove(88)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
e->printPretty();
std::cout << (c->insert(226)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
*e=*c;
std::cout << (b->insert(376)) << std::endl;
*b=*a;
*d=*d;
std::cout << (e->remove(226)) << std::endl;
*d=*a;
std::cout << (c->insert(358)) << std::endl;
c->printPretty();
std::cout << (b->insert(41)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
*c=*a;
*e=*c;
std::cout << (e->insert(276)) << std::endl;
a->printPretty();
std::cout << (a->insert(259)) << std::endl;
d->printPretty();
std::cout << (d->insert(248)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
std::cout << (a->insert(135)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
e->printPretty();
std::cout << (a->insert(442)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
b->printPretty();
std::cout << (c->insert(432)) << std::endl;
e->printPretty();
std::cout << (e->insert(227)) << std::endl;
d->printPretty();
std::cout << (d->remove(259)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
c->printPretty();
std::cout << (d->remove(248)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->insert(259)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
b->printPretty();
std::cout << (b->insert(478)) << std::endl;
*c=*d;
std::cout << (e->remove(227)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (c->remove(478)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
std::cout << (d->insert(431)) << std::endl;
d->printPretty();
std::cout << (d->insert(222)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
std::cout << (a->insert(338)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
e->printPretty();
std::cout << (c->remove(489)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
e->printPretty();
std::cout << (c->insert(59)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*c=*e;
std::cout << (c->insert(16)) << std::endl;
std::cout << (a->insert(338)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
*d=*c;
std::cout << (c->insert(249)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
*b=*e;
std::cout << (d->insert(229)) << std::endl;
a->printPretty();
std::cout << (d->remove(155)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
d->printPretty();
e->printPretty();
d->printPretty();
std::cout << (a->insert(251)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
*d=*d;
std::cout << (e->remove(407)) << std::endl;
d->printPretty();
std::cout << (a->remove(405)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
*d=*c;
e->printPretty();
*d=*c;
std::cout << (e->remove(16)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (a->insert(71)) << std::endl;
std::cout << (a->remove(299)) << std::endl;
*c=*d;
*b=*d;
std::cout << (e->remove(276)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
c->printPretty();
std::cout << (d->remove(276)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
b->printPretty();
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->remove(437)) << std::endl;
*c=*b;
std::cout << (a->remove(111)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
*b=*d;
std::cout << (d->remove(478)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
*e=*b;
std::cout << (d->remove(16)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
c->printPretty();
std::cout << (d->remove(190)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
*e=*a;
std::cout << (b->remove(115)) << std::endl;
*b=*e;
std::cout << (a->remove(338)) << std::endl;
return 0;
}
