#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (b->insert(82)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(295)) << std::endl;
c->printPretty();
b->printPretty();
*c=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
std::cout << (a->insert(35)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
*b=*b;
std::cout << (d->remove(82)) << std::endl;
c->printPretty();
a->printPretty();
*c=*a;
std::cout << (b->insert(22)) << std::endl;
*e=*d;
std::cout << (a->insert(35)) << std::endl;
b->printPretty();
std::cout << (d->remove(388)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
std::cout << (c->insert(174)) << std::endl;
std::cout << (e->remove(347)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
*d=*a;
*b=*c;
*e=*c;
std::cout << (b->remove(174)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (e->remove(146)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (a->remove(35)) << std::endl;
std::cout << (c->insert(174)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
*e=*d;
std::cout << (e->insert(461)) << std::endl;
std::cout << (e->insert(80)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
*a=*c;
std::cout << (b->remove(80)) << std::endl;
b->printPretty();
std::cout << (b->remove(82)) << std::endl;
*d=*a;
*d=*b;
std::cout << (a->insert(175)) << std::endl;
*b=*a;
*a=*a;
*c=*d;
std::cout << (e->insert(8)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (a->remove(248)) << std::endl;
d->printPretty();
std::cout << (e->remove(80)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
c->printPretty();
std::cout << (b->insert(258)) << std::endl;
*a=*c;
std::cout << (e->remove(497)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
b->printPretty();
e->printPretty();
c->printPretty();
*c=*d;
std::cout << (b->insert(258)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
std::cout << (c->insert(25)) << std::endl;
std::cout << (e->insert(243)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
*c=*a;
*a=*d;
std::cout << (a->insert(440)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
c->printPretty();
std::cout << (c->remove(300)) << std::endl;
*d=*d;
std::cout << (e->insert(249)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
*a=*c;
std::cout << (b->remove(480)) << std::endl;
std::cout << (d->insert(48)) << std::endl;
std::cout << (c->insert(317)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->remove(82)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
std::cout << (a->remove(288)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (b->remove(382)) << std::endl;
*e=*e;
d->printPretty();
a->printPretty();
std::cout << (b->remove(246)) << std::endl;
*e=*e;
std::cout << (e->insert(156)) << std::endl;
*c=*c;
b->printPretty();
*b=*c;
std::cout << (d->insert(316)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
*e=*a;
std::cout << (e->insert(13)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (c->insert(81)) << std::endl;
*a=*d;
*a=*c;
std::cout << (a->insert(81)) << std::endl;
b->printPretty();
std::cout << (b->insert(381)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
c->printPretty();
std::cout << (e->insert(316)) << std::endl;
d->printPretty();
std::cout << (e->insert(229)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
*e=*b;
std::cout << (c->insert(277)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(381)) << std::endl;
a->printPretty();
std::cout << (e->remove(210)) << std::endl;
c->printPretty();
std::cout << (a->remove(222)) << std::endl;
*b=*e;
std::cout << (c->remove(15)) << std::endl;
std::cout << (e->insert(200)) << std::endl;
e->printPretty();
std::cout << (b->insert(381)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (c->remove(119)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (d->remove(277)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (e->insert(132)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (b->insert(381)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
*e=*e;
std::cout << (b->remove(381)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
std::cout << (a->insert(338)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->insert(163)) << std::endl;
c->printPretty();
b->printPretty();
*a=*d;
std::cout << (a->remove(436)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (b->remove(345)) << std::endl;
*a=*b;
std::cout << (c->insert(81)) << std::endl;
b->printPretty();
*b=*c;
*e=*d;
c->printPretty();
std::cout << (e->remove(81)) << std::endl;
*d=*a;
std::cout << (c->remove(453)) << std::endl;
*b=*c;
b->printPretty();
e->printPretty();
std::cout << (c->remove(81)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
*c=*e;
*d=*a;
std::cout << (d->insert(269)) << std::endl;
*d=*a;
std::cout << (b->remove(110)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
a->printPretty();
std::cout << (c->insert(453)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (a->insert(163)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
*a=*d;
std::cout << (e->insert(453)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
std::cout << (d->insert(462)) << std::endl;
std::cout << (e->insert(324)) << std::endl;
std::cout << (d->remove(462)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (c->insert(38)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (c->remove(15)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
*d=*b;
std::cout << (e->remove(275)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
*d=*b;
std::cout << (d->insert(229)) << std::endl;
std::cout << (e->insert(324)) << std::endl;
*a=*a;
*c=*c;
e->printPretty();
*b=*b;
std::cout << (c->insert(38)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
*e=*b;
*e=*b;
std::cout << (a->insert(13)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (a->insert(278)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
*a=*b;
std::cout << (c->remove(152)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
std::cout << (c->remove(13)) << std::endl;
c->printPretty();
std::cout << (d->insert(117)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
*e=*a;
std::cout << (c->insert(122)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
*e=*b;
std::cout << (e->insert(36)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (e->insert(493)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (b->remove(142)) << std::endl;
std::cout << (e->insert(493)) << std::endl;
e->printPretty();
std::cout << (b->remove(325)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
b->printPretty();
std::cout << (a->remove(394)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (a->remove(125)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
std::cout << (c->remove(118)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
*d=*c;
std::cout << (e->remove(109)) << std::endl;
e->printPretty();
std::cout << (b->remove(425)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
*b=*e;
*a=*a;
std::cout << (e->remove(122)) << std::endl;
*b=*b;
std::cout << (e->remove(54)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
std::cout << (c->remove(26)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
b->printPretty();
std::cout << (d->remove(443)) << std::endl;
std::cout << (b->insert(346)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
*d=*a;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->insert(214)) << std::endl;
*c=*c;
*b=*e;
std::cout << (b->remove(42)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(280)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (a->remove(98)) << std::endl;
*d=*b;
*d=*a;
std::cout << (d->insert(73)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
c->printPretty();
*a=*b;
e->printPretty();
std::cout << (b->remove(493)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
b->printPretty();
std::cout << (d->remove(432)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (a->insert(158)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
*c=*c;
std::cout << (d->insert(214)) << std::endl;
std::cout << (c->remove(227)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
d->printPretty();
std::cout << (a->insert(158)) << std::endl;
a->printPretty();
std::cout << (b->remove(18)) << std::endl;
*b=*c;
std::cout << (a->remove(18)) << std::endl;
std::cout << (b->insert(162)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
c->printPretty();
a->printPretty();
a->printPretty();
std::cout << (a->insert(158)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
d->printPretty();
std::cout << (a->insert(392)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
*c=*d;
std::cout << (b->insert(162)) << std::endl;
*d=*a;
std::cout << (e->remove(493)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (a->insert(423)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->remove(367)) << std::endl;
std::cout << (c->remove(214)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
d->printPretty();
std::cout << (d->remove(407)) << std::endl;
std::cout << (a->insert(158)) << std::endl;
a->printPretty();
std::cout << (a->insert(423)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (a->insert(158)) << std::endl;
std::cout << (a->insert(23)) << std::endl;
*a=*e;
std::cout << (a->insert(386)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
std::cout << (b->remove(201)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
*b=*d;
std::cout << (c->remove(410)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
c->printPretty();
std::cout << (d->insert(158)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
b->printPretty();
std::cout << (a->insert(386)) << std::endl;
c->printPretty();
*e=*d;
*d=*b;
std::cout << (a->remove(273)) << std::endl;
std::cout << (a->remove(5)) << std::endl;
*a=*d;
d->printPretty();
*b=*c;
std::cout << (a->remove(439)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
a->printPretty();
std::cout << (b->remove(148)) << std::endl;
*d=*b;
std::cout << (d->insert(224)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
a->printPretty();
c->printPretty();
e->printPretty();
std::cout << (e->remove(158)) << std::endl;
std::cout << (d->insert(372)) << std::endl;
a->printPretty();
std::cout << (c->remove(372)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
d->printPretty();
std::cout << (c->insert(218)) << std::endl;
*b=*d;
std::cout << (c->insert(185)) << std::endl;
std::cout << (e->insert(302)) << std::endl;
a->printPretty();
*a=*c;
d->printPretty();
std::cout << (c->remove(81)) << std::endl;
*d=*d;
std::cout << (a->insert(391)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (e->insert(302)) << std::endl;
*e=*c;
std::cout << (c->remove(491)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (b->insert(91)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
*a=*b;
std::cout << (c->remove(217)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
*b=*e;
std::cout << (b->insert(460)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
*e=*c;
std::cout << (a->remove(311)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
a->printPretty();
std::cout << (a->remove(218)) << std::endl;
c->printPretty();
std::cout << (a->remove(185)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
*d=*e;
std::cout << (e->insert(398)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (c->remove(352)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->insert(311)) << std::endl;
*b=*c;
*b=*d;
c->printPretty();
std::cout << (e->insert(357)) << std::endl;
*c=*a;
std::cout << (c->insert(285)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (b->insert(5)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
e->printPretty();
std::cout << (c->remove(310)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
std::cout << (e->insert(285)) << std::endl;
e->printPretty();
std::cout << (b->remove(66)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(363)) << std::endl;
c->printPretty();
*b=*c;
a->printPretty();
std::cout << (d->remove(52)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
e->printPretty();
std::cout << (a->insert(408)) << std::endl;
*b=*a;
*c=*b;
std::cout << (b->remove(285)) << std::endl;
c->printPretty();
std::cout << (a->insert(337)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
*c=*b;
*c=*d;
std::cout << (e->insert(357)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (b->insert(225)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
e->printPretty();
*a=*b;
e->printPretty();
c->printPretty();
std::cout << (b->insert(480)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
*a=*c;
*e=*c;
std::cout << (b->remove(408)) << std::endl;
std::cout << (a->insert(21)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
*e=*a;
*b=*c;
*d=*e;
b->printPretty();
*e=*d;
std::cout << (d->remove(23)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
*d=*d;
std::cout << (d->remove(218)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
*a=*b;
std::cout << (d->insert(148)) << std::endl;
e->printPretty();
std::cout << (a->insert(148)) << std::endl;
e->printPretty();
std::cout << (e->insert(53)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
*c=*e;
std::cout << (e->remove(31)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
*e=*a;
std::cout << (d->insert(157)) << std::endl;
std::cout << (a->insert(148)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (c->remove(354)) << std::endl;
*e=*b;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->insert(218)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (e->remove(428)) << std::endl;
*d=*a;
std::cout << (d->remove(50)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
*a=*b;
*c=*b;
d->printPretty();
std::cout << (d->insert(469)) << std::endl;
std::cout << (d->remove(267)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
a->printPretty();
std::cout << (d->insert(217)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (b->insert(157)) << std::endl;
*d=*e;
std::cout << (b->remove(154)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
std::cout << (b->insert(157)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (b->remove(269)) << std::endl;
std::cout << (b->remove(285)) << std::endl;
c->printPretty();
std::cout << (a->insert(391)) << std::endl;
*a=*d;
std::cout << (c->remove(285)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (b->insert(183)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (c->remove(441)) << std::endl;
*e=*d;
*e=*b;
std::cout << (d->insert(391)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
*b=*b;
std::cout << (d->remove(365)) << std::endl;
std::cout << (d->insert(185)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (a->insert(185)) << std::endl;
*c=*a;
std::cout << (a->remove(185)) << std::endl;
std::cout << (c->insert(185)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (d->remove(470)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
c->printPretty();
std::cout << (a->insert(157)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
*d=*a;
*c=*e;
std::cout << (c->insert(172)) << std::endl;
*c=*a;
std::cout << (c->insert(38)) << std::endl;
*d=*c;
std::cout << (e->remove(113)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (d->insert(157)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
std::cout << (a->remove(391)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
std::cout << (e->remove(183)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
a->printPretty();
std::cout << (d->remove(247)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
std::cout << (b->insert(133)) << std::endl;
*d=*c;
std::cout << (c->insert(6)) << std::endl;
*a=*c;
*d=*c;
*c=*e;
std::cout << (c->insert(336)) << std::endl;
std::cout << (a->insert(378)) << std::endl;
b->printPretty();
std::cout << (c->insert(41)) << std::endl;
return 0;
}
