#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(203)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
*b=*b;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
*b=*a;
std::cout << (c->insert(222)) << std::endl;
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(238)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*c=*b;
std::cout << (a->remove(238)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*c=*d;
*b=*e;
std::cout << (c->insert(30)) << std::endl;
e->printPretty();
std::cout << (b->insert(337)) << std::endl;
std::cout << (e->remove(266)) << std::endl;
*a=*e;
std::cout << (b->remove(337)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
*e=*d;
std::cout << (b->insert(336)) << std::endl;
e->printPretty();
e->printPretty();
e->printPretty();
b->printPretty();
b->printPretty();
*d=*b;
std::cout << (c->insert(158)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (e->insert(465)) << std::endl;
std::cout << (a->insert(490)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
*a=*e;
std::cout << (c->remove(12)) << std::endl;
b->printPretty();
std::cout << (a->insert(465)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->remove(465)) << std::endl;
*e=*b;
e->printPretty();
*b=*c;
std::cout << (e->remove(359)) << std::endl;
std::cout << (e->insert(269)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
*e=*b;
std::cout << (e->insert(294)) << std::endl;
*c=*b;
b->printPretty();
b->printPretty();
std::cout << (c->remove(294)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (b->remove(265)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
d->printPretty();
d->printPretty();
d->printPretty();
std::cout << (d->remove(237)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
*c=*c;
std::cout << (b->insert(158)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (c->remove(158)) << std::endl;
std::cout << (d->insert(336)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
a->printPretty();
std::cout << (c->remove(415)) << std::endl;
std::cout << (c->remove(187)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
e->printPretty();
std::cout << (b->remove(451)) << std::endl;
b->printPretty();
std::cout << (e->remove(353)) << std::endl;
std::cout << (b->insert(87)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
*e=*a;
std::cout << (b->remove(380)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(436)) << std::endl;
d->printPretty();
std::cout << (a->remove(130)) << std::endl;
*e=*d;
*d=*e;
std::cout << (e->remove(280)) << std::endl;
e->printPretty();
std::cout << (d->remove(479)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
*d=*a;
std::cout << (d->insert(305)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
a->printPretty();
*e=*b;
std::cout << (a->insert(411)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
*c=*a;
d->printPretty();
*b=*c;
std::cout << (e->remove(80)) << std::endl;
std::cout << (d->remove(170)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
std::cout << (e->insert(158)) << std::endl;
*b=*d;
std::cout << (e->insert(158)) << std::endl;
*d=*a;
std::cout << (a->remove(480)) << std::endl;
d->printPretty();
std::cout << (a->insert(411)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
c->printPretty();
std::cout << (a->insert(467)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (e->insert(87)) << std::endl;
*d=*d;
std::cout << (c->remove(411)) << std::endl;
std::cout << (d->insert(411)) << std::endl;
a->printPretty();
std::cout << (c->insert(216)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->remove(411)) << std::endl;
*e=*a;
std::cout << (a->insert(467)) << std::endl;
c->printPretty();
c->printPretty();
*e=*b;
std::cout << (c->insert(355)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(411)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
std::cout << (d->insert(411)) << std::endl;
b->printPretty();
std::cout << (e->insert(489)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (e->remove(310)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
std::cout << (e->insert(489)) << std::endl;
std::cout << (b->remove(325)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
*a=*b;
std::cout << (b->insert(216)) << std::endl;
a->printPretty();
std::cout << (a->insert(422)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (c->insert(129)) << std::endl;
*a=*d;
*d=*c;
std::cout << (b->remove(411)) << std::endl;
*d=*e;
std::cout << (c->insert(224)) << std::endl;
c->printPretty();
std::cout << (c->remove(280)) << std::endl;
*e=*b;
std::cout << (b->remove(375)) << std::endl;
std::cout << (a->insert(346)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
e->printPretty();
*c=*b;
*b=*a;
*b=*b;
std::cout << (a->insert(449)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->remove(428)) << std::endl;
*e=*c;
std::cout << (e->insert(377)) << std::endl;
std::cout << (e->insert(83)) << std::endl;
b->printPretty();
std::cout << (b->remove(346)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
b->printPretty();
std::cout << (c->insert(357)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (b->remove(487)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (d->remove(83)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
b->printPretty();
std::cout << (d->insert(377)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
c->printPretty();
std::cout << (b->insert(79)) << std::endl;
*e=*a;
*a=*e;
std::cout << (b->remove(460)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*b=*e;
std::cout << (b->remove(449)) << std::endl;
std::cout << (d->remove(127)) << std::endl;
*d=*e;
std::cout << (c->insert(154)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
std::cout << (c->insert(115)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*a=*e;
c->printPretty();
a->printPretty();
*b=*e;
*e=*a;
*a=*c;
std::cout << (c->remove(263)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
*c=*a;
std::cout << (b->remove(467)) << std::endl;
*e=*e;
*c=*d;
b->printPretty();
std::cout << (e->insert(465)) << std::endl;
*b=*c;
std::cout << (e->remove(132)) << std::endl;
*d=*a;
std::cout << (d->remove(154)) << std::endl;
*b=*c;
*c=*d;
*b=*e;
std::cout << (a->insert(383)) << std::endl;
*b=*b;
*a=*a;
std::cout << (b->remove(346)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
e->printPretty();
std::cout << (e->remove(138)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (e->insert(392)) << std::endl;
*a=*e;
std::cout << (e->remove(14)) << std::endl;
*c=*c;
std::cout << (c->remove(312)) << std::endl;
std::cout << (e->remove(465)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (b->insert(87)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (a->insert(346)) << std::endl;
*b=*e;
*c=*b;
std::cout << (b->insert(402)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
e->printPretty();
*d=*a;
d->printPretty();
std::cout << (b->insert(392)) << std::endl;
c->printPretty();
std::cout << (e->remove(404)) << std::endl;
b->printPretty();
*c=*a;
std::cout << (e->remove(346)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (c->insert(449)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
std::cout << (b->insert(392)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
b->printPretty();
std::cout << (e->remove(47)) << std::endl;
*e=*d;
std::cout << (e->insert(449)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->remove(467)) << std::endl;
*e=*c;
std::cout << (a->insert(465)) << std::endl;
b->printPretty();
std::cout << (a->insert(392)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (e->remove(122)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
*b=*a;
std::cout << (a->insert(392)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (c->remove(24)) << std::endl;
a->printPretty();
std::cout << (d->remove(22)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->remove(41)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
*e=*b;
std::cout << (b->remove(14)) << std::endl;
std::cout << (d->insert(8)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (e->remove(392)) << std::endl;
*c=*e;
std::cout << (a->insert(465)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
*d=*c;
*a=*e;
std::cout << (a->insert(443)) << std::endl;
*b=*d;
std::cout << (b->insert(467)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
c->printPretty();
std::cout << (b->insert(175)) << std::endl;
std::cout << (d->insert(467)) << std::endl;
b->printPretty();
std::cout << (d->remove(284)) << std::endl;
*b=*c;
*d=*b;
std::cout << (a->remove(466)) << std::endl;
*a=*c;
e->printPretty();
*d=*e;
e->printPretty();
std::cout << (c->remove(14)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
c->printPretty();
std::cout << (e->remove(190)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
*e=*a;
*a=*e;
std::cout << (a->insert(467)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
b->printPretty();
std::cout << (c->remove(170)) << std::endl;
std::cout << (d->insert(467)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
*a=*b;
*c=*d;
std::cout << (c->insert(14)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
c->printPretty();
std::cout << (c->insert(481)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (d->insert(467)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
*a=*e;
std::cout << (a->insert(14)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
e->printPretty();
std::cout << (c->insert(467)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
c->printPretty();
std::cout << (c->insert(467)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
a->printPretty();
*b=*a;
*e=*d;
e->printPretty();
c->printPretty();
std::cout << (d->remove(14)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
*d=*d;
std::cout << (c->remove(14)) << std::endl;
*d=*d;
std::cout << (d->remove(116)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (d->insert(321)) << std::endl;
e->printPretty();
std::cout << (e->insert(14)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(321)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (d->insert(433)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
*e=*d;
*d=*c;
std::cout << (d->remove(208)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
*e=*a;
std::cout << (c->remove(303)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
b->printPretty();
std::cout << (b->insert(192)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
std::cout << (c->remove(208)) << std::endl;
*e=*e;
std::cout << (d->insert(453)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (b->insert(300)) << std::endl;
std::cout << (e->remove(236)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
*c=*d;
*d=*a;
std::cout << (b->insert(467)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
*a=*d;
std::cout << (c->insert(227)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
a->printPretty();
std::cout << (e->insert(20)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (c->remove(227)) << std::endl;
std::cout << (e->remove(150)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
*e=*a;
*c=*a;
std::cout << (a->insert(20)) << std::endl;
e->printPretty();
std::cout << (c->remove(467)) << std::endl;
*c=*c;
std::cout << (b->insert(82)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->remove(293)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
*e=*b;
std::cout << (c->insert(248)) << std::endl;
std::cout << (c->insert(392)) << std::endl;
std::cout << (c->remove(412)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (c->insert(444)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
b->printPretty();
std::cout << (c->insert(325)) << std::endl;
std::cout << (c->insert(412)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
c->printPretty();
std::cout << (a->insert(20)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (c->insert(20)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
a->printPretty();
std::cout << (a->remove(24)) << std::endl;
a->printPretty();
std::cout << (e->insert(388)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
*e=*d;
std::cout << (b->insert(20)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
*d=*d;
std::cout << (a->remove(20)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
*b=*a;
std::cout << (a->insert(467)) << std::endl;
std::cout << (b->remove(232)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (d->remove(83)) << std::endl;
std::cout << (c->insert(392)) << std::endl;
*d=*e;
std::cout << (b->remove(467)) << std::endl;
std::cout << (b->insert(334)) << std::endl;
std::cout << (d->insert(385)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
*b=*e;
std::cout << (d->remove(467)) << std::endl;
*b=*e;
std::cout << (d->remove(14)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
a->printPretty();
std::cout << (a->insert(456)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
*c=*b;
*e=*c;
a->printPretty();
std::cout << (c->insert(186)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
b->printPretty();
*b=*b;
e->printPretty();
std::cout << (d->insert(385)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
std::cout << (e->insert(20)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
*e=*a;
std::cout << (a->insert(31)) << std::endl;
*a=*d;
std::cout << (d->insert(367)) << std::endl;
std::cout << (e->insert(454)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
*c=*d;
std::cout << (d->insert(345)) << std::endl;
std::cout << (b->remove(309)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (e->remove(456)) << std::endl;
b->printPretty();
std::cout << (d->insert(216)) << std::endl;
*c=*c;
c->printPretty();
a->printPretty();
std::cout << (c->insert(430)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
std::cout << (a->insert(215)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
*e=*b;
std::cout << (b->remove(49)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
*d=*a;
*a=*d;
std::cout << (d->insert(347)) << std::endl;
*d=*c;
std::cout << (c->remove(81)) << std::endl;
std::cout << (c->remove(20)) << std::endl;
std::cout << (d->remove(279)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->remove(310)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
std::cout << (c->insert(34)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (c->insert(430)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
a->printPretty();
std::cout << (d->insert(46)) << std::endl;
*c=*b;
std::cout << (d->insert(385)) << std::endl;
std::cout << (d->remove(150)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
e->printPretty();
*c=*d;
std::cout << (c->insert(470)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
std::cout << (c->insert(221)) << std::endl;
*e=*a;
*b=*d;
a->printPretty();
std::cout << (c->remove(223)) << std::endl;
*d=*a;
std::cout << (c->insert(34)) << std::endl;
*a=*b;
std::cout << (e->remove(258)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
std::cout << (b->insert(249)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
*d=*c;
c->printPretty();
*c=*c;
*d=*d;
std::cout << (a->insert(286)) << std::endl;
*e=*c;
std::cout << (d->remove(379)) << std::endl;
*b=*d;
*b=*b;
std::cout << (c->insert(287)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (e->insert(162)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (c->insert(221)) << std::endl;
*b=*e;
*a=*a;
*b=*a;
std::cout << (d->insert(486)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
a->printPretty();
std::cout << (c->insert(339)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
d->printPretty();
a->printPretty();
*b=*c;
std::cout << (c->insert(284)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
a->printPretty();
std::cout << (b->remove(435)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
e->printPretty();
c->printPretty();
a->printPretty();
std::cout << (d->insert(154)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
e->printPretty();
std::cout << (c->insert(51)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
e->printPretty();
std::cout << (b->insert(385)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (b->insert(470)) << std::endl;
*c=*a;
std::cout << (e->insert(224)) << std::endl;
std::cout << (a->insert(286)) << std::endl;
std::cout << (d->remove(247)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
d->printPretty();
std::cout << (a->insert(291)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
*e=*c;
std::cout << (b->remove(169)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (e->remove(405)) << std::endl;
c->printPretty();
std::cout << (e->remove(371)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
return 0;
}
