#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(406)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (a->insert(269)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (c->remove(269)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (a->remove(141)) << std::endl;
*d=*e;
c->printPretty();
std::cout << (a->remove(212)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
e->printPretty();
std::cout << (a->insert(269)) << std::endl;
c->printPretty();
std::cout << (b->remove(269)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
c->printPretty();
std::cout << (c->insert(212)) << std::endl;
*c=*d;
std::cout << (e->remove(382)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (d->remove(122)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
*a=*c;
*c=*e;
std::cout << (d->insert(337)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
b->printPretty();
std::cout << (e->insert(387)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (d->insert(398)) << std::endl;
std::cout << (d->insert(398)) << std::endl;
std::cout << (e->remove(89)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
c->printPretty();
std::cout << (e->remove(239)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
*e=*c;
*c=*b;
*a=*c;
c->printPretty();
c->printPretty();
*b=*c;
std::cout << (a->insert(261)) << std::endl;
*b=*c;
b->printPretty();
*b=*c;
*c=*b;
d->printPretty();
std::cout << (c->remove(190)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (b->remove(358)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
*d=*d;
std::cout << (a->remove(446)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
std::cout << (d->insert(55)) << std::endl;
*a=*c;
std::cout << (c->insert(391)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
*a=*b;
std::cout << (a->remove(27)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
*e=*c;
*c=*d;
std::cout << (d->insert(55)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
d->printPretty();
std::cout << (d->remove(88)) << std::endl;
b->printPretty();
std::cout << (c->remove(93)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
*a=*d;
std::cout << (a->remove(421)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (a->remove(89)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
std::cout << (d->remove(490)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
*b=*c;
d->printPretty();
std::cout << (b->remove(50)) << std::endl;
a->printPretty();
std::cout << (a->insert(475)) << std::endl;
d->printPretty();
std::cout << (c->remove(33)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
c->printPretty();
std::cout << (e->remove(175)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
*c=*e;
std::cout << (d->insert(247)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (e->remove(395)) << std::endl;
e->printPretty();
std::cout << (a->remove(337)) << std::endl;
c->printPretty();
*b=*b;
*c=*d;
*b=*e;
std::cout << (d->insert(64)) << std::endl;
*a=*b;
*e=*d;
a->printPretty();
std::cout << (b->remove(189)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
*b=*b;
std::cout << (d->remove(282)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
b->printPretty();
std::cout << (a->insert(247)) << std::endl;
std::cout << (d->insert(337)) << std::endl;
d->printPretty();
std::cout << (e->remove(44)) << std::endl;
*e=*e;
*e=*e;
std::cout << (a->insert(247)) << std::endl;
*a=*c;
std::cout << (a->remove(77)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
std::cout << (a->remove(55)) << std::endl;
b->printPretty();
d->printPretty();
*d=*d;
std::cout << (a->insert(265)) << std::endl;
*b=*a;
std::cout << (c->remove(361)) << std::endl;
e->printPretty();
std::cout << (d->remove(421)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
*e=*c;
std::cout << (e->remove(337)) << std::endl;
std::cout << (e->insert(82)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
e->printPretty();
std::cout << (a->insert(471)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
d->printPretty();
std::cout << (a->remove(50)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
std::cout << (c->remove(337)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
*c=*c;
std::cout << (b->remove(27)) << std::endl;
*c=*a;
*b=*a;
c->printPretty();
std::cout << (a->remove(4)) << std::endl;
std::cout << (e->insert(432)) << std::endl;
*a=*a;
std::cout << (b->insert(336)) << std::endl;
*c=*c;
std::cout << (e->insert(358)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
*e=*e;
std::cout << (e->remove(247)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (a->insert(105)) << std::endl;
std::cout << (a->insert(105)) << std::endl;
std::cout << (d->remove(337)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (d->insert(30)) << std::endl;
*b=*d;
std::cout << (d->remove(358)) << std::endl;
*e=*e;
std::cout << (d->insert(30)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
*d=*e;
std::cout << (e->insert(258)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
c->printPretty();
std::cout << (d->insert(399)) << std::endl;
*d=*b;
c->printPretty();
*a=*e;
std::cout << (c->remove(337)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
d->printPretty();
std::cout << (e->remove(432)) << std::endl;
a->printPretty();
std::cout << (b->insert(398)) << std::endl;
*a=*b;
std::cout << (e->remove(55)) << std::endl;
std::cout << (b->insert(179)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(299)) << std::endl;
d->printPretty();
std::cout << (c->insert(466)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
std::cout << (a->remove(453)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
*e=*d;
std::cout << (c->remove(376)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
*b=*c;
std::cout << (d->insert(140)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
std::cout << (a->remove(308)) << std::endl;
*a=*b;
*d=*e;
std::cout << (b->remove(10)) << std::endl;
e->printPretty();
std::cout << (d->insert(398)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
*c=*c;
std::cout << (d->remove(247)) << std::endl;
std::cout << (d->insert(299)) << std::endl;
d->printPretty();
e->printPretty();
e->printPretty();
std::cout << (a->remove(113)) << std::endl;
e->printPretty();
std::cout << (e->insert(89)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (b->remove(135)) << std::endl;
b->printPretty();
std::cout << (c->insert(466)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (c->remove(388)) << std::endl;
*b=*a;
*c=*c;
std::cout << (e->remove(493)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
c->printPretty();
std::cout << (c->insert(406)) << std::endl;
*e=*a;
*d=*e;
d->printPretty();
*b=*e;
std::cout << (a->remove(53)) << std::endl;
b->printPretty();
std::cout << (e->remove(421)) << std::endl;
*c=*d;
std::cout << (c->remove(74)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
c->printPretty();
std::cout << (c->remove(358)) << std::endl;
std::cout << (e->insert(358)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (c->remove(56)) << std::endl;
std::cout << (d->remove(433)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
*d=*e;
std::cout << (b->insert(190)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (a->remove(56)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->remove(35)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
*e=*d;
*d=*a;
*d=*b;
a->printPretty();
std::cout << (e->insert(53)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
c->printPretty();
std::cout << (d->remove(393)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
*b=*b;
*b=*e;
std::cout << (b->insert(439)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
*d=*a;
std::cout << (d->remove(232)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
*b=*d;
std::cout << (c->insert(471)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(431)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
b->printPretty();
std::cout << (b->insert(143)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (b->remove(298)) << std::endl;
*d=*c;
std::cout << (d->remove(106)) << std::endl;
c->printPretty();
std::cout << (d->insert(466)) << std::endl;
std::cout << (a->remove(431)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
e->printPretty();
std::cout << (e->insert(30)) << std::endl;
*e=*c;
std::cout << (d->remove(10)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
c->printPretty();
std::cout << (e->remove(10)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
a->printPretty();
std::cout << (d->remove(471)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
e->printPretty();
*a=*c;
*a=*d;
std::cout << (c->insert(249)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
d->printPretty();
std::cout << (a->remove(466)) << std::endl;
*b=*d;
std::cout << (c->insert(9)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
d->printPretty();
std::cout << (c->insert(106)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(466)) << std::endl;
b->printPretty();
b->printPretty();
c->printPretty();
std::cout << (c->insert(338)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
e->printPretty();
std::cout << (c->remove(421)) << std::endl;
std::cout << (d->remove(421)) << std::endl;
a->printPretty();
*c=*d;
c->printPretty();
std::cout << (d->remove(466)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
*e=*c;
std::cout << (b->remove(421)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->remove(447)) << std::endl;
*e=*d;
std::cout << (a->insert(484)) << std::endl;
*b=*b;
std::cout << (a->remove(85)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (b->remove(7)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->remove(311)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
c->printPretty();
std::cout << (e->insert(248)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
*a=*c;
std::cout << (c->remove(112)) << std::endl;
std::cout << (e->insert(110)) << std::endl;
b->printPretty();
a->printPretty();
*c=*c;
*c=*c;
std::cout << (c->insert(158)) << std::endl;
*e=*a;
*b=*a;
std::cout << (a->insert(71)) << std::endl;
b->printPretty();
a->printPretty();
e->printPretty();
std::cout << (a->remove(319)) << std::endl;
*c=*b;
std::cout << (a->insert(71)) << std::endl;
c->printPretty();
std::cout << (b->remove(266)) << std::endl;
c->printPretty();
std::cout << (c->insert(213)) << std::endl;
e->printPretty();
std::cout << (a->remove(472)) << std::endl;
*e=*b;
*a=*e;
d->printPretty();
*e=*b;
*c=*c;
std::cout << (e->remove(222)) << std::endl;
*d=*d;
std::cout << (c->remove(269)) << std::endl;
std::cout << (c->remove(213)) << std::endl;
*a=*a;
std::cout << (d->remove(206)) << std::endl;
c->printPretty();
std::cout << (c->remove(361)) << std::endl;
std::cout << (c->remove(20)) << std::endl;
*e=*a;
*e=*b;
std::cout << (a->insert(119)) << std::endl;
*e=*c;
std::cout << (d->remove(341)) << std::endl;
*b=*c;
std::cout << (b->insert(390)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
*d=*b;
std::cout << (e->insert(373)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
c->printPretty();
*e=*c;
std::cout << (c->remove(362)) << std::endl;
*d=*c;
std::cout << (b->insert(242)) << std::endl;
e->printPretty();
std::cout << (a->insert(119)) << std::endl;
a->printPretty();
std::cout << (c->remove(344)) << std::endl;
d->printPretty();
std::cout << (a->insert(119)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
*c=*d;
std::cout << (e->remove(206)) << std::endl;
*b=*b;
a->printPretty();
std::cout << (a->remove(433)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
*a=*d;
std::cout << (b->remove(200)) << std::endl;
*e=*b;
std::cout << (b->remove(390)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
*b=*b;
std::cout << (b->insert(53)) << std::endl;
std::cout << (b->remove(464)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
*c=*a;
d->printPretty();
*a=*c;
*a=*d;
std::cout << (e->remove(448)) << std::endl;
*d=*c;
std::cout << (c->insert(477)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (a->insert(28)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
std::cout << (d->remove(385)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
*b=*a;
std::cout << (e->remove(415)) << std::endl;
b->printPretty();
*b=*e;
a->printPretty();
*a=*b;
*c=*e;
*e=*c;
std::cout << (a->remove(372)) << std::endl;
*d=*a;
std::cout << (a->remove(242)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->remove(29)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
*e=*d;
std::cout << (a->insert(284)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
*b=*b;
std::cout << (d->insert(235)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
b->printPretty();
std::cout << (a->insert(284)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->insert(388)) << std::endl;
*d=*b;
std::cout << (e->insert(144)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
c->printPretty();
std::cout << (e->insert(144)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
*c=*c;
std::cout << (a->remove(281)) << std::endl;
*e=*b;
std::cout << (b->insert(252)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (c->remove(390)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->insert(431)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->insert(70)) << std::endl;
std::cout << (a->remove(267)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
e->printPretty();
std::cout << (e->remove(83)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
a->printPretty();
std::cout << (d->insert(284)) << std::endl;
d->printPretty();
std::cout << (e->remove(389)) << std::endl;
*c=*c;
*c=*a;
b->printPretty();
std::cout << (e->insert(372)) << std::endl;
std::cout << (e->remove(284)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
a->printPretty();
std::cout << (d->insert(29)) << std::endl;
a->printPretty();
std::cout << (a->remove(27)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
*c=*a;
std::cout << (e->insert(431)) << std::endl;
c->printPretty();
std::cout << (b->insert(242)) << std::endl;
std::cout << (e->remove(191)) << std::endl;
e->printPretty();
std::cout << (c->insert(451)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
d->printPretty();
std::cout << (b->remove(291)) << std::endl;
b->printPretty();
std::cout << (c->remove(479)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
*e=*a;
std::cout << (d->remove(157)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
*e=*d;
std::cout << (d->insert(428)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
a->printPretty();
std::cout << (c->insert(101)) << std::endl;
std::cout << (e->remove(431)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
*a=*c;
std::cout << (e->remove(284)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (b->remove(390)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
std::cout << (c->remove(195)) << std::endl;
std::cout << (b->remove(330)) << std::endl;
*b=*e;
std::cout << (d->insert(218)) << std::endl;
*b=*d;
std::cout << (b->remove(206)) << std::endl;
std::cout << (a->remove(433)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
c->printPretty();
std::cout << (b->remove(227)) << std::endl;
*c=*c;
std::cout << (b->insert(417)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
*a=*c;
std::cout << (d->remove(431)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (a->insert(471)) << std::endl;
std::cout << (b->insert(442)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
*b=*b;
std::cout << (c->insert(372)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (b->remove(431)) << std::endl;
*e=*b;
*c=*a;
std::cout << (b->insert(400)) << std::endl;
*c=*e;
b->printPretty();
d->printPretty();
std::cout << (e->insert(119)) << std::endl;
*a=*d;
e->printPretty();
*d=*a;
std::cout << (c->remove(129)) << std::endl;
std::cout << (e->remove(159)) << std::endl;
std::cout << (a->insert(242)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
e->printPretty();
std::cout << (d->insert(250)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (e->remove(120)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
*b=*c;
a->printPretty();
return 0;
}
