#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(138)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (a->insert(138)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
*d=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (e->remove(324)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
d->printPretty();
std::cout << (b->insert(138)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
c->printPretty();
std::cout << (e->remove(372)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
std::cout << (b->remove(138)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
a->printPretty();
std::cout << (c->remove(175)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
*d=*b;
std::cout << (c->insert(134)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
a->printPretty();
std::cout << (d->insert(258)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
d->printPretty();
std::cout << (d->insert(225)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
std::cout << (c->remove(314)) << std::endl;
c->printPretty();
e->printPretty();
*e=*a;
std::cout << (d->insert(477)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
b->printPretty();
*b=*a;
b->printPretty();
std::cout << (d->remove(258)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (d->insert(114)) << std::endl;
*c=*a;
std::cout << (b->remove(269)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
*e=*b;
std::cout << (d->remove(477)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(268)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
e->printPretty();
std::cout << (e->insert(31)) << std::endl;
c->printPretty();
std::cout << (a->insert(229)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
b->printPretty();
std::cout << (c->insert(292)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
d->printPretty();
std::cout << (c->insert(292)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
*a=*e;
std::cout << (e->insert(31)) << std::endl;
*b=*c;
std::cout << (b->remove(477)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
*c=*d;
std::cout << (c->insert(229)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (b->remove(482)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
std::cout << (a->remove(31)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (c->insert(464)) << std::endl;
*d=*d;
std::cout << (b->remove(388)) << std::endl;
*d=*c;
std::cout << (a->insert(237)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (c->insert(229)) << std::endl;
std::cout << (d->remove(30)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
*e=*b;
std::cout << (a->remove(435)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
*a=*e;
std::cout << (b->insert(169)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (e->remove(454)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (e->insert(292)) << std::endl;
std::cout << (b->remove(358)) << std::endl;
d->printPretty();
std::cout << (e->insert(114)) << std::endl;
std::cout << (c->insert(319)) << std::endl;
b->printPretty();
std::cout << (c->insert(83)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (e->insert(410)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->remove(229)) << std::endl;
b->printPretty();
std::cout << (a->insert(161)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
*d=*e;
std::cout << (b->remove(384)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->remove(84)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
b->printPretty();
std::cout << (a->insert(307)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
e->printPretty();
std::cout << (e->remove(114)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
*b=*d;
*e=*c;
*a=*d;
std::cout << (a->insert(114)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (b->insert(44)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
*e=*b;
std::cout << (a->remove(426)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
c->printPretty();
std::cout << (e->insert(89)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
*c=*c;
*a=*d;
b->printPretty();
std::cout << (e->remove(299)) << std::endl;
*c=*c;
std::cout << (b->remove(430)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
c->printPretty();
std::cout << (a->remove(225)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
b->printPretty();
std::cout << (e->remove(418)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (e->remove(89)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
*c=*d;
std::cout << (c->insert(225)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
e->printPretty();
std::cout << (d->remove(467)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->remove(244)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
*a=*c;
std::cout << (b->insert(373)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
d->printPretty();
std::cout << (c->insert(487)) << std::endl;
*a=*e;
*c=*e;
*c=*c;
std::cout << (d->insert(396)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
*d=*d;
std::cout << (e->remove(479)) << std::endl;
*d=*a;
*c=*a;
std::cout << (c->remove(400)) << std::endl;
std::cout << (a->remove(188)) << std::endl;
*b=*a;
std::cout << (b->remove(127)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
*b=*a;
std::cout << (e->remove(188)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
std::cout << (e->insert(488)) << std::endl;
*e=*c;
std::cout << (d->insert(44)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
*a=*d;
std::cout << (e->insert(382)) << std::endl;
*a=*d;
std::cout << (c->insert(44)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
*a=*c;
std::cout << (a->remove(390)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (d->insert(188)) << std::endl;
std::cout << (a->remove(382)) << std::endl;
e->printPretty();
std::cout << (c->remove(247)) << std::endl;
e->printPretty();
std::cout << (d->insert(260)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
std::cout << (e->remove(268)) << std::endl;
*d=*b;
std::cout << (d->remove(382)) << std::endl;
*a=*c;
std::cout << (c->insert(22)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
*d=*d;
std::cout << (e->insert(304)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (d->remove(130)) << std::endl;
*d=*a;
*e=*c;
*b=*d;
std::cout << (d->remove(65)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
b->printPretty();
std::cout << (b->remove(497)) << std::endl;
*d=*e;
std::cout << (b->remove(28)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
std::cout << (e->insert(477)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
std::cout << (b->remove(6)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
*a=*d;
*d=*b;
std::cout << (c->insert(22)) << std::endl;
e->printPretty();
std::cout << (e->remove(190)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
std::cout << (c->insert(392)) << std::endl;
*c=*b;
std::cout << (e->remove(424)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*d=*c;
std::cout << (c->remove(44)) << std::endl;
std::cout << (c->insert(188)) << std::endl;
std::cout << (c->remove(89)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (a->remove(233)) << std::endl;
*c=*b;
std::cout << (d->remove(137)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (a->remove(436)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
a->printPretty();
*c=*d;
*e=*e;
std::cout << (d->insert(188)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
*a=*a;
std::cout << (a->insert(368)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
*b=*a;
c->printPretty();
e->printPretty();
std::cout << (e->remove(379)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
a->printPretty();
std::cout << (b->insert(313)) << std::endl;
std::cout << (a->remove(188)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
*e=*c;
std::cout << (d->insert(266)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
a->printPretty();
*a=*b;
d->printPretty();
std::cout << (c->remove(492)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
b->printPretty();
std::cout << (b->insert(368)) << std::endl;
*c=*e;
std::cout << (c->insert(188)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
*d=*d;
*a=*a;
*d=*e;
std::cout << (b->remove(48)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
std::cout << (a->remove(59)) << std::endl;
std::cout << (a->remove(264)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
c->printPretty();
std::cout << (c->insert(54)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
*b=*a;
std::cout << (d->insert(54)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (c->remove(85)) << std::endl;
*c=*e;
std::cout << (b->insert(436)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->insert(47)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
*d=*c;
std::cout << (c->remove(360)) << std::endl;
b->printPretty();
std::cout << (a->insert(46)) << std::endl;
e->printPretty();
std::cout << (d->remove(113)) << std::endl;
*b=*a;
std::cout << (b->insert(45)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (d->remove(347)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
*a=*d;
std::cout << (c->remove(126)) << std::endl;
*a=*b;
std::cout << (e->remove(487)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(271)) << std::endl;
std::cout << (b->remove(45)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (a->remove(67)) << std::endl;
b->printPretty();
*e=*a;
*a=*e;
std::cout << (e->remove(45)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(263)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
std::cout << (a->insert(479)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
*c=*a;
std::cout << (c->insert(313)) << std::endl;
*e=*a;
std::cout << (c->remove(297)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
d->printPretty();
std::cout << (b->remove(120)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
c->printPretty();
std::cout << (d->insert(360)) << std::endl;
e->printPretty();
std::cout << (c->insert(368)) << std::endl;
*d=*c;
std::cout << (c->remove(471)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
std::cout << (d->remove(50)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
c->printPretty();
std::cout << (a->remove(44)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
*e=*c;
std::cout << (b->insert(188)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
e->printPretty();
std::cout << (e->remove(500)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
d->printPretty();
std::cout << (b->remove(64)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (c->remove(498)) << std::endl;
d->printPretty();
std::cout << (a->insert(13)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
d->printPretty();
std::cout << (e->remove(2)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
*a=*a;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (e->remove(311)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->remove(378)) << std::endl;
a->printPretty();
std::cout << (a->remove(313)) << std::endl;
*c=*c;
std::cout << (d->insert(7)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (d->remove(7)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (b->remove(458)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
b->printPretty();
std::cout << (b->insert(114)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
std::cout << (a->remove(446)) << std::endl;
*a=*b;
std::cout << (b->remove(475)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
d->printPretty();
std::cout << (c->insert(46)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (e->remove(45)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
*a=*a;
std::cout << (b->insert(188)) << std::endl;
a->printPretty();
std::cout << (e->insert(303)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
c->printPretty();
std::cout << (b->remove(396)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
*c=*c;
std::cout << (a->insert(368)) << std::endl;
std::cout << (b->insert(480)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
*a=*a;
std::cout << (a->remove(282)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
std::cout << (d->remove(50)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (a->insert(204)) << std::endl;
e->printPretty();
std::cout << (a->remove(325)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
*b=*d;
std::cout << (d->remove(471)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
c->printPretty();
std::cout << (b->insert(376)) << std::endl;
a->printPretty();
std::cout << (a->insert(378)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
e->printPretty();
std::cout << (c->insert(313)) << std::endl;
std::cout << (c->remove(13)) << std::endl;
d->printPretty();
std::cout << (a->insert(283)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
*a=*c;
*a=*a;
*c=*a;
*e=*a;
e->printPretty();
std::cout << (d->remove(2)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (c->insert(176)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (e->insert(188)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (d->insert(297)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(275)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (e->remove(494)) << std::endl;
*e=*d;
std::cout << (a->insert(174)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
e->printPretty();
std::cout << (e->remove(188)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
*b=*b;
std::cout << (b->remove(392)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
b->printPretty();
std::cout << (a->insert(493)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (d->remove(299)) << std::endl;
std::cout << (a->remove(151)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (e->insert(255)) << std::endl;
c->printPretty();
std::cout << (b->insert(431)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
std::cout << (a->remove(299)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (a->insert(395)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->insert(104)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
*e=*e;
std::cout << (b->remove(174)) << std::endl;
*d=*d;
*e=*a;
e->printPretty();
b->printPretty();
std::cout << (d->remove(80)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
a->printPretty();
std::cout << (e->remove(297)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
*e=*a;
std::cout << (a->insert(395)) << std::endl;
a->printPretty();
std::cout << (e->remove(22)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*d=*a;
std::cout << (a->insert(473)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
e->printPretty();
std::cout << (d->insert(368)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
c->printPretty();
std::cout << (c->remove(395)) << std::endl;
e->printPretty();
std::cout << (c->insert(22)) << std::endl;
a->printPretty();
d->printPretty();
d->printPretty();
*a=*e;
std::cout << (d->insert(115)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
*e=*b;
*a=*d;
std::cout << (b->insert(266)) << std::endl;
*e=*e;
std::cout << (a->insert(431)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
std::cout << (d->remove(376)) << std::endl;
return 0;
}
