#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(407)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
*c=*d;
*c=*b;
b->printPretty();
*e=*e;
std::cout << (b->insert(448)) << std::endl;
std::cout << (d->insert(144)) << std::endl;
c->printPretty();
a->printPretty();
e->printPretty();
*b=*a;
*c=*c;
*d=*b;
std::cout << (b->insert(105)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (b->insert(105)) << std::endl;
*c=*b;
*c=*d;
std::cout << (b->remove(105)) << std::endl;
d->printPretty();
std::cout << (b->remove(436)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(469)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (b->remove(242)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->remove(377)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->remove(286)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
*c=*a;
std::cout << (d->remove(7)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (d->insert(60)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
std::cout << (b->remove(267)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (c->remove(219)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (e->remove(496)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
d->printPretty();
std::cout << (d->remove(230)) << std::endl;
*c=*e;
*b=*b;
std::cout << (c->remove(395)) << std::endl;
*c=*b;
std::cout << (e->insert(58)) << std::endl;
*a=*a;
std::cout << (e->insert(58)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (c->remove(57)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
b->printPretty();
std::cout << (b->remove(487)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
*b=*d;
std::cout << (c->remove(425)) << std::endl;
c->printPretty();
std::cout << (d->remove(197)) << std::endl;
*a=*b;
*d=*c;
std::cout << (b->remove(197)) << std::endl;
c->printPretty();
std::cout << (d->remove(396)) << std::endl;
std::cout << (d->insert(323)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (d->insert(323)) << std::endl;
c->printPretty();
std::cout << (e->insert(143)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(370)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
a->printPretty();
std::cout << (d->insert(323)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
*c=*b;
std::cout << (a->remove(460)) << std::endl;
std::cout << (a->insert(315)) << std::endl;
d->printPretty();
std::cout << (d->insert(237)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (d->insert(237)) << std::endl;
*e=*a;
std::cout << (d->insert(436)) << std::endl;
std::cout << (e->remove(315)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (d->remove(315)) << std::endl;
std::cout << (b->remove(358)) << std::endl;
std::cout << (a->insert(11)) << std::endl;
*b=*d;
std::cout << (d->insert(164)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
*b=*a;
*e=*d;
*b=*e;
std::cout << (e->remove(177)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (b->remove(478)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
*e=*d;
std::cout << (d->remove(164)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
*a=*b;
*e=*a;
c->printPretty();
std::cout << (d->insert(384)) << std::endl;
*b=*e;
std::cout << (c->remove(315)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->insert(164)) << std::endl;
std::cout << (b->insert(164)) << std::endl;
std::cout << (a->remove(164)) << std::endl;
e->printPretty();
*d=*d;
*c=*b;
std::cout << (b->remove(405)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
c->printPretty();
std::cout << (b->insert(146)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
d->printPretty();
b->printPretty();
d->printPretty();
std::cout << (b->insert(431)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
c->printPretty();
d->printPretty();
*d=*d;
std::cout << (c->remove(212)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
std::cout << (d->insert(485)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (d->insert(485)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (a->remove(55)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (a->remove(172)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
a->printPretty();
std::cout << (d->insert(52)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
b->printPretty();
std::cout << (d->insert(499)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (c->remove(307)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
e->printPretty();
std::cout << (a->remove(393)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
*b=*c;
e->printPretty();
*a=*a;
std::cout << (e->remove(314)) << std::endl;
*c=*a;
std::cout << (d->remove(240)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
*b=*e;
std::cout << (e->remove(150)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
*b=*d;
std::cout << (e->insert(296)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
*c=*a;
*b=*c;
std::cout << (b->remove(465)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
*c=*c;
std::cout << (b->insert(61)) << std::endl;
*e=*d;
*a=*c;
std::cout << (a->remove(196)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (b->insert(313)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (d->insert(286)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
*d=*e;
std::cout << (a->remove(433)) << std::endl;
*e=*a;
*e=*e;
e->printPretty();
std::cout << (d->insert(58)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->insert(129)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (a->remove(333)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
*e=*d;
std::cout << (d->remove(58)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
a->printPretty();
std::cout << (c->insert(61)) << std::endl;
c->printPretty();
std::cout << (a->insert(61)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
*a=*c;
std::cout << (b->insert(313)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
b->printPretty();
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (a->remove(452)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
*c=*a;
std::cout << (a->insert(263)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
*e=*c;
*a=*d;
std::cout << (e->insert(372)) << std::endl;
std::cout << (b->insert(129)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (a->remove(256)) << std::endl;
std::cout << (d->remove(287)) << std::endl;
std::cout << (a->remove(336)) << std::endl;
b->printPretty();
std::cout << (e->insert(139)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
d->printPretty();
std::cout << (e->insert(139)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
*b=*a;
std::cout << (d->remove(362)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (e->remove(139)) << std::endl;
std::cout << (d->remove(121)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->remove(67)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(198)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (d->remove(286)) << std::endl;
std::cout << (c->remove(158)) << std::endl;
a->printPretty();
std::cout << (b->remove(45)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
*a=*b;
std::cout << (e->remove(181)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (d->insert(29)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (b->remove(214)) << std::endl;
c->printPretty();
std::cout << (b->insert(346)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->insert(310)) << std::endl;
b->printPretty();
std::cout << (b->insert(346)) << std::endl;
*b=*c;
std::cout << (e->remove(372)) << std::endl;
std::cout << (b->remove(267)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
e->printPretty();
std::cout << (e->insert(426)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (d->remove(281)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (e->remove(463)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (e->remove(61)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (e->remove(299)) << std::endl;
*d=*b;
std::cout << (e->insert(426)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (b->insert(450)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (b->insert(36)) << std::endl;
*d=*a;
std::cout << (a->insert(325)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
e->printPretty();
std::cout << (a->remove(325)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
*a=*d;
*b=*a;
d->printPretty();
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
e->printPretty();
std::cout << (d->insert(325)) << std::endl;
c->printPretty();
std::cout << (c->insert(290)) << std::endl;
e->printPretty();
std::cout << (d->insert(38)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
d->printPretty();
std::cout << (a->remove(325)) << std::endl;
*d=*d;
std::cout << (d->insert(325)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
*a=*d;
std::cout << (c->remove(147)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
*c=*d;
std::cout << (e->remove(426)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
*a=*e;
a->printPretty();
*d=*b;
*e=*e;
std::cout << (b->remove(296)) << std::endl;
*e=*e;
std::cout << (e->remove(296)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (e->insert(78)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (e->remove(78)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (a->remove(224)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
*b=*e;
std::cout << (a->remove(277)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (d->remove(258)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
*c=*b;
std::cout << (b->insert(481)) << std::endl;
a->printPretty();
*a=*a;
*c=*e;
std::cout << (a->insert(438)) << std::endl;
b->printPretty();
*b=*d;
a->printPretty();
a->printPretty();
std::cout << (a->remove(158)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (e->insert(90)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(484)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
d->printPretty();
std::cout << (c->remove(236)) << std::endl;
a->printPretty();
std::cout << (d->insert(235)) << std::endl;
e->printPretty();
std::cout << (a->insert(296)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
std::cout << (a->remove(296)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
*e=*a;
std::cout << (e->insert(221)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (a->insert(438)) << std::endl;
std::cout << (b->remove(438)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(221)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (a->remove(438)) << std::endl;
c->printPretty();
std::cout << (d->remove(119)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
*e=*e;
std::cout << (c->remove(141)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
a->printPretty();
std::cout << (b->insert(221)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->remove(65)) << std::endl;
*a=*e;
std::cout << (b->insert(76)) << std::endl;
*c=*e;
std::cout << (d->insert(151)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (d->remove(151)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
*b=*e;
d->printPretty();
b->printPretty();
std::cout << (c->remove(221)) << std::endl;
c->printPretty();
std::cout << (b->remove(221)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
*a=*a;
std::cout << (d->insert(351)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (c->insert(304)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
a->printPretty();
std::cout << (c->insert(472)) << std::endl;
std::cout << (c->insert(304)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
*b=*c;
std::cout << (e->insert(221)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (b->remove(472)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (e->remove(286)) << std::endl;
*e=*a;
*d=*e;
std::cout << (e->remove(434)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (d->remove(97)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
*b=*a;
d->printPretty();
d->printPretty();
b->printPretty();
std::cout << (e->insert(398)) << std::endl;
std::cout << (d->remove(434)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
*a=*a;
*a=*a;
std::cout << (b->insert(274)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
*b=*d;
std::cout << (a->remove(224)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
*a=*d;
std::cout << (e->insert(86)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
d->printPretty();
std::cout << (d->remove(157)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (c->insert(412)) << std::endl;
std::cout << (d->remove(223)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (b->remove(189)) << std::endl;
*b=*a;
std::cout << (b->insert(226)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
*d=*e;
std::cout << (d->remove(86)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (d->remove(97)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
*a=*b;
std::cout << (c->remove(390)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
*b=*e;
std::cout << (c->remove(398)) << std::endl;
e->printPretty();
*a=*e;
d->printPretty();
std::cout << (b->remove(97)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
a->printPretty();
std::cout << (c->remove(300)) << std::endl;
std::cout << (c->remove(86)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (c->remove(120)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
e->printPretty();
*d=*c;
d->printPretty();
std::cout << (d->remove(204)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (a->insert(46)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (d->insert(141)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->insert(8)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (c->remove(211)) << std::endl;
std::cout << (b->insert(449)) << std::endl;
*d=*b;
*b=*b;
std::cout << (a->remove(309)) << std::endl;
*b=*e;
std::cout << (a->remove(181)) << std::endl;
return 0;
}
