#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(63)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (b->remove(41)) << std::endl;
std::cout << (c->remove(329)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(237)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
*e=*a;
c->printPretty();
b->printPretty();
*d=*c;
std::cout << (e->remove(62)) << std::endl;
a->printPretty();
std::cout << (e->remove(237)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (a->remove(237)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
std::cout << (b->remove(307)) << std::endl;
d->printPretty();
std::cout << (d->insert(156)) << std::endl;
b->printPretty();
a->printPretty();
*a=*d;
std::cout << (c->insert(300)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
e->printPretty();
std::cout << (d->remove(57)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
std::cout << (a->insert(490)) << std::endl;
c->printPretty();
std::cout << (a->remove(152)) << std::endl;
std::cout << (e->remove(431)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
a->printPretty();
std::cout << (e->insert(150)) << std::endl;
std::cout << (b->remove(103)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
b->printPretty();
*e=*a;
*a=*a;
a->printPretty();
*e=*b;
*e=*c;
d->printPretty();
*e=*e;
std::cout << (d->insert(77)) << std::endl;
a->printPretty();
std::cout << (d->insert(77)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(77)) << std::endl;
std::cout << (a->remove(490)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (e->remove(479)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (b->remove(264)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
b->printPretty();
std::cout << (c->insert(191)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (b->insert(39)) << std::endl;
*d=*c;
std::cout << (b->insert(39)) << std::endl;
c->printPretty();
std::cout << (d->insert(35)) << std::endl;
*c=*b;
std::cout << (a->insert(263)) << std::endl;
std::cout << (b->insert(39)) << std::endl;
std::cout << (b->remove(41)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
*a=*c;
std::cout << (d->insert(35)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
d->printPretty();
std::cout << (d->remove(152)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->insert(109)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (d->remove(191)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
*a=*b;
std::cout << (e->remove(447)) << std::endl;
d->printPretty();
std::cout << (d->remove(109)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
c->printPretty();
std::cout << (c->remove(124)) << std::endl;
b->printPretty();
std::cout << (a->remove(258)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
*e=*a;
std::cout << (a->insert(241)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
e->printPretty();
std::cout << (d->remove(256)) << std::endl;
*b=*a;
std::cout << (d->remove(341)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->remove(421)) << std::endl;
std::cout << (b->insert(90)) << std::endl;
*a=*e;
std::cout << (d->remove(362)) << std::endl;
std::cout << (c->remove(39)) << std::endl;
std::cout << (c->insert(327)) << std::endl;
std::cout << (c->remove(327)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
*d=*b;
std::cout << (c->remove(402)) << std::endl;
*d=*b;
*a=*c;
std::cout << (d->insert(391)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
d->printPretty();
std::cout << (e->remove(306)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
*c=*d;
std::cout << (b->remove(68)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
*d=*e;
std::cout << (e->remove(160)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
*a=*d;
d->printPretty();
e->printPretty();
std::cout << (e->insert(39)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(313)) << std::endl;
std::cout << (b->remove(490)) << std::endl;
std::cout << (e->insert(110)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
d->printPretty();
std::cout << (b->insert(39)) << std::endl;
a->printPretty();
std::cout << (d->insert(389)) << std::endl;
std::cout << (d->insert(492)) << std::endl;
*b=*c;
std::cout << (c->insert(241)) << std::endl;
std::cout << (c->insert(405)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
c->printPretty();
std::cout << (b->remove(290)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
*a=*d;
std::cout << (a->remove(492)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (a->insert(39)) << std::endl;
*d=*d;
std::cout << (b->remove(389)) << std::endl;
c->printPretty();
std::cout << (b->remove(479)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(28)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
*b=*a;
std::cout << (b->remove(39)) << std::endl;
*e=*a;
std::cout << (b->remove(264)) << std::endl;
*c=*c;
*d=*c;
std::cout << (a->remove(4)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
e->printPretty();
std::cout << (e->insert(68)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (c->remove(11)) << std::endl;
*c=*d;
std::cout << (c->remove(39)) << std::endl;
*b=*c;
std::cout << (d->remove(156)) << std::endl;
*e=*a;
std::cout << (c->remove(405)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (a->insert(212)) << std::endl;
std::cout << (b->insert(162)) << std::endl;
b->printPretty();
std::cout << (c->insert(391)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
a->printPretty();
std::cout << (e->insert(389)) << std::endl;
std::cout << (c->insert(90)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (a->insert(436)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (d->insert(391)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
*b=*d;
std::cout << (b->insert(487)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
c->printPretty();
std::cout << (e->remove(478)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
c->printPretty();
std::cout << (d->remove(416)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
b->printPretty();
std::cout << (e->remove(487)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
*c=*a;
c->printPretty();
a->printPretty();
std::cout << (c->remove(202)) << std::endl;
e->printPretty();
std::cout << (b->remove(469)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (a->remove(176)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
*a=*c;
std::cout << (c->insert(436)) << std::endl;
*b=*d;
*c=*b;
std::cout << (e->insert(312)) << std::endl;
b->printPretty();
std::cout << (e->insert(440)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
b->printPretty();
std::cout << (b->remove(98)) << std::endl;
std::cout << (a->insert(436)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
a->printPretty();
std::cout << (e->insert(312)) << std::endl;
*b=*c;
std::cout << (a->remove(7)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
std::cout << (a->remove(436)) << std::endl;
c->printPretty();
std::cout << (c->remove(304)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
d->printPretty();
std::cout << (d->insert(197)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (d->insert(311)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (d->insert(311)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (d->insert(264)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
*a=*c;
std::cout << (d->remove(43)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
d->printPretty();
*a=*b;
c->printPretty();
c->printPretty();
std::cout << (c->insert(39)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
c->printPretty();
std::cout << (c->remove(26)) << std::endl;
c->printPretty();
std::cout << (c->remove(39)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
*b=*d;
std::cout << (e->insert(475)) << std::endl;
std::cout << (d->remove(348)) << std::endl;
e->printPretty();
std::cout << (d->remove(304)) << std::endl;
d->printPretty();
std::cout << (d->remove(249)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (e->insert(304)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
*d=*a;
std::cout << (b->remove(304)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (a->remove(440)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (d->remove(295)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
a->printPretty();
std::cout << (a->remove(236)) << std::endl;
d->printPretty();
std::cout << (e->remove(19)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (d->insert(304)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
d->printPretty();
std::cout << (e->insert(260)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
b->printPretty();
a->printPretty();
*c=*c;
std::cout << (e->insert(426)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
std::cout << (b->remove(90)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
*b=*d;
std::cout << (b->insert(408)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
*a=*e;
std::cout << (a->remove(260)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
*c=*e;
*b=*a;
std::cout << (e->insert(131)) << std::endl;
*b=*a;
std::cout << (d->remove(391)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
*d=*a;
std::cout << (d->insert(215)) << std::endl;
e->printPretty();
std::cout << (c->insert(440)) << std::endl;
*a=*c;
std::cout << (e->insert(260)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
std::cout << (c->insert(90)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
a->printPretty();
std::cout << (b->insert(304)) << std::endl;
*b=*d;
std::cout << (b->insert(475)) << std::endl;
c->printPretty();
std::cout << (a->insert(415)) << std::endl;
std::cout << (a->insert(435)) << std::endl;
b->printPretty();
std::cout << (e->remove(107)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
*d=*a;
b->printPretty();
*e=*b;
*b=*b;
std::cout << (a->remove(447)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (c->insert(361)) << std::endl;
std::cout << (a->insert(107)) << std::endl;
c->printPretty();
std::cout << (e->remove(447)) << std::endl;
c->printPretty();
std::cout << (d->insert(260)) << std::endl;
std::cout << (b->insert(426)) << std::endl;
std::cout << (e->remove(304)) << std::endl;
std::cout << (e->remove(440)) << std::endl;
std::cout << (e->remove(495)) << std::endl;
std::cout << (e->remove(90)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (e->insert(435)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (b->remove(90)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (c->insert(34)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (d->insert(107)) << std::endl;
*a=*a;
std::cout << (d->remove(90)) << std::endl;
e->printPretty();
std::cout << (d->insert(447)) << std::endl;
std::cout << (e->remove(303)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
*d=*c;
e->printPretty();
d->printPretty();
std::cout << (a->insert(215)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
*a=*c;
std::cout << (c->insert(418)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (a->remove(364)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->remove(440)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
*a=*a;
std::cout << (d->insert(260)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (a->remove(435)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
e->printPretty();
std::cout << (d->insert(316)) << std::endl;
c->printPretty();
*e=*c;
b->printPretty();
std::cout << (c->insert(245)) << std::endl;
*e=*c;
std::cout << (e->insert(312)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (b->remove(385)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (e->remove(449)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
a->printPretty();
std::cout << (d->remove(496)) << std::endl;
std::cout << (b->remove(167)) << std::endl;
*c=*a;
a->printPretty();
d->printPretty();
std::cout << (d->insert(127)) << std::endl;
std::cout << (a->insert(145)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
d->printPretty();
d->printPretty();
a->printPretty();
std::cout << (b->insert(304)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
std::cout << (c->remove(145)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (d->remove(284)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
c->printPretty();
std::cout << (d->insert(311)) << std::endl;
std::cout << (a->insert(271)) << std::endl;
std::cout << (b->remove(257)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (c->insert(418)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
*d=*d;
*a=*b;
std::cout << (d->remove(487)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (c->remove(435)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (d->remove(276)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (b->remove(215)) << std::endl;
*b=*e;
std::cout << (d->insert(312)) << std::endl;
c->printPretty();
std::cout << (c->remove(426)) << std::endl;
*b=*e;
std::cout << (e->remove(332)) << std::endl;
*e=*a;
*c=*d;
std::cout << (a->insert(215)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
*e=*e;
std::cout << (c->insert(260)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
*d=*c;
std::cout << (e->remove(121)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
b->printPretty();
std::cout << (d->insert(437)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(475)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (a->insert(435)) << std::endl;
*e=*b;
std::cout << (c->insert(90)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
e->printPretty();
std::cout << (c->remove(475)) << std::endl;
*d=*d;
std::cout << (c->remove(311)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (e->remove(215)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (b->remove(435)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
std::cout << (e->remove(313)) << std::endl;
std::cout << (d->insert(219)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
*e=*e;
std::cout << (b->insert(332)) << std::endl;
*d=*b;
std::cout << (b->insert(440)) << std::endl;
*b=*a;
std::cout << (b->remove(186)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (d->insert(215)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
std::cout << (b->insert(392)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (b->remove(145)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (b->insert(426)) << std::endl;
std::cout << (a->insert(145)) << std::endl;
d->printPretty();
std::cout << (b->remove(107)) << std::endl;
e->printPretty();
std::cout << (e->insert(134)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
*d=*b;
std::cout << (c->remove(180)) << std::endl;
d->printPretty();
std::cout << (e->remove(304)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
*b=*a;
std::cout << (e->insert(394)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
d->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
*a=*a;
std::cout << (e->remove(256)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
c->printPretty();
std::cout << (b->insert(136)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
*b=*e;
std::cout << (b->remove(241)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
std::cout << (e->insert(381)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
*b=*b;
std::cout << (a->insert(78)) << std::endl;
*d=*d;
std::cout << (a->insert(235)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (a->insert(286)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
c->printPretty();
std::cout << (d->insert(394)) << std::endl;
std::cout << (c->remove(215)) << std::endl;
*a=*c;
std::cout << (a->insert(440)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
std::cout << (b->insert(31)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (b->insert(381)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
a->printPretty();
std::cout << (e->remove(362)) << std::endl;
c->printPretty();
std::cout << (e->remove(394)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
*e=*a;
*d=*a;
std::cout << (d->insert(235)) << std::endl;
*a=*d;
std::cout << (e->remove(383)) << std::endl;
std::cout << (e->remove(299)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
std::cout << (b->insert(31)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
*e=*e;
std::cout << (d->insert(107)) << std::endl;
c->printPretty();
std::cout << (c->remove(113)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (a->remove(145)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (e->insert(273)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
*c=*e;
std::cout << (e->remove(414)) << std::endl;
return 0;
}
