#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(411)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (b->remove(365)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
std::cout << (a->remove(447)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
b->printPretty();
std::cout << (e->insert(184)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
std::cout << (d->insert(491)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
std::cout << (d->insert(468)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
a->printPretty();
b->printPretty();
e->printPretty();
a->printPretty();
std::cout << (c->remove(217)) << std::endl;
b->printPretty();
std::cout << (b->remove(75)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
b->printPretty();
std::cout << (d->remove(491)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
*b=*c;
std::cout << (b->remove(111)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
c->printPretty();
std::cout << (a->remove(11)) << std::endl;
std::cout << (c->insert(343)) << std::endl;
std::cout << (e->insert(5)) << std::endl;
*e=*c;
std::cout << (c->insert(169)) << std::endl;
*d=*d;
std::cout << (e->remove(111)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(101)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (d->insert(468)) << std::endl;
*d=*c;
std::cout << (d->remove(343)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
c->printPretty();
std::cout << (a->remove(387)) << std::endl;
*d=*e;
d->printPretty();
*d=*b;
*a=*a;
c->printPretty();
std::cout << (a->insert(261)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
std::cout << (c->insert(343)) << std::endl;
*d=*a;
std::cout << (c->remove(343)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
std::cout << (a->insert(347)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
*e=*a;
std::cout << (c->insert(111)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (d->insert(151)) << std::endl;
*b=*b;
std::cout << (b->insert(187)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
b->printPretty();
b->printPretty();
*e=*e;
std::cout << (b->remove(119)) << std::endl;
*e=*b;
*a=*e;
std::cout << (e->insert(187)) << std::endl;
std::cout << (d->remove(151)) << std::endl;
e->printPretty();
std::cout << (b->insert(187)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (b->remove(187)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
std::cout << (e->remove(187)) << std::endl;
*a=*d;
std::cout << (a->insert(261)) << std::endl;
*b=*c;
*a=*c;
std::cout << (b->insert(337)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
b->printPretty();
std::cout << (a->insert(268)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
*e=*c;
*e=*b;
std::cout << (e->insert(24)) << std::endl;
c->printPretty();
std::cout << (c->remove(169)) << std::endl;
*a=*e;
std::cout << (e->remove(169)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (e->insert(233)) << std::endl;
*d=*c;
*c=*d;
*b=*b;
c->printPretty();
std::cout << (a->insert(60)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
c->printPretty();
std::cout << (a->insert(179)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (a->insert(24)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
*a=*d;
*b=*d;
std::cout << (c->remove(15)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
*e=*b;
*a=*e;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->insert(55)) << std::endl;
std::cout << (d->remove(31)) << std::endl;
a->printPretty();
std::cout << (a->insert(310)) << std::endl;
*a=*c;
std::cout << (c->remove(359)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
*e=*d;
*e=*d;
std::cout << (d->insert(371)) << std::endl;
std::cout << (a->remove(55)) << std::endl;
*d=*c;
std::cout << (b->insert(367)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
*c=*b;
std::cout << (a->remove(128)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (e->remove(68)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (c->remove(305)) << std::endl;
c->printPretty();
std::cout << (d->remove(450)) << std::endl;
std::cout << (c->remove(20)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
c->printPretty();
*c=*c;
*e=*a;
c->printPretty();
*e=*a;
a->printPretty();
*b=*d;
d->printPretty();
d->printPretty();
std::cout << (e->remove(351)) << std::endl;
a->printPretty();
std::cout << (b->remove(47)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
c->printPretty();
*d=*b;
*d=*b;
std::cout << (a->insert(253)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->remove(45)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
b->printPretty();
std::cout << (a->insert(253)) << std::endl;
e->printPretty();
std::cout << (d->insert(232)) << std::endl;
*e=*c;
std::cout << (c->insert(345)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
*c=*a;
std::cout << (a->remove(181)) << std::endl;
*e=*a;
b->printPretty();
e->printPretty();
std::cout << (c->remove(253)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (c->insert(457)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (c->insert(433)) << std::endl;
*c=*e;
std::cout << (e->insert(335)) << std::endl;
std::cout << (c->remove(253)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (d->remove(175)) << std::endl;
e->printPretty();
std::cout << (a->remove(253)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(319)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
*e=*b;
std::cout << (e->remove(253)) << std::endl;
*c=*e;
*a=*b;
a->printPretty();
std::cout << (a->insert(253)) << std::endl;
c->printPretty();
std::cout << (a->insert(253)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
std::cout << (b->insert(301)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
e->printPretty();
std::cout << (b->remove(301)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
a->printPretty();
std::cout << (e->insert(388)) << std::endl;
std::cout << (e->insert(388)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(253)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
d->printPretty();
std::cout << (c->insert(153)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
*b=*a;
std::cout << (a->remove(457)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
a->printPretty();
b->printPretty();
*c=*a;
std::cout << (a->remove(253)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (b->insert(253)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
d->printPretty();
std::cout << (e->remove(232)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
d->printPretty();
std::cout << (b->insert(112)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
*a=*b;
std::cout << (d->insert(232)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
a->printPretty();
std::cout << (e->remove(212)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
std::cout << (c->remove(211)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
b->printPretty();
std::cout << (d->remove(139)) << std::endl;
std::cout << (c->insert(451)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
c->printPretty();
std::cout << (d->insert(212)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
*e=*e;
std::cout << (a->insert(84)) << std::endl;
*b=*d;
*a=*e;
e->printPretty();
std::cout << (e->insert(446)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
*e=*b;
std::cout << (d->remove(225)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (a->remove(322)) << std::endl;
std::cout << (e->insert(212)) << std::endl;
std::cout << (b->remove(212)) << std::endl;
std::cout << (b->remove(446)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (c->insert(498)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
*b=*e;
std::cout << (d->remove(461)) << std::endl;
*a=*d;
std::cout << (c->insert(212)) << std::endl;
*c=*a;
*d=*e;
*b=*e;
std::cout << (a->insert(237)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
*d=*a;
*a=*c;
std::cout << (b->remove(422)) << std::endl;
std::cout << (e->remove(252)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (b->remove(446)) << std::endl;
a->printPretty();
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
d->printPretty();
std::cout << (d->remove(35)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (a->remove(252)) << std::endl;
std::cout << (a->insert(16)) << std::endl;
std::cout << (d->insert(237)) << std::endl;
a->printPretty();
std::cout << (e->remove(227)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
std::cout << (c->remove(446)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
*d=*a;
std::cout << (c->remove(464)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->remove(267)) << std::endl;
*d=*e;
*b=*a;
d->printPretty();
c->printPretty();
*d=*e;
std::cout << (c->remove(155)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->remove(21)) << std::endl;
*b=*c;
std::cout << (e->remove(252)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (a->remove(35)) << std::endl;
b->printPretty();
std::cout << (d->insert(252)) << std::endl;
*b=*e;
std::cout << (c->remove(148)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
*d=*c;
*d=*d;
std::cout << (d->insert(313)) << std::endl;
*e=*b;
*b=*a;
std::cout << (d->insert(313)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
*b=*d;
std::cout << (d->remove(313)) << std::endl;
*d=*d;
*e=*d;
*b=*d;
std::cout << (d->remove(477)) << std::endl;
b->printPretty();
std::cout << (e->remove(477)) << std::endl;
std::cout << (e->insert(278)) << std::endl;
e->printPretty();
*a=*c;
*b=*d;
std::cout << (c->insert(98)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (a->remove(99)) << std::endl;
*a=*b;
a->printPretty();
a->printPretty();
std::cout << (c->remove(241)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (a->remove(374)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (c->remove(98)) << std::endl;
*e=*c;
std::cout << (c->remove(11)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
*b=*c;
*d=*d;
*d=*c;
std::cout << (d->insert(486)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
a->printPretty();
e->printPretty();
*e=*e;
std::cout << (b->remove(287)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
std::cout << (e->insert(342)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (a->remove(300)) << std::endl;
*b=*c;
*e=*e;
std::cout << (c->remove(199)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
e->printPretty();
std::cout << (e->remove(287)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
*e=*b;
std::cout << (c->remove(1)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
b->printPretty();
std::cout << (a->insert(259)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
d->printPretty();
std::cout << (c->insert(454)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
*b=*e;
std::cout << (a->insert(259)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (c->remove(454)) << std::endl;
*c=*b;
std::cout << (c->remove(453)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
std::cout << (b->insert(28)) << std::endl;
b->printPretty();
std::cout << (c->insert(392)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
b->printPretty();
std::cout << (b->insert(28)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
b->printPretty();
b->printPretty();
b->printPretty();
std::cout << (d->insert(346)) << std::endl;
std::cout << (b->insert(215)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (d->insert(457)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (d->insert(428)) << std::endl;
std::cout << (e->insert(488)) << std::endl;
std::cout << (c->insert(325)) << std::endl;
e->printPretty();
std::cout << (b->remove(303)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
*a=*c;
std::cout << (d->remove(428)) << std::endl;
*c=*b;
std::cout << (e->remove(165)) << std::endl;
a->printPretty();
std::cout << (b->remove(28)) << std::endl;
*d=*a;
std::cout << (a->insert(392)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
b->printPretty();
*d=*c;
*d=*e;
std::cout << (c->remove(303)) << std::endl;
*d=*a;
std::cout << (d->remove(345)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
*b=*d;
d->printPretty();
*d=*e;
std::cout << (b->insert(75)) << std::endl;
c->printPretty();
e->printPretty();
*a=*e;
std::cout << (a->insert(488)) << std::endl;
a->printPretty();
*b=*c;
b->printPretty();
std::cout << (d->insert(390)) << std::endl;
*d=*a;
std::cout << (c->insert(28)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (a->insert(488)) << std::endl;
*d=*b;
std::cout << (a->remove(165)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
e->printPretty();
std::cout << (e->remove(247)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (c->remove(67)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
*d=*b;
std::cout << (a->remove(333)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (e->insert(191)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
*e=*c;
std::cout << (a->remove(22)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (a->insert(25)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(226)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (a->insert(488)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (d->remove(135)) << std::endl;
*b=*d;
std::cout << (d->insert(300)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
*d=*c;
std::cout << (a->remove(226)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (d->remove(131)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
a->printPretty();
std::cout << (c->insert(404)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (d->insert(156)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
*d=*a;
*a=*c;
std::cout << (a->insert(295)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
e->printPretty();
std::cout << (e->insert(256)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
a->printPretty();
std::cout << (a->insert(148)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
*c=*d;
std::cout << (b->remove(137)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->remove(488)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (d->insert(372)) << std::endl;
c->printPretty();
std::cout << (d->remove(464)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
*d=*b;
std::cout << (b->remove(399)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
b->printPretty();
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
a->printPretty();
std::cout << (a->insert(176)) << std::endl;
*d=*d;
std::cout << (c->insert(25)) << std::endl;
std::cout << (c->remove(349)) << std::endl;
d->printPretty();
std::cout << (b->insert(297)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
*b=*a;
*b=*b;
std::cout << (a->remove(170)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (b->remove(6)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
e->printPretty();
*e=*a;
b->printPretty();
std::cout << (d->insert(235)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (a->insert(176)) << std::endl;
*c=*d;
std::cout << (e->insert(53)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
d->printPretty();
std::cout << (e->remove(27)) << std::endl;
*e=*c;
std::cout << (d->insert(235)) << std::endl;
std::cout << (c->remove(242)) << std::endl;
std::cout << (c->remove(63)) << std::endl;
c->printPretty();
std::cout << (a->remove(176)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
b->printPretty();
std::cout << (d->remove(242)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
*a=*c;
b->printPretty();
*a=*d;
*d=*b;
*e=*e;
std::cout << (b->remove(443)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
return 0;
}
