#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->insert(373)) << std::endl;
std::cout << (b->remove(373)) << std::endl;
std::cout << (b->insert(387)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
*a=*a;
std::cout << (a->remove(188)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
b->printPretty();
std::cout << (a->insert(56)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
*b=*a;
std::cout << (b->remove(189)) << std::endl;
*b=*b;
*a=*b;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (c->remove(472)) << std::endl;
a->printPretty();
std::cout << (a->insert(146)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*a=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
c->printPretty();
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (d->remove(56)) << std::endl;
std::cout << (e->insert(441)) << std::endl;
*a=*b;
b->printPretty();
c->printPretty();
std::cout << (a->remove(56)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
*a=*a;
a->printPretty();
*d=*b;
std::cout << (b->remove(56)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (c->insert(98)) << std::endl;
std::cout << (e->remove(441)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
e->printPretty();
std::cout << (d->remove(106)) << std::endl;
*b=*c;
std::cout << (e->insert(94)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
a->printPretty();
std::cout << (e->remove(197)) << std::endl;
*c=*e;
std::cout << (c->remove(422)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
c->printPretty();
std::cout << (d->insert(115)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (a->remove(488)) << std::endl;
e->printPretty();
std::cout << (c->remove(283)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (e->insert(94)) << std::endl;
*d=*e;
std::cout << (d->insert(380)) << std::endl;
std::cout << (d->insert(187)) << std::endl;
std::cout << (d->remove(94)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->remove(94)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (d->remove(44)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
c->printPretty();
std::cout << (d->insert(409)) << std::endl;
std::cout << (a->insert(244)) << std::endl;
e->printPretty();
std::cout << (e->remove(381)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
*c=*c;
std::cout << (e->remove(280)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(409)) << std::endl;
c->printPretty();
std::cout << (d->remove(409)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (b->insert(20)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
*a=*c;
std::cout << (c->remove(322)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (e->remove(354)) << std::endl;
*e=*a;
std::cout << (a->insert(28)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
*d=*b;
*a=*a;
*c=*b;
std::cout << (b->insert(110)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
e->printPretty();
std::cout << (c->remove(336)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
b->printPretty();
std::cout << (a->remove(29)) << std::endl;
*c=*a;
std::cout << (a->remove(123)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
a->printPretty();
std::cout << (a->remove(494)) << std::endl;
b->printPretty();
a->printPretty();
d->printPretty();
*b=*a;
std::cout << (c->remove(322)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
*b=*c;
*a=*a;
b->printPretty();
std::cout << (d->remove(192)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
*d=*b;
std::cout << (c->remove(234)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->insert(322)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
b->printPretty();
std::cout << (e->remove(348)) << std::endl;
*c=*e;
std::cout << (b->insert(300)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
d->printPretty();
std::cout << (c->insert(255)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
std::cout << (a->remove(378)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (d->remove(422)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
*a=*c;
std::cout << (a->remove(322)) << std::endl;
*e=*b;
std::cout << (c->remove(394)) << std::endl;
*d=*d;
*e=*a;
c->printPretty();
std::cout << (a->remove(333)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
*d=*d;
std::cout << (b->remove(38)) << std::endl;
b->printPretty();
std::cout << (d->remove(41)) << std::endl;
*a=*e;
*d=*d;
std::cout << (e->remove(255)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
*a=*e;
std::cout << (e->remove(497)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
c->printPretty();
std::cout << (d->insert(336)) << std::endl;
*b=*c;
std::cout << (d->insert(260)) << std::endl;
c->printPretty();
*d=*e;
a->printPretty();
std::cout << (a->remove(364)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
a->printPretty();
*d=*e;
a->printPretty();
*e=*b;
std::cout << (c->remove(255)) << std::endl;
d->printPretty();
std::cout << (e->insert(475)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (a->insert(405)) << std::endl;
std::cout << (c->insert(255)) << std::endl;
*c=*c;
std::cout << (c->remove(264)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
*b=*b;
std::cout << (d->insert(483)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (c->insert(322)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
*a=*a;
std::cout << (c->remove(106)) << std::endl;
*d=*c;
std::cout << (b->remove(255)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(475)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (c->remove(391)) << std::endl;
*b=*a;
*e=*c;
*d=*d;
*a=*a;
std::cout << (d->insert(275)) << std::endl;
*b=*a;
std::cout << (d->remove(61)) << std::endl;
*b=*c;
b->printPretty();
d->printPretty();
std::cout << (e->insert(255)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (d->remove(275)) << std::endl;
*c=*b;
std::cout << (c->remove(367)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (a->remove(144)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
*d=*d;
*d=*e;
std::cout << (a->remove(205)) << std::endl;
*a=*d;
*b=*c;
std::cout << (c->remove(182)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (b->insert(227)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
b->printPretty();
std::cout << (c->insert(263)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(322)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->remove(272)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
*c=*c;
e->printPretty();
c->printPretty();
*d=*c;
std::cout << (a->remove(300)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
*c=*b;
b->printPretty();
std::cout << (c->insert(79)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
*c=*d;
std::cout << (a->remove(460)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
d->printPretty();
b->printPretty();
*a=*a;
std::cout << (c->insert(43)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (b->remove(459)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
e->printPretty();
std::cout << (c->remove(240)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
b->printPretty();
std::cout << (b->remove(353)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
std::cout << (a->remove(500)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (b->remove(10)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (d->remove(166)) << std::endl;
*c=*c;
std::cout << (b->insert(110)) << std::endl;
*a=*b;
std::cout << (d->remove(463)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
*a=*e;
*d=*e;
std::cout << (d->remove(43)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
*b=*d;
std::cout << (d->remove(381)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
*e=*d;
std::cout << (a->insert(306)) << std::endl;
a->printPretty();
std::cout << (a->insert(295)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (b->remove(381)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (a->insert(351)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (a->remove(191)) << std::endl;
*a=*b;
std::cout << (c->insert(306)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
*c=*b;
d->printPretty();
*b=*c;
*c=*d;
a->printPretty();
std::cout << (b->insert(407)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
*e=*c;
*d=*d;
std::cout << (e->insert(185)) << std::endl;
d->printPretty();
std::cout << (b->remove(344)) << std::endl;
*d=*e;
std::cout << (c->insert(43)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(440)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
*d=*d;
std::cout << (a->insert(289)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->insert(390)) << std::endl;
e->printPretty();
std::cout << (e->insert(185)) << std::endl;
d->printPretty();
std::cout << (b->remove(376)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
d->printPretty();
std::cout << (c->remove(399)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (b->remove(398)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (a->insert(87)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
*e=*e;
std::cout << (c->remove(460)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
*d=*a;
b->printPretty();
e->printPretty();
std::cout << (e->remove(66)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
e->printPretty();
std::cout << (d->remove(321)) << std::endl;
d->printPretty();
std::cout << (c->remove(1)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
*c=*a;
std::cout << (c->insert(269)) << std::endl;
std::cout << (d->remove(258)) << std::endl;
d->printPretty();
std::cout << (b->remove(91)) << std::endl;
std::cout << (b->insert(132)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (b->insert(132)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (a->insert(209)) << std::endl;
d->printPretty();
std::cout << (b->insert(8)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(173)) << std::endl;
c->printPretty();
std::cout << (c->insert(289)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (b->insert(261)) << std::endl;
b->printPretty();
std::cout << (c->remove(289)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (a->insert(289)) << std::endl;
*d=*a;
std::cout << (b->remove(381)) << std::endl;
e->printPretty();
std::cout << (b->insert(476)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (a->remove(116)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (a->insert(261)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
a->printPretty();
std::cout << (a->remove(87)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (e->remove(219)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
e->printPretty();
std::cout << (a->remove(488)) << std::endl;
a->printPretty();
std::cout << (e->insert(273)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(359)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
c->printPretty();
std::cout << (a->insert(261)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (e->remove(461)) << std::endl;
std::cout << (a->remove(261)) << std::endl;
b->printPretty();
std::cout << (e->remove(273)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(500)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (d->insert(49)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
b->printPretty();
*c=*e;
*e=*b;
std::cout << (d->remove(319)) << std::endl;
c->printPretty();
std::cout << (d->insert(209)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
*b=*c;
std::cout << (d->remove(495)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
*a=*d;
std::cout << (b->remove(196)) << std::endl;
*e=*b;
*b=*b;
std::cout << (b->insert(335)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
d->printPretty();
std::cout << (e->remove(249)) << std::endl;
d->printPretty();
a->printPretty();
e->printPretty();
c->printPretty();
std::cout << (e->remove(452)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
c->printPretty();
std::cout << (c->insert(335)) << std::endl;
*d=*e;
std::cout << (d->remove(335)) << std::endl;
e->printPretty();
std::cout << (c->remove(335)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (c->insert(457)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
*a=*c;
std::cout << (a->remove(255)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
*c=*c;
a->printPretty();
*e=*a;
*d=*d;
c->printPretty();
std::cout << (c->remove(3)) << std::endl;
*d=*b;
*d=*d;
std::cout << (e->insert(152)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (e->insert(120)) << std::endl;
std::cout << (c->remove(457)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
*b=*d;
c->printPretty();
*b=*e;
a->printPretty();
std::cout << (b->remove(38)) << std::endl;
*e=*d;
d->printPretty();
*c=*b;
std::cout << (e->remove(496)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
d->printPretty();
std::cout << (a->remove(46)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
*c=*b;
a->printPretty();
*c=*d;
std::cout << (b->remove(284)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
*e=*b;
std::cout << (e->insert(120)) << std::endl;
*a=*b;
*d=*b;
std::cout << (b->insert(120)) << std::endl;
b->printPretty();
e->printPretty();
b->printPretty();
std::cout << (a->insert(85)) << std::endl;
*b=*b;
*a=*c;
a->printPretty();
d->printPretty();
std::cout << (e->remove(162)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
*d=*b;
std::cout << (e->remove(205)) << std::endl;
std::cout << (d->insert(457)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (a->remove(320)) << std::endl;
*e=*b;
std::cout << (a->insert(120)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
*d=*e;
*a=*b;
std::cout << (a->insert(120)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
*d=*e;
std::cout << (b->remove(120)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (b->insert(470)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
a->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->insert(448)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
c->printPretty();
std::cout << (a->insert(120)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
c->printPretty();
std::cout << (a->insert(120)) << std::endl;
*d=*b;
std::cout << (d->insert(28)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
*e=*c;
std::cout << (e->remove(125)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->insert(120)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
*b=*d;
*b=*a;
std::cout << (d->remove(446)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
std::cout << (e->insert(221)) << std::endl;
c->printPretty();
std::cout << (b->insert(457)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
d->printPretty();
std::cout << (d->insert(470)) << std::endl;
e->printPretty();
std::cout << (d->insert(73)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
return 0;
}
