#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(83)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(83)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
*b=*b;
a->printPretty();
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (a->remove(454)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*c=*c;
std::cout << (c->insert(432)) << std::endl;
b->printPretty();
std::cout << (a->remove(85)) << std::endl;
e->printPretty();
*c=*b;
a->printPretty();
std::cout << (a->remove(333)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (d->insert(80)) << std::endl;
c->printPretty();
std::cout << (d->insert(45)) << std::endl;
d->printPretty();
*c=*c;
*e=*a;
a->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
*e=*b;
std::cout << (b->remove(174)) << std::endl;
std::cout << (b->insert(45)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
b->printPretty();
std::cout << (b->remove(45)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
d->printPretty();
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
*d=*b;
*e=*a;
b->printPretty();
*e=*e;
*c=*c;
std::cout << (a->insert(89)) << std::endl;
std::cout << (e->remove(430)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
b->printPretty();
b->printPretty();
*b=*b;
*d=*d;
std::cout << (a->remove(224)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
*d=*b;
*e=*b;
std::cout << (b->remove(415)) << std::endl;
std::cout << (b->remove(302)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (c->remove(131)) << std::endl;
*e=*a;
a->printPretty();
*a=*c;
e->printPretty();
*e=*c;
std::cout << (a->insert(153)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
*a=*c;
*b=*a;
*a=*c;
*d=*b;
std::cout << (d->insert(166)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (b->insert(161)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
std::cout << (d->remove(141)) << std::endl;
d->printPretty();
std::cout << (b->remove(161)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (b->insert(378)) << std::endl;
*c=*d;
b->printPretty();
*c=*d;
std::cout << (d->insert(450)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
*c=*d;
std::cout << (a->remove(468)) << std::endl;
d->printPretty();
std::cout << (c->insert(450)) << std::endl;
d->printPretty();
std::cout << (d->insert(450)) << std::endl;
*c=*b;
std::cout << (d->remove(450)) << std::endl;
c->printPretty();
std::cout << (b->remove(378)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
std::cout << (c->remove(378)) << std::endl;
b->printPretty();
std::cout << (e->remove(393)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
b->printPretty();
std::cout << (e->remove(97)) << std::endl;
c->printPretty();
*d=*a;
e->printPretty();
std::cout << (a->insert(166)) << std::endl;
std::cout << (b->insert(63)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (d->remove(375)) << std::endl;
e->printPretty();
std::cout << (e->remove(486)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
std::cout << (c->remove(446)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->insert(470)) << std::endl;
std::cout << (b->remove(63)) << std::endl;
*e=*d;
std::cout << (d->insert(445)) << std::endl;
b->printPretty();
std::cout << (c->remove(270)) << std::endl;
a->printPretty();
std::cout << (c->insert(206)) << std::endl;
d->printPretty();
std::cout << (a->remove(66)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (d->insert(204)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (d->remove(165)) << std::endl;
e->printPretty();
std::cout << (c->insert(206)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
*b=*d;
*e=*c;
std::cout << (e->insert(206)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (c->insert(206)) << std::endl;
std::cout << (e->insert(314)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
std::cout << (e->remove(328)) << std::endl;
*a=*e;
*a=*d;
*e=*b;
std::cout << (b->insert(155)) << std::endl;
*d=*e;
*c=*c;
b->printPretty();
std::cout << (a->insert(122)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
a->printPretty();
std::cout << (c->insert(373)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
*a=*a;
std::cout << (c->remove(373)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (c->remove(13)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
*b=*c;
*b=*d;
std::cout << (c->insert(206)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (e->remove(399)) << std::endl;
a->printPretty();
std::cout << (e->remove(419)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
e->printPretty();
std::cout << (d->insert(302)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->insert(3)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
a->printPretty();
std::cout << (c->remove(345)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->insert(396)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
b->printPretty();
std::cout << (c->insert(396)) << std::endl;
b->printPretty();
std::cout << (d->insert(460)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (e->insert(438)) << std::endl;
std::cout << (e->insert(3)) << std::endl;
std::cout << (e->insert(242)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
d->printPretty();
a->printPretty();
*b=*e;
*a=*b;
b->printPretty();
std::cout << (a->remove(91)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
e->printPretty();
std::cout << (e->remove(185)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
*d=*b;
std::cout << (e->insert(336)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
*c=*b;
std::cout << (c->insert(438)) << std::endl;
d->printPretty();
std::cout << (d->insert(438)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
e->printPretty();
std::cout << (a->insert(242)) << std::endl;
*e=*a;
d->printPretty();
a->printPretty();
std::cout << (e->remove(25)) << std::endl;
std::cout << (b->insert(438)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
c->printPretty();
std::cout << (e->remove(60)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (d->insert(438)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (b->remove(438)) << std::endl;
std::cout << (e->insert(81)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
std::cout << (a->insert(438)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
*e=*c;
*c=*d;
std::cout << (c->insert(125)) << std::endl;
d->printPretty();
std::cout << (d->remove(132)) << std::endl;
std::cout << (a->insert(310)) << std::endl;
*b=*e;
std::cout << (d->remove(49)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
*d=*c;
std::cout << (c->remove(336)) << std::endl;
e->printPretty();
std::cout << (a->remove(310)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (e->insert(223)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
*e=*c;
*d=*d;
std::cout << (c->insert(356)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
c->printPretty();
*e=*a;
*e=*d;
std::cout << (d->insert(356)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
*e=*d;
std::cout << (d->insert(481)) << std::endl;
a->printPretty();
*a=*c;
std::cout << (e->remove(145)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(111)) << std::endl;
std::cout << (e->remove(125)) << std::endl;
*a=*a;
std::cout << (a->remove(356)) << std::endl;
*e=*c;
std::cout << (d->insert(435)) << std::endl;
c->printPretty();
std::cout << (b->remove(209)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (a->insert(390)) << std::endl;
std::cout << (c->insert(389)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (c->remove(389)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
a->printPretty();
*b=*b;
*e=*b;
a->printPretty();
*a=*b;
*d=*a;
*d=*d;
std::cout << (d->insert(170)) << std::endl;
*a=*e;
std::cout << (a->remove(260)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
b->printPretty();
*a=*e;
e->printPretty();
std::cout << (c->remove(337)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (e->remove(445)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
std::cout << (e->insert(362)) << std::endl;
*a=*c;
std::cout << (b->remove(306)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
*c=*a;
std::cout << (c->insert(266)) << std::endl;
e->printPretty();
std::cout << (b->remove(175)) << std::endl;
b->printPretty();
std::cout << (c->insert(165)) << std::endl;
*c=*b;
std::cout << (d->insert(426)) << std::endl;
*c=*d;
std::cout << (d->insert(111)) << std::endl;
*b=*d;
std::cout << (b->insert(42)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (d->insert(124)) << std::endl;
e->printPretty();
std::cout << (c->remove(98)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->insert(426)) << std::endl;
d->printPretty();
std::cout << (c->remove(69)) << std::endl;
e->printPretty();
std::cout << (b->insert(330)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
b->printPretty();
std::cout << (a->remove(164)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
a->printPretty();
std::cout << (d->insert(177)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
*d=*d;
std::cout << (b->remove(341)) << std::endl;
*a=*a;
std::cout << (b->remove(19)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (e->remove(362)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (b->remove(293)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->remove(486)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
std::cout << (a->insert(398)) << std::endl;
*b=*d;
std::cout << (b->insert(177)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
a->printPretty();
*c=*e;
c->printPretty();
a->printPretty();
std::cout << (e->remove(31)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (d->remove(117)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(151)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (b->remove(324)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (c->insert(333)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
*e=*e;
std::cout << (d->remove(99)) << std::endl;
*c=*b;
*e=*e;
std::cout << (c->remove(456)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (b->remove(225)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
*e=*b;
std::cout << (e->insert(170)) << std::endl;
c->printPretty();
std::cout << (a->insert(149)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
*b=*b;
std::cout << (d->remove(25)) << std::endl;
std::cout << (e->remove(426)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->insert(124)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
*d=*c;
std::cout << (d->remove(160)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
*b=*a;
std::cout << (d->remove(177)) << std::endl;
*b=*e;
*e=*a;
std::cout << (b->insert(42)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
e->printPretty();
std::cout << (e->remove(106)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
a->printPretty();
std::cout << (e->remove(339)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (c->remove(277)) << std::endl;
b->printPretty();
std::cout << (c->insert(254)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (e->insert(32)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (b->remove(53)) << std::endl;
b->printPretty();
e->printPretty();
*b=*e;
e->printPretty();
e->printPretty();
std::cout << (d->remove(124)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
*a=*a;
*c=*e;
std::cout << (c->remove(281)) << std::endl;
*b=*b;
*a=*b;
std::cout << (e->insert(149)) << std::endl;
e->printPretty();
std::cout << (b->remove(149)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
std::cout << (a->insert(32)) << std::endl;
c->printPretty();
std::cout << (a->remove(32)) << std::endl;
std::cout << (d->insert(26)) << std::endl;
a->printPretty();
std::cout << (c->remove(50)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
*e=*c;
*b=*b;
e->printPretty();
*c=*b;
std::cout << (b->remove(481)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (c->insert(42)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
a->printPretty();
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->remove(382)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (a->remove(348)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
*a=*a;
std::cout << (b->remove(426)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
*e=*a;
std::cout << (a->remove(188)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
*b=*a;
std::cout << (b->remove(195)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
std::cout << (b->remove(319)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (e->remove(249)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
std::cout << (d->insert(26)) << std::endl;
c->printPretty();
std::cout << (a->remove(477)) << std::endl;
c->printPretty();
std::cout << (c->insert(319)) << std::endl;
c->printPretty();
std::cout << (d->insert(426)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
*e=*b;
std::cout << (c->insert(319)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
e->printPretty();
std::cout << (b->insert(478)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->insert(49)) << std::endl;
*d=*c;
std::cout << (c->insert(61)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*a=*d;
std::cout << (c->remove(355)) << std::endl;
d->printPretty();
std::cout << (e->remove(472)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
b->printPretty();
std::cout << (e->remove(8)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
b->printPretty();
std::cout << (c->remove(35)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
d->printPretty();
*c=*d;
a->printPretty();
e->printPretty();
b->printPretty();
std::cout << (d->remove(106)) << std::endl;
c->printPretty();
std::cout << (c->insert(192)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (e->insert(357)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
d->printPretty();
std::cout << (b->remove(303)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
d->printPretty();
std::cout << (a->remove(76)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
*d=*a;
std::cout << (d->insert(401)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
*d=*c;
a->printPretty();
*b=*e;
std::cout << (d->insert(364)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
c->printPretty();
std::cout << (c->insert(401)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
*d=*b;
std::cout << (b->remove(307)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
*d=*b;
std::cout << (b->insert(429)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
b->printPretty();
std::cout << (b->remove(440)) << std::endl;
*d=*e;
std::cout << (d->remove(437)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
c->printPretty();
std::cout << (e->remove(372)) << std::endl;
std::cout << (b->remove(100)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
d->printPretty();
std::cout << (a->remove(401)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
*c=*c;
std::cout << (e->remove(285)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
*e=*c;
*a=*d;
std::cout << (d->remove(83)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
return 0;
}
