#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (c->remove(476)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
d->printPretty();
b->printPretty();
*b=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
*c=*b;
a->printPretty();
d->printPretty();
std::cout << (a->insert(219)) << std::endl;
std::cout << (d->remove(86)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
std::cout << (e->remove(75)) << std::endl;
*d=*b;
std::cout << (a->insert(219)) << std::endl;
*a=*e;
*a=*c;
b->printPretty();
*c=*e;
*e=*e;
std::cout << (b->remove(11)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->insert(93)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
*d=*a;
a->printPretty();
*c=*c;
b->printPretty();
std::cout << (d->insert(352)) << std::endl;
a->printPretty();
std::cout << (d->remove(352)) << std::endl;
d->printPretty();
std::cout << (b->remove(198)) << std::endl;
*d=*b;
std::cout << (e->insert(305)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
c->printPretty();
c->printPretty();
c->printPretty();
e->printPretty();
b->printPretty();
std::cout << (b->remove(93)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
*b=*e;
d->printPretty();
a->printPretty();
a->printPretty();
std::cout << (e->insert(352)) << std::endl;
std::cout << (b->insert(60)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
d->printPretty();
std::cout << (a->remove(36)) << std::endl;
a->printPretty();
std::cout << (e->remove(305)) << std::endl;
std::cout << (a->insert(200)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
d->printPretty();
std::cout << (b->insert(305)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
*c=*d;
std::cout << (d->insert(93)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
*d=*a;
std::cout << (c->remove(22)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
std::cout << (a->insert(95)) << std::endl;
std::cout << (e->insert(28)) << std::endl;
d->printPretty();
std::cout << (a->remove(95)) << std::endl;
std::cout << (e->insert(352)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
c->printPretty();
std::cout << (b->remove(60)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (e->insert(28)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
a->printPretty();
std::cout << (b->insert(200)) << std::endl;
*e=*d;
std::cout << (b->insert(352)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
e->printPretty();
std::cout << (d->remove(352)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
*c=*c;
*a=*b;
std::cout << (e->remove(5)) << std::endl;
a->printPretty();
std::cout << (e->remove(276)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
*e=*a;
std::cout << (a->remove(352)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (d->insert(200)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
e->printPretty();
std::cout << (e->remove(200)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (e->remove(271)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (d->insert(200)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
std::cout << (e->insert(352)) << std::endl;
std::cout << (c->remove(200)) << std::endl;
*c=*d;
*b=*a;
*b=*d;
*c=*c;
std::cout << (b->remove(200)) << std::endl;
e->printPretty();
std::cout << (a->insert(172)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
*a=*c;
std::cout << (e->insert(289)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
d->printPretty();
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
std::cout << (d->remove(200)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
b->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (a->insert(307)) << std::endl;
e->printPretty();
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
*b=*e;
std::cout << (a->remove(45)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (c->insert(421)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
*c=*e;
std::cout << (a->insert(307)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->remove(222)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (e->insert(274)) << std::endl;
b->printPretty();
std::cout << (a->insert(307)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
a->printPretty();
std::cout << (e->insert(352)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->insert(170)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(337)) << std::endl;
c->printPretty();
std::cout << (e->remove(93)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (a->insert(307)) << std::endl;
*d=*a;
std::cout << (c->remove(9)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
a->printPretty();
std::cout << (d->remove(258)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
b->printPretty();
std::cout << (e->remove(73)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
b->printPretty();
*e=*a;
d->printPretty();
std::cout << (e->insert(446)) << std::endl;
e->printPretty();
std::cout << (b->insert(493)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
*a=*e;
std::cout << (d->insert(352)) << std::endl;
*b=*c;
d->printPretty();
std::cout << (d->remove(27)) << std::endl;
std::cout << (e->insert(313)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
b->printPretty();
std::cout << (e->insert(480)) << std::endl;
c->printPretty();
e->printPretty();
*a=*d;
a->printPretty();
std::cout << (d->remove(371)) << std::endl;
*c=*c;
d->printPretty();
c->printPretty();
b->printPretty();
*e=*e;
c->printPretty();
std::cout << (e->insert(279)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
*d=*d;
std::cout << (d->insert(369)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
c->printPretty();
std::cout << (e->remove(307)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
d->printPretty();
std::cout << (e->remove(446)) << std::endl;
std::cout << (e->insert(313)) << std::endl;
d->printPretty();
std::cout << (b->insert(105)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
*a=*b;
std::cout << (a->insert(137)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (d->remove(65)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (e->remove(430)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
*c=*c;
std::cout << (d->remove(436)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
*b=*d;
std::cout << (c->insert(250)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (c->insert(198)) << std::endl;
a->printPretty();
std::cout << (c->remove(378)) << std::endl;
std::cout << (e->insert(313)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
b->printPretty();
std::cout << (b->remove(369)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
*c=*b;
std::cout << (a->remove(233)) << std::endl;
e->printPretty();
std::cout << (c->insert(204)) << std::endl;
*d=*d;
std::cout << (a->remove(66)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
*a=*a;
std::cout << (e->insert(27)) << std::endl;
a->printPretty();
std::cout << (b->insert(408)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
*b=*d;
std::cout << (e->insert(484)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (a->remove(20)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (c->remove(145)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (e->remove(382)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (c->remove(408)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(415)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
c->printPretty();
std::cout << (e->remove(442)) << std::endl;
std::cout << (b->remove(43)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
d->printPretty();
std::cout << (d->insert(177)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (b->insert(475)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
*e=*b;
std::cout << (d->insert(155)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
std::cout << (e->remove(316)) << std::endl;
*a=*b;
std::cout << (a->remove(320)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
d->printPretty();
std::cout << (b->remove(307)) << std::endl;
*c=*c;
std::cout << (e->insert(422)) << std::endl;
e->printPretty();
std::cout << (a->insert(376)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (b->insert(496)) << std::endl;
*b=*a;
std::cout << (a->remove(253)) << std::endl;
d->printPretty();
std::cout << (d->remove(444)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (c->remove(352)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
c->printPretty();
std::cout << (d->remove(352)) << std::endl;
d->printPretty();
std::cout << (e->remove(429)) << std::endl;
std::cout << (b->remove(429)) << std::endl;
*b=*a;
std::cout << (b->remove(204)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (d->remove(279)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (d->remove(307)) << std::endl;
a->printPretty();
std::cout << (a->remove(312)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
d->printPretty();
std::cout << (e->remove(412)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
e->printPretty();
std::cout << (d->remove(352)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
c->printPretty();
*c=*d;
c->printPretty();
c->printPretty();
std::cout << (d->remove(22)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (a->insert(307)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (e->insert(307)) << std::endl;
std::cout << (d->remove(324)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (d->insert(415)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
b->printPretty();
std::cout << (d->insert(392)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (c->remove(137)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
std::cout << (b->insert(139)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
*b=*b;
std::cout << (d->insert(415)) << std::endl;
*b=*d;
std::cout << (d->insert(415)) << std::endl;
d->printPretty();
std::cout << (b->remove(415)) << std::endl;
*e=*e;
*d=*d;
std::cout << (b->remove(130)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (c->insert(498)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (c->insert(317)) << std::endl;
c->printPretty();
std::cout << (e->insert(11)) << std::endl;
*d=*e;
std::cout << (c->insert(498)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
*d=*a;
a->printPretty();
b->printPretty();
std::cout << (e->insert(359)) << std::endl;
d->printPretty();
std::cout << (e->remove(282)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
std::cout << (e->insert(374)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
*d=*c;
std::cout << (a->remove(6)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (c->insert(124)) << std::endl;
std::cout << (c->remove(376)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
*e=*e;
*b=*a;
std::cout << (e->insert(23)) << std::endl;
*e=*c;
*b=*a;
*c=*a;
std::cout << (d->remove(328)) << std::endl;
std::cout << (b->remove(273)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
*a=*e;
std::cout << (a->remove(374)) << std::endl;
*a=*a;
std::cout << (e->remove(352)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
*a=*c;
std::cout << (d->remove(498)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
*e=*d;
*e=*c;
*a=*b;
std::cout << (c->remove(163)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
std::cout << (c->insert(336)) << std::endl;
d->printPretty();
std::cout << (c->insert(47)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
*a=*b;
std::cout << (c->insert(203)) << std::endl;
e->printPretty();
*d=*d;
*d=*d;
std::cout << (c->remove(60)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
c->printPretty();
std::cout << (a->remove(466)) << std::endl;
*d=*d;
std::cout << (c->insert(202)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
*a=*e;
std::cout << (e->remove(119)) << std::endl;
b->printPretty();
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->remove(99)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
*c=*a;
std::cout << (e->insert(296)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
d->printPretty();
std::cout << (a->remove(99)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (e->insert(321)) << std::endl;
d->printPretty();
std::cout << (d->insert(175)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
c->printPretty();
*c=*b;
c->printPretty();
d->printPretty();
std::cout << (a->insert(175)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
*b=*c;
std::cout << (d->insert(175)) << std::endl;
*c=*e;
std::cout << (b->remove(321)) << std::endl;
std::cout << (a->insert(432)) << std::endl;
*d=*b;
std::cout << (d->remove(154)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
std::cout << (d->remove(98)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
std::cout << (d->insert(204)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
a->printPretty();
std::cout << (b->remove(328)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
b->printPretty();
std::cout << (e->remove(48)) << std::endl;
b->printPretty();
std::cout << (a->remove(155)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
*b=*d;
std::cout << (d->insert(415)) << std::endl;
std::cout << (e->insert(176)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
c->printPretty();
std::cout << (e->insert(75)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (e->remove(176)) << std::endl;
*e=*c;
std::cout << (a->remove(181)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(175)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
*d=*e;
std::cout << (b->remove(87)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (c->insert(321)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*e=*d;
*e=*a;
*a=*e;
c->printPretty();
*a=*d;
std::cout << (b->remove(499)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
e->printPretty();
std::cout << (b->insert(245)) << std::endl;
d->printPretty();
std::cout << (c->remove(96)) << std::endl;
*e=*d;
*b=*c;
*b=*c;
std::cout << (a->remove(296)) << std::endl;
std::cout << (c->remove(314)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (e->insert(499)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (b->remove(219)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->insert(415)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
b->printPretty();
std::cout << (d->insert(140)) << std::endl;
e->printPretty();
std::cout << (d->insert(352)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (b->insert(121)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
*d=*c;
std::cout << (a->insert(336)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
*a=*e;
std::cout << (c->insert(380)) << std::endl;
std::cout << (d->insert(337)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
std::cout << (b->remove(446)) << std::endl;
a->printPretty();
*b=*a;
*e=*c;
c->printPretty();
std::cout << (b->remove(302)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
*e=*e;
std::cout << (a->remove(33)) << std::endl;
std::cout << (d->remove(337)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
b->printPretty();
std::cout << (e->insert(376)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
*d=*b;
std::cout << (a->insert(352)) << std::endl;
a->printPretty();
std::cout << (a->insert(6)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (e->insert(401)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
std::cout << (e->remove(415)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
*e=*a;
*d=*d;
std::cout << (d->remove(415)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (c->insert(75)) << std::endl;
std::cout << (b->remove(219)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
a->printPretty();
std::cout << (a->remove(487)) << std::endl;
std::cout << (c->remove(333)) << std::endl;
*b=*d;
*e=*a;
std::cout << (e->insert(405)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (d->insert(299)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
e->printPretty();
std::cout << (a->insert(55)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
d->printPretty();
std::cout << (a->remove(499)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
*a=*e;
std::cout << (c->remove(415)) << std::endl;
std::cout << (d->insert(425)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
c->printPretty();
a->printPretty();
*e=*d;
std::cout << (c->remove(303)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
*b=*e;
std::cout << (e->insert(229)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
d->printPretty();
std::cout << (b->insert(39)) << std::endl;
e->printPretty();
std::cout << (e->remove(229)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
return 0;
}
