#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(62)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (b->insert(330)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(353)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (b->insert(330)) << std::endl;
*b=*a;
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
e->printPretty();
*b=*e;
*a=*d;
*d=*c;
std::cout << (b->insert(274)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (b->insert(321)) << std::endl;
d->printPretty();
std::cout << (b->remove(286)) << std::endl;
std::cout << (a->remove(303)) << std::endl;
b->printPretty();
std::cout << (d->remove(327)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
*e=*e;
std::cout << (e->remove(354)) << std::endl;
a->printPretty();
std::cout << (d->insert(493)) << std::endl;
std::cout << (d->insert(493)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (d->remove(493)) << std::endl;
*d=*c;
*d=*e;
b->printPretty();
*d=*e;
std::cout << (b->remove(342)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
a->printPretty();
std::cout << (d->insert(294)) << std::endl;
*e=*a;
b->printPretty();
d->printPretty();
c->printPretty();
*b=*b;
std::cout << (b->insert(321)) << std::endl;
d->printPretty();
std::cout << (d->remove(274)) << std::endl;
std::cout << (d->insert(218)) << std::endl;
std::cout << (a->insert(462)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
*b=*c;
std::cout << (b->insert(467)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
std::cout << (e->remove(303)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (d->remove(170)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
a->printPretty();
std::cout << (c->insert(240)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
d->printPretty();
std::cout << (e->remove(111)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
*e=*a;
std::cout << (c->remove(240)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
*b=*e;
std::cout << (a->remove(462)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->insert(271)) << std::endl;
*d=*e;
std::cout << (b->insert(117)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
std::cout << (d->remove(462)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->remove(7)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
*e=*c;
std::cout << (d->insert(173)) << std::endl;
std::cout << (b->insert(120)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
a->printPretty();
d->printPretty();
*c=*e;
std::cout << (d->insert(75)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
*b=*e;
std::cout << (a->remove(494)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
*d=*a;
std::cout << (d->insert(498)) << std::endl;
*e=*d;
*e=*d;
*d=*a;
std::cout << (b->remove(414)) << std::endl;
d->printPretty();
std::cout << (e->remove(498)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
*b=*d;
std::cout << (c->insert(88)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
*a=*c;
std::cout << (a->remove(496)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
a->printPretty();
std::cout << (c->remove(402)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (a->remove(273)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
*b=*e;
*a=*d;
std::cout << (c->remove(88)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
c->printPretty();
std::cout << (a->remove(107)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (e->insert(180)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
*e=*b;
std::cout << (d->insert(219)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
c->printPretty();
*e=*c;
b->printPretty();
*d=*b;
*e=*c;
b->printPretty();
std::cout << (e->remove(369)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->insert(152)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
*b=*c;
*c=*c;
e->printPretty();
*b=*c;
std::cout << (e->insert(385)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(369)) << std::endl;
std::cout << (b->remove(464)) << std::endl;
d->printPretty();
std::cout << (b->insert(369)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
*c=*a;
std::cout << (e->insert(238)) << std::endl;
std::cout << (e->insert(238)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
b->printPretty();
std::cout << (e->insert(326)) << std::endl;
*a=*e;
*d=*e;
d->printPretty();
std::cout << (d->remove(59)) << std::endl;
std::cout << (a->insert(5)) << std::endl;
*d=*d;
std::cout << (b->insert(369)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (c->remove(420)) << std::endl;
*d=*c;
*a=*a;
std::cout << (a->remove(192)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->insert(489)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
c->printPretty();
std::cout << (c->insert(489)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (c->remove(377)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (a->insert(326)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (a->insert(46)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
std::cout << (e->remove(238)) << std::endl;
d->printPretty();
a->printPretty();
e->printPretty();
std::cout << (b->remove(369)) << std::endl;
a->printPretty();
std::cout << (c->remove(489)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
std::cout << (d->remove(144)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->insert(264)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
d->printPretty();
a->printPretty();
e->printPretty();
std::cout << (c->remove(119)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
a->printPretty();
std::cout << (e->insert(326)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
*a=*b;
*b=*c;
std::cout << (a->remove(495)) << std::endl;
std::cout << (e->remove(454)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->insert(247)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
*d=*c;
*e=*b;
*d=*c;
std::cout << (d->insert(446)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
b->printPretty();
std::cout << (e->remove(257)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (c->remove(288)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
b->printPretty();
std::cout << (d->insert(446)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
d->printPretty();
std::cout << (d->remove(179)) << std::endl;
*c=*b;
*b=*c;
e->printPretty();
std::cout << (d->remove(375)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
d->printPretty();
std::cout << (c->remove(413)) << std::endl;
*a=*c;
*a=*d;
std::cout << (b->insert(471)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
b->printPretty();
*b=*e;
*a=*d;
std::cout << (d->remove(446)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->remove(451)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (a->remove(19)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (d->insert(67)) << std::endl;
std::cout << (d->insert(210)) << std::endl;
b->printPretty();
std::cout << (a->insert(395)) << std::endl;
*e=*e;
std::cout << (d->insert(285)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
*d=*a;
std::cout << (e->insert(394)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
b->printPretty();
std::cout << (d->insert(243)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (a->remove(66)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (c->remove(304)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
c->printPretty();
std::cout << (d->insert(243)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
*b=*a;
*a=*e;
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
*e=*d;
*b=*d;
d->printPretty();
std::cout << (a->remove(343)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
a->printPretty();
std::cout << (a->insert(483)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
std::cout << (a->insert(483)) << std::endl;
std::cout << (a->insert(483)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
*e=*a;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
c->printPretty();
std::cout << (c->remove(244)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (c->insert(245)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
c->printPretty();
std::cout << (b->remove(66)) << std::endl;
a->printPretty();
std::cout << (e->remove(483)) << std::endl;
std::cout << (d->remove(98)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
e->printPretty();
std::cout << (a->remove(116)) << std::endl;
*d=*e;
std::cout << (a->insert(483)) << std::endl;
std::cout << (a->insert(483)) << std::endl;
std::cout << (a->remove(483)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
c->printPretty();
std::cout << (a->insert(92)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
e->printPretty();
std::cout << (c->insert(64)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
c->printPretty();
std::cout << (e->remove(173)) << std::endl;
*d=*e;
std::cout << (b->insert(395)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
b->printPretty();
std::cout << (a->remove(92)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
*c=*e;
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
*a=*b;
std::cout << (a->remove(258)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
b->printPretty();
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
b->printPretty();
std::cout << (d->insert(60)) << std::endl;
*d=*a;
std::cout << (b->remove(496)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
e->printPretty();
*b=*d;
*c=*b;
b->printPretty();
std::cout << (c->insert(492)) << std::endl;
b->printPretty();
std::cout << (a->remove(313)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
a->printPretty();
std::cout << (b->remove(3)) << std::endl;
*e=*d;
std::cout << (d->remove(360)) << std::endl;
*a=*d;
d->printPretty();
b->printPretty();
std::cout << (c->insert(324)) << std::endl;
*d=*a;
std::cout << (c->insert(1)) << std::endl;
*c=*e;
std::cout << (d->remove(361)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
d->printPretty();
std::cout << (c->insert(432)) << std::endl;
*e=*a;
std::cout << (d->insert(41)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
*e=*d;
std::cout << (c->insert(432)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
std::cout << (d->remove(41)) << std::endl;
a->printPretty();
std::cout << (d->insert(458)) << std::endl;
*d=*b;
a->printPretty();
e->printPretty();
std::cout << (a->insert(252)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (c->remove(432)) << std::endl;
a->printPretty();
*e=*b;
c->printPretty();
*c=*b;
std::cout << (c->insert(197)) << std::endl;
std::cout << (b->insert(121)) << std::endl;
*a=*c;
std::cout << (b->remove(175)) << std::endl;
c->printPretty();
e->printPretty();
*c=*b;
std::cout << (a->remove(197)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->remove(378)) << std::endl;
c->printPretty();
std::cout << (b->remove(221)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
std::cout << (b->insert(72)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
*c=*e;
std::cout << (d->insert(342)) << std::endl;
c->printPretty();
std::cout << (b->insert(93)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (a->insert(430)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
d->printPretty();
std::cout << (c->insert(257)) << std::endl;
*b=*a;
std::cout << (a->insert(430)) << std::endl;
*a=*b;
std::cout << (b->insert(395)) << std::endl;
c->printPretty();
std::cout << (b->insert(430)) << std::endl;
*b=*a;
*b=*d;
*a=*b;
std::cout << (e->insert(187)) << std::endl;
std::cout << (a->remove(342)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
b->printPretty();
std::cout << (e->remove(261)) << std::endl;
b->printPretty();
*b=*c;
e->printPretty();
std::cout << (a->remove(159)) << std::endl;
*e=*e;
std::cout << (d->insert(342)) << std::endl;
c->printPretty();
std::cout << (e->insert(29)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
*d=*c;
*c=*a;
std::cout << (a->insert(25)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
*a=*b;
*c=*d;
std::cout << (b->insert(302)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
a->printPretty();
*b=*d;
*a=*d;
std::cout << (c->insert(493)) << std::endl;
std::cout << (c->remove(458)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
*e=*b;
std::cout << (d->remove(355)) << std::endl;
a->printPretty();
std::cout << (a->insert(86)) << std::endl;
*b=*d;
*e=*a;
std::cout << (b->insert(486)) << std::endl;
c->printPretty();
std::cout << (b->insert(316)) << std::endl;
e->printPretty();
std::cout << (a->remove(86)) << std::endl;
*a=*e;
std::cout << (d->remove(270)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
*d=*e;
std::cout << (a->insert(86)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
d->printPretty();
std::cout << (b->insert(486)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
std::cout << (c->insert(12)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (c->insert(12)) << std::endl;
*b=*d;
*a=*c;
*b=*a;
std::cout << (d->remove(86)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (e->insert(428)) << std::endl;
*d=*e;
std::cout << (e->insert(20)) << std::endl;
std::cout << (a->insert(455)) << std::endl;
*e=*a;
std::cout << (b->insert(12)) << std::endl;
std::cout << (c->remove(10)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
*d=*b;
std::cout << (a->insert(239)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
std::cout << (b->insert(252)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->remove(230)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (b->insert(252)) << std::endl;
b->printPretty();
std::cout << (b->remove(284)) << std::endl;
*c=*c;
std::cout << (c->remove(12)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (d->remove(12)) << std::endl;
*c=*d;
*b=*e;
std::cout << (b->insert(312)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
*b=*e;
std::cout << (c->remove(286)) << std::endl;
*e=*a;
*b=*a;
e->printPretty();
*e=*a;
std::cout << (e->remove(3)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
e->printPretty();
std::cout << (c->insert(236)) << std::endl;
d->printPretty();
std::cout << (b->insert(145)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(396)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->insert(470)) << std::endl;
*a=*e;
std::cout << (a->remove(12)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
*a=*e;
std::cout << (b->remove(144)) << std::endl;
*c=*d;
std::cout << (d->remove(242)) << std::endl;
e->printPretty();
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->remove(396)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (c->remove(304)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
*d=*e;
std::cout << (a->insert(460)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (b->remove(126)) << std::endl;
std::cout << (c->remove(135)) << std::endl;
std::cout << (e->remove(370)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
a->printPretty();
*b=*e;
*a=*c;
std::cout << (b->remove(352)) << std::endl;
c->printPretty();
std::cout << (e->remove(326)) << std::endl;
c->printPretty();
std::cout << (b->remove(237)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (d->insert(101)) << std::endl;
std::cout << (a->insert(433)) << std::endl;
std::cout << (d->remove(351)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
a->printPretty();
std::cout << (b->remove(418)) << std::endl;
std::cout << (c->insert(97)) << std::endl;
*e=*d;
std::cout << (e->insert(298)) << std::endl;
*c=*c;
std::cout << (d->insert(294)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
*b=*c;
std::cout << (a->remove(433)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
return 0;
}
