#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(225)) << std::endl;
std::cout << (a->insert(225)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
a->printPretty();
std::cout << (a->remove(161)) << std::endl;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (d->remove(402)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
e->printPretty();
e->printPretty();
std::cout << (a->insert(106)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
*d=*d;
std::cout << (b->remove(106)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(263)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(481)) << std::endl;
b->printPretty();
std::cout << (c->remove(109)) << std::endl;
*c=*b;
std::cout << (c->remove(95)) << std::endl;
std::cout << (e->remove(221)) << std::endl;
*d=*b;
std::cout << (d->remove(171)) << std::endl;
b->printPretty();
std::cout << (a->insert(49)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (b->remove(49)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
*a=*d;
std::cout << (d->insert(268)) << std::endl;
*b=*d;
std::cout << (d->insert(355)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
d->printPretty();
std::cout << (a->insert(376)) << std::endl;
*b=*b;
*d=*b;
a->printPretty();
a->printPretty();
std::cout << (c->insert(280)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
std::cout << (a->remove(376)) << std::endl;
std::cout << (d->insert(268)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
d->printPretty();
std::cout << (a->remove(465)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
std::cout << (e->insert(20)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->remove(285)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (a->remove(486)) << std::endl;
std::cout << (c->insert(268)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
*b=*a;
std::cout << (a->remove(397)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
*b=*d;
std::cout << (a->insert(476)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
*b=*d;
std::cout << (b->insert(397)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
*a=*c;
*a=*c;
std::cout << (b->insert(495)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
*c=*c;
std::cout << (a->remove(344)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
*d=*b;
std::cout << (d->remove(306)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
e->printPretty();
std::cout << (e->insert(20)) << std::endl;
*a=*a;
std::cout << (c->insert(354)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
d->printPretty();
std::cout << (e->remove(204)) << std::endl;
std::cout << (c->insert(354)) << std::endl;
*d=*a;
std::cout << (b->remove(314)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
*c=*a;
std::cout << (a->insert(39)) << std::endl;
std::cout << (d->insert(437)) << std::endl;
std::cout << (a->insert(68)) << std::endl;
a->printPretty();
std::cout << (d->insert(460)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (b->insert(403)) << std::endl;
b->printPretty();
std::cout << (c->remove(351)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (d->remove(403)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
*e=*e;
std::cout << (d->remove(495)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (e->insert(20)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
*a=*a;
std::cout << (c->insert(363)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (b->remove(54)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
*c=*d;
std::cout << (a->remove(161)) << std::endl;
e->printPretty();
std::cout << (c->remove(302)) << std::endl;
*a=*a;
std::cout << (e->insert(424)) << std::endl;
std::cout << (c->remove(496)) << std::endl;
b->printPretty();
std::cout << (e->remove(424)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (e->remove(426)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
c->printPretty();
std::cout << (b->remove(190)) << std::endl;
*a=*c;
std::cout << (a->insert(481)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (c->remove(381)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(89)) << std::endl;
b->printPretty();
std::cout << (a->remove(481)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
std::cout << (c->insert(89)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (c->remove(89)) << std::endl;
*d=*e;
*a=*b;
std::cout << (c->insert(268)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
*e=*a;
std::cout << (c->remove(151)) << std::endl;
d->printPretty();
*a=*b;
a->printPretty();
*b=*b;
d->printPretty();
std::cout << (c->remove(439)) << std::endl;
std::cout << (c->insert(268)) << std::endl;
b->printPretty();
std::cout << (c->remove(268)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(66)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->remove(60)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(280)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
std::cout << (e->insert(410)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
b->printPretty();
std::cout << (e->insert(280)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
c->printPretty();
std::cout << (b->insert(375)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
d->printPretty();
std::cout << (d->remove(448)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
c->printPretty();
std::cout << (e->remove(410)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*d=*c;
std::cout << (c->insert(289)) << std::endl;
std::cout << (c->insert(77)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
*d=*a;
std::cout << (e->remove(280)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
*a=*c;
std::cout << (c->insert(346)) << std::endl;
e->printPretty();
std::cout << (e->remove(466)) << std::endl;
std::cout << (a->remove(67)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
c->printPretty();
std::cout << (c->remove(48)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
*d=*d;
std::cout << (e->remove(110)) << std::endl;
*c=*a;
std::cout << (a->remove(75)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
a->printPretty();
std::cout << (b->remove(271)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (a->insert(349)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
*b=*d;
std::cout << (b->insert(405)) << std::endl;
std::cout << (c->remove(127)) << std::endl;
std::cout << (c->remove(289)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
e->printPretty();
std::cout << (a->remove(115)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
b->printPretty();
std::cout << (a->remove(499)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
*e=*e;
*a=*e;
std::cout << (e->insert(51)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
std::cout << (e->remove(210)) << std::endl;
d->printPretty();
std::cout << (d->remove(411)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
*c=*b;
*d=*b;
*d=*d;
std::cout << (a->insert(444)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->remove(457)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
*e=*d;
*e=*a;
std::cout << (a->remove(444)) << std::endl;
std::cout << (d->insert(405)) << std::endl;
std::cout << (c->remove(84)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
b->printPretty();
std::cout << (b->insert(21)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
*b=*a;
std::cout << (c->insert(405)) << std::endl;
*e=*c;
std::cout << (b->remove(111)) << std::endl;
*b=*b;
std::cout << (e->remove(405)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (c->remove(405)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->insert(84)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
*b=*d;
*e=*b;
std::cout << (d->insert(84)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (b->insert(405)) << std::endl;
a->printPretty();
std::cout << (d->remove(405)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->remove(108)) << std::endl;
*e=*a;
std::cout << (c->remove(380)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
b->printPretty();
std::cout << (b->insert(397)) << std::endl;
*e=*d;
*c=*e;
std::cout << (a->insert(221)) << std::endl;
d->printPretty();
std::cout << (e->insert(84)) << std::endl;
std::cout << (e->remove(356)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
*c=*c;
std::cout << (d->insert(201)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
d->printPretty();
std::cout << (a->remove(219)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
c->printPretty();
std::cout << (d->remove(211)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
*a=*d;
std::cout << (a->remove(201)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (c->remove(288)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
c->printPretty();
c->printPretty();
*e=*b;
std::cout << (e->insert(333)) << std::endl;
b->printPretty();
std::cout << (c->remove(84)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
d->printPretty();
e->printPretty();
a->printPretty();
*e=*e;
std::cout << (e->remove(333)) << std::endl;
e->printPretty();
std::cout << (b->remove(405)) << std::endl;
d->printPretty();
std::cout << (d->remove(5)) << std::endl;
std::cout << (d->remove(389)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (c->remove(118)) << std::endl;
e->printPretty();
std::cout << (c->remove(482)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
*e=*b;
std::cout << (b->remove(86)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->insert(333)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
*d=*e;
std::cout << (d->remove(333)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->insert(333)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
std::cout << (b->insert(118)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (a->remove(73)) << std::endl;
c->printPretty();
std::cout << (a->insert(377)) << std::endl;
*c=*b;
std::cout << (d->insert(186)) << std::endl;
std::cout << (b->remove(473)) << std::endl;
std::cout << (e->insert(133)) << std::endl;
d->printPretty();
std::cout << (b->insert(186)) << std::endl;
std::cout << (a->remove(377)) << std::endl;
a->printPretty();
std::cout << (e->insert(333)) << std::endl;
*b=*e;
std::cout << (e->remove(262)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
*c=*a;
*d=*c;
std::cout << (c->remove(408)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
d->printPretty();
std::cout << (b->remove(475)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->insert(316)) << std::endl;
d->printPretty();
std::cout << (a->remove(280)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (b->insert(292)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
d->printPretty();
std::cout << (a->insert(316)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
e->printPretty();
std::cout << (a->insert(38)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
d->printPretty();
std::cout << (e->remove(186)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
*a=*a;
std::cout << (d->insert(88)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(332)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
std::cout << (e->insert(87)) << std::endl;
std::cout << (d->remove(88)) << std::endl;
std::cout << (b->insert(480)) << std::endl;
std::cout << (e->insert(318)) << std::endl;
std::cout << (e->insert(87)) << std::endl;
std::cout << (b->insert(362)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(186)) << std::endl;
std::cout << (e->insert(433)) << std::endl;
std::cout << (c->remove(442)) << std::endl;
*e=*c;
*c=*b;
std::cout << (b->remove(314)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
*a=*d;
std::cout << (b->remove(133)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
*b=*a;
std::cout << (a->insert(448)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
c->printPretty();
std::cout << (e->remove(111)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
*c=*d;
std::cout << (a->insert(229)) << std::endl;
e->printPretty();
*c=*e;
e->printPretty();
c->printPretty();
*b=*b;
std::cout << (a->remove(229)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (b->insert(102)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
*b=*a;
std::cout << (e->remove(472)) << std::endl;
*e=*d;
std::cout << (e->remove(228)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
std::cout << (d->remove(448)) << std::endl;
*e=*e;
std::cout << (c->insert(86)) << std::endl;
d->printPretty();
std::cout << (e->insert(448)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
*d=*e;
std::cout << (a->remove(274)) << std::endl;
*a=*a;
std::cout << (d->insert(279)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (e->insert(400)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
*e=*d;
*d=*b;
std::cout << (a->remove(119)) << std::endl;
std::cout << (e->insert(302)) << std::endl;
*c=*e;
std::cout << (d->insert(293)) << std::endl;
*d=*b;
b->printPretty();
d->printPretty();
std::cout << (c->insert(193)) << std::endl;
*b=*e;
std::cout << (d->remove(487)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
*d=*d;
std::cout << (e->remove(193)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
e->printPretty();
std::cout << (e->insert(448)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
std::cout << (d->insert(264)) << std::endl;
*d=*e;
std::cout << (d->remove(279)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
std::cout << (b->remove(158)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (a->insert(317)) << std::endl;
c->printPretty();
*a=*e;
d->printPretty();
c->printPretty();
std::cout << (d->insert(229)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (c->remove(58)) << std::endl;
std::cout << (e->remove(448)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->insert(448)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
c->printPretty();
std::cout << (c->remove(448)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
b->printPretty();
std::cout << (e->insert(188)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (e->insert(83)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (d->remove(448)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
a->printPretty();
std::cout << (a->remove(448)) << std::endl;
*d=*a;
*b=*a;
std::cout << (a->remove(279)) << std::endl;
c->printPretty();
std::cout << (d->remove(236)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
std::cout << (e->insert(83)) << std::endl;
e->printPretty();
std::cout << (c->insert(229)) << std::endl;
d->printPretty();
b->printPretty();
*c=*b;
std::cout << (c->remove(401)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
std::cout << (d->insert(279)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
d->printPretty();
*c=*c;
d->printPretty();
*b=*b;
std::cout << (d->remove(207)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
e->printPretty();
std::cout << (c->remove(302)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (b->insert(129)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
d->printPretty();
std::cout << (e->remove(329)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
e->printPretty();
std::cout << (d->remove(279)) << std::endl;
std::cout << (e->insert(83)) << std::endl;
std::cout << (a->remove(491)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (b->remove(302)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(83)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
*d=*d;
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (a->insert(302)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (e->insert(465)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
std::cout << (a->remove(433)) << std::endl;
b->printPretty();
*d=*c;
*c=*b;
std::cout << (b->insert(96)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
std::cout << (d->insert(314)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
*e=*b;
std::cout << (a->remove(34)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->insert(279)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (e->remove(96)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (b->insert(96)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
*e=*c;
std::cout << (a->remove(258)) << std::endl;
*c=*e;
std::cout << (a->insert(365)) << std::endl;
*d=*b;
std::cout << (a->insert(14)) << std::endl;
*d=*d;
std::cout << (c->remove(83)) << std::endl;
c->printPretty();
e->printPretty();
return 0;
}
