#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
b->printPretty();
b->printPretty();
std::cout << (d->remove(274)) << std::endl;
*b=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
a->printPretty();
c->printPretty();
*d=*e;
std::cout << (d->insert(115)) << std::endl;
*c=*a;
std::cout << (a->remove(300)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
*c=*e;
std::cout << (b->remove(201)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
d->printPretty();
std::cout << (a->remove(119)) << std::endl;
*d=*a;
std::cout << (b->remove(130)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
*a=*b;
d->printPretty();
*d=*c;
std::cout << (b->insert(28)) << std::endl;
d->printPretty();
std::cout << (b->remove(390)) << std::endl;
*c=*b;
std::cout << (b->insert(49)) << std::endl;
std::cout << (d->remove(352)) << std::endl;
*c=*e;
std::cout << (b->remove(255)) << std::endl;
*b=*e;
*b=*a;
std::cout << (a->insert(297)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
*e=*e;
*c=*e;
std::cout << (b->remove(134)) << std::endl;
c->printPretty();
std::cout << (c->insert(490)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
std::cout << (c->insert(490)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
b->printPretty();
std::cout << (a->insert(218)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
std::cout << (b->remove(293)) << std::endl;
*b=*d;
*d=*c;
std::cout << (c->remove(118)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (e->insert(258)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
b->printPretty();
*e=*a;
*b=*b;
std::cout << (d->insert(136)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (c->insert(319)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
std::cout << (d->insert(136)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (a->insert(90)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
*d=*a;
std::cout << (a->insert(323)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
std::cout << (b->remove(115)) << std::endl;
std::cout << (a->remove(342)) << std::endl;
std::cout << (e->insert(138)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (a->insert(345)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->remove(90)) << std::endl;
a->printPretty();
*e=*b;
std::cout << (a->insert(438)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
*c=*b;
*e=*d;
a->printPretty();
std::cout << (e->remove(297)) << std::endl;
*d=*a;
std::cout << (c->insert(107)) << std::endl;
std::cout << (d->insert(218)) << std::endl;
*a=*c;
*c=*e;
std::cout << (c->insert(218)) << std::endl;
std::cout << (c->remove(79)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
*c=*e;
std::cout << (b->remove(10)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
e->printPretty();
std::cout << (c->insert(218)) << std::endl;
a->printPretty();
std::cout << (d->remove(218)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
*a=*e;
std::cout << (d->remove(202)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
*b=*e;
*e=*b;
std::cout << (c->remove(218)) << std::endl;
d->printPretty();
std::cout << (a->remove(255)) << std::endl;
*d=*a;
std::cout << (a->insert(412)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (b->insert(317)) << std::endl;
std::cout << (b->insert(57)) << std::endl;
d->printPretty();
std::cout << (b->remove(7)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
a->printPretty();
std::cout << (e->insert(80)) << std::endl;
e->printPretty();
std::cout << (a->insert(80)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
*c=*a;
std::cout << (a->remove(438)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
d->printPretty();
std::cout << (a->remove(212)) << std::endl;
std::cout << (a->insert(109)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (c->insert(79)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
*a=*b;
std::cout << (b->insert(114)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (b->insert(152)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (c->insert(47)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
std::cout << (a->remove(80)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
b->printPretty();
std::cout << (e->insert(88)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
c->printPretty();
std::cout << (b->insert(44)) << std::endl;
a->printPretty();
std::cout << (b->remove(44)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
a->printPretty();
std::cout << (d->insert(495)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
*e=*e;
std::cout << (d->insert(495)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
c->printPretty();
std::cout << (c->insert(329)) << std::endl;
std::cout << (e->insert(253)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
std::cout << (c->remove(448)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
*d=*a;
std::cout << (e->insert(207)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
*c=*b;
std::cout << (e->remove(53)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (e->remove(31)) << std::endl;
*d=*a;
std::cout << (c->remove(30)) << std::endl;
d->printPretty();
std::cout << (b->insert(152)) << std::endl;
std::cout << (d->insert(445)) << std::endl;
e->printPretty();
std::cout << (e->remove(365)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
c->printPretty();
std::cout << (e->remove(255)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (c->insert(170)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (d->insert(207)) << std::endl;
std::cout << (e->insert(253)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
std::cout << (d->insert(55)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(52)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (e->insert(439)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
b->printPretty();
std::cout << (b->insert(197)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
*b=*a;
std::cout << (d->insert(55)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
*e=*c;
std::cout << (a->remove(493)) << std::endl;
d->printPretty();
b->printPretty();
c->printPretty();
std::cout << (d->insert(423)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(152)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
std::cout << (d->remove(433)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
*a=*c;
std::cout << (c->insert(482)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (c->remove(136)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->insert(482)) << std::endl;
d->printPretty();
std::cout << (c->insert(152)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
std::cout << (c->remove(380)) << std::endl;
*b=*c;
std::cout << (a->remove(152)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
*e=*a;
std::cout << (e->remove(455)) << std::endl;
a->printPretty();
std::cout << (e->remove(437)) << std::endl;
std::cout << (a->insert(168)) << std::endl;
*a=*c;
std::cout << (e->insert(94)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
d->printPretty();
*b=*d;
*d=*c;
d->printPretty();
std::cout << (c->insert(44)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->insert(152)) << std::endl;
*e=*d;
*a=*e;
*d=*c;
*b=*c;
std::cout << (e->remove(363)) << std::endl;
std::cout << (a->remove(463)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (a->insert(437)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (b->insert(482)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
a->printPretty();
e->printPretty();
b->printPretty();
std::cout << (b->remove(356)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->remove(437)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
*c=*d;
std::cout << (a->insert(289)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
c->printPretty();
std::cout << (c->remove(429)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
*d=*b;
std::cout << (a->remove(482)) << std::endl;
e->printPretty();
std::cout << (b->insert(367)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
d->printPretty();
std::cout << (e->remove(482)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
b->printPretty();
std::cout << (a->remove(368)) << std::endl;
*e=*e;
*c=*d;
std::cout << (a->remove(205)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (d->insert(308)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (a->insert(11)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (c->remove(11)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
e->printPretty();
std::cout << (d->insert(189)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
e->printPretty();
std::cout << (c->remove(482)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
c->printPretty();
std::cout << (e->insert(437)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
d->printPretty();
std::cout << (d->insert(12)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
d->printPretty();
std::cout << (d->remove(482)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
e->printPretty();
std::cout << (c->remove(37)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->remove(15)) << std::endl;
b->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
*e=*d;
std::cout << (a->remove(484)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (b->remove(73)) << std::endl;
std::cout << (a->insert(11)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (e->insert(82)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
std::cout << (b->insert(482)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
*d=*d;
std::cout << (e->insert(399)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
c->printPretty();
std::cout << (b->insert(359)) << std::endl;
e->printPretty();
std::cout << (d->remove(241)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
b->printPretty();
std::cout << (a->remove(11)) << std::endl;
d->printPretty();
std::cout << (e->remove(63)) << std::endl;
*a=*d;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
c->printPretty();
std::cout << (a->insert(189)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (a->remove(288)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
e->printPretty();
std::cout << (e->remove(308)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
b->printPretty();
std::cout << (e->insert(13)) << std::endl;
c->printPretty();
std::cout << (b->insert(189)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
std::cout << (b->insert(147)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
a->printPretty();
a->printPretty();
*b=*c;
*e=*c;
std::cout << (b->remove(153)) << std::endl;
*c=*d;
std::cout << (b->remove(73)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (a->insert(399)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
b->printPretty();
std::cout << (d->remove(12)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
std::cout << (d->remove(363)) << std::endl;
c->printPretty();
std::cout << (a->insert(457)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->remove(363)) << std::endl;
std::cout << (d->remove(104)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
c->printPretty();
std::cout << (d->remove(13)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
c->printPretty();
std::cout << (c->remove(11)) << std::endl;
*c=*d;
*b=*e;
a->printPretty();
std::cout << (b->remove(454)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (d->insert(356)) << std::endl;
a->printPretty();
std::cout << (d->insert(399)) << std::endl;
c->printPretty();
std::cout << (b->remove(363)) << std::endl;
std::cout << (a->insert(147)) << std::endl;
a->printPretty();
std::cout << (c->remove(152)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
std::cout << (c->remove(447)) << std::endl;
*c=*b;
std::cout << (a->insert(333)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
b->printPretty();
std::cout << (e->remove(158)) << std::endl;
e->printPretty();
*e=*e;
*e=*c;
std::cout << (c->insert(73)) << std::endl;
c->printPretty();
std::cout << (e->remove(291)) << std::endl;
*d=*b;
*c=*a;
std::cout << (b->remove(300)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (c->insert(333)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
std::cout << (a->insert(185)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (b->insert(215)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (a->insert(390)) << std::endl;
a->printPretty();
std::cout << (d->remove(368)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (a->insert(15)) << std::endl;
std::cout << (e->remove(393)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
*e=*b;
*d=*b;
std::cout << (c->remove(249)) << std::endl;
*e=*a;
std::cout << (e->insert(316)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
*b=*e;
std::cout << (b->remove(346)) << std::endl;
std::cout << (a->insert(315)) << std::endl;
std::cout << (e->insert(76)) << std::endl;
*d=*c;
std::cout << (a->insert(346)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (d->remove(441)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
e->printPretty();
std::cout << (e->insert(229)) << std::endl;
*c=*a;
std::cout << (e->remove(242)) << std::endl;
std::cout << (c->remove(333)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
*c=*c;
std::cout << (b->remove(328)) << std::endl;
a->printPretty();
std::cout << (e->remove(195)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (b->remove(417)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (e->remove(329)) << std::endl;
*a=*e;
std::cout << (a->insert(53)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
d->printPretty();
std::cout << (c->remove(346)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
b->printPretty();
std::cout << (e->remove(234)) << std::endl;
*d=*b;
*c=*c;
*d=*d;
std::cout << (c->insert(12)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (d->insert(116)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
*b=*d;
std::cout << (c->remove(7)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (c->insert(379)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(207)) << std::endl;
*e=*d;
*e=*c;
c->printPretty();
b->printPretty();
std::cout << (c->insert(477)) << std::endl;
std::cout << (d->remove(127)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
d->printPretty();
std::cout << (b->insert(6)) << std::endl;
*c=*c;
*c=*a;
std::cout << (e->remove(379)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
*e=*b;
std::cout << (c->remove(457)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
*a=*e;
*a=*c;
std::cout << (b->insert(290)) << std::endl;
std::cout << (b->remove(275)) << std::endl;
std::cout << (c->remove(13)) << std::endl;
b->printPretty();
std::cout << (a->insert(315)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
*d=*e;
std::cout << (c->remove(356)) << std::endl;
b->printPretty();
std::cout << (c->insert(177)) << std::endl;
a->printPretty();
std::cout << (d->insert(6)) << std::endl;
std::cout << (c->remove(97)) << std::endl;
*c=*e;
std::cout << (b->insert(390)) << std::endl;
b->printPretty();
std::cout << (b->remove(12)) << std::endl;
std::cout << (c->insert(333)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
a->printPretty();
std::cout << (a->insert(15)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
*b=*d;
std::cout << (e->remove(6)) << std::endl;
a->printPretty();
std::cout << (a->remove(15)) << std::endl;
std::cout << (a->insert(49)) << std::endl;
std::cout << (b->remove(401)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (c->insert(189)) << std::endl;
b->printPretty();
std::cout << (d->insert(452)) << std::endl;
*c=*a;
*a=*b;
std::cout << (c->insert(12)) << std::endl;
std::cout << (c->insert(315)) << std::endl;
*e=*d;
std::cout << (d->insert(36)) << std::endl;
std::cout << (c->remove(468)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (b->remove(496)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
e->printPretty();
std::cout << (b->insert(390)) << std::endl;
std::cout << (a->insert(363)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
*a=*b;
std::cout << (e->insert(116)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
*b=*b;
std::cout << (b->insert(333)) << std::endl;
std::cout << (b->remove(12)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (c->remove(157)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
e->printPretty();
*a=*e;
*c=*e;
std::cout << (b->insert(333)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
return 0;
}
