#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
a->printPretty();
std::cout << (b->remove(131)) << std::endl;
*b=*a;
std::cout << (a->insert(188)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->remove(285)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (e->remove(188)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
a->printPretty();
d->printPretty();
a->printPretty();
std::cout << (d->insert(199)) << std::endl;
std::cout << (a->remove(331)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
*e=*c;
d->printPretty();
b->printPretty();
std::cout << (a->insert(225)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
std::cout << (a->insert(450)) << std::endl;
c->printPretty();
std::cout << (d->remove(109)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
*a=*d;
std::cout << (b->remove(356)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (d->remove(366)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (e->insert(347)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(472)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
*a=*c;
std::cout << (c->insert(468)) << std::endl;
std::cout << (c->insert(468)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
*c=*c;
std::cout << (a->insert(417)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
a->printPretty();
std::cout << (c->insert(468)) << std::endl;
*c=*b;
std::cout << (d->remove(199)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
d->printPretty();
*c=*d;
b->printPretty();
std::cout << (a->remove(417)) << std::endl;
e->printPretty();
std::cout << (e->insert(347)) << std::endl;
b->printPretty();
c->printPretty();
c->printPretty();
c->printPretty();
std::cout << (d->remove(46)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
std::cout << (e->remove(347)) << std::endl;
e->printPretty();
std::cout << (c->remove(97)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
*d=*d;
std::cout << (b->insert(379)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (e->remove(200)) << std::endl;
a->printPretty();
c->printPretty();
e->printPretty();
std::cout << (b->insert(16)) << std::endl;
a->printPretty();
std::cout << (b->remove(73)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (c->insert(468)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (d->remove(205)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
e->printPretty();
std::cout << (e->remove(190)) << std::endl;
std::cout << (c->insert(123)) << std::endl;
std::cout << (d->remove(30)) << std::endl;
b->printPretty();
std::cout << (c->insert(16)) << std::endl;
*e=*e;
d->printPretty();
a->printPretty();
d->printPretty();
*e=*a;
std::cout << (b->remove(344)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
std::cout << (c->insert(468)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
*b=*e;
std::cout << (a->insert(211)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
a->printPretty();
std::cout << (c->remove(126)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (a->remove(116)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (d->remove(238)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->remove(224)) << std::endl;
*b=*b;
std::cout << (d->insert(487)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
*e=*b;
d->printPretty();
*e=*d;
std::cout << (b->insert(489)) << std::endl;
b->printPretty();
std::cout << (d->remove(34)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
d->printPretty();
std::cout << (a->insert(205)) << std::endl;
std::cout << (d->remove(327)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->insert(79)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
d->printPretty();
c->printPretty();
*c=*b;
*a=*e;
c->printPretty();
a->printPretty();
*a=*a;
std::cout << (c->remove(24)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
*c=*b;
*c=*c;
std::cout << (a->insert(198)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
*a=*e;
*a=*b;
std::cout << (e->insert(312)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
a->printPretty();
std::cout << (c->insert(52)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
c->printPretty();
std::cout << (d->remove(242)) << std::endl;
std::cout << (e->insert(5)) << std::endl;
e->printPretty();
std::cout << (d->insert(436)) << std::endl;
a->printPretty();
std::cout << (c->remove(402)) << std::endl;
std::cout << (d->remove(436)) << std::endl;
b->printPretty();
std::cout << (b->remove(111)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
*c=*b;
std::cout << (e->insert(487)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (b->remove(8)) << std::endl;
*c=*a;
*c=*a;
std::cout << (e->remove(151)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
*d=*d;
*e=*d;
std::cout << (e->insert(321)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (e->insert(165)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (b->insert(333)) << std::endl;
std::cout << (e->remove(261)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
*d=*c;
std::cout << (e->remove(477)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
*e=*c;
b->printPretty();
*c=*d;
c->printPretty();
std::cout << (c->remove(289)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
a->printPretty();
std::cout << (d->remove(89)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(289)) << std::endl;
e->printPretty();
std::cout << (c->insert(4)) << std::endl;
*c=*a;
*d=*a;
b->printPretty();
a->printPretty();
std::cout << (d->remove(121)) << std::endl;
c->printPretty();
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
e->printPretty();
std::cout << (c->remove(121)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
*e=*a;
std::cout << (b->insert(155)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
*a=*c;
std::cout << (b->remove(439)) << std::endl;
std::cout << (a->insert(490)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (a->remove(490)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
*e=*e;
b->printPretty();
*e=*a;
std::cout << (d->remove(360)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*c=*b;
std::cout << (e->remove(156)) << std::endl;
*d=*b;
*a=*d;
a->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
*c=*d;
std::cout << (d->insert(155)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
d->printPretty();
std::cout << (d->insert(155)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
*b=*e;
std::cout << (a->remove(117)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
a->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
*e=*c;
std::cout << (e->insert(155)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
*a=*b;
std::cout << (b->remove(357)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (b->remove(473)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
*b=*e;
std::cout << (d->remove(85)) << std::endl;
e->printPretty();
std::cout << (c->remove(310)) << std::endl;
c->printPretty();
std::cout << (b->remove(155)) << std::endl;
std::cout << (c->remove(232)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
a->printPretty();
std::cout << (a->insert(357)) << std::endl;
d->printPretty();
std::cout << (d->insert(333)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
*a=*d;
std::cout << (a->remove(469)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
b->printPretty();
std::cout << (d->insert(333)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
a->printPretty();
std::cout << (d->remove(469)) << std::endl;
*a=*b;
std::cout << (a->remove(1)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (d->insert(333)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
d->printPretty();
std::cout << (c->insert(471)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (b->remove(366)) << std::endl;
c->printPretty();
std::cout << (b->insert(238)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (b->remove(210)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (d->insert(333)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (a->remove(333)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
std::cout << (d->remove(333)) << std::endl;
std::cout << (b->remove(432)) << std::endl;
e->printPretty();
e->printPretty();
d->printPretty();
c->printPretty();
std::cout << (d->remove(63)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
*e=*d;
*b=*c;
std::cout << (e->insert(118)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
b->printPretty();
std::cout << (e->remove(118)) << std::endl;
*d=*b;
*d=*a;
std::cout << (b->insert(413)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (c->remove(98)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
d->printPretty();
std::cout << (e->remove(99)) << std::endl;
c->printPretty();
std::cout << (c->remove(1)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->insert(163)) << std::endl;
*c=*a;
std::cout << (c->remove(269)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
std::cout << (c->remove(346)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
*c=*e;
std::cout << (b->remove(217)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
*b=*c;
std::cout << (a->insert(6)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
d->printPretty();
std::cout << (d->remove(170)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
*c=*c;
std::cout << (e->remove(410)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
*d=*a;
std::cout << (e->insert(481)) << std::endl;
std::cout << (c->remove(94)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
e->printPretty();
std::cout << (a->remove(34)) << std::endl;
*c=*e;
std::cout << (c->insert(481)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
*a=*a;
*c=*e;
std::cout << (e->insert(481)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
b->printPretty();
std::cout << (c->remove(481)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (c->insert(163)) << std::endl;
*d=*a;
std::cout << (e->insert(481)) << std::endl;
*a=*d;
std::cout << (e->remove(481)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
*b=*a;
std::cout << (e->remove(242)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
*e=*e;
std::cout << (c->insert(451)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
b->printPretty();
std::cout << (c->insert(451)) << std::endl;
std::cout << (d->remove(304)) << std::endl;
e->printPretty();
std::cout << (c->insert(234)) << std::endl;
*a=*d;
*b=*a;
std::cout << (b->insert(176)) << std::endl;
*e=*b;
std::cout << (e->remove(206)) << std::endl;
*e=*a;
*a=*d;
std::cout << (e->remove(130)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (c->insert(451)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (a->insert(13)) << std::endl;
*e=*c;
*e=*b;
std::cout << (d->remove(412)) << std::endl;
c->printPretty();
std::cout << (c->insert(451)) << std::endl;
*c=*b;
std::cout << (a->remove(13)) << std::endl;
d->printPretty();
std::cout << (e->insert(176)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
*c=*a;
std::cout << (b->remove(223)) << std::endl;
c->printPretty();
std::cout << (d->remove(258)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
std::cout << (b->insert(354)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
a->printPretty();
std::cout << (e->insert(172)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
std::cout << (b->insert(354)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
d->printPretty();
std::cout << (c->insert(41)) << std::endl;
a->printPretty();
*a=*b;
*a=*b;
std::cout << (c->remove(41)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (c->remove(394)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (b->insert(189)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(276)) << std::endl;
a->printPretty();
std::cout << (c->remove(226)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
*c=*d;
std::cout << (b->remove(273)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
b->printPretty();
std::cout << (b->remove(80)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
*d=*b;
std::cout << (d->remove(354)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
*d=*d;
*a=*c;
c->printPretty();
std::cout << (a->insert(42)) << std::endl;
std::cout << (c->insert(388)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
*b=*d;
*e=*a;
std::cout << (e->insert(262)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
*b=*c;
std::cout << (e->remove(42)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
*e=*b;
std::cout << (c->remove(388)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
*e=*b;
std::cout << (a->insert(71)) << std::endl;
std::cout << (d->remove(306)) << std::endl;
std::cout << (d->insert(382)) << std::endl;
*c=*c;
*e=*c;
std::cout << (e->insert(418)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
*e=*c;
std::cout << (c->insert(33)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
d->printPretty();
std::cout << (e->remove(262)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (c->remove(262)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
d->printPretty();
std::cout << (b->insert(137)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
d->printPretty();
std::cout << (b->remove(353)) << std::endl;
std::cout << (b->remove(33)) << std::endl;
*a=*e;
std::cout << (d->insert(189)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (b->remove(33)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
c->printPretty();
std::cout << (e->insert(353)) << std::endl;
e->printPretty();
std::cout << (b->insert(234)) << std::endl;
b->printPretty();
std::cout << (a->remove(353)) << std::endl;
c->printPretty();
std::cout << (e->remove(33)) << std::endl;
e->printPretty();
std::cout << (a->insert(33)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*d=*a;
*d=*b;
*d=*a;
std::cout << (b->remove(353)) << std::endl;
*a=*c;
std::cout << (b->insert(478)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
d->printPretty();
*c=*c;
*e=*a;
d->printPretty();
*a=*c;
e->printPretty();
std::cout << (c->insert(133)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (b->remove(213)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
b->printPretty();
std::cout << (d->insert(261)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
b->printPretty();
std::cout << (b->remove(413)) << std::endl;
*a=*a;
std::cout << (d->remove(433)) << std::endl;
d->printPretty();
std::cout << (c->remove(390)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(22)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (c->insert(22)) << std::endl;
*b=*e;
std::cout << (e->remove(468)) << std::endl;
*a=*d;
a->printPretty();
*b=*c;
std::cout << (e->insert(39)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*a=*b;
std::cout << (d->insert(497)) << std::endl;
c->printPretty();
a->printPretty();
*a=*e;
c->printPretty();
*a=*c;
*a=*d;
*e=*b;
a->printPretty();
c->printPretty();
b->printPretty();
*e=*b;
std::cout << (b->insert(492)) << std::endl;
return 0;
}
