#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(215)) << std::endl;
a->printPretty();
std::cout << (a->insert(487)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(487)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->remove(487)) << std::endl;
b->printPretty();
c->printPretty();
*b=*a;
std::cout << (c->insert(363)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (d->remove(363)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
c->printPretty();
std::cout << (c->remove(363)) << std::endl;
d->printPretty();
std::cout << (c->insert(446)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
*d=*a;
*e=*b;
*d=*c;
a->printPretty();
std::cout << (a->remove(286)) << std::endl;
*d=*a;
std::cout << (b->remove(484)) << std::endl;
a->printPretty();
std::cout << (e->remove(300)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
*e=*a;
*b=*e;
*d=*c;
std::cout << (c->insert(446)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
std::cout << (a->insert(240)) << std::endl;
*a=*d;
a->printPretty();
d->printPretty();
std::cout << (c->remove(136)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
*d=*a;
std::cout << (c->remove(83)) << std::endl;
e->printPretty();
std::cout << (b->remove(232)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
*a=*a;
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
*e=*b;
std::cout << (c->remove(339)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
*a=*e;
c->printPretty();
b->printPretty();
*e=*b;
std::cout << (c->insert(446)) << std::endl;
e->printPretty();
std::cout << (b->remove(366)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
*d=*c;
std::cout << (c->insert(17)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
std::cout << (c->insert(162)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(17)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (a->remove(168)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
d->printPretty();
std::cout << (b->remove(257)) << std::endl;
std::cout << (e->insert(442)) << std::endl;
*d=*b;
std::cout << (c->remove(182)) << std::endl;
std::cout << (b->insert(319)) << std::endl;
*d=*a;
std::cout << (c->remove(446)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
*d=*c;
std::cout << (e->remove(442)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
*e=*c;
std::cout << (e->insert(97)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
*a=*a;
std::cout << (d->insert(162)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
*a=*c;
std::cout << (c->remove(471)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (b->remove(319)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (e->insert(358)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (d->remove(456)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
*a=*e;
std::cout << (b->insert(349)) << std::endl;
*c=*d;
std::cout << (b->insert(250)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
*d=*c;
std::cout << (c->insert(399)) << std::endl;
*a=*d;
std::cout << (d->insert(482)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (c->insert(399)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
c->printPretty();
std::cout << (c->insert(399)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
c->printPretty();
std::cout << (a->insert(482)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
b->printPretty();
std::cout << (c->insert(63)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->remove(115)) << std::endl;
*d=*c;
std::cout << (b->remove(349)) << std::endl;
std::cout << (b->remove(177)) << std::endl;
std::cout << (a->remove(251)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(482)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
*b=*d;
b->printPretty();
*c=*a;
*b=*d;
std::cout << (b->remove(94)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (d->insert(474)) << std::endl;
a->printPretty();
std::cout << (e->remove(250)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
*a=*d;
std::cout << (b->remove(243)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
*d=*b;
std::cout << (c->insert(124)) << std::endl;
std::cout << (b->remove(63)) << std::endl;
*e=*b;
*e=*e;
b->printPretty();
std::cout << (c->insert(112)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
a->printPretty();
std::cout << (a->insert(482)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
d->printPretty();
std::cout << (d->insert(36)) << std::endl;
*c=*d;
std::cout << (d->remove(395)) << std::endl;
std::cout << (a->remove(55)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
*d=*b;
std::cout << (c->remove(63)) << std::endl;
*a=*e;
a->printPretty();
*a=*d;
e->printPretty();
*a=*e;
std::cout << (a->remove(119)) << std::endl;
d->printPretty();
std::cout << (b->insert(295)) << std::endl;
*a=*b;
std::cout << (c->insert(119)) << std::endl;
*d=*c;
std::cout << (e->remove(300)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (a->insert(120)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
*a=*a;
std::cout << (c->insert(399)) << std::endl;
*d=*c;
std::cout << (e->insert(399)) << std::endl;
*a=*b;
a->printPretty();
c->printPretty();
std::cout << (c->insert(399)) << std::endl;
*a=*d;
std::cout << (c->insert(302)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
std::cout << (a->remove(267)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
*c=*e;
std::cout << (b->remove(295)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (d->remove(301)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (d->remove(452)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
*d=*b;
std::cout << (b->insert(176)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
*e=*d;
std::cout << (b->remove(206)) << std::endl;
std::cout << (a->insert(119)) << std::endl;
std::cout << (b->insert(449)) << std::endl;
e->printPretty();
std::cout << (a->remove(275)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
c->printPretty();
std::cout << (b->insert(119)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(449)) << std::endl;
std::cout << (b->insert(324)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
c->printPretty();
std::cout << (c->insert(450)) << std::endl;
std::cout << (b->remove(323)) << std::endl;
e->printPretty();
std::cout << (e->insert(199)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
*e=*d;
std::cout << (a->insert(200)) << std::endl;
*d=*d;
std::cout << (e->remove(62)) << std::endl;
*c=*d;
std::cout << (c->insert(199)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (b->remove(199)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
b->printPretty();
std::cout << (d->remove(273)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (d->insert(57)) << std::endl;
e->printPretty();
std::cout << (d->remove(57)) << std::endl;
b->printPretty();
std::cout << (a->insert(295)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
*b=*d;
e->printPretty();
*d=*b;
std::cout << (b->insert(276)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
*d=*d;
*a=*c;
std::cout << (c->insert(262)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (c->remove(491)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (e->remove(276)) << std::endl;
std::cout << (e->remove(281)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
*c=*c;
std::cout << (d->remove(246)) << std::endl;
e->printPretty();
a->printPretty();
*b=*c;
std::cout << (a->insert(262)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (b->remove(202)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
d->printPretty();
std::cout << (c->insert(12)) << std::endl;
d->printPretty();
*d=*e;
a->printPretty();
*a=*e;
std::cout << (c->remove(12)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
*b=*e;
std::cout << (d->insert(199)) << std::endl;
*a=*e;
std::cout << (c->insert(424)) << std::endl;
*c=*a;
*d=*e;
b->printPretty();
std::cout << (b->insert(119)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
*b=*e;
std::cout << (e->remove(63)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (e->remove(119)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
std::cout << (e->remove(349)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
*e=*a;
*e=*d;
*d=*b;
c->printPretty();
std::cout << (d->insert(43)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
*e=*b;
std::cout << (d->remove(78)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
c->printPretty();
std::cout << (a->insert(171)) << std::endl;
e->printPretty();
std::cout << (a->insert(171)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
*a=*e;
std::cout << (c->insert(422)) << std::endl;
std::cout << (a->insert(199)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
*e=*d;
std::cout << (c->insert(157)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
std::cout << (a->insert(119)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->insert(43)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
d->printPretty();
std::cout << (b->remove(56)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (c->remove(257)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (b->remove(199)) << std::endl;
d->printPretty();
std::cout << (a->remove(1)) << std::endl;
std::cout << (c->remove(199)) << std::endl;
*d=*e;
std::cout << (e->remove(43)) << std::endl;
std::cout << (e->insert(253)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
a->printPretty();
std::cout << (c->insert(41)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
e->printPretty();
std::cout << (d->remove(60)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (c->insert(86)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
std::cout << (d->remove(337)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (d->insert(55)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
*e=*b;
std::cout << (e->insert(162)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
d->printPretty();
std::cout << (c->insert(129)) << std::endl;
std::cout << (e->insert(162)) << std::endl;
*e=*b;
std::cout << (b->remove(48)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
*d=*b;
std::cout << (a->insert(199)) << std::endl;
*a=*c;
std::cout << (d->insert(430)) << std::endl;
*c=*b;
std::cout << (a->insert(75)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (e->remove(19)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
*e=*d;
*d=*e;
std::cout << (e->insert(430)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
*b=*c;
a->printPretty();
*b=*e;
std::cout << (a->insert(359)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
*c=*c;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
b->printPretty();
std::cout << (d->remove(348)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
*d=*c;
std::cout << (d->remove(327)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
std::cout << (c->remove(85)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
*a=*e;
std::cout << (e->remove(430)) << std::endl;
std::cout << (e->remove(200)) << std::endl;
*a=*b;
*c=*b;
d->printPretty();
std::cout << (c->remove(151)) << std::endl;
a->printPretty();
std::cout << (a->insert(214)) << std::endl;
std::cout << (d->insert(8)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
a->printPretty();
std::cout << (c->remove(185)) << std::endl;
*a=*d;
std::cout << (c->remove(448)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
*a=*d;
*d=*d;
std::cout << (e->insert(3)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
*b=*b;
*a=*c;
*c=*b;
std::cout << (c->insert(453)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (a->insert(224)) << std::endl;
c->printPretty();
e->printPretty();
c->printPretty();
e->printPretty();
std::cout << (c->remove(108)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (a->remove(340)) << std::endl;
*d=*a;
std::cout << (c->remove(453)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
*d=*e;
std::cout << (d->insert(453)) << std::endl;
e->printPretty();
d->printPretty();
a->printPretty();
d->printPretty();
std::cout << (c->insert(283)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(142)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
b->printPretty();
std::cout << (c->insert(193)) << std::endl;
*c=*c;
*b=*e;
*c=*b;
std::cout << (b->insert(250)) << std::endl;
std::cout << (d->remove(453)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
e->printPretty();
std::cout << (d->remove(134)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (d->insert(236)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(224)) << std::endl;
*c=*b;
std::cout << (b->remove(393)) << std::endl;
*e=*e;
std::cout << (c->insert(365)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->remove(250)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
e->printPretty();
*e=*c;
*c=*c;
std::cout << (e->insert(453)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
e->printPretty();
std::cout << (b->remove(453)) << std::endl;
d->printPretty();
std::cout << (e->insert(250)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(236)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
*a=*c;
std::cout << (b->insert(194)) << std::endl;
std::cout << (b->insert(480)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
b->printPretty();
std::cout << (b->insert(336)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (b->insert(480)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
a->printPretty();
*b=*a;
*a=*b;
std::cout << (e->insert(365)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
*e=*d;
std::cout << (d->insert(441)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
std::cout << (b->remove(307)) << std::endl;
*d=*e;
std::cout << (b->insert(1)) << std::endl;
std::cout << (c->insert(188)) << std::endl;
std::cout << (b->insert(118)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
*b=*b;
std::cout << (c->insert(188)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
std::cout << (c->remove(86)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
std::cout << (b->insert(118)) << std::endl;
*d=*c;
d->printPretty();
*c=*d;
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (b->insert(433)) << std::endl;
*c=*c;
std::cout << (d->insert(90)) << std::endl;
*d=*c;
*b=*c;
*d=*c;
std::cout << (a->remove(358)) << std::endl;
b->printPretty();
std::cout << (d->insert(188)) << std::endl;
a->printPretty();
std::cout << (d->insert(440)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
d->printPretty();
std::cout << (b->remove(188)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (a->insert(345)) << std::endl;
std::cout << (e->remove(238)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
std::cout << (c->remove(330)) << std::endl;
*a=*b;
std::cout << (d->remove(440)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
*c=*a;
std::cout << (d->remove(96)) << std::endl;
*e=*b;
std::cout << (c->remove(455)) << std::endl;
std::cout << (d->insert(188)) << std::endl;
*a=*b;
std::cout << (b->insert(397)) << std::endl;
std::cout << (c->insert(8)) << std::endl;
*a=*c;
std::cout << (c->insert(8)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
b->printPretty();
std::cout << (a->remove(8)) << std::endl;
*d=*d;
std::cout << (c->insert(8)) << std::endl;
*e=*a;
std::cout << (e->insert(26)) << std::endl;
std::cout << (c->insert(8)) << std::endl;
d->printPretty();
c->printPretty();
*d=*e;
std::cout << (d->insert(164)) << std::endl;
b->printPretty();
std::cout << (c->remove(335)) << std::endl;
a->printPretty();
std::cout << (b->insert(397)) << std::endl;
std::cout << (e->insert(26)) << std::endl;
std::cout << (e->insert(26)) << std::endl;
*a=*d;
std::cout << (b->remove(397)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
a->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->remove(111)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
*a=*b;
std::cout << (c->remove(8)) << std::endl;
b->printPretty();
e->printPretty();
*a=*b;
*c=*b;
std::cout << (e->insert(377)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
*d=*c;
std::cout << (e->insert(377)) << std::endl;
*a=*d;
*c=*d;
std::cout << (e->remove(359)) << std::endl;
*e=*e;
std::cout << (a->remove(389)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
*c=*e;
*c=*b;
std::cout << (a->remove(10)) << std::endl;
b->printPretty();
std::cout << (a->insert(83)) << std::endl;
return 0;
}
