#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(30)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(329)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*d=*c;
std::cout << (c->insert(341)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(457)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (a->insert(404)) << std::endl;
a->printPretty();
std::cout << (a->remove(391)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (a->insert(314)) << std::endl;
*c=*b;
std::cout << (e->insert(107)) << std::endl;
std::cout << (b->remove(100)) << std::endl;
d->printPretty();
std::cout << (a->insert(240)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
d->printPretty();
std::cout << (c->remove(313)) << std::endl;
*a=*e;
std::cout << (a->insert(107)) << std::endl;
*b=*a;
*e=*c;
std::cout << (d->insert(494)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
b->printPretty();
std::cout << (d->insert(181)) << std::endl;
std::cout << (c->remove(199)) << std::endl;
std::cout << (b->remove(212)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(185)) << std::endl;
e->printPretty();
std::cout << (c->remove(185)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
e->printPretty();
std::cout << (b->remove(281)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (b->remove(307)) << std::endl;
e->printPretty();
std::cout << (c->insert(149)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
std::cout << (d->remove(181)) << std::endl;
*c=*d;
*c=*a;
std::cout << (a->remove(133)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
*b=*e;
std::cout << (d->insert(263)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
d->printPretty();
std::cout << (d->insert(213)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (c->remove(233)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (a->insert(215)) << std::endl;
std::cout << (b->remove(240)) << std::endl;
std::cout << (d->insert(221)) << std::endl;
e->printPretty();
std::cout << (a->remove(356)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->insert(317)) << std::endl;
*d=*d;
std::cout << (b->remove(317)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (d->remove(494)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
*c=*c;
std::cout << (b->insert(234)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
std::cout << (b->remove(311)) << std::endl;
a->printPretty();
std::cout << (a->insert(215)) << std::endl;
*b=*d;
*a=*e;
a->printPretty();
std::cout << (a->insert(256)) << std::endl;
e->printPretty();
std::cout << (b->remove(482)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (e->insert(355)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
*d=*c;
std::cout << (d->remove(175)) << std::endl;
*d=*c;
std::cout << (d->remove(54)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
*c=*e;
*e=*c;
*b=*a;
e->printPretty();
*c=*d;
*e=*a;
*d=*e;
std::cout << (b->remove(101)) << std::endl;
a->printPretty();
a->printPretty();
e->printPretty();
std::cout << (a->remove(101)) << std::endl;
d->printPretty();
std::cout << (b->insert(80)) << std::endl;
*e=*c;
std::cout << (b->insert(254)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (d->remove(270)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
b->printPretty();
std::cout << (d->insert(101)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
*e=*a;
std::cout << (d->remove(101)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
std::cout << (b->remove(403)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
*e=*e;
std::cout << (e->remove(375)) << std::endl;
*d=*b;
std::cout << (d->remove(358)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (b->remove(80)) << std::endl;
d->printPretty();
std::cout << (e->insert(125)) << std::endl;
*b=*c;
std::cout << (d->remove(80)) << std::endl;
*a=*e;
std::cout << (e->insert(270)) << std::endl;
e->printPretty();
std::cout << (a->insert(375)) << std::endl;
*d=*d;
std::cout << (a->insert(121)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
c->printPretty();
std::cout << (c->insert(66)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
*d=*b;
std::cout << (d->insert(490)) << std::endl;
d->printPretty();
std::cout << (c->insert(66)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
a->printPretty();
std::cout << (a->remove(299)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(21)) << std::endl;
*b=*a;
std::cout << (e->insert(125)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(494)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
*e=*a;
std::cout << (d->remove(166)) << std::endl;
*c=*e;
*d=*e;
c->printPretty();
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
*a=*d;
std::cout << (e->remove(121)) << std::endl;
d->printPretty();
std::cout << (d->remove(121)) << std::endl;
d->printPretty();
std::cout << (e->insert(47)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
*d=*b;
std::cout << (b->insert(375)) << std::endl;
std::cout << (a->insert(384)) << std::endl;
*e=*e;
std::cout << (a->insert(104)) << std::endl;
c->printPretty();
*c=*e;
d->printPretty();
*c=*c;
*e=*d;
std::cout << (c->insert(148)) << std::endl;
a->printPretty();
std::cout << (a->remove(384)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(496)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
*d=*e;
std::cout << (c->remove(215)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
*e=*b;
std::cout << (a->insert(121)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (a->remove(125)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
*d=*b;
std::cout << (d->insert(227)) << std::endl;
*d=*b;
std::cout << (a->insert(359)) << std::endl;
*a=*e;
std::cout << (b->insert(66)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
*b=*b;
std::cout << (e->remove(121)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*c=*b;
*e=*b;
std::cout << (a->insert(9)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
c->printPretty();
std::cout << (c->insert(172)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
d->printPretty();
std::cout << (a->insert(121)) << std::endl;
b->printPretty();
std::cout << (c->remove(110)) << std::endl;
c->printPretty();
std::cout << (d->remove(446)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (a->remove(125)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (d->remove(121)) << std::endl;
a->printPretty();
std::cout << (b->insert(4)) << std::endl;
*b=*d;
*c=*c;
e->printPretty();
std::cout << (b->remove(114)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
*e=*d;
std::cout << (d->insert(375)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
b->printPretty();
std::cout << (b->insert(375)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
c->printPretty();
std::cout << (b->remove(335)) << std::endl;
e->printPretty();
std::cout << (c->insert(375)) << std::endl;
*e=*b;
*d=*e;
std::cout << (c->remove(496)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (d->remove(223)) << std::endl;
b->printPretty();
std::cout << (b->remove(172)) << std::endl;
*d=*d;
std::cout << (b->insert(108)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
b->printPretty();
std::cout << (e->insert(297)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
d->printPretty();
std::cout << (e->insert(414)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (d->remove(333)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
*d=*b;
std::cout << (a->insert(11)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
*a=*c;
std::cout << (c->insert(275)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
d->printPretty();
std::cout << (c->insert(19)) << std::endl;
b->printPretty();
std::cout << (c->insert(19)) << std::endl;
std::cout << (c->remove(66)) << std::endl;
std::cout << (b->remove(496)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
*b=*e;
std::cout << (e->insert(67)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
*e=*b;
std::cout << (a->remove(459)) << std::endl;
*d=*e;
std::cout << (e->remove(492)) << std::endl;
*d=*d;
*d=*d;
std::cout << (d->remove(448)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(375)) << std::endl;
c->printPretty();
std::cout << (c->remove(313)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
*e=*a;
std::cout << (d->insert(359)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
std::cout << (a->remove(151)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
*e=*b;
std::cout << (e->remove(414)) << std::endl;
c->printPretty();
std::cout << (b->insert(346)) << std::endl;
*a=*d;
*d=*a;
std::cout << (b->remove(69)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (d->remove(237)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (b->insert(346)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
*e=*c;
std::cout << (c->insert(101)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (c->insert(433)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
*e=*a;
std::cout << (b->remove(240)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (c->remove(383)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
std::cout << (d->insert(452)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
e->printPretty();
std::cout << (b->insert(17)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
e->printPretty();
std::cout << (e->insert(126)) << std::endl;
*a=*a;
std::cout << (e->remove(68)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
d->printPretty();
std::cout << (a->insert(414)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
std::cout << (c->insert(79)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (b->insert(496)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
*b=*c;
std::cout << (a->remove(346)) << std::endl;
std::cout << (c->insert(433)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
e->printPretty();
std::cout << (b->remove(425)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (b->insert(275)) << std::endl;
b->printPretty();
std::cout << (e->remove(471)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (d->insert(235)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (d->remove(236)) << std::endl;
*a=*a;
*c=*a;
std::cout << (b->remove(99)) << std::endl;
std::cout << (c->insert(496)) << std::endl;
*c=*c;
std::cout << (e->remove(389)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->insert(301)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->remove(370)) << std::endl;
c->printPretty();
std::cout << (c->insert(352)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
*a=*b;
std::cout << (d->insert(492)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
*e=*d;
std::cout << (e->remove(92)) << std::endl;
*e=*c;
std::cout << (b->insert(101)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
c->printPretty();
*c=*e;
*d=*e;
std::cout << (c->insert(496)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
d->printPretty();
std::cout << (e->insert(496)) << std::endl;
b->printPretty();
std::cout << (d->insert(92)) << std::endl;
b->printPretty();
std::cout << (d->insert(461)) << std::endl;
c->printPretty();
std::cout << (d->remove(461)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (c->remove(380)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (c->insert(230)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
b->printPretty();
*a=*d;
a->printPretty();
std::cout << (b->remove(450)) << std::endl;
*b=*a;
e->printPretty();
*c=*c;
*a=*b;
e->printPretty();
std::cout << (e->insert(492)) << std::endl;
std::cout << (e->insert(285)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (d->insert(431)) << std::endl;
*c=*e;
std::cout << (b->insert(352)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (a->insert(80)) << std::endl;
std::cout << (e->remove(496)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(92)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
*c=*a;
std::cout << (b->insert(492)) << std::endl;
*e=*a;
std::cout << (d->insert(35)) << std::endl;
*d=*d;
std::cout << (e->remove(41)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
*e=*a;
std::cout << (e->remove(492)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
c->printPretty();
std::cout << (d->remove(92)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
c->printPretty();
std::cout << (c->remove(89)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
e->printPretty();
d->printPretty();
d->printPretty();
*b=*d;
std::cout << (d->insert(6)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
*a=*d;
e->printPretty();
a->printPretty();
std::cout << (c->remove(240)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
b->printPretty();
std::cout << (a->insert(496)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (d->insert(226)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
std::cout << (a->insert(433)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
*e=*a;
std::cout << (d->remove(497)) << std::endl;
std::cout << (d->insert(370)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
*d=*b;
std::cout << (a->remove(104)) << std::endl;
d->printPretty();
std::cout << (e->insert(235)) << std::endl;
std::cout << (d->insert(382)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
b->printPretty();
std::cout << (b->insert(35)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
b->printPretty();
std::cout << (b->remove(235)) << std::endl;
std::cout << (a->remove(431)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->remove(150)) << std::endl;
std::cout << (b->remove(349)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
c->printPretty();
b->printPretty();
*c=*e;
std::cout << (e->remove(104)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (c->insert(54)) << std::endl;
e->printPretty();
std::cout << (e->remove(235)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->remove(352)) << std::endl;
e->printPretty();
d->printPretty();
*e=*b;
std::cout << (c->insert(104)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
*a=*d;
std::cout << (e->insert(55)) << std::endl;
*b=*e;
std::cout << (d->remove(324)) << std::endl;
*a=*e;
std::cout << (e->insert(470)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
a->printPretty();
std::cout << (b->remove(352)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (b->insert(38)) << std::endl;
std::cout << (e->insert(433)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
*c=*a;
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
b->printPretty();
std::cout << (c->insert(487)) << std::endl;
*c=*c;
std::cout << (c->remove(79)) << std::endl;
std::cout << (a->remove(248)) << std::endl;
std::cout << (b->remove(131)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
*e=*b;
std::cout << (d->remove(418)) << std::endl;
std::cout << (d->remove(90)) << std::endl;
std::cout << (b->insert(185)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
*c=*d;
std::cout << (b->remove(293)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
a->printPretty();
std::cout << (d->remove(241)) << std::endl;
a->printPretty();
std::cout << (c->insert(496)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
*a=*d;
std::cout << (e->insert(446)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->remove(184)) << std::endl;
*d=*c;
*c=*b;
std::cout << (d->insert(469)) << std::endl;
*d=*c;
std::cout << (c->insert(75)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
d->printPretty();
std::cout << (e->insert(114)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
*d=*d;
d->printPretty();
d->printPretty();
std::cout << (a->remove(382)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (c->insert(431)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
*a=*d;
std::cout << (b->remove(492)) << std::endl;
std::cout << (b->remove(269)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (b->remove(328)) << std::endl;
*c=*c;
std::cout << (e->remove(254)) << std::endl;
*e=*e;
d->printPretty();
*c=*e;
std::cout << (e->remove(490)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
*c=*e;
std::cout << (c->remove(220)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (c->remove(96)) << std::endl;
*e=*e;
std::cout << (a->insert(232)) << std::endl;
std::cout << (e->insert(464)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
c->printPretty();
return 0;
}
