#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
b->printPretty();
b->printPretty();
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (c->remove(86)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (d->insert(119)) << std::endl;
*d=*c;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
e->printPretty();
*d=*a;
e->printPretty();
std::cout << (d->insert(246)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
*a=*d;
*d=*b;
std::cout << (d->insert(365)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
*e=*b;
std::cout << (c->remove(70)) << std::endl;
*d=*c;
*c=*c;
a->printPretty();
std::cout << (e->insert(371)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
*a=*e;
std::cout << (e->insert(80)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->remove(255)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (a->remove(222)) << std::endl;
*d=*c;
std::cout << (e->remove(80)) << std::endl;
*b=*a;
a->printPretty();
e->printPretty();
*c=*d;
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
*e=*d;
std::cout << (a->insert(365)) << std::endl;
a->printPretty();
std::cout << (a->remove(111)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (a->insert(365)) << std::endl;
std::cout << (d->remove(434)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (e->remove(85)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
b->printPretty();
b->printPretty();
a->printPretty();
*b=*b;
b->printPretty();
std::cout << (d->remove(371)) << std::endl;
std::cout << (c->insert(365)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
*e=*e;
std::cout << (e->insert(371)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
c->printPretty();
std::cout << (c->remove(365)) << std::endl;
a->printPretty();
std::cout << (a->insert(447)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (d->remove(204)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->insert(371)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (e->remove(381)) << std::endl;
std::cout << (a->insert(365)) << std::endl;
a->printPretty();
std::cout << (e->remove(149)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
e->printPretty();
std::cout << (d->insert(469)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(473)) << std::endl;
e->printPretty();
std::cout << (e->remove(195)) << std::endl;
d->printPretty();
std::cout << (e->remove(66)) << std::endl;
c->printPretty();
std::cout << (b->insert(365)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
*e=*a;
b->printPretty();
*b=*b;
std::cout << (d->remove(384)) << std::endl;
std::cout << (b->remove(429)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (a->insert(365)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
*b=*e;
std::cout << (e->remove(479)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (a->remove(488)) << std::endl;
*d=*e;
std::cout << (b->remove(365)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
b->printPretty();
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(338)) << std::endl;
*e=*d;
std::cout << (b->remove(479)) << std::endl;
*a=*e;
std::cout << (e->remove(288)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
std::cout << (b->insert(338)) << std::endl;
*d=*b;
*b=*c;
std::cout << (a->remove(371)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
*a=*a;
std::cout << (d->remove(338)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (a->insert(132)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
a->printPretty();
std::cout << (a->insert(53)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
d->printPretty();
std::cout << (e->insert(365)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (a->insert(347)) << std::endl;
d->printPretty();
std::cout << (b->insert(414)) << std::endl;
std::cout << (c->remove(414)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
std::cout << (a->remove(121)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
d->printPretty();
std::cout << (e->remove(297)) << std::endl;
std::cout << (c->remove(49)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (c->insert(390)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
a->printPretty();
e->printPretty();
*b=*b;
*c=*c;
std::cout << (e->remove(40)) << std::endl;
c->printPretty();
std::cout << (c->insert(63)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
*c=*a;
std::cout << (a->insert(121)) << std::endl;
*a=*a;
std::cout << (d->insert(301)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->insert(53)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
*a=*e;
std::cout << (c->remove(247)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
*c=*d;
std::cout << (c->remove(241)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
*e=*b;
*a=*e;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
*a=*b;
std::cout << (d->insert(301)) << std::endl;
a->printPretty();
std::cout << (a->remove(288)) << std::endl;
b->printPretty();
std::cout << (d->remove(288)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (b->insert(369)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->remove(110)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
*a=*c;
std::cout << (a->remove(150)) << std::endl;
std::cout << (c->remove(288)) << std::endl;
e->printPretty();
std::cout << (d->remove(301)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
*c=*a;
std::cout << (b->remove(369)) << std::endl;
std::cout << (d->remove(240)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
b->printPretty();
std::cout << (e->remove(288)) << std::endl;
std::cout << (b->insert(301)) << std::endl;
*c=*c;
std::cout << (c->insert(371)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (c->remove(301)) << std::endl;
*e=*d;
std::cout << (a->insert(310)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
b->printPretty();
std::cout << (b->insert(45)) << std::endl;
*e=*e;
std::cout << (e->insert(366)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
*c=*e;
std::cout << (b->remove(43)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
*b=*c;
std::cout << (a->remove(371)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
*c=*a;
std::cout << (a->remove(11)) << std::endl;
c->printPretty();
d->printPretty();
e->printPretty();
std::cout << (e->insert(366)) << std::endl;
a->printPretty();
std::cout << (b->insert(366)) << std::endl;
std::cout << (b->insert(171)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
std::cout << (b->remove(366)) << std::endl;
d->printPretty();
std::cout << (b->remove(247)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
*d=*a;
std::cout << (c->insert(310)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (a->insert(310)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
*b=*d;
*a=*d;
std::cout << (b->remove(288)) << std::endl;
std::cout << (d->insert(288)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (e->insert(334)) << std::endl;
std::cout << (c->insert(310)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
a->printPretty();
std::cout << (a->remove(179)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
std::cout << (a->remove(288)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (a->remove(471)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (a->insert(467)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
c->printPretty();
std::cout << (a->insert(310)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(310)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (b->insert(72)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
*b=*c;
std::cout << (a->insert(402)) << std::endl;
e->printPretty();
std::cout << (a->remove(309)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
*e=*c;
std::cout << (a->remove(394)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
std::cout << (e->remove(310)) << std::endl;
*c=*d;
d->printPretty();
std::cout << (c->insert(211)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
d->printPretty();
std::cout << (d->remove(310)) << std::endl;
std::cout << (e->insert(274)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
*e=*e;
std::cout << (e->insert(17)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
a->printPretty();
std::cout << (c->remove(310)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (d->insert(381)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (e->insert(17)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (d->insert(407)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
*c=*d;
*e=*e;
std::cout << (a->insert(467)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (d->remove(127)) << std::endl;
b->printPretty();
std::cout << (d->insert(472)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (a->remove(287)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
*c=*a;
c->printPretty();
*d=*e;
std::cout << (b->remove(113)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (c->insert(79)) << std::endl;
*e=*e;
std::cout << (a->insert(462)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
std::cout << (c->remove(429)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (c->insert(472)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
*b=*e;
std::cout << (d->insert(281)) << std::endl;
c->printPretty();
std::cout << (c->insert(211)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
*b=*a;
std::cout << (e->insert(472)) << std::endl;
*d=*a;
std::cout << (b->insert(211)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (a->remove(462)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->remove(462)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (d->insert(79)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
b->printPretty();
std::cout << (c->remove(79)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (d->insert(407)) << std::endl;
std::cout << (c->remove(200)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(28)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(472)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
*d=*c;
std::cout << (c->insert(407)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
b->printPretty();
std::cout << (c->remove(17)) << std::endl;
*a=*b;
std::cout << (a->insert(132)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->insert(65)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
std::cout << (d->insert(464)) << std::endl;
*d=*a;
std::cout << (d->remove(132)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
std::cout << (a->insert(212)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
*a=*a;
std::cout << (a->insert(79)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
*c=*c;
std::cout << (c->insert(157)) << std::endl;
a->printPretty();
std::cout << (e->insert(436)) << std::endl;
*c=*c;
std::cout << (a->remove(5)) << std::endl;
d->printPretty();
std::cout << (b->remove(17)) << std::endl;
std::cout << (e->remove(150)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
*b=*d;
*e=*a;
*c=*d;
e->printPretty();
e->printPretty();
std::cout << (e->remove(132)) << std::endl;
std::cout << (d->remove(356)) << std::endl;
b->printPretty();
std::cout << (e->remove(373)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
*b=*d;
std::cout << (a->insert(407)) << std::endl;
*d=*c;
std::cout << (c->insert(144)) << std::endl;
c->printPretty();
std::cout << (b->remove(407)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
*d=*d;
std::cout << (e->insert(351)) << std::endl;
*d=*d;
*c=*d;
*b=*d;
c->printPretty();
std::cout << (e->insert(351)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
std::cout << (a->remove(144)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
*a=*b;
std::cout << (e->insert(186)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (c->remove(17)) << std::endl;
*a=*a;
std::cout << (e->remove(79)) << std::endl;
std::cout << (d->insert(432)) << std::endl;
a->printPretty();
std::cout << (c->remove(472)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
b->printPretty();
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
c->printPretty();
std::cout << (b->remove(209)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
b->printPretty();
std::cout << (a->remove(407)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
*a=*e;
std::cout << (b->insert(40)) << std::endl;
e->printPretty();
std::cout << (c->insert(39)) << std::endl;
*a=*c;
std::cout << (b->remove(148)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
d->printPretty();
std::cout << (b->remove(472)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
*d=*c;
std::cout << (e->insert(407)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
*a=*b;
std::cout << (b->remove(43)) << std::endl;
*d=*d;
std::cout << (c->remove(79)) << std::endl;
std::cout << (a->remove(176)) << std::endl;
std::cout << (e->insert(50)) << std::endl;
e->printPretty();
std::cout << (c->insert(229)) << std::endl;
e->printPretty();
std::cout << (b->insert(369)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
*e=*a;
std::cout << (b->remove(127)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (e->insert(17)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
e->printPretty();
b->printPretty();
a->printPretty();
std::cout << (d->insert(336)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (c->insert(65)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
std::cout << (a->remove(187)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (c->insert(79)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
*e=*d;
std::cout << (b->insert(65)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (a->insert(65)) << std::endl;
*e=*e;
std::cout << (c->insert(59)) << std::endl;
std::cout << (c->remove(59)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
*b=*b;
std::cout << (e->insert(491)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(269)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
std::cout << (d->insert(79)) << std::endl;
a->printPretty();
std::cout << (b->remove(174)) << std::endl;
c->printPretty();
std::cout << (b->insert(173)) << std::endl;
std::cout << (a->insert(102)) << std::endl;
*e=*b;
std::cout << (e->remove(425)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
std::cout << (d->remove(336)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
e->printPretty();
std::cout << (b->insert(103)) << std::endl;
c->printPretty();
std::cout << (c->insert(102)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (d->insert(411)) << std::endl;
std::cout << (d->insert(411)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (d->insert(411)) << std::endl;
*d=*b;
std::cout << (a->insert(143)) << std::endl;
std::cout << (d->insert(103)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (c->insert(49)) << std::endl;
std::cout << (c->insert(327)) << std::endl;
*e=*e;
std::cout << (e->insert(65)) << std::endl;
std::cout << (c->insert(79)) << std::endl;
a->printPretty();
std::cout << (b->remove(65)) << std::endl;
a->printPretty();
std::cout << (c->remove(17)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
*d=*c;
*b=*b;
std::cout << (e->remove(25)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
b->printPretty();
std::cout << (a->remove(198)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (b->insert(294)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
*b=*b;
std::cout << (d->remove(143)) << std::endl;
c->printPretty();
std::cout << (c->remove(40)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
b->printPretty();
std::cout << (d->remove(79)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (b->insert(439)) << std::endl;
std::cout << (a->insert(237)) << std::endl;
a->printPretty();
*d=*a;
d->printPretty();
std::cout << (a->insert(102)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
*a=*d;
std::cout << (c->insert(90)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
*c=*e;
std::cout << (a->remove(493)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
*b=*b;
std::cout << (b->remove(411)) << std::endl;
std::cout << (b->remove(192)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
*b=*a;
std::cout << (b->remove(204)) << std::endl;
*c=*b;
*b=*c;
std::cout << (d->insert(369)) << std::endl;
c->printPretty();
std::cout << (c->remove(190)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (c->insert(237)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
*a=*e;
std::cout << (a->remove(411)) << std::endl;
*e=*a;
std::cout << (b->remove(437)) << std::endl;
std::cout << (c->remove(102)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
return 0;
}
