#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(67)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
a->printPretty();
std::cout << (a->remove(389)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
a->printPretty();
std::cout << (b->insert(267)) << std::endl;
a->printPretty();
std::cout << (b->remove(267)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (b->insert(354)) << std::endl;
c->printPretty();
std::cout << (b->remove(354)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(487)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
*d=*e;
std::cout << (c->insert(134)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
*c=*d;
*a=*a;
c->printPretty();
c->printPretty();
std::cout << (c->remove(251)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
std::cout << (c->remove(23)) << std::endl;
e->printPretty();
std::cout << (d->insert(317)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (b->insert(208)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
*a=*a;
std::cout << (e->insert(295)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
b->printPretty();
std::cout << (b->remove(208)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
*b=*b;
*a=*b;
std::cout << (e->remove(295)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (c->remove(209)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (e->remove(3)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (c->insert(47)) << std::endl;
b->printPretty();
std::cout << (a->remove(351)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
*d=*b;
*c=*e;
e->printPretty();
a->printPretty();
b->printPretty();
*b=*e;
*d=*b;
*a=*b;
std::cout << (b->insert(371)) << std::endl;
*e=*c;
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->insert(310)) << std::endl;
b->printPretty();
std::cout << (c->insert(310)) << std::endl;
std::cout << (b->insert(371)) << std::endl;
*e=*a;
std::cout << (b->remove(371)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
*c=*d;
std::cout << (a->remove(305)) << std::endl;
*c=*e;
std::cout << (b->remove(404)) << std::endl;
std::cout << (a->remove(215)) << std::endl;
d->printPretty();
std::cout << (b->insert(25)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
std::cout << (a->insert(164)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
*c=*e;
std::cout << (d->insert(330)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
*e=*a;
std::cout << (e->remove(244)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
*a=*e;
std::cout << (d->remove(176)) << std::endl;
std::cout << (b->insert(389)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
b->printPretty();
std::cout << (d->remove(263)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (c->remove(163)) << std::endl;
b->printPretty();
std::cout << (b->insert(417)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
c->printPretty();
std::cout << (a->remove(191)) << std::endl;
*d=*c;
std::cout << (c->remove(30)) << std::endl;
*b=*a;
*e=*c;
c->printPretty();
*a=*b;
std::cout << (d->remove(497)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
a->printPretty();
std::cout << (d->insert(431)) << std::endl;
std::cout << (a->remove(88)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
*a=*c;
std::cout << (b->insert(284)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
std::cout << (d->remove(201)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (b->remove(284)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
d->printPretty();
std::cout << (e->insert(258)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
d->printPretty();
e->printPretty();
*e=*c;
e->printPretty();
c->printPretty();
*a=*b;
std::cout << (b->remove(85)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
*e=*a;
e->printPretty();
*a=*c;
std::cout << (e->insert(216)) << std::endl;
*b=*b;
std::cout << (c->remove(339)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->insert(339)) << std::endl;
std::cout << (b->remove(485)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (b->insert(204)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
*c=*b;
std::cout << (c->insert(472)) << std::endl;
*d=*a;
std::cout << (d->insert(339)) << std::endl;
std::cout << (e->insert(454)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (e->insert(454)) << std::endl;
*b=*c;
std::cout << (a->remove(6)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
*a=*e;
std::cout << (c->insert(420)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(430)) << std::endl;
*d=*d;
*e=*c;
std::cout << (d->insert(274)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
*a=*b;
std::cout << (e->remove(434)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
std::cout << (c->remove(60)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
b->printPretty();
std::cout << (b->remove(216)) << std::endl;
*b=*d;
std::cout << (b->insert(88)) << std::endl;
std::cout << (d->insert(397)) << std::endl;
std::cout << (e->remove(177)) << std::endl;
*a=*a;
*e=*d;
std::cout << (d->remove(335)) << std::endl;
e->printPretty();
std::cout << (e->insert(397)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
d->printPretty();
e->printPretty();
*d=*e;
a->printPretty();
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
b->printPretty();
std::cout << (d->remove(193)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
*b=*b;
d->printPretty();
*a=*a;
std::cout << (d->remove(397)) << std::endl;
*c=*a;
std::cout << (e->insert(348)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (b->insert(88)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
a->printPretty();
std::cout << (d->remove(284)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (a->insert(82)) << std::endl;
a->printPretty();
std::cout << (c->remove(193)) << std::endl;
std::cout << (d->remove(192)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (b->insert(88)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
*d=*e;
*b=*a;
std::cout << (b->remove(460)) << std::endl;
*d=*e;
*d=*d;
std::cout << (a->insert(155)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (d->insert(397)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (e->remove(363)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
std::cout << (c->insert(371)) << std::endl;
*d=*b;
std::cout << (b->insert(178)) << std::endl;
std::cout << (b->remove(123)) << std::endl;
c->printPretty();
b->printPretty();
*a=*e;
std::cout << (a->insert(397)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (a->remove(291)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
std::cout << (a->insert(348)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
c->printPretty();
b->printPretty();
*a=*b;
std::cout << (b->remove(269)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
*b=*c;
std::cout << (c->remove(216)) << std::endl;
*c=*e;
c->printPretty();
*e=*b;
std::cout << (d->insert(390)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (b->insert(371)) << std::endl;
std::cout << (c->insert(315)) << std::endl;
*d=*a;
std::cout << (c->insert(31)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
*a=*c;
std::cout << (a->remove(274)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
std::cout << (c->insert(348)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
std::cout << (d->remove(262)) << std::endl;
e->printPretty();
std::cout << (b->remove(469)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (d->insert(431)) << std::endl;
*c=*b;
b->printPretty();
std::cout << (b->insert(60)) << std::endl;
*b=*e;
std::cout << (b->insert(277)) << std::endl;
std::cout << (d->insert(431)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (e->insert(477)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
*a=*e;
std::cout << (a->insert(216)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
*b=*e;
std::cout << (a->remove(125)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (a->insert(29)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
*a=*c;
*a=*b;
std::cout << (c->remove(256)) << std::endl;
std::cout << (c->insert(193)) << std::endl;
*d=*d;
*e=*d;
std::cout << (a->remove(216)) << std::endl;
*d=*b;
std::cout << (e->remove(256)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
*e=*a;
*d=*e;
e->printPretty();
b->printPretty();
d->printPretty();
std::cout << (b->insert(216)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (a->remove(340)) << std::endl;
std::cout << (c->insert(371)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
*b=*a;
*a=*d;
*a=*c;
std::cout << (c->insert(371)) << std::endl;
d->printPretty();
std::cout << (e->insert(15)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (c->insert(209)) << std::endl;
std::cout << (a->remove(100)) << std::endl;
*d=*e;
std::cout << (b->insert(477)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
d->printPretty();
std::cout << (b->remove(12)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (e->insert(438)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
*a=*e;
std::cout << (e->remove(449)) << std::endl;
std::cout << (e->remove(454)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
c->printPretty();
std::cout << (a->remove(369)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
a->printPretty();
std::cout << (e->insert(396)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
c->printPretty();
std::cout << (d->remove(498)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (b->remove(310)) << std::endl;
std::cout << (e->insert(448)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
*a=*d;
*a=*c;
*d=*b;
std::cout << (a->insert(239)) << std::endl;
*e=*d;
std::cout << (c->insert(321)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (e->remove(454)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (c->remove(266)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (b->insert(290)) << std::endl;
d->printPretty();
std::cout << (d->insert(371)) << std::endl;
e->printPretty();
std::cout << (b->insert(237)) << std::endl;
*c=*c;
std::cout << (d->insert(405)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
*b=*b;
std::cout << (e->insert(340)) << std::endl;
*c=*a;
std::cout << (d->insert(307)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
*d=*d;
std::cout << (d->remove(477)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
d->printPretty();
std::cout << (c->remove(340)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
std::cout << (a->remove(367)) << std::endl;
e->printPretty();
std::cout << (e->remove(66)) << std::endl;
*b=*a;
std::cout << (a->remove(405)) << std::endl;
std::cout << (c->insert(50)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
d->printPretty();
std::cout << (b->remove(340)) << std::endl;
*e=*d;
std::cout << (b->remove(209)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
*c=*c;
*b=*a;
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (c->insert(209)) << std::endl;
std::cout << (b->remove(477)) << std::endl;
std::cout << (d->remove(340)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
*e=*a;
std::cout << (a->remove(69)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
d->printPretty();
a->printPretty();
e->printPretty();
std::cout << (a->remove(374)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (a->remove(340)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
*a=*a;
std::cout << (d->insert(363)) << std::endl;
*b=*a;
*c=*b;
*a=*e;
*a=*e;
std::cout << (c->remove(315)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (c->remove(403)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
c->printPretty();
std::cout << (c->remove(102)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
*c=*c;
std::cout << (e->insert(340)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
c->printPretty();
std::cout << (d->insert(373)) << std::endl;
*c=*b;
std::cout << (a->insert(304)) << std::endl;
*e=*d;
std::cout << (b->remove(376)) << std::endl;
*a=*b;
*c=*c;
*e=*a;
*d=*c;
std::cout << (a->remove(199)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
*e=*a;
std::cout << (a->remove(286)) << std::endl;
d->printPretty();
std::cout << (a->remove(138)) << std::endl;
*b=*a;
*d=*e;
*d=*c;
std::cout << (d->insert(54)) << std::endl;
e->printPretty();
std::cout << (d->insert(239)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
c->printPretty();
std::cout << (c->remove(31)) << std::endl;
std::cout << (b->insert(461)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
b->printPretty();
std::cout << (b->remove(461)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
*c=*d;
*a=*d;
std::cout << (d->remove(239)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
a->printPretty();
std::cout << (d->remove(239)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
*a=*c;
*e=*b;
std::cout << (c->remove(22)) << std::endl;
*c=*b;
*c=*c;
*b=*a;
a->printPretty();
d->printPretty();
std::cout << (b->remove(335)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
d->printPretty();
std::cout << (b->insert(27)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (e->remove(328)) << std::endl;
*e=*a;
*b=*d;
std::cout << (d->insert(145)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
e->printPretty();
*d=*d;
*c=*a;
std::cout << (d->remove(76)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
b->printPretty();
std::cout << (a->insert(374)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
*d=*d;
std::cout << (b->remove(104)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
*b=*a;
*c=*c;
std::cout << (b->insert(239)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (b->insert(374)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
std::cout << (a->remove(159)) << std::endl;
std::cout << (a->insert(348)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
*a=*d;
std::cout << (b->insert(81)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(19)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (a->remove(145)) << std::endl;
c->printPretty();
std::cout << (a->insert(155)) << std::endl;
d->printPretty();
*a=*e;
a->printPretty();
std::cout << (e->remove(100)) << std::endl;
e->printPretty();
*e=*d;
*d=*e;
std::cout << (b->insert(329)) << std::endl;
b->printPretty();
std::cout << (b->remove(329)) << std::endl;
b->printPretty();
*c=*a;
e->printPretty();
std::cout << (e->remove(245)) << std::endl;
b->printPretty();
std::cout << (c->remove(469)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (b->remove(27)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
*c=*e;
d->printPretty();
b->printPretty();
c->printPretty();
d->printPretty();
std::cout << (e->insert(85)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
c->printPretty();
std::cout << (b->insert(390)) << std::endl;
c->printPretty();
std::cout << (e->insert(272)) << std::endl;
*e=*b;
std::cout << (d->remove(404)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
a->printPretty();
std::cout << (b->remove(81)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (a->insert(101)) << std::endl;
*e=*c;
c->printPretty();
*a=*a;
d->printPretty();
*c=*a;
std::cout << (e->remove(272)) << std::endl;
d->printPretty();
std::cout << (c->remove(101)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
std::cout << (b->insert(374)) << std::endl;
*d=*e;
*e=*d;
*c=*d;
b->printPretty();
*c=*c;
d->printPretty();
std::cout << (e->remove(132)) << std::endl;
std::cout << (c->insert(168)) << std::endl;
*c=*e;
std::cout << (d->remove(251)) << std::endl;
b->printPretty();
std::cout << (e->insert(196)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
std::cout << (d->insert(108)) << std::endl;
*d=*b;
std::cout << (a->insert(324)) << std::endl;
*e=*a;
return 0;
}
