#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
a->printPretty();
std::cout << (a->remove(349)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
a->printPretty();
std::cout << (a->insert(243)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(243)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->remove(25)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (e->remove(228)) << std::endl;
d->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
*a=*b;
*b=*c;
*e=*d;
*d=*e;
a->printPretty();
*c=*b;
std::cout << (e->insert(22)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
b->printPretty();
std::cout << (c->remove(17)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
*e=*d;
std::cout << (c->remove(394)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->insert(128)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (e->remove(313)) << std::endl;
c->printPretty();
std::cout << (d->insert(165)) << std::endl;
b->printPretty();
std::cout << (b->remove(376)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (a->insert(452)) << std::endl;
std::cout << (b->insert(3)) << std::endl;
std::cout << (b->insert(3)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
std::cout << (c->insert(183)) << std::endl;
std::cout << (d->remove(165)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
*c=*d;
d->printPretty();
*c=*a;
std::cout << (b->remove(445)) << std::endl;
c->printPretty();
std::cout << (d->remove(286)) << std::endl;
a->printPretty();
std::cout << (a->remove(109)) << std::endl;
*b=*b;
std::cout << (b->insert(460)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
*e=*e;
std::cout << (e->remove(128)) << std::endl;
*b=*b;
std::cout << (a->remove(452)) << std::endl;
std::cout << (d->remove(121)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
b->printPretty();
*a=*c;
*d=*a;
std::cout << (b->insert(58)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
d->printPretty();
std::cout << (c->insert(17)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
*e=*d;
std::cout << (e->insert(470)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
std::cout << (b->remove(382)) << std::endl;
*a=*e;
*a=*e;
std::cout << (a->remove(86)) << std::endl;
std::cout << (a->insert(72)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
*a=*c;
std::cout << (a->insert(494)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
std::cout << (a->remove(494)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (d->remove(403)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
*c=*a;
std::cout << (d->insert(166)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (b->insert(83)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
c->printPretty();
std::cout << (e->remove(425)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
c->printPretty();
std::cout << (a->insert(17)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
*b=*e;
std::cout << (d->remove(467)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
*c=*e;
std::cout << (a->insert(17)) << std::endl;
d->printPretty();
std::cout << (a->insert(493)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
std::cout << (c->remove(267)) << std::endl;
*a=*c;
std::cout << (b->insert(300)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
b->printPretty();
std::cout << (d->remove(320)) << std::endl;
*d=*b;
std::cout << (e->remove(345)) << std::endl;
c->printPretty();
a->printPretty();
*b=*c;
c->printPretty();
*e=*a;
*b=*a;
std::cout << (b->remove(438)) << std::endl;
*a=*d;
std::cout << (a->insert(300)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
d->printPretty();
std::cout << (b->insert(32)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (b->insert(35)) << std::endl;
*e=*a;
std::cout << (c->remove(22)) << std::endl;
c->printPretty();
*d=*d;
*c=*a;
std::cout << (a->remove(239)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(300)) << std::endl;
c->printPretty();
std::cout << (e->insert(300)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
d->printPretty();
std::cout << (c->insert(101)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
*d=*c;
std::cout << (b->remove(413)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
b->printPretty();
std::cout << (b->remove(103)) << std::endl;
*b=*d;
std::cout << (b->insert(464)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
*e=*d;
std::cout << (c->remove(300)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
c->printPretty();
std::cout << (a->remove(247)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (c->insert(464)) << std::endl;
*a=*d;
std::cout << (a->insert(300)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
*e=*b;
std::cout << (a->remove(300)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (b->insert(454)) << std::endl;
std::cout << (e->insert(434)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (a->remove(453)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
*d=*c;
std::cout << (e->remove(419)) << std::endl;
a->printPretty();
std::cout << (a->remove(248)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
c->printPretty();
std::cout << (c->insert(301)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->remove(101)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
*b=*c;
std::cout << (d->remove(301)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
e->printPretty();
std::cout << (b->remove(271)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (c->remove(467)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (e->insert(48)) << std::endl;
*a=*d;
std::cout << (d->remove(326)) << std::endl;
std::cout << (d->remove(101)) << std::endl;
std::cout << (a->remove(464)) << std::endl;
d->printPretty();
std::cout << (a->remove(119)) << std::endl;
*d=*c;
*b=*b;
std::cout << (a->insert(406)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (e->insert(300)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (c->insert(101)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
e->printPretty();
std::cout << (d->remove(464)) << std::endl;
e->printPretty();
std::cout << (e->insert(404)) << std::endl;
a->printPretty();
std::cout << (c->insert(211)) << std::endl;
*a=*e;
std::cout << (b->remove(81)) << std::endl;
*e=*e;
std::cout << (b->insert(134)) << std::endl;
*d=*b;
std::cout << (b->insert(454)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
*a=*a;
std::cout << (c->insert(101)) << std::endl;
e->printPretty();
*e=*c;
e->printPretty();
std::cout << (a->remove(404)) << std::endl;
*d=*a;
*a=*c;
e->printPretty();
c->printPretty();
std::cout << (c->insert(464)) << std::endl;
*b=*e;
std::cout << (a->remove(168)) << std::endl;
std::cout << (b->remove(464)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
d->printPretty();
std::cout << (d->remove(101)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (a->insert(92)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
*d=*e;
std::cout << (d->insert(464)) << std::endl;
std::cout << (d->remove(77)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
e->printPretty();
std::cout << (e->remove(403)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (d->insert(299)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
*e=*b;
std::cout << (a->remove(291)) << std::endl;
a->printPretty();
std::cout << (c->remove(101)) << std::endl;
c->printPretty();
std::cout << (e->remove(238)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
a->printPretty();
std::cout << (d->insert(210)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
*e=*e;
*b=*e;
b->printPretty();
std::cout << (c->remove(68)) << std::endl;
std::cout << (e->insert(301)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
std::cout << (b->insert(437)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (b->insert(170)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (b->insert(387)) << std::endl;
*c=*c;
a->printPretty();
a->printPretty();
std::cout << (e->insert(36)) << std::endl;
c->printPretty();
std::cout << (a->remove(211)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
std::cout << (b->remove(287)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (a->remove(211)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
std::cout << (c->remove(211)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (a->remove(352)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
d->printPretty();
*c=*b;
b->printPretty();
std::cout << (b->remove(228)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
d->printPretty();
std::cout << (e->remove(101)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
b->printPretty();
std::cout << (e->remove(157)) << std::endl;
e->printPretty();
std::cout << (b->insert(170)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
*d=*b;
*a=*b;
d->printPretty();
*c=*d;
e->printPretty();
std::cout << (a->insert(228)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (e->insert(352)) << std::endl;
e->printPretty();
std::cout << (e->insert(197)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
*b=*b;
std::cout << (d->remove(437)) << std::endl;
std::cout << (b->insert(159)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
*c=*e;
std::cout << (b->remove(416)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
std::cout << (b->insert(170)) << std::endl;
*b=*d;
std::cout << (b->insert(271)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
e->printPretty();
std::cout << (a->insert(465)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
*b=*d;
*c=*e;
*b=*d;
std::cout << (a->remove(301)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
*c=*e;
*e=*c;
std::cout << (b->insert(190)) << std::endl;
std::cout << (e->remove(301)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (b->remove(301)) << std::endl;
std::cout << (d->insert(388)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
c->printPretty();
d->printPretty();
c->printPretty();
*c=*e;
std::cout << (a->remove(447)) << std::endl;
b->printPretty();
std::cout << (c->insert(485)) << std::endl;
std::cout << (e->remove(197)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->insert(153)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (e->remove(356)) << std::endl;
d->printPretty();
std::cout << (c->remove(388)) << std::endl;
std::cout << (a->insert(23)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
e->printPretty();
*e=*a;
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (a->remove(83)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(170)) << std::endl;
d->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
*a=*b;
std::cout << (c->insert(480)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
*c=*d;
std::cout << (a->remove(322)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
*a=*b;
std::cout << (e->remove(110)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (b->insert(204)) << std::endl;
b->printPretty();
std::cout << (a->insert(202)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (b->insert(183)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (d->remove(388)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
e->printPretty();
std::cout << (e->insert(228)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
c->printPretty();
std::cout << (a->remove(477)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (d->remove(181)) << std::endl;
*b=*c;
std::cout << (c->insert(24)) << std::endl;
*e=*e;
e->printPretty();
std::cout << (b->insert(301)) << std::endl;
std::cout << (d->remove(101)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
*b=*e;
std::cout << (e->insert(228)) << std::endl;
*b=*c;
std::cout << (e->insert(150)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
*e=*b;
std::cout << (e->insert(108)) << std::endl;
d->printPretty();
std::cout << (e->remove(388)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
std::cout << (e->insert(74)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(301)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
a->printPretty();
b->printPretty();
e->printPretty();
std::cout << (c->insert(340)) << std::endl;
std::cout << (e->insert(495)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
*c=*e;
std::cout << (a->remove(332)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
*b=*a;
std::cout << (d->insert(83)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
a->printPretty();
std::cout << (a->insert(76)) << std::endl;
std::cout << (d->insert(340)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
*a=*a;
std::cout << (d->insert(197)) << std::endl;
b->printPretty();
std::cout << (a->insert(351)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (b->remove(93)) << std::endl;
std::cout << (b->insert(149)) << std::endl;
std::cout << (d->remove(81)) << std::endl;
d->printPretty();
std::cout << (a->insert(221)) << std::endl;
c->printPretty();
std::cout << (b->insert(78)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
*d=*d;
std::cout << (a->remove(266)) << std::endl;
std::cout << (a->insert(101)) << std::endl;
e->printPretty();
e->printPretty();
*a=*d;
c->printPretty();
std::cout << (a->remove(243)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
*e=*b;
std::cout << (a->remove(83)) << std::endl;
*d=*c;
b->printPretty();
*d=*c;
e->printPretty();
std::cout << (d->insert(445)) << std::endl;
*a=*e;
c->printPretty();
*b=*c;
std::cout << (a->insert(133)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
b->printPretty();
std::cout << (a->insert(83)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
*a=*c;
std::cout << (e->insert(88)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(500)) << std::endl;
*b=*b;
*b=*b;
*e=*c;
std::cout << (b->insert(416)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
*c=*d;
std::cout << (e->remove(307)) << std::endl;
*d=*c;
std::cout << (d->insert(500)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
*d=*a;
std::cout << (c->remove(495)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
*c=*a;
std::cout << (e->insert(379)) << std::endl;
std::cout << (e->remove(327)) << std::endl;
a->printPretty();
std::cout << (d->remove(379)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
*e=*a;
std::cout << (a->insert(174)) << std::endl;
*b=*d;
std::cout << (d->insert(467)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
*e=*c;
std::cout << (d->insert(416)) << std::endl;
*d=*d;
std::cout << (e->remove(108)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
*b=*e;
std::cout << (a->insert(310)) << std::endl;
e->printPretty();
std::cout << (d->remove(416)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
e->printPretty();
std::cout << (c->insert(211)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
a->printPretty();
std::cout << (a->remove(379)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
*a=*c;
std::cout << (b->remove(233)) << std::endl;
c->printPretty();
std::cout << (c->insert(24)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (c->remove(74)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
*a=*d;
std::cout << (d->remove(301)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
b->printPretty();
std::cout << (e->insert(393)) << std::endl;
c->printPretty();
std::cout << (b->remove(152)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
*e=*b;
*c=*b;
std::cout << (c->insert(96)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
*a=*d;
std::cout << (d->insert(83)) << std::endl;
a->printPretty();
std::cout << (c->insert(500)) << std::endl;
std::cout << (c->insert(174)) << std::endl;
b->printPretty();
std::cout << (c->insert(24)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
std::cout << (d->remove(108)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (c->insert(96)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
b->printPretty();
*c=*b;
*e=*d;
std::cout << (e->insert(24)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
*e=*b;
std::cout << (b->insert(455)) << std::endl;
c->printPretty();
std::cout << (d->remove(224)) << std::endl;
std::cout << (a->insert(225)) << std::endl;
*b=*a;
std::cout << (b->remove(442)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
*c=*c;
std::cout << (b->insert(24)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
*a=*e;
std::cout << (d->insert(326)) << std::endl;
c->printPretty();
std::cout << (d->remove(467)) << std::endl;
std::cout << (a->insert(46)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (c->insert(61)) << std::endl;
*b=*e;
std::cout << (b->remove(357)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (d->remove(74)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (e->remove(101)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
*c=*a;
*e=*d;
std::cout << (a->insert(67)) << std::endl;
return 0;
}
