#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->remove(480)) << std::endl;
*e=*b;
std::cout << (d->remove(276)) << std::endl;
d->printPretty();
std::cout << (d->insert(415)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
*c=*b;
std::cout << (b->insert(101)) << std::endl;
std::cout << (b->remove(275)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
a->printPretty();
std::cout << (c->remove(101)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
a->printPretty();
std::cout << (d->remove(327)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
*c=*e;
std::cout << (b->insert(297)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (c->remove(9)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
b->printPretty();
std::cout << (a->insert(151)) << std::endl;
std::cout << (a->remove(296)) << std::endl;
std::cout << (a->remove(455)) << std::endl;
c->printPretty();
std::cout << (c->insert(271)) << std::endl;
*b=*a;
std::cout << (a->remove(414)) << std::endl;
c->printPretty();
d->printPretty();
d->printPretty();
std::cout << (d->insert(297)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
*b=*d;
std::cout << (e->insert(271)) << std::endl;
*d=*a;
std::cout << (d->insert(151)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (b->remove(297)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
std::cout << (b->remove(124)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
std::cout << (d->insert(337)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
*e=*e;
std::cout << (c->remove(259)) << std::endl;
std::cout << (e->remove(479)) << std::endl;
std::cout << (c->remove(271)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
e->printPretty();
std::cout << (d->remove(337)) << std::endl;
*d=*e;
std::cout << (e->remove(19)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (e->remove(445)) << std::endl;
b->printPretty();
std::cout << (a->remove(271)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
*b=*c;
std::cout << (e->insert(436)) << std::endl;
*c=*a;
*e=*a;
std::cout << (a->insert(150)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (e->insert(17)) << std::endl;
std::cout << (d->remove(150)) << std::endl;
*e=*e;
std::cout << (b->insert(466)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
*a=*d;
std::cout << (b->remove(320)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
e->printPretty();
std::cout << (e->remove(157)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
c->printPretty();
std::cout << (b->remove(282)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (e->insert(164)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (e->insert(320)) << std::endl;
*c=*b;
std::cout << (a->remove(271)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (e->insert(466)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
*a=*e;
*e=*e;
std::cout << (c->insert(372)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
*c=*a;
std::cout << (a->remove(163)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
d->printPretty();
std::cout << (e->remove(101)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (b->remove(67)) << std::endl;
a->printPretty();
std::cout << (b->remove(331)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
d->printPretty();
std::cout << (c->remove(445)) << std::endl;
c->printPretty();
std::cout << (c->remove(466)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->remove(150)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (c->insert(255)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
*a=*e;
std::cout << (a->insert(150)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
a->printPretty();
std::cout << (d->remove(165)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->remove(271)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (b->insert(498)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
*a=*b;
std::cout << (d->remove(346)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (e->remove(315)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (e->remove(429)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
std::cout << (a->insert(303)) << std::endl;
e->printPretty();
std::cout << (d->remove(181)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
*a=*b;
*b=*c;
std::cout << (b->insert(305)) << std::endl;
d->printPretty();
std::cout << (e->insert(150)) << std::endl;
b->printPretty();
std::cout << (b->remove(255)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
a->printPretty();
std::cout << (d->insert(17)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (a->insert(226)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (a->insert(402)) << std::endl;
c->printPretty();
std::cout << (a->insert(402)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (c->insert(477)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
b->printPretty();
std::cout << (c->remove(119)) << std::endl;
c->printPretty();
std::cout << (a->insert(47)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
*b=*d;
std::cout << (d->remove(407)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->remove(150)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
std::cout << (c->insert(255)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->remove(23)) << std::endl;
*d=*c;
std::cout << (b->remove(270)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
*e=*b;
std::cout << (a->remove(402)) << std::endl;
c->printPretty();
std::cout << (d->insert(477)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
*c=*a;
std::cout << (b->insert(180)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
*d=*a;
std::cout << (e->insert(28)) << std::endl;
e->printPretty();
std::cout << (e->insert(28)) << std::endl;
*b=*d;
*e=*c;
std::cout << (a->insert(116)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
c->printPretty();
std::cout << (c->remove(215)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (b->remove(180)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
std::cout << (d->insert(378)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
std::cout << (c->remove(86)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
a->printPretty();
std::cout << (c->insert(438)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
*a=*e;
std::cout << (d->insert(498)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
*b=*d;
std::cout << (e->insert(419)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (d->insert(116)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (d->remove(186)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (d->insert(498)) << std::endl;
std::cout << (b->remove(378)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
e->printPretty();
*b=*a;
*e=*d;
std::cout << (e->remove(494)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (a->remove(330)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
b->printPretty();
std::cout << (c->remove(226)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
e->printPretty();
std::cout << (b->insert(47)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (a->remove(312)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
*b=*e;
std::cout << (c->remove(243)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
*d=*b;
std::cout << (c->remove(368)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
*c=*e;
*d=*d;
std::cout << (b->remove(162)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
b->printPretty();
std::cout << (b->insert(445)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
*a=*c;
std::cout << (d->insert(243)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
b->printPretty();
std::cout << (c->remove(407)) << std::endl;
b->printPretty();
std::cout << (a->remove(381)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
c->printPretty();
std::cout << (d->remove(347)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
*b=*a;
std::cout << (e->insert(93)) << std::endl;
std::cout << (d->remove(32)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
*c=*b;
std::cout << (b->remove(461)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
b->printPretty();
std::cout << (c->insert(229)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (c->insert(208)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
e->printPretty();
std::cout << (c->insert(116)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (b->remove(116)) << std::endl;
a->printPretty();
*e=*a;
c->printPretty();
std::cout << (d->insert(7)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (a->remove(343)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
c->printPretty();
std::cout << (e->remove(243)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (c->insert(387)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
*a=*a;
std::cout << (b->remove(226)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (b->insert(469)) << std::endl;
std::cout << (b->insert(179)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
b->printPretty();
std::cout << (e->insert(73)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
*d=*c;
std::cout << (d->insert(73)) << std::endl;
*c=*a;
std::cout << (a->insert(491)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (c->remove(189)) << std::endl;
*c=*e;
*a=*d;
*d=*e;
*b=*d;
std::cout << (d->remove(226)) << std::endl;
*d=*b;
*a=*d;
*c=*a;
*c=*b;
std::cout << (b->insert(83)) << std::endl;
*a=*d;
*a=*c;
std::cout << (e->insert(229)) << std::endl;
*d=*b;
std::cout << (e->insert(220)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
*c=*d;
std::cout << (c->insert(413)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
std::cout << (c->remove(83)) << std::endl;
*c=*b;
*a=*b;
std::cout << (e->remove(327)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
*e=*e;
std::cout << (b->remove(304)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
b->printPretty();
*c=*b;
b->printPretty();
d->printPretty();
std::cout << (d->insert(11)) << std::endl;
a->printPretty();
std::cout << (a->remove(144)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (c->insert(231)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
*c=*b;
std::cout << (e->insert(316)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
e->printPretty();
std::cout << (a->insert(116)) << std::endl;
std::cout << (b->insert(323)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
*e=*d;
*e=*b;
*a=*a;
*e=*b;
*c=*d;
std::cout << (b->remove(231)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
d->printPretty();
std::cout << (c->remove(226)) << std::endl;
*d=*d;
std::cout << (d->insert(73)) << std::endl;
e->printPretty();
std::cout << (e->insert(323)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
*a=*b;
*b=*c;
std::cout << (e->remove(249)) << std::endl;
*a=*e;
*c=*c;
std::cout << (a->insert(458)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
*b=*c;
std::cout << (a->insert(78)) << std::endl;
b->printPretty();
std::cout << (a->remove(362)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
e->printPretty();
std::cout << (c->remove(189)) << std::endl;
std::cout << (c->insert(498)) << std::endl;
std::cout << (e->insert(73)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
*e=*a;
a->printPretty();
*c=*b;
a->printPretty();
d->printPretty();
std::cout << (e->remove(243)) << std::endl;
std::cout << (a->insert(321)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
*d=*d;
std::cout << (b->insert(116)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
*d=*d;
std::cout << (a->insert(446)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
*d=*c;
std::cout << (c->remove(11)) << std::endl;
*e=*a;
std::cout << (d->insert(11)) << std::endl;
*d=*c;
std::cout << (d->remove(107)) << std::endl;
d->printPretty();
std::cout << (a->insert(243)) << std::endl;
b->printPretty();
std::cout << (e->remove(446)) << std::endl;
*b=*a;
*e=*d;
std::cout << (d->insert(73)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (e->remove(12)) << std::endl;
std::cout << (e->insert(229)) << std::endl;
b->printPretty();
std::cout << (d->insert(320)) << std::endl;
b->printPretty();
std::cout << (e->insert(429)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
*d=*a;
std::cout << (a->remove(444)) << std::endl;
*d=*a;
std::cout << (b->remove(344)) << std::endl;
std::cout << (d->insert(467)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (d->remove(375)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (e->insert(229)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
*a=*e;
std::cout << (c->insert(277)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
*a=*e;
*b=*b;
std::cout << (e->remove(147)) << std::endl;
a->printPretty();
std::cout << (b->remove(103)) << std::endl;
std::cout << (c->insert(2)) << std::endl;
e->printPretty();
std::cout << (b->remove(68)) << std::endl;
*d=*a;
a->printPretty();
d->printPretty();
a->printPretty();
std::cout << (d->remove(265)) << std::endl;
*d=*d;
std::cout << (e->remove(489)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (d->insert(488)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
e->printPretty();
std::cout << (e->remove(5)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (b->remove(243)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(83)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
b->printPretty();
std::cout << (e->insert(73)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
d->printPretty();
std::cout << (d->remove(34)) << std::endl;
*b=*d;
std::cout << (e->insert(369)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
e->printPretty();
std::cout << (b->remove(320)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (d->insert(83)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
b->printPretty();
std::cout << (c->insert(248)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
*b=*a;
std::cout << (d->remove(62)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
b->printPretty();
*d=*d;
*a=*e;
std::cout << (d->insert(73)) << std::endl;
std::cout << (e->insert(32)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (e->insert(32)) << std::endl;
*b=*a;
std::cout << (d->remove(320)) << std::endl;
d->printPretty();
std::cout << (c->insert(73)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
d->printPretty();
std::cout << (a->insert(369)) << std::endl;
*c=*d;
*b=*c;
std::cout << (b->insert(328)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (b->remove(208)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (d->remove(488)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
*d=*d;
std::cout << (b->insert(491)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
a->printPretty();
std::cout << (c->remove(306)) << std::endl;
c->printPretty();
std::cout << (c->remove(83)) << std::endl;
std::cout << (c->remove(429)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (e->remove(83)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
c->printPretty();
std::cout << (e->insert(419)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
std::cout << (d->remove(363)) << std::endl;
b->printPretty();
*a=*b;
*c=*b;
std::cout << (c->insert(73)) << std::endl;
a->printPretty();
std::cout << (e->remove(354)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
*a=*a;
std::cout << (a->insert(207)) << std::endl;
*c=*e;
std::cout << (d->remove(354)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (a->remove(430)) << std::endl;
*e=*c;
std::cout << (d->insert(229)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (a->insert(46)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
a->printPretty();
std::cout << (d->remove(328)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
e->printPretty();
std::cout << (d->insert(83)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
a->printPretty();
std::cout << (e->remove(135)) << std::endl;
*e=*a;
std::cout << (c->remove(208)) << std::endl;
*d=*d;
std::cout << (b->insert(317)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
a->printPretty();
std::cout << (d->remove(83)) << std::endl;
*e=*a;
*c=*e;
std::cout << (d->remove(488)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (d->remove(230)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
b->printPretty();
*d=*b;
*b=*d;
std::cout << (a->remove(73)) << std::endl;
return 0;
}
