#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(487)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->insert(227)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->insert(252)) << std::endl;
*b=*c;
std::cout << (b->remove(148)) << std::endl;
*a=*d;
*c=*a;
std::cout << (a->remove(444)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (c->remove(261)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
a->printPretty();
std::cout << (b->remove(252)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (a->remove(329)) << std::endl;
a->printPretty();
*b=*d;
a->printPretty();
std::cout << (b->insert(370)) << std::endl;
*c=*e;
std::cout << (c->remove(24)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (c->insert(204)) << std::endl;
std::cout << (b->insert(370)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (c->insert(59)) << std::endl;
d->printPretty();
std::cout << (c->remove(5)) << std::endl;
*b=*d;
std::cout << (c->remove(204)) << std::endl;
std::cout << (d->remove(493)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
e->printPretty();
std::cout << (c->insert(59)) << std::endl;
a->printPretty();
*a=*d;
b->printPretty();
std::cout << (b->insert(366)) << std::endl;
c->printPretty();
*e=*e;
*a=*d;
d->printPretty();
std::cout << (d->insert(334)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
*b=*c;
*c=*d;
*e=*a;
std::cout << (d->insert(289)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
*b=*d;
std::cout << (d->remove(134)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
*d=*a;
std::cout << (e->remove(275)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (e->remove(158)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
d->printPretty();
*a=*b;
b->printPretty();
*d=*b;
std::cout << (b->insert(378)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (c->insert(334)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (b->remove(378)) << std::endl;
*d=*a;
std::cout << (c->insert(334)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (a->remove(334)) << std::endl;
*d=*c;
std::cout << (a->remove(401)) << std::endl;
*a=*d;
a->printPretty();
a->printPretty();
b->printPretty();
std::cout << (a->remove(484)) << std::endl;
std::cout << (d->remove(334)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
*d=*a;
a->printPretty();
*c=*e;
*a=*c;
b->printPretty();
*d=*e;
std::cout << (a->remove(398)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->remove(356)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
*b=*d;
*b=*e;
std::cout << (d->insert(38)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
c->printPretty();
std::cout << (d->remove(38)) << std::endl;
*a=*a;
std::cout << (c->insert(419)) << std::endl;
*c=*a;
*b=*e;
std::cout << (d->remove(220)) << std::endl;
*d=*c;
*e=*c;
*a=*b;
std::cout << (d->insert(232)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (c->insert(307)) << std::endl;
*b=*d;
std::cout << (c->insert(307)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
*a=*e;
std::cout << (b->insert(232)) << std::endl;
std::cout << (e->remove(465)) << std::endl;
*d=*c;
*a=*d;
std::cout << (d->insert(229)) << std::endl;
*c=*c;
std::cout << (c->insert(485)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (a->remove(252)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (a->insert(338)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->insert(338)) << std::endl;
std::cout << (a->remove(495)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
std::cout << (c->remove(436)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
b->printPretty();
std::cout << (d->insert(179)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(436)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
*b=*e;
std::cout << (e->insert(101)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
*e=*a;
std::cout << (c->remove(49)) << std::endl;
*c=*a;
std::cout << (d->insert(338)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
e->printPretty();
std::cout << (d->remove(229)) << std::endl;
std::cout << (d->insert(416)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (b->insert(101)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (b->remove(101)) << std::endl;
std::cout << (a->remove(61)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
std::cout << (d->insert(185)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(229)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
*c=*c;
*a=*e;
std::cout << (d->remove(317)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (d->insert(185)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
*a=*c;
*b=*b;
*e=*d;
std::cout << (b->remove(453)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
std::cout << (e->insert(132)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (e->remove(150)) << std::endl;
*e=*e;
std::cout << (a->remove(101)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (d->insert(185)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (d->insert(135)) << std::endl;
c->printPretty();
std::cout << (d->remove(486)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (d->insert(179)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
*c=*b;
*d=*d;
std::cout << (b->insert(6)) << std::endl;
std::cout << (c->insert(427)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
c->printPretty();
std::cout << (b->remove(6)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
*c=*a;
std::cout << (d->insert(246)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
*d=*a;
*a=*c;
std::cout << (e->remove(476)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
*e=*d;
std::cout << (e->remove(13)) << std::endl;
b->printPretty();
a->printPretty();
c->printPretty();
*b=*e;
std::cout << (a->remove(365)) << std::endl;
*d=*b;
std::cout << (b->insert(289)) << std::endl;
*c=*a;
*b=*c;
std::cout << (b->remove(295)) << std::endl;
std::cout << (d->insert(270)) << std::endl;
b->printPretty();
std::cout << (a->insert(31)) << std::endl;
*a=*b;
*e=*d;
*a=*a;
d->printPretty();
std::cout << (c->remove(97)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
b->printPretty();
*c=*b;
d->printPretty();
std::cout << (a->insert(304)) << std::endl;
e->printPretty();
std::cout << (c->insert(381)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (b->remove(224)) << std::endl;
*d=*c;
std::cout << (c->remove(330)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (c->remove(381)) << std::endl;
std::cout << (a->remove(80)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (e->remove(370)) << std::endl;
*a=*d;
std::cout << (a->insert(187)) << std::endl;
*d=*e;
std::cout << (a->remove(55)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (d->insert(171)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->remove(304)) << std::endl;
d->printPretty();
std::cout << (a->insert(187)) << std::endl;
*a=*c;
std::cout << (e->insert(269)) << std::endl;
a->printPretty();
std::cout << (d->insert(304)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
d->printPretty();
std::cout << (c->insert(58)) << std::endl;
std::cout << (e->remove(427)) << std::endl;
*b=*b;
std::cout << (a->insert(84)) << std::endl;
*e=*d;
c->printPretty();
*c=*b;
std::cout << (a->remove(84)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
*e=*a;
std::cout << (c->insert(159)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
*b=*a;
std::cout << (d->insert(426)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
std::cout << (b->insert(252)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
std::cout << (e->insert(66)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (b->insert(252)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
*c=*a;
std::cout << (e->remove(159)) << std::endl;
*a=*c;
std::cout << (e->insert(448)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
a->printPretty();
*e=*d;
e->printPretty();
d->printPretty();
std::cout << (e->insert(304)) << std::endl;
*a=*c;
std::cout << (d->insert(426)) << std::endl;
c->printPretty();
std::cout << (d->insert(119)) << std::endl;
b->printPretty();
std::cout << (e->remove(426)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
std::cout << (e->insert(304)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
*d=*d;
std::cout << (e->remove(304)) << std::endl;
a->printPretty();
*b=*d;
e->printPretty();
b->printPretty();
*e=*e;
std::cout << (c->insert(228)) << std::endl;
std::cout << (c->insert(267)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
e->printPretty();
std::cout << (e->insert(122)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
*d=*e;
std::cout << (e->insert(283)) << std::endl;
b->printPretty();
std::cout << (d->remove(122)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
std::cout << (d->insert(299)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
*e=*e;
std::cout << (c->insert(228)) << std::endl;
d->printPretty();
std::cout << (b->remove(21)) << std::endl;
std::cout << (d->insert(314)) << std::endl;
std::cout << (d->remove(314)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
c->printPretty();
a->printPretty();
c->printPretty();
std::cout << (d->insert(182)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
b->printPretty();
std::cout << (e->remove(283)) << std::endl;
e->printPretty();
std::cout << (d->remove(299)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
*e=*b;
std::cout << (e->remove(426)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
c->printPretty();
std::cout << (b->remove(159)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (a->insert(318)) << std::endl;
*e=*c;
std::cout << (b->insert(480)) << std::endl;
*b=*d;
std::cout << (a->remove(379)) << std::endl;
e->printPretty();
std::cout << (e->remove(228)) << std::endl;
std::cout << (a->remove(318)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
c->printPretty();
std::cout << (a->insert(27)) << std::endl;
*d=*b;
std::cout << (c->insert(84)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
*c=*a;
*c=*b;
*b=*e;
*c=*b;
std::cout << (e->remove(372)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->remove(183)) << std::endl;
*d=*a;
std::cout << (a->insert(269)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (b->insert(476)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(295)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
b->printPretty();
std::cout << (c->insert(242)) << std::endl;
d->printPretty();
std::cout << (c->insert(242)) << std::endl;
e->printPretty();
std::cout << (e->remove(89)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
*c=*b;
*a=*e;
std::cout << (e->remove(84)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
std::cout << (e->insert(318)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (a->insert(7)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
a->printPretty();
std::cout << (c->remove(285)) << std::endl;
std::cout << (c->remove(267)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
*c=*d;
std::cout << (c->remove(25)) << std::endl;
std::cout << (c->insert(182)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
*b=*e;
std::cout << (c->insert(499)) << std::endl;
std::cout << (a->remove(61)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (a->insert(267)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
std::cout << (a->remove(267)) << std::endl;
*a=*b;
std::cout << (b->insert(318)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
d->printPretty();
std::cout << (b->insert(77)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (e->insert(292)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
*a=*d;
std::cout << (b->remove(139)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
*b=*c;
std::cout << (a->insert(188)) << std::endl;
c->printPretty();
c->printPretty();
a->printPretty();
a->printPretty();
std::cout << (c->insert(167)) << std::endl;
*d=*a;
std::cout << (a->insert(188)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->remove(318)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
b->printPretty();
std::cout << (a->insert(188)) << std::endl;
b->printPretty();
std::cout << (a->insert(475)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*a=*a;
b->printPretty();
*a=*e;
std::cout << (c->remove(467)) << std::endl;
*d=*c;
e->printPretty();
c->printPretty();
std::cout << (c->remove(119)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
*d=*b;
std::cout << (b->insert(247)) << std::endl;
*b=*b;
*a=*a;
*d=*e;
std::cout << (a->insert(80)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
d->printPretty();
std::cout << (a->insert(80)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (b->remove(346)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (e->insert(267)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
*c=*c;
e->printPretty();
b->printPretty();
std::cout << (a->insert(267)) << std::endl;
std::cout << (c->remove(267)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (b->remove(384)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
a->printPretty();
std::cout << (c->insert(242)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
e->printPretty();
std::cout << (d->insert(40)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (a->remove(240)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (c->remove(242)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
a->printPretty();
std::cout << (b->remove(294)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
*d=*a;
std::cout << (b->insert(460)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
e->printPretty();
d->printPretty();
c->printPretty();
*a=*d;
b->printPretty();
std::cout << (e->remove(7)) << std::endl;
std::cout << (d->remove(267)) << std::endl;
std::cout << (e->insert(267)) << std::endl;
*c=*b;
std::cout << (c->remove(460)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (c->insert(44)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
*d=*d;
std::cout << (d->remove(80)) << std::endl;
c->printPretty();
a->printPretty();
b->printPretty();
std::cout << (b->remove(460)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (e->insert(267)) << std::endl;
a->printPretty();
e->printPretty();
e->printPretty();
b->printPretty();
*b=*c;
std::cout << (b->remove(353)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
d->printPretty();
std::cout << (a->insert(103)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
d->printPretty();
std::cout << (d->remove(408)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
*d=*c;
c->printPretty();
*e=*e;
std::cout << (b->insert(53)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
*a=*d;
std::cout << (c->remove(326)) << std::endl;
std::cout << (b->remove(335)) << std::endl;
std::cout << (b->remove(210)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
*b=*d;
d->printPretty();
c->printPretty();
*a=*b;
*c=*e;
*e=*b;
std::cout << (d->remove(44)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
*c=*e;
a->printPretty();
*b=*a;
std::cout << (e->insert(44)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (b->insert(96)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->remove(289)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
return 0;
}
