#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
d->printPretty();
std::cout << (d->insert(326)) << std::endl;
a->printPretty();
std::cout << (b->remove(271)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(126)) << std::endl;
*d=*d;
*a=*e;
std::cout << (e->remove(28)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (c->insert(269)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
*a=*d;
*d=*a;
std::cout << (e->insert(344)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
*a=*c;
*d=*c;
d->printPretty();
*b=*a;
std::cout << (e->remove(223)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
d->printPretty();
std::cout << (e->remove(121)) << std::endl;
a->printPretty();
std::cout << (a->remove(398)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
std::cout << (b->insert(230)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
*b=*d;
std::cout << (d->remove(483)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (a->insert(434)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
*b=*d;
*a=*c;
std::cout << (c->remove(56)) << std::endl;
std::cout << (a->remove(210)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (b->remove(465)) << std::endl;
*b=*b;
std::cout << (a->remove(170)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
*c=*d;
std::cout << (b->insert(197)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
*a=*a;
std::cout << (a->insert(180)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
c->printPretty();
std::cout << (b->remove(491)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
*d=*b;
std::cout << (c->insert(23)) << std::endl;
*c=*a;
std::cout << (d->insert(197)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (d->insert(196)) << std::endl;
*e=*a;
std::cout << (d->insert(397)) << std::endl;
*e=*e;
std::cout << (c->remove(180)) << std::endl;
std::cout << (c->remove(446)) << std::endl;
e->printPretty();
std::cout << (d->insert(197)) << std::endl;
*d=*c;
std::cout << (a->remove(102)) << std::endl;
*a=*c;
*d=*e;
*c=*b;
d->printPretty();
std::cout << (a->insert(408)) << std::endl;
*c=*d;
std::cout << (c->insert(180)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (b->remove(197)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
*b=*a;
std::cout << (c->insert(322)) << std::endl;
std::cout << (d->insert(343)) << std::endl;
a->printPretty();
*e=*d;
*b=*c;
std::cout << (b->remove(180)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
a->printPretty();
std::cout << (a->insert(180)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
*e=*b;
std::cout << (d->remove(343)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
c->printPretty();
std::cout << (d->remove(488)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (a->insert(347)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
*a=*b;
std::cout << (b->remove(64)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
*c=*d;
std::cout << (d->insert(234)) << std::endl;
std::cout << (c->remove(349)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(326)) << std::endl;
e->printPretty();
std::cout << (d->insert(398)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
a->printPretty();
std::cout << (a->insert(6)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
*b=*e;
std::cout << (c->remove(145)) << std::endl;
std::cout << (b->insert(442)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (a->insert(218)) << std::endl;
d->printPretty();
std::cout << (a->remove(73)) << std::endl;
std::cout << (a->insert(363)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
*c=*b;
std::cout << (c->insert(45)) << std::endl;
std::cout << (c->remove(447)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
*c=*c;
*d=*b;
std::cout << (d->insert(442)) << std::endl;
std::cout << (d->insert(442)) << std::endl;
std::cout << (d->insert(442)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (a->insert(363)) << std::endl;
*d=*b;
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
e->printPretty();
std::cout << (b->remove(210)) << std::endl;
c->printPretty();
std::cout << (c->remove(474)) << std::endl;
d->printPretty();
std::cout << (a->insert(194)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
d->printPretty();
std::cout << (e->remove(291)) << std::endl;
e->printPretty();
std::cout << (c->remove(442)) << std::endl;
std::cout << (d->remove(385)) << std::endl;
a->printPretty();
std::cout << (c->remove(224)) << std::endl;
std::cout << (d->insert(464)) << std::endl;
*b=*e;
std::cout << (e->remove(480)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
a->printPretty();
std::cout << (e->insert(307)) << std::endl;
std::cout << (b->remove(401)) << std::endl;
*b=*c;
d->printPretty();
*d=*c;
std::cout << (a->remove(194)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
*b=*b;
std::cout << (e->insert(331)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
*d=*b;
*b=*e;
std::cout << (d->remove(329)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
e->printPretty();
std::cout << (d->remove(45)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (a->insert(317)) << std::endl;
*b=*e;
*e=*e;
e->printPretty();
std::cout << (c->remove(45)) << std::endl;
c->printPretty();
*d=*a;
e->printPretty();
d->printPretty();
*c=*c;
std::cout << (a->remove(335)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (b->insert(59)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(275)) << std::endl;
e->printPretty();
std::cout << (b->insert(439)) << std::endl;
a->printPretty();
std::cout << (c->insert(482)) << std::endl;
e->printPretty();
std::cout << (b->remove(118)) << std::endl;
*e=*c;
b->printPretty();
e->printPretty();
std::cout << (b->insert(59)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
b->printPretty();
c->printPretty();
c->printPretty();
std::cout << (b->remove(327)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
*e=*c;
*c=*c;
std::cout << (e->remove(482)) << std::endl;
*d=*d;
std::cout << (b->remove(439)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
*d=*e;
*b=*a;
d->printPretty();
d->printPretty();
std::cout << (a->insert(130)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(442)) << std::endl;
std::cout << (b->insert(317)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
a->printPretty();
c->printPretty();
*d=*a;
std::cout << (a->insert(317)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(130)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
*e=*b;
std::cout << (e->insert(231)) << std::endl;
b->printPretty();
std::cout << (e->remove(304)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
*c=*c;
std::cout << (c->insert(56)) << std::endl;
a->printPretty();
std::cout << (a->insert(22)) << std::endl;
c->printPretty();
std::cout << (c->remove(425)) << std::endl;
*b=*d;
std::cout << (d->remove(41)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (d->insert(442)) << std::endl;
std::cout << (e->insert(317)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
std::cout << (e->insert(388)) << std::endl;
std::cout << (e->insert(317)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (a->insert(423)) << std::endl;
*c=*e;
std::cout << (e->insert(474)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
a->printPretty();
std::cout << (e->insert(388)) << std::endl;
c->printPretty();
std::cout << (b->insert(292)) << std::endl;
*b=*d;
std::cout << (d->remove(499)) << std::endl;
std::cout << (d->insert(442)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (a->insert(423)) << std::endl;
std::cout << (e->insert(474)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
std::cout << (e->insert(355)) << std::endl;
std::cout << (e->insert(30)) << std::endl;
std::cout << (e->remove(30)) << std::endl;
*d=*e;
std::cout << (e->remove(388)) << std::endl;
d->printPretty();
std::cout << (a->insert(423)) << std::endl;
*e=*b;
std::cout << (c->remove(317)) << std::endl;
a->printPretty();
std::cout << (c->remove(464)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
e->printPretty();
std::cout << (e->remove(87)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (d->insert(447)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (e->insert(126)) << std::endl;
b->printPretty();
std::cout << (a->remove(211)) << std::endl;
*d=*a;
*c=*d;
std::cout << (b->remove(362)) << std::endl;
e->printPretty();
std::cout << (a->insert(130)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
*e=*e;
std::cout << (e->insert(64)) << std::endl;
c->printPretty();
std::cout << (c->remove(130)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
*d=*c;
std::cout << (d->remove(9)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
std::cout << (c->remove(9)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
*c=*d;
d->printPretty();
b->printPretty();
std::cout << (c->remove(423)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (e->remove(167)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (e->insert(358)) << std::endl;
*b=*e;
std::cout << (a->remove(249)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
std::cout << (d->remove(423)) << std::endl;
c->printPretty();
std::cout << (a->remove(304)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
*c=*a;
*c=*b;
std::cout << (d->insert(166)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (d->remove(292)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
*d=*a;
*c=*d;
std::cout << (a->remove(223)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (e->insert(456)) << std::endl;
std::cout << (a->insert(320)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
*b=*b;
std::cout << (e->insert(232)) << std::endl;
*c=*b;
std::cout << (c->insert(317)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
*d=*b;
std::cout << (d->insert(442)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
*b=*b;
std::cout << (e->remove(119)) << std::endl;
e->printPretty();
std::cout << (b->remove(214)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (e->remove(456)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
c->printPretty();
c->printPretty();
*d=*e;
std::cout << (a->remove(499)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
d->printPretty();
std::cout << (d->insert(138)) << std::endl;
std::cout << (c->insert(34)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
*e=*b;
std::cout << (d->insert(325)) << std::endl;
c->printPretty();
std::cout << (c->remove(230)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
c->printPretty();
std::cout << (e->remove(104)) << std::endl;
std::cout << (c->insert(47)) << std::endl;
*e=*d;
std::cout << (e->remove(183)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (a->remove(180)) << std::endl;
*c=*d;
e->printPretty();
*c=*c;
e->printPretty();
std::cout << (e->insert(138)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
e->printPretty();
std::cout << (c->remove(325)) << std::endl;
a->printPretty();
std::cout << (e->insert(138)) << std::endl;
a->printPretty();
std::cout << (c->insert(320)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
*d=*e;
std::cout << (e->remove(34)) << std::endl;
std::cout << (a->remove(320)) << std::endl;
d->printPretty();
std::cout << (c->remove(320)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (a->insert(427)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
a->printPretty();
std::cout << (b->insert(386)) << std::endl;
*d=*b;
b->printPretty();
std::cout << (a->remove(255)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
*b=*e;
std::cout << (c->insert(138)) << std::endl;
c->printPretty();
std::cout << (e->remove(23)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
*a=*d;
*b=*d;
std::cout << (d->remove(286)) << std::endl;
*c=*e;
std::cout << (d->insert(415)) << std::endl;
*c=*e;
std::cout << (e->insert(471)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
d->printPretty();
std::cout << (a->insert(429)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
*b=*d;
b->printPretty();
*c=*c;
std::cout << (e->remove(352)) << std::endl;
*a=*e;
*c=*a;
std::cout << (e->insert(394)) << std::endl;
e->printPretty();
std::cout << (a->insert(471)) << std::endl;
std::cout << (c->remove(120)) << std::endl;
e->printPretty();
std::cout << (e->insert(394)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
std::cout << (b->insert(442)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
std::cout << (e->remove(222)) << std::endl;
d->printPretty();
std::cout << (b->remove(202)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (b->insert(395)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (a->insert(482)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (d->remove(246)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
a->printPretty();
std::cout << (d->remove(442)) << std::endl;
*b=*a;
*a=*e;
std::cout << (d->remove(140)) << std::endl;
d->printPretty();
std::cout << (d->remove(492)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
b->printPretty();
std::cout << (c->insert(471)) << std::endl;
*c=*d;
std::cout << (b->insert(482)) << std::endl;
*d=*e;
std::cout << (a->remove(394)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
b->printPretty();
std::cout << (c->insert(416)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (b->insert(482)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
*d=*b;
*a=*c;
std::cout << (c->insert(87)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
*e=*e;
std::cout << (b->insert(456)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(218)) << std::endl;
*c=*c;
std::cout << (d->insert(482)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
std::cout << (b->insert(482)) << std::endl;
b->printPretty();
std::cout << (c->remove(458)) << std::endl;
*a=*d;
a->printPretty();
*c=*b;
b->printPretty();
std::cout << (c->remove(176)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
*c=*d;
std::cout << (a->insert(482)) << std::endl;
b->printPretty();
std::cout << (c->remove(203)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
a->printPretty();
*d=*c;
*c=*e;
std::cout << (e->remove(471)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
d->printPretty();
std::cout << (d->remove(151)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (a->remove(173)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
a->printPretty();
std::cout << (a->remove(471)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (a->remove(98)) << std::endl;
*b=*a;
std::cout << (d->remove(482)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (d->remove(422)) << std::endl;
b->printPretty();
std::cout << (c->insert(489)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
*e=*a;
std::cout << (c->insert(451)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (c->insert(405)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (a->insert(280)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(86)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (c->remove(405)) << std::endl;
*e=*d;
std::cout << (a->insert(284)) << std::endl;
std::cout << (e->remove(120)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
b->printPretty();
std::cout << (e->remove(411)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
c->printPretty();
std::cout << (a->insert(284)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
c->printPretty();
std::cout << (b->remove(205)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
std::cout << (c->insert(18)) << std::endl;
c->printPretty();
std::cout << (c->insert(126)) << std::endl;
*c=*e;
std::cout << (e->remove(77)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (e->remove(471)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
d->printPretty();
e->printPretty();
*e=*c;
std::cout << (e->insert(404)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
*e=*b;
std::cout << (d->insert(302)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
std::cout << (e->insert(490)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (a->insert(159)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
b->printPretty();
d->printPretty();
*e=*c;
std::cout << (c->insert(404)) << std::endl;
d->printPretty();
std::cout << (e->remove(77)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (b->insert(139)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
e->printPretty();
std::cout << (c->remove(13)) << std::endl;
*a=*c;
std::cout << (b->insert(139)) << std::endl;
std::cout << (e->remove(177)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (a->insert(77)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
a->printPretty();
*b=*b;
e->printPretty();
std::cout << (a->remove(345)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->insert(384)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
*a=*e;
return 0;
}
