#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
a->printPretty();
std::cout << (b->insert(497)) << std::endl;
*a=*b;
std::cout << (a->remove(217)) << std::endl;
*a=*a;
*a=*a;
a->printPretty();
std::cout << (b->insert(85)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->remove(85)) << std::endl;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->insert(79)) << std::endl;
d->printPretty();
std::cout << (c->remove(433)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
*b=*b;
c->printPretty();
*b=*c;
std::cout << (a->remove(497)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
b->printPretty();
std::cout << (c->insert(79)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
e->printPretty();
std::cout << (a->insert(408)) << std::endl;
*e=*e;
*e=*d;
std::cout << (c->remove(145)) << std::endl;
*e=*b;
*a=*e;
std::cout << (e->insert(79)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (e->remove(79)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*a=*e;
std::cout << (a->insert(391)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (a->remove(391)) << std::endl;
std::cout << (c->remove(458)) << std::endl;
a->printPretty();
std::cout << (d->remove(349)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
c->printPretty();
*e=*e;
d->printPretty();
*b=*e;
std::cout << (a->remove(326)) << std::endl;
d->printPretty();
*a=*e;
*e=*d;
std::cout << (c->remove(368)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(382)) << std::endl;
std::cout << (c->remove(79)) << std::endl;
std::cout << (c->remove(327)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (d->insert(264)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(146)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
*b=*d;
*b=*d;
a->printPretty();
d->printPretty();
c->printPretty();
std::cout << (a->insert(168)) << std::endl;
std::cout << (c->insert(267)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
*a=*b;
std::cout << (a->insert(264)) << std::endl;
d->printPretty();
std::cout << (c->remove(146)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
*e=*c;
*e=*a;
std::cout << (b->insert(264)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
a->printPretty();
*a=*a;
b->printPretty();
std::cout << (e->remove(264)) << std::endl;
*c=*b;
std::cout << (a->remove(264)) << std::endl;
*c=*c;
*d=*c;
d->printPretty();
*e=*d;
std::cout << (c->remove(336)) << std::endl;
std::cout << (d->insert(264)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
e->printPretty();
*b=*b;
b->printPretty();
std::cout << (c->remove(436)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
e->printPretty();
*e=*c;
std::cout << (e->insert(100)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
c->printPretty();
std::cout << (d->insert(337)) << std::endl;
*d=*e;
std::cout << (b->remove(355)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
b->printPretty();
std::cout << (e->remove(85)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
*c=*b;
std::cout << (b->remove(62)) << std::endl;
*c=*c;
std::cout << (b->insert(325)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
e->printPretty();
std::cout << (c->remove(337)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
*b=*a;
d->printPretty();
*a=*d;
std::cout << (c->insert(264)) << std::endl;
d->printPretty();
std::cout << (e->insert(98)) << std::endl;
b->printPretty();
std::cout << (c->remove(486)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (d->insert(376)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->remove(264)) << std::endl;
e->printPretty();
std::cout << (e->remove(219)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
a->printPretty();
std::cout << (a->remove(387)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (c->remove(62)) << std::endl;
*e=*d;
std::cout << (e->remove(350)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(36)) << std::endl;
std::cout << (b->remove(113)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
b->printPretty();
std::cout << (d->insert(219)) << std::endl;
*b=*b;
std::cout << (e->insert(174)) << std::endl;
std::cout << (d->remove(376)) << std::endl;
a->printPretty();
std::cout << (a->insert(39)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
a->printPretty();
std::cout << (e->remove(429)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
*b=*d;
std::cout << (d->insert(337)) << std::endl;
a->printPretty();
std::cout << (c->insert(315)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(337)) << std::endl;
*c=*a;
b->printPretty();
b->printPretty();
std::cout << (d->insert(237)) << std::endl;
*b=*c;
e->printPretty();
std::cout << (a->insert(155)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
*d=*b;
e->printPretty();
*c=*a;
std::cout << (c->insert(62)) << std::endl;
std::cout << (a->remove(288)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
*a=*e;
std::cout << (e->insert(393)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
b->printPretty();
a->printPretty();
*b=*b;
*d=*d;
*d=*c;
std::cout << (c->insert(484)) << std::endl;
c->printPretty();
*c=*e;
*c=*c;
std::cout << (c->insert(100)) << std::endl;
e->printPretty();
b->printPretty();
e->printPretty();
e->printPretty();
std::cout << (b->insert(84)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
*c=*a;
std::cout << (c->insert(337)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(192)) << std::endl;
*e=*e;
std::cout << (b->remove(84)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->insert(95)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
*d=*b;
std::cout << (a->insert(119)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
b->printPretty();
std::cout << (a->insert(95)) << std::endl;
std::cout << (e->insert(177)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
*a=*e;
std::cout << (c->remove(360)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (b->remove(75)) << std::endl;
*e=*a;
*a=*d;
std::cout << (a->remove(332)) << std::endl;
a->printPretty();
std::cout << (c->insert(62)) << std::endl;
*a=*b;
std::cout << (c->insert(95)) << std::endl;
std::cout << (e->remove(430)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (c->remove(10)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (d->insert(312)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (c->remove(84)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
b->printPretty();
std::cout << (b->remove(387)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
*c=*b;
*c=*b;
*a=*e;
std::cout << (d->insert(420)) << std::endl;
d->printPretty();
std::cout << (c->remove(489)) << std::endl;
*c=*b;
std::cout << (b->remove(100)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
*c=*d;
std::cout << (b->remove(219)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
*a=*d;
std::cout << (a->insert(332)) << std::endl;
*c=*c;
a->printPretty();
b->printPretty();
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
*a=*d;
std::cout << (c->remove(460)) << std::endl;
c->printPretty();
std::cout << (d->insert(17)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (e->insert(318)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
c->printPretty();
std::cout << (c->insert(420)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (e->remove(489)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
d->printPretty();
c->printPretty();
*e=*d;
b->printPretty();
*a=*a;
c->printPretty();
*b=*d;
std::cout << (e->remove(420)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
std::cout << (c->remove(117)) << std::endl;
e->printPretty();
std::cout << (d->insert(172)) << std::endl;
*a=*c;
std::cout << (b->remove(170)) << std::endl;
d->printPretty();
*d=*d;
d->printPretty();
*e=*a;
std::cout << (b->remove(355)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
d->printPretty();
std::cout << (c->remove(332)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(86)) << std::endl;
*c=*a;
std::cout << (c->remove(420)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
*d=*a;
std::cout << (a->remove(420)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
*a=*d;
b->printPretty();
*b=*b;
std::cout << (c->insert(57)) << std::endl;
std::cout << (e->remove(431)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
*b=*d;
d->printPretty();
e->printPretty();
std::cout << (d->insert(336)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
d->printPretty();
std::cout << (c->remove(484)) << std::endl;
b->printPretty();
std::cout << (a->insert(159)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
std::cout << (b->remove(408)) << std::endl;
*c=*a;
std::cout << (a->remove(34)) << std::endl;
std::cout << (c->remove(420)) << std::endl;
b->printPretty();
*d=*b;
e->printPretty();
std::cout << (b->insert(332)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
e->printPretty();
std::cout << (a->remove(316)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
*e=*a;
std::cout << (c->remove(402)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (c->insert(400)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
*d=*a;
std::cout << (e->remove(180)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
std::cout << (c->insert(400)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
d->printPretty();
*a=*b;
*c=*e;
std::cout << (c->remove(289)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
c->printPretty();
std::cout << (d->insert(159)) << std::endl;
*e=*d;
std::cout << (e->insert(418)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
std::cout << (b->remove(247)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
*d=*a;
std::cout << (b->remove(385)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
std::cout << (d->insert(89)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
std::cout << (e->remove(266)) << std::endl;
*d=*e;
std::cout << (b->remove(332)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (a->remove(332)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (c->insert(6)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
*a=*a;
std::cout << (a->remove(159)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
*d=*a;
std::cout << (b->insert(159)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
*d=*b;
*d=*e;
*c=*e;
*b=*e;
std::cout << (c->insert(40)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
c->printPretty();
std::cout << (d->remove(239)) << std::endl;
std::cout << (c->remove(447)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
a->printPretty();
*c=*c;
c->printPretty();
std::cout << (a->insert(472)) << std::endl;
e->printPretty();
std::cout << (a->remove(66)) << std::endl;
e->printPretty();
std::cout << (e->insert(159)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
std::cout << (d->insert(105)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
c->printPretty();
std::cout << (c->insert(105)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
c->printPretty();
*b=*a;
e->printPretty();
std::cout << (d->insert(178)) << std::endl;
*d=*c;
std::cout << (c->remove(105)) << std::endl;
b->printPretty();
std::cout << (c->remove(159)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (c->insert(103)) << std::endl;
std::cout << (d->remove(418)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
d->printPretty();
std::cout << (d->insert(283)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
b->printPretty();
std::cout << (d->insert(103)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
*b=*e;
std::cout << (b->insert(304)) << std::endl;
*c=*a;
std::cout << (d->remove(388)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
*b=*c;
*e=*b;
std::cout << (c->remove(225)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
*b=*a;
std::cout << (b->insert(24)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
d->printPretty();
std::cout << (e->insert(159)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
*c=*e;
std::cout << (d->insert(304)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (d->remove(304)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
d->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->insert(400)) << std::endl;
*a=*c;
*c=*d;
c->printPretty();
std::cout << (d->insert(40)) << std::endl;
*c=*e;
*e=*b;
std::cout << (c->remove(442)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (c->remove(222)) << std::endl;
b->printPretty();
*c=*e;
*a=*c;
std::cout << (c->insert(66)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
*a=*c;
std::cout << (d->remove(124)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
d->printPretty();
std::cout << (d->remove(70)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (e->remove(66)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
d->printPretty();
std::cout << (d->insert(443)) << std::endl;
*a=*e;
*d=*c;
std::cout << (b->remove(108)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
*c=*a;
std::cout << (c->remove(407)) << std::endl;
c->printPretty();
std::cout << (d->insert(76)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
e->printPretty();
std::cout << (e->remove(407)) << std::endl;
std::cout << (b->remove(349)) << std::endl;
std::cout << (b->insert(319)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
a->printPretty();
std::cout << (c->insert(4)) << std::endl;
*e=*e;
std::cout << (b->insert(319)) << std::endl;
*b=*b;
std::cout << (a->insert(155)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
std::cout << (b->insert(319)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
d->printPretty();
*b=*a;
b->printPretty();
std::cout << (a->insert(155)) << std::endl;
*a=*e;
std::cout << (a->insert(222)) << std::endl;
c->printPretty();
*a=*d;
*d=*b;
std::cout << (e->insert(222)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (a->remove(143)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(155)) << std::endl;
a->printPretty();
std::cout << (e->insert(285)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (e->insert(285)) << std::endl;
b->printPretty();
std::cout << (b->insert(315)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
*d=*b;
*c=*c;
std::cout << (a->remove(55)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
*c=*a;
std::cout << (d->insert(228)) << std::endl;
*b=*c;
std::cout << (c->remove(272)) << std::endl;
d->printPretty();
std::cout << (a->insert(97)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
b->printPretty();
std::cout << (d->remove(6)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->remove(113)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
std::cout << (b->remove(452)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (c->remove(66)) << std::endl;
*e=*c;
std::cout << (c->remove(324)) << std::endl;
std::cout << (e->remove(66)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (a->remove(135)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (e->insert(76)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
*e=*a;
std::cout << (d->insert(481)) << std::endl;
b->printPretty();
std::cout << (d->remove(313)) << std::endl;
*a=*c;
std::cout << (b->remove(239)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (c->remove(66)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
*b=*a;
std::cout << (e->insert(399)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
*a=*d;
std::cout << (e->remove(97)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
*a=*e;
std::cout << (a->remove(396)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
*e=*a;
std::cout << (d->insert(481)) << std::endl;
std::cout << (c->remove(97)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
*b=*c;
std::cout << (d->remove(66)) << std::endl;
*b=*a;
std::cout << (e->insert(399)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
a->printPretty();
std::cout << (a->insert(66)) << std::endl;
*d=*e;
std::cout << (d->remove(66)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
c->printPretty();
std::cout << (c->remove(212)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
*b=*e;
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(269)) << std::endl;
*d=*a;
std::cout << (c->remove(104)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
*a=*e;
*c=*e;
c->printPretty();
d->printPretty();
std::cout << (e->remove(190)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (c->insert(324)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
*a=*d;
*d=*a;
std::cout << (b->insert(159)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
a->printPretty();
std::cout << (a->remove(399)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
d->printPretty();
return 0;
}
