#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->insert(479)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
a->printPretty();
b->printPretty();
*a=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(434)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (a->insert(172)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (b->remove(41)) << std::endl;
e->printPretty();
std::cout << (e->remove(309)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
d->printPretty();
std::cout << (d->remove(195)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (b->remove(434)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (a->remove(96)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (e->remove(287)) << std::endl;
std::cout << (a->insert(479)) << std::endl;
std::cout << (b->remove(247)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
c->printPretty();
std::cout << (a->insert(213)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->remove(105)) << std::endl;
*d=*a;
std::cout << (a->insert(35)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (d->insert(203)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(223)) << std::endl;
b->printPretty();
std::cout << (d->remove(213)) << std::endl;
*a=*e;
*d=*b;
std::cout << (d->insert(2)) << std::endl;
std::cout << (d->remove(192)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(479)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->insert(69)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
*a=*a;
std::cout << (b->insert(467)) << std::endl;
c->printPretty();
*e=*a;
a->printPretty();
std::cout << (b->insert(28)) << std::endl;
*b=*b;
*b=*e;
std::cout << (b->remove(233)) << std::endl;
*a=*a;
std::cout << (d->insert(2)) << std::endl;
*b=*e;
std::cout << (d->remove(2)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*b=*c;
b->printPretty();
*b=*c;
std::cout << (d->insert(404)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (b->remove(432)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (c->remove(94)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(500)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
b->printPretty();
std::cout << (b->insert(2)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (e->remove(24)) << std::endl;
*e=*c;
std::cout << (e->remove(21)) << std::endl;
*d=*e;
std::cout << (b->insert(12)) << std::endl;
*e=*a;
std::cout << (a->remove(6)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (c->insert(2)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
*c=*d;
std::cout << (d->remove(214)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
*c=*a;
*c=*a;
*d=*a;
std::cout << (c->remove(470)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (c->remove(118)) << std::endl;
*c=*d;
std::cout << (e->insert(167)) << std::endl;
e->printPretty();
std::cout << (c->remove(448)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
*e=*a;
std::cout << (c->remove(99)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
*a=*a;
std::cout << (b->remove(96)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
*a=*a;
*d=*a;
std::cout << (b->remove(125)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (b->remove(12)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (c->insert(117)) << std::endl;
d->printPretty();
std::cout << (d->insert(305)) << std::endl;
*a=*e;
*b=*e;
std::cout << (e->insert(203)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
*c=*c;
std::cout << (a->insert(99)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
*a=*e;
d->printPretty();
c->printPretty();
std::cout << (d->remove(287)) << std::endl;
std::cout << (a->insert(203)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(203)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (c->insert(117)) << std::endl;
std::cout << (c->insert(117)) << std::endl;
d->printPretty();
std::cout << (a->remove(423)) << std::endl;
*a=*c;
std::cout << (a->remove(117)) << std::endl;
std::cout << (d->insert(427)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(192)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
std::cout << (c->remove(117)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (b->remove(99)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (d->insert(399)) << std::endl;
std::cout << (c->insert(295)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
e->printPretty();
std::cout << (b->insert(89)) << std::endl;
*c=*a;
std::cout << (a->remove(273)) << std::endl;
d->printPretty();
*c=*b;
a->printPretty();
std::cout << (e->insert(203)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
std::cout << (e->remove(268)) << std::endl;
b->printPretty();
std::cout << (d->insert(300)) << std::endl;
*c=*d;
std::cout << (d->remove(399)) << std::endl;
*a=*d;
b->printPretty();
std::cout << (d->insert(300)) << std::endl;
*b=*e;
std::cout << (a->insert(224)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
*a=*a;
std::cout << (a->insert(300)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
*b=*a;
std::cout << (c->remove(302)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (c->remove(300)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
*e=*d;
*d=*a;
*a=*b;
std::cout << (c->insert(347)) << std::endl;
std::cout << (a->remove(168)) << std::endl;
std::cout << (e->insert(317)) << std::endl;
std::cout << (a->remove(302)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (d->remove(300)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
*c=*d;
std::cout << (d->remove(302)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (c->insert(272)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
a->printPretty();
std::cout << (d->insert(233)) << std::endl;
*d=*c;
*a=*a;
std::cout << (d->insert(161)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (a->remove(127)) << std::endl;
c->printPretty();
std::cout << (a->insert(475)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (e->remove(475)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
std::cout << (a->insert(87)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
b->printPretty();
std::cout << (a->insert(388)) << std::endl;
*e=*d;
std::cout << (b->remove(219)) << std::endl;
a->printPretty();
std::cout << (d->insert(228)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
b->printPretty();
*b=*b;
*e=*c;
std::cout << (d->remove(228)) << std::endl;
std::cout << (c->remove(272)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
*a=*e;
std::cout << (e->insert(10)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
*a=*a;
std::cout << (e->insert(179)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
std::cout << (a->remove(302)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
*a=*c;
std::cout << (b->remove(157)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
std::cout << (e->insert(197)) << std::endl;
*c=*c;
std::cout << (b->remove(300)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (b->remove(302)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
c->printPretty();
std::cout << (b->insert(317)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
b->printPretty();
std::cout << (a->insert(195)) << std::endl;
std::cout << (e->remove(197)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
*e=*d;
std::cout << (c->remove(289)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (c->remove(31)) << std::endl;
e->printPretty();
*c=*c;
a->printPretty();
*b=*d;
std::cout << (c->remove(302)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->remove(182)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->remove(227)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
b->printPretty();
std::cout << (c->remove(95)) << std::endl;
*e=*b;
std::cout << (a->remove(367)) << std::endl;
std::cout << (a->remove(309)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (b->insert(254)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (b->insert(362)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
*d=*b;
std::cout << (d->remove(254)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (b->remove(362)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
e->printPretty();
*a=*e;
*e=*a;
std::cout << (a->insert(223)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
b->printPretty();
*e=*e;
c->printPretty();
std::cout << (d->insert(235)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (c->remove(227)) << std::endl;
*b=*c;
std::cout << (e->insert(140)) << std::endl;
*b=*a;
std::cout << (b->remove(223)) << std::endl;
*b=*b;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->insert(28)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (b->insert(175)) << std::endl;
c->printPretty();
std::cout << (d->remove(235)) << std::endl;
c->printPretty();
std::cout << (e->insert(18)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
std::cout << (c->insert(116)) << std::endl;
c->printPretty();
std::cout << (d->insert(139)) << std::endl;
std::cout << (a->remove(391)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
*a=*b;
*b=*d;
std::cout << (b->remove(139)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
*a=*d;
std::cout << (d->remove(201)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
e->printPretty();
std::cout << (e->insert(223)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->remove(472)) << std::endl;
std::cout << (e->insert(51)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
*e=*c;
std::cout << (b->insert(62)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (c->insert(116)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
e->printPretty();
std::cout << (a->remove(454)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
std::cout << (a->insert(362)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
*e=*c;
std::cout << (a->insert(55)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (c->insert(153)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (a->remove(353)) << std::endl;
*e=*d;
std::cout << (e->remove(405)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->remove(116)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
*e=*e;
std::cout << (d->insert(39)) << std::endl;
a->printPretty();
std::cout << (b->remove(465)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
*b=*c;
*d=*c;
std::cout << (c->insert(134)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
c->printPretty();
std::cout << (d->insert(274)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
*a=*d;
std::cout << (b->insert(202)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (c->remove(116)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
e->printPretty();
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
*d=*a;
std::cout << (b->insert(134)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
d->printPretty();
std::cout << (c->insert(485)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
d->printPretty();
std::cout << (e->insert(42)) << std::endl;
b->printPretty();
std::cout << (d->remove(474)) << std::endl;
e->printPretty();
*d=*e;
*c=*b;
std::cout << (b->remove(202)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (a->remove(116)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(495)) << std::endl;
std::cout << (d->remove(168)) << std::endl;
*a=*d;
std::cout << (e->remove(153)) << std::endl;
*d=*e;
std::cout << (c->remove(141)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
*a=*d;
*c=*c;
std::cout << (a->remove(54)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
c->printPretty();
std::cout << (e->insert(375)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (b->insert(151)) << std::endl;
std::cout << (b->insert(315)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
std::cout << (b->remove(376)) << std::endl;
std::cout << (d->remove(363)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (b->remove(315)) << std::endl;
std::cout << (c->remove(248)) << std::endl;
a->printPretty();
std::cout << (e->remove(42)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (d->remove(116)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
*a=*e;
std::cout << (c->insert(116)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (c->insert(42)) << std::endl;
*e=*a;
*e=*d;
std::cout << (a->remove(85)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
e->printPretty();
std::cout << (b->remove(239)) << std::endl;
std::cout << (c->insert(162)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
std::cout << (e->insert(27)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
a->printPretty();
std::cout << (c->remove(42)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
std::cout << (d->remove(121)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->insert(279)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(42)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
c->printPretty();
std::cout << (b->insert(58)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*d=*c;
std::cout << (e->remove(448)) << std::endl;
*e=*b;
std::cout << (b->insert(410)) << std::endl;
*d=*b;
std::cout << (b->insert(483)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (a->remove(263)) << std::endl;
*b=*b;
std::cout << (a->insert(18)) << std::endl;
*a=*c;
std::cout << (e->insert(116)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (b->remove(247)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (d->insert(473)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (a->insert(468)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (a->insert(468)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
*d=*e;
d->printPretty();
b->printPretty();
std::cout << (c->insert(406)) << std::endl;
a->printPretty();
std::cout << (e->remove(489)) << std::endl;
std::cout << (c->remove(408)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
std::cout << (d->remove(120)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
*d=*c;
std::cout << (d->insert(222)) << std::endl;
std::cout << (a->remove(349)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
*a=*a;
std::cout << (d->remove(222)) << std::endl;
std::cout << (a->insert(230)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
d->printPretty();
std::cout << (d->insert(406)) << std::endl;
e->printPretty();
std::cout << (b->insert(127)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
*b=*b;
std::cout << (d->insert(406)) << std::endl;
std::cout << (b->remove(222)) << std::endl;
*c=*c;
e->printPretty();
*a=*d;
std::cout << (b->remove(463)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
*a=*b;
std::cout << (d->insert(443)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
*a=*b;
std::cout << (d->remove(443)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
d->printPretty();
*c=*b;
*a=*a;
std::cout << (a->remove(382)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
e->printPretty();
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
*c=*d;
std::cout << (e->remove(492)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
*b=*d;
std::cout << (e->remove(225)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->remove(110)) << std::endl;
b->printPretty();
std::cout << (c->remove(285)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (b->remove(348)) << std::endl;
*d=*e;
std::cout << (d->insert(338)) << std::endl;
*b=*a;
*b=*d;
std::cout << (e->remove(372)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (d->insert(338)) << std::endl;
std::cout << (e->insert(176)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
*b=*d;
std::cout << (b->insert(338)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (d->insert(176)) << std::endl;
std::cout << (a->insert(176)) << std::endl;
b->printPretty();
std::cout << (d->remove(176)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
e->printPretty();
std::cout << (d->insert(338)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
*a=*d;
*e=*a;
c->printPretty();
std::cout << (e->remove(350)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
b->printPretty();
std::cout << (e->insert(338)) << std::endl;
*a=*a;
std::cout << (d->insert(338)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
c->printPretty();
std::cout << (b->insert(461)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (c->remove(107)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(367)) << std::endl;
return 0;
}
