#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->remove(224)) << std::endl;
c->printPretty();
std::cout << (b->remove(42)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
*a=*e;
std::cout << (b->remove(205)) << std::endl;
*b=*e;
std::cout << (c->remove(224)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (d->insert(493)) << std::endl;
std::cout << (c->remove(435)) << std::endl;
*c=*c;
a->printPretty();
*d=*d;
e->printPretty();
*c=*a;
*a=*d;
std::cout << (a->remove(452)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (a->remove(493)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
*b=*e;
std::cout << (b->insert(197)) << std::endl;
*c=*e;
*b=*d;
std::cout << (d->remove(479)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (d->insert(347)) << std::endl;
*b=*e;
*d=*a;
*a=*a;
std::cout << (e->remove(475)) << std::endl;
a->printPretty();
std::cout << (c->insert(127)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (c->remove(48)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
*d=*a;
std::cout << (b->insert(487)) << std::endl;
a->printPretty();
*e=*d;
*a=*a;
d->printPretty();
std::cout << (d->remove(16)) << std::endl;
c->printPretty();
*d=*a;
a->printPretty();
d->printPretty();
std::cout << (a->remove(329)) << std::endl;
e->printPretty();
std::cout << (a->insert(55)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
b->printPretty();
c->printPretty();
*b=*c;
std::cout << (a->remove(55)) << std::endl;
*c=*d;
std::cout << (c->remove(37)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
*d=*a;
*e=*d;
d->printPretty();
d->printPretty();
std::cout << (e->remove(342)) << std::endl;
std::cout << (d->insert(486)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->insert(111)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
*e=*c;
std::cout << (a->insert(193)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
d->printPretty();
std::cout << (e->remove(127)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(177)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (c->remove(127)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
*d=*d;
std::cout << (a->remove(193)) << std::endl;
std::cout << (e->insert(185)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
*e=*e;
d->printPretty();
a->printPretty();
std::cout << (b->remove(3)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
*c=*c;
std::cout << (b->insert(56)) << std::endl;
*d=*d;
std::cout << (b->insert(56)) << std::endl;
*d=*a;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->remove(384)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->remove(415)) << std::endl;
*a=*d;
*b=*d;
*d=*e;
std::cout << (d->insert(237)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
a->printPretty();
a->printPretty();
a->printPretty();
*e=*a;
*a=*a;
std::cout << (e->insert(398)) << std::endl;
*c=*c;
std::cout << (e->insert(257)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->remove(270)) << std::endl;
*a=*a;
std::cout << (b->remove(259)) << std::endl;
*c=*a;
std::cout << (d->insert(237)) << std::endl;
a->printPretty();
std::cout << (d->insert(237)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(237)) << std::endl;
*c=*c;
std::cout << (d->insert(342)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (b->insert(140)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
*a=*c;
std::cout << (e->insert(257)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
*c=*d;
std::cout << (c->remove(297)) << std::endl;
b->printPretty();
*b=*a;
*d=*a;
b->printPretty();
a->printPretty();
d->printPretty();
*b=*d;
*e=*c;
*b=*e;
std::cout << (a->remove(88)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
c->printPretty();
std::cout << (b->remove(342)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
*c=*d;
std::cout << (e->remove(342)) << std::endl;
*b=*e;
*d=*b;
std::cout << (e->remove(115)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
*d=*b;
std::cout << (a->remove(20)) << std::endl;
*b=*e;
std::cout << (a->remove(164)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
e->printPretty();
*c=*c;
b->printPretty();
std::cout << (d->remove(253)) << std::endl;
d->printPretty();
std::cout << (e->remove(408)) << std::endl;
b->printPretty();
std::cout << (d->remove(115)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (c->insert(184)) << std::endl;
*b=*d;
std::cout << (a->remove(410)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
*b=*e;
*a=*c;
d->printPretty();
std::cout << (d->remove(388)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
c->printPretty();
*b=*e;
*b=*c;
*b=*a;
std::cout << (a->insert(184)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (d->remove(263)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
*e=*b;
std::cout << (d->insert(405)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (e->remove(181)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
c->printPretty();
std::cout << (a->insert(29)) << std::endl;
b->printPretty();
std::cout << (d->remove(184)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (a->insert(107)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
*d=*b;
std::cout << (c->remove(330)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
e->printPretty();
std::cout << (c->remove(151)) << std::endl;
*c=*c;
std::cout << (b->insert(184)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
*c=*d;
std::cout << (b->remove(263)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
d->printPretty();
std::cout << (a->insert(107)) << std::endl;
*b=*a;
std::cout << (d->insert(37)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (d->remove(37)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (c->remove(142)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(457)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
*b=*a;
*d=*d;
std::cout << (d->remove(457)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->insert(29)) << std::endl;
*c=*c;
*d=*a;
std::cout << (d->insert(107)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
a->printPretty();
std::cout << (d->remove(273)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
*c=*e;
std::cout << (e->remove(176)) << std::endl;
a->printPretty();
std::cout << (c->remove(115)) << std::endl;
c->printPretty();
a->printPretty();
*a=*b;
std::cout << (b->remove(118)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (a->insert(321)) << std::endl;
a->printPretty();
std::cout << (e->insert(244)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (a->insert(368)) << std::endl;
std::cout << (e->remove(125)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
e->printPretty();
std::cout << (b->remove(324)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (c->remove(405)) << std::endl;
c->printPretty();
std::cout << (b->remove(459)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
std::cout << (d->remove(494)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->remove(55)) << std::endl;
a->printPretty();
std::cout << (a->insert(321)) << std::endl;
c->printPretty();
std::cout << (c->insert(290)) << std::endl;
*e=*d;
std::cout << (c->insert(420)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
*e=*d;
*d=*b;
a->printPretty();
std::cout << (b->remove(107)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
*b=*e;
*d=*c;
*a=*a;
std::cout << (e->remove(494)) << std::endl;
std::cout << (a->remove(125)) << std::endl;
e->printPretty();
std::cout << (c->insert(420)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
std::cout << (e->remove(101)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (a->insert(321)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (b->insert(159)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
b->printPretty();
std::cout << (b->insert(101)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (c->remove(13)) << std::endl;
std::cout << (e->remove(443)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
d->printPretty();
std::cout << (a->insert(321)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
b->printPretty();
std::cout << (b->insert(443)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(43)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
a->printPretty();
std::cout << (e->remove(164)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
*b=*c;
*b=*d;
std::cout << (d->remove(368)) << std::endl;
*a=*e;
std::cout << (c->insert(79)) << std::endl;
e->printPretty();
std::cout << (c->remove(133)) << std::endl;
*d=*b;
std::cout << (a->remove(401)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
*b=*b;
*b=*b;
c->printPretty();
e->printPretty();
std::cout << (e->remove(483)) << std::endl;
*a=*d;
std::cout << (e->insert(339)) << std::endl;
std::cout << (e->remove(362)) << std::endl;
*e=*c;
std::cout << (c->remove(79)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
b->printPretty();
std::cout << (e->remove(161)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->insert(408)) << std::endl;
*a=*e;
std::cout << (a->insert(79)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
c->printPretty();
std::cout << (a->remove(79)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
std::cout << (a->remove(290)) << std::endl;
std::cout << (c->insert(384)) << std::endl;
e->printPretty();
std::cout << (b->insert(368)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
d->printPretty();
std::cout << (e->remove(79)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
*a=*c;
std::cout << (d->remove(305)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (b->remove(143)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
c->printPretty();
*a=*b;
*b=*e;
d->printPretty();
std::cout << (e->remove(448)) << std::endl;
std::cout << (c->remove(168)) << std::endl;
*e=*c;
a->printPretty();
d->printPretty();
std::cout << (a->remove(267)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
c->printPretty();
std::cout << (b->insert(413)) << std::endl;
*d=*c;
*b=*e;
std::cout << (d->insert(384)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (d->insert(420)) << std::endl;
*e=*a;
std::cout << (c->insert(371)) << std::endl;
*c=*d;
std::cout << (e->insert(465)) << std::endl;
d->printPretty();
std::cout << (c->insert(365)) << std::endl;
std::cout << (a->insert(209)) << std::endl;
std::cout << (c->insert(365)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (b->remove(380)) << std::endl;
std::cout << (c->remove(23)) << std::endl;
a->printPretty();
std::cout << (e->insert(406)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
*a=*e;
std::cout << (a->insert(4)) << std::endl;
e->printPretty();
std::cout << (c->remove(365)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
*b=*c;
std::cout << (b->insert(433)) << std::endl;
*b=*c;
std::cout << (e->insert(233)) << std::endl;
std::cout << (a->insert(326)) << std::endl;
d->printPretty();
std::cout << (a->remove(326)) << std::endl;
std::cout << (d->insert(402)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
*c=*c;
std::cout << (d->remove(384)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
*b=*d;
std::cout << (a->remove(486)) << std::endl;
std::cout << (e->remove(465)) << std::endl;
std::cout << (e->remove(406)) << std::endl;
c->printPretty();
std::cout << (a->remove(182)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (b->remove(309)) << std::endl;
std::cout << (c->insert(384)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (d->remove(439)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (c->insert(368)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
*a=*b;
std::cout << (a->insert(120)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
e->printPretty();
std::cout << (a->remove(346)) << std::endl;
std::cout << (d->insert(498)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
*d=*e;
*d=*c;
std::cout << (d->insert(303)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (d->insert(7)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
*d=*b;
*d=*b;
*e=*a;
std::cout << (c->insert(233)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (d->insert(368)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (b->remove(4)) << std::endl;
c->printPretty();
std::cout << (e->remove(340)) << std::endl;
d->printPretty();
std::cout << (b->insert(92)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
std::cout << (d->remove(7)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (b->remove(373)) << std::endl;
*d=*b;
std::cout << (b->remove(7)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
d->printPretty();
std::cout << (c->insert(233)) << std::endl;
std::cout << (c->remove(230)) << std::endl;
b->printPretty();
std::cout << (a->insert(307)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
a->printPretty();
std::cout << (c->insert(233)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
b->printPretty();
*c=*e;
b->printPretty();
std::cout << (b->remove(340)) << std::endl;
std::cout << (c->remove(483)) << std::endl;
c->printPretty();
std::cout << (c->remove(257)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
c->printPretty();
std::cout << (d->insert(7)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
*c=*a;
std::cout << (e->remove(92)) << std::endl;
std::cout << (a->remove(292)) << std::endl;
c->printPretty();
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
b->printPretty();
std::cout << (c->remove(340)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
b->printPretty();
std::cout << (d->insert(439)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
b->printPretty();
std::cout << (d->insert(368)) << std::endl;
a->printPretty();
std::cout << (c->remove(307)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
std::cout << (c->insert(413)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (c->insert(175)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
a->printPretty();
std::cout << (d->remove(368)) << std::endl;
std::cout << (c->insert(175)) << std::endl;
c->printPretty();
std::cout << (a->remove(7)) << std::endl;
c->printPretty();
a->printPretty();
*e=*d;
std::cout << (e->remove(7)) << std::endl;
return 0;
}
