#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
b->printPretty();
std::cout << (b->remove(403)) << std::endl;
*c=*b;
c->printPretty();
b->printPretty();
*a=*a;
std::cout << (a->remove(313)) << std::endl;
*b=*c;
*a=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(181)) << std::endl;
c->printPretty();
std::cout << (d->remove(478)) << std::endl;
b->printPretty();
std::cout << (b->remove(448)) << std::endl;
*a=*b;
std::cout << (b->remove(181)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
a->printPretty();
std::cout << (b->remove(176)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (d->insert(312)) << std::endl;
a->printPretty();
std::cout << (a->insert(181)) << std::endl;
*a=*a;
std::cout << (d->insert(238)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
*b=*d;
std::cout << (d->remove(243)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (c->insert(87)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
*d=*e;
std::cout << (e->insert(204)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
*b=*d;
*e=*b;
*c=*d;
std::cout << (e->insert(312)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
e->printPretty();
std::cout << (e->insert(129)) << std::endl;
*d=*c;
a->printPretty();
std::cout << (c->remove(312)) << std::endl;
*c=*c;
c->printPretty();
*a=*b;
std::cout << (b->remove(312)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
*a=*a;
std::cout << (c->remove(274)) << std::endl;
c->printPretty();
b->printPretty();
*d=*a;
std::cout << (e->remove(376)) << std::endl;
*c=*b;
std::cout << (c->insert(420)) << std::endl;
*a=*b;
std::cout << (a->remove(274)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(329)) << std::endl;
*b=*c;
*e=*e;
std::cout << (d->insert(189)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
*b=*d;
a->printPretty();
*e=*c;
std::cout << (c->remove(339)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
a->printPretty();
std::cout << (c->insert(471)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (b->remove(398)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (a->remove(182)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
e->printPretty();
a->printPretty();
*e=*a;
*d=*c;
c->printPretty();
std::cout << (b->remove(126)) << std::endl;
std::cout << (b->remove(452)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(198)) << std::endl;
*c=*a;
*e=*a;
*a=*d;
*d=*b;
*a=*d;
std::cout << (d->insert(312)) << std::endl;
a->printPretty();
std::cout << (c->remove(69)) << std::endl;
std::cout << (a->remove(89)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
c->printPretty();
std::cout << (b->insert(189)) << std::endl;
*a=*d;
*c=*d;
d->printPretty();
std::cout << (c->insert(198)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
*b=*b;
std::cout << (d->remove(391)) << std::endl;
b->printPretty();
std::cout << (a->insert(493)) << std::endl;
*b=*d;
c->printPretty();
*c=*a;
std::cout << (a->remove(431)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (d->insert(89)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
*a=*e;
std::cout << (b->remove(189)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
e->printPretty();
std::cout << (c->remove(493)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
d->printPretty();
*c=*e;
*e=*d;
std::cout << (b->remove(59)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
*c=*d;
std::cout << (c->remove(198)) << std::endl;
e->printPretty();
std::cout << (d->remove(78)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
e->printPretty();
std::cout << (e->insert(499)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
*d=*d;
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
std::cout << (d->insert(28)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (a->insert(142)) << std::endl;
b->printPretty();
std::cout << (c->remove(347)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
a->printPretty();
std::cout << (a->remove(320)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
*e=*a;
*e=*e;
std::cout << (b->remove(452)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(28)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (e->remove(354)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (b->insert(312)) << std::endl;
*c=*d;
std::cout << (e->remove(309)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
c->printPretty();
std::cout << (b->insert(429)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
*e=*d;
std::cout << (a->insert(183)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
*b=*d;
std::cout << (e->remove(468)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (c->insert(275)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
*d=*c;
std::cout << (a->insert(358)) << std::endl;
*e=*a;
*e=*d;
*b=*e;
c->printPretty();
std::cout << (e->remove(30)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
*a=*e;
std::cout << (a->remove(130)) << std::endl;
std::cout << (e->remove(275)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
d->printPretty();
std::cout << (c->insert(309)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (d->remove(5)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
e->printPretty();
std::cout << (d->insert(312)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
e->printPretty();
d->printPretty();
*d=*c;
std::cout << (e->remove(198)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (d->remove(326)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
*c=*c;
std::cout << (b->insert(388)) << std::endl;
d->printPretty();
*d=*c;
*d=*a;
std::cout << (b->insert(199)) << std::endl;
b->printPretty();
std::cout << (b->insert(199)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (e->insert(309)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
*d=*b;
std::cout << (e->remove(312)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
e->printPretty();
std::cout << (b->remove(122)) << std::endl;
std::cout << (e->insert(309)) << std::endl;
*d=*c;
std::cout << (c->remove(396)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (c->insert(275)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
*c=*a;
c->printPretty();
d->printPretty();
std::cout << (b->remove(275)) << std::endl;
e->printPretty();
std::cout << (b->insert(470)) << std::endl;
*c=*a;
std::cout << (b->remove(468)) << std::endl;
e->printPretty();
std::cout << (b->insert(59)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
c->printPretty();
std::cout << (b->insert(18)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (d->remove(309)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
*b=*d;
std::cout << (d->insert(490)) << std::endl;
std::cout << (d->insert(132)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (e->insert(309)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
c->printPretty();
std::cout << (b->insert(169)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
c->printPretty();
std::cout << (e->insert(309)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
std::cout << (b->remove(275)) << std::endl;
std::cout << (b->remove(115)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (c->insert(389)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
std::cout << (a->remove(275)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (d->insert(456)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
c->printPretty();
*c=*a;
*a=*d;
a->printPretty();
*e=*d;
std::cout << (a->insert(481)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
e->printPretty();
std::cout << (c->remove(463)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
std::cout << (c->insert(309)) << std::endl;
b->printPretty();
std::cout << (c->insert(176)) << std::endl;
a->printPretty();
std::cout << (c->insert(410)) << std::endl;
e->printPretty();
std::cout << (c->insert(69)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
*a=*b;
*d=*c;
std::cout << (a->insert(388)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
*b=*c;
std::cout << (d->remove(480)) << std::endl;
a->printPretty();
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
*a=*d;
std::cout << (a->remove(470)) << std::endl;
std::cout << (b->insert(249)) << std::endl;
*c=*b;
std::cout << (b->remove(344)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
*b=*d;
*e=*e;
d->printPretty();
std::cout << (d->remove(309)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
std::cout << (d->remove(437)) << std::endl;
std::cout << (a->remove(176)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
std::cout << (e->remove(448)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
e->printPretty();
std::cout << (a->insert(312)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
a->printPretty();
*b=*b;
d->printPretty();
std::cout << (a->remove(309)) << std::endl;
e->printPretty();
std::cout << (c->remove(309)) << std::endl;
*b=*b;
a->printPretty();
*c=*b;
std::cout << (a->remove(69)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
*e=*c;
std::cout << (a->insert(242)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
d->printPretty();
std::cout << (d->insert(470)) << std::endl;
*a=*d;
b->printPretty();
std::cout << (c->insert(386)) << std::endl;
b->printPretty();
std::cout << (c->insert(15)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
d->printPretty();
b->printPretty();
c->printPretty();
std::cout << (b->remove(38)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
std::cout << (c->remove(437)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
c->printPretty();
std::cout << (e->remove(320)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
*d=*d;
std::cout << (a->insert(176)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
*a=*d;
*d=*c;
std::cout << (d->insert(369)) << std::endl;
d->printPretty();
b->printPretty();
*b=*a;
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
*d=*b;
std::cout << (b->remove(470)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (a->insert(237)) << std::endl;
std::cout << (b->insert(22)) << std::endl;
std::cout << (b->remove(67)) << std::endl;
*c=*a;
std::cout << (e->remove(455)) << std::endl;
d->printPretty();
std::cout << (b->insert(219)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
std::cout << (d->remove(432)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
a->printPretty();
*c=*e;
*a=*a;
std::cout << (a->insert(108)) << std::endl;
*e=*b;
std::cout << (c->insert(410)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
*c=*a;
std::cout << (b->insert(219)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (b->insert(22)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->remove(312)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
*a=*d;
b->printPretty();
std::cout << (d->remove(422)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
std::cout << (b->insert(346)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
e->printPretty();
std::cout << (b->insert(202)) << std::endl;
c->printPretty();
std::cout << (b->remove(194)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
*e=*c;
std::cout << (e->insert(336)) << std::endl;
c->printPretty();
std::cout << (a->insert(176)) << std::endl;
std::cout << (b->remove(93)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
d->printPretty();
std::cout << (b->insert(219)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
*a=*a;
e->printPretty();
a->printPretty();
std::cout << (a->insert(288)) << std::endl;
std::cout << (c->insert(199)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
b->printPretty();
std::cout << (b->insert(138)) << std::endl;
*a=*d;
std::cout << (a->remove(410)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
*b=*c;
std::cout << (c->insert(152)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (e->insert(181)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->remove(401)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
*c=*a;
std::cout << (b->insert(22)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->insert(424)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(233)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
e->printPretty();
std::cout << (e->insert(101)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
b->printPretty();
std::cout << (d->insert(471)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (d->insert(471)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (e->insert(470)) << std::endl;
std::cout << (b->remove(251)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
c->printPretty();
std::cout << (c->insert(172)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (e->insert(190)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(69)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
e->printPretty();
std::cout << (c->remove(352)) << std::endl;
*c=*e;
std::cout << (e->remove(468)) << std::endl;
std::cout << (e->remove(286)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (e->remove(316)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
c->printPretty();
d->printPretty();
b->printPretty();
*a=*a;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->insert(176)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
a->printPretty();
std::cout << (b->insert(312)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
b->printPretty();
std::cout << (b->remove(176)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (b->remove(407)) << std::endl;
e->printPretty();
std::cout << (d->remove(199)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
b->printPretty();
std::cout << (c->insert(33)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (d->insert(319)) << std::endl;
a->printPretty();
std::cout << (e->remove(389)) << std::endl;
*b=*b;
std::cout << (b->remove(203)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (d->remove(237)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
b->printPretty();
std::cout << (e->insert(272)) << std::endl;
std::cout << (b->insert(496)) << std::endl;
*a=*c;
std::cout << (c->insert(63)) << std::endl;
*a=*e;
std::cout << (a->insert(272)) << std::endl;
e->printPretty();
std::cout << (a->remove(335)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
*c=*d;
std::cout << (d->remove(258)) << std::endl;
*d=*d;
*c=*c;
std::cout << (c->insert(163)) << std::endl;
std::cout << (d->insert(194)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
a->printPretty();
std::cout << (b->remove(389)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (d->remove(205)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
a->printPretty();
std::cout << (e->insert(188)) << std::endl;
*c=*b;
std::cout << (e->insert(272)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (a->insert(312)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
c->printPretty();
std::cout << (e->insert(159)) << std::endl;
e->printPretty();
*a=*c;
c->printPretty();
std::cout << (b->remove(280)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (a->remove(312)) << std::endl;
*e=*b;
a->printPretty();
a->printPretty();
std::cout << (d->remove(108)) << std::endl;
std::cout << (c->insert(199)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (e->insert(337)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
*c=*a;
std::cout << (c->remove(153)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
*b=*e;
std::cout << (d->insert(477)) << std::endl;
*e=*e;
std::cout << (c->remove(265)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
*b=*d;
std::cout << (c->insert(69)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
std::cout << (c->remove(496)) << std::endl;
*b=*c;
std::cout << (c->remove(199)) << std::endl;
std::cout << (c->insert(374)) << std::endl;
*e=*b;
std::cout << (d->insert(155)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (e->insert(432)) << std::endl;
d->printPretty();
std::cout << (a->remove(183)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
b->printPretty();
std::cout << (c->insert(230)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (d->remove(237)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (c->insert(194)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
*d=*a;
std::cout << (d->remove(348)) << std::endl;
std::cout << (c->insert(210)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
*b=*d;
*c=*e;
*b=*b;
a->printPretty();
e->printPretty();
std::cout << (a->insert(199)) << std::endl;
return 0;
}
