#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->insert(113)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
b->printPretty();
std::cout << (a->insert(113)) << std::endl;
*b=*b;
std::cout << (a->insert(113)) << std::endl;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (c->remove(52)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->remove(182)) << std::endl;
std::cout << (d->insert(31)) << std::endl;
std::cout << (e->remove(3)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (d->insert(424)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
*d=*e;
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (d->insert(437)) << std::endl;
*a=*c;
std::cout << (e->remove(437)) << std::endl;
*a=*d;
*b=*d;
*e=*c;
std::cout << (e->remove(53)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
*e=*c;
std::cout << (d->insert(130)) << std::endl;
std::cout << (a->insert(437)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->remove(130)) << std::endl;
c->printPretty();
*b=*c;
*d=*a;
std::cout << (d->insert(64)) << std::endl;
*e=*d;
std::cout << (b->insert(113)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
c->printPretty();
std::cout << (e->insert(11)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
c->printPretty();
std::cout << (d->remove(456)) << std::endl;
*e=*b;
std::cout << (e->insert(113)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
c->printPretty();
std::cout << (e->insert(156)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
d->printPretty();
std::cout << (c->remove(278)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
*c=*e;
std::cout << (b->insert(80)) << std::endl;
*c=*c;
*c=*b;
std::cout << (c->insert(80)) << std::endl;
*a=*b;
e->printPretty();
c->printPretty();
*c=*c;
std::cout << (a->insert(113)) << std::endl;
a->printPretty();
std::cout << (b->remove(113)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
e->printPretty();
*b=*d;
a->printPretty();
*d=*d;
std::cout << (c->insert(80)) << std::endl;
b->printPretty();
std::cout << (b->insert(151)) << std::endl;
*a=*d;
std::cout << (e->insert(156)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
*a=*a;
std::cout << (e->remove(156)) << std::endl;
d->printPretty();
std::cout << (b->insert(182)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (c->remove(113)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
d->printPretty();
std::cout << (d->remove(437)) << std::endl;
std::cout << (b->insert(31)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (d->remove(7)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
e->printPretty();
std::cout << (a->remove(272)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
std::cout << (e->remove(316)) << std::endl;
std::cout << (d->insert(485)) << std::endl;
std::cout << (b->remove(419)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
b->printPretty();
std::cout << (c->insert(80)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
*e=*c;
std::cout << (c->insert(412)) << std::endl;
*b=*d;
std::cout << (e->insert(394)) << std::endl;
*a=*c;
*e=*d;
std::cout << (e->insert(264)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
*b=*a;
*a=*d;
std::cout << (d->remove(485)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
*a=*c;
std::cout << (e->insert(64)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
e->printPretty();
std::cout << (c->remove(357)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (c->remove(412)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (e->insert(485)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (a->remove(80)) << std::endl;
std::cout << (a->insert(412)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
std::cout << (e->remove(471)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (a->insert(412)) << std::endl;
*a=*d;
std::cout << (b->insert(485)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
a->printPretty();
std::cout << (b->insert(215)) << std::endl;
a->printPretty();
*e=*b;
std::cout << (d->remove(447)) << std::endl;
std::cout << (a->insert(214)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (d->remove(214)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
*d=*b;
*b=*d;
std::cout << (c->insert(265)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (c->remove(346)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
*d=*c;
std::cout << (d->remove(468)) << std::endl;
*b=*e;
std::cout << (d->insert(294)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (c->remove(376)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
*c=*d;
std::cout << (a->remove(214)) << std::endl;
*e=*d;
std::cout << (b->insert(281)) << std::endl;
a->printPretty();
*e=*c;
e->printPretty();
std::cout << (e->insert(206)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
*b=*e;
*b=*b;
std::cout << (e->remove(173)) << std::endl;
c->printPretty();
std::cout << (e->remove(214)) << std::endl;
b->printPretty();
std::cout << (e->insert(8)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (c->remove(151)) << std::endl;
a->printPretty();
std::cout << (e->remove(318)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
e->printPretty();
std::cout << (c->remove(214)) << std::endl;
e->printPretty();
b->printPretty();
d->printPretty();
std::cout << (d->insert(214)) << std::endl;
c->printPretty();
std::cout << (e->remove(8)) << std::endl;
d->printPretty();
std::cout << (e->insert(206)) << std::endl;
d->printPretty();
*b=*a;
*a=*a;
std::cout << (d->remove(159)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(206)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
a->printPretty();
std::cout << (c->remove(376)) << std::endl;
*c=*a;
a->printPretty();
*d=*d;
d->printPretty();
d->printPretty();
*a=*e;
*d=*d;
*c=*d;
std::cout << (a->insert(310)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
*c=*c;
std::cout << (e->insert(324)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
*d=*b;
std::cout << (b->insert(51)) << std::endl;
a->printPretty();
b->printPretty();
d->printPretty();
b->printPretty();
c->printPretty();
d->printPretty();
b->printPretty();
*b=*a;
c->printPretty();
*c=*e;
std::cout << (b->remove(486)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (c->insert(206)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (e->insert(117)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->remove(51)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
*e=*a;
*b=*a;
std::cout << (b->insert(166)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
*c=*e;
e->printPretty();
*d=*d;
std::cout << (d->insert(468)) << std::endl;
b->printPretty();
std::cout << (c->remove(462)) << std::endl;
*d=*b;
std::cout << (e->insert(128)) << std::endl;
e->printPretty();
std::cout << (a->remove(320)) << std::endl;
std::cout << (e->insert(48)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
a->printPretty();
std::cout << (c->remove(307)) << std::endl;
c->printPretty();
std::cout << (b->remove(307)) << std::endl;
*d=*c;
*a=*a;
std::cout << (d->remove(182)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (b->insert(166)) << std::endl;
*e=*d;
*d=*c;
std::cout << (b->remove(475)) << std::endl;
*e=*b;
std::cout << (a->insert(51)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (a->remove(166)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->remove(489)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
std::cout << (b->insert(166)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
a->printPretty();
std::cout << (c->remove(51)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
*c=*e;
std::cout << (e->insert(224)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(51)) << std::endl;
b->printPretty();
std::cout << (b->remove(213)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (b->insert(159)) << std::endl;
e->printPretty();
b->printPretty();
b->printPretty();
std::cout << (a->insert(166)) << std::endl;
*b=*c;
std::cout << (a->insert(166)) << std::endl;
std::cout << (e->insert(9)) << std::endl;
*d=*c;
std::cout << (c->insert(354)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
d->printPretty();
std::cout << (e->insert(290)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(9)) << std::endl;
b->printPretty();
std::cout << (a->remove(366)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
b->printPretty();
std::cout << (b->insert(397)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
*a=*c;
std::cout << (a->insert(276)) << std::endl;
std::cout << (e->insert(9)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
a->printPretty();
std::cout << (e->insert(224)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
*c=*e;
std::cout << (a->remove(17)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (a->insert(429)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
c->printPretty();
std::cout << (a->remove(219)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
d->printPretty();
std::cout << (b->remove(199)) << std::endl;
*b=*e;
std::cout << (d->insert(25)) << std::endl;
b->printPretty();
std::cout << (b->insert(224)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (d->insert(316)) << std::endl;
d->printPretty();
std::cout << (d->remove(211)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
std::cout << (b->remove(385)) << std::endl;
a->printPretty();
std::cout << (e->remove(9)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (d->remove(316)) << std::endl;
a->printPretty();
std::cout << (b->remove(413)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(290)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
*d=*e;
std::cout << (c->remove(134)) << std::endl;
std::cout << (c->remove(9)) << std::endl;
e->printPretty();
std::cout << (c->insert(221)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
e->printPretty();
std::cout << (c->insert(237)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (e->insert(290)) << std::endl;
*e=*c;
std::cout << (b->insert(224)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
*b=*b;
std::cout << (b->insert(9)) << std::endl;
*a=*d;
std::cout << (d->insert(290)) << std::endl;
std::cout << (a->insert(290)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
a->printPretty();
std::cout << (e->insert(221)) << std::endl;
e->printPretty();
std::cout << (e->remove(221)) << std::endl;
std::cout << (e->insert(76)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (c->insert(237)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->remove(264)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
std::cout << (a->insert(290)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (c->insert(456)) << std::endl;
d->printPretty();
std::cout << (d->insert(127)) << std::endl;
*c=*a;
std::cout << (d->remove(484)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
std::cout << (a->remove(478)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
std::cout << (d->remove(127)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (a->remove(290)) << std::endl;
d->printPretty();
std::cout << (c->insert(378)) << std::endl;
*e=*d;
std::cout << (d->remove(262)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
c->printPretty();
std::cout << (c->remove(378)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
a->printPretty();
std::cout << (b->remove(224)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
c->printPretty();
std::cout << (e->remove(130)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (a->remove(116)) << std::endl;
d->printPretty();
std::cout << (e->remove(340)) << std::endl;
*b=*e;
std::cout << (e->remove(291)) << std::endl;
d->printPretty();
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->remove(144)) << std::endl;
e->printPretty();
std::cout << (a->insert(375)) << std::endl;
b->printPretty();
std::cout << (e->insert(340)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (c->remove(84)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
b->printPretty();
std::cout << (e->remove(340)) << std::endl;
c->printPretty();
std::cout << (b->insert(140)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (b->insert(278)) << std::endl;
*b=*e;
std::cout << (c->remove(349)) << std::endl;
*a=*a;
std::cout << (d->insert(37)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
*a=*a;
std::cout << (c->insert(280)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
d->printPretty();
std::cout << (e->insert(151)) << std::endl;
*c=*c;
std::cout << (b->remove(310)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (c->remove(58)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(271)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
*b=*a;
std::cout << (a->remove(268)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
std::cout << (e->insert(328)) << std::endl;
c->printPretty();
std::cout << (c->insert(228)) << std::endl;
std::cout << (b->remove(210)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
*a=*d;
std::cout << (a->insert(229)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (a->remove(318)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
a->printPretty();
c->printPretty();
c->printPretty();
std::cout << (a->insert(229)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (c->remove(228)) << std::endl;
std::cout << (d->remove(131)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (a->insert(37)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
*b=*e;
e->printPretty();
std::cout << (e->remove(484)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
c->printPretty();
std::cout << (c->insert(254)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
a->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (b->remove(12)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (e->remove(413)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
*c=*a;
*e=*c;
std::cout << (e->remove(37)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
std::cout << (c->remove(442)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
c->printPretty();
std::cout << (c->insert(131)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (b->insert(82)) << std::endl;
*c=*b;
std::cout << (e->remove(434)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
*c=*a;
std::cout << (b->remove(276)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
d->printPretty();
std::cout << (c->remove(320)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
*c=*b;
std::cout << (d->remove(393)) << std::endl;
std::cout << (b->remove(82)) << std::endl;
*a=*a;
std::cout << (d->insert(209)) << std::endl;
*e=*d;
std::cout << (b->insert(445)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (a->insert(473)) << std::endl;
e->printPretty();
std::cout << (c->remove(82)) << std::endl;
std::cout << (e->remove(147)) << std::endl;
d->printPretty();
std::cout << (e->insert(400)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (a->remove(31)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
c->printPretty();
std::cout << (d->remove(450)) << std::endl;
std::cout << (b->insert(319)) << std::endl;
*b=*e;
*e=*e;
std::cout << (b->insert(209)) << std::endl;
std::cout << (d->remove(193)) << std::endl;
b->printPretty();
std::cout << (a->remove(434)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (b->remove(63)) << std::endl;
*b=*e;
*c=*b;
std::cout << (a->remove(131)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(123)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (e->insert(73)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
std::cout << (c->insert(209)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
b->printPretty();
std::cout << (d->insert(131)) << std::endl;
a->printPretty();
std::cout << (e->insert(305)) << std::endl;
*b=*b;
std::cout << (d->remove(400)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
std::cout << (d->remove(337)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
*a=*b;
std::cout << (a->insert(400)) << std::endl;
std::cout << (d->remove(462)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
b->printPretty();
*b=*e;
*c=*e;
a->printPretty();
*d=*c;
std::cout << (b->insert(415)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
e->printPretty();
std::cout << (a->insert(354)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (c->remove(256)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*a=*c;
std::cout << (a->insert(252)) << std::endl;
a->printPretty();
std::cout << (c->remove(305)) << std::endl;
std::cout << (b->remove(335)) << std::endl;
std::cout << (e->remove(415)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (a->remove(469)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
*c=*d;
std::cout << (a->insert(270)) << std::endl;
*c=*b;
std::cout << (e->insert(321)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
return 0;
}
