#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->insert(111)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*b=*b;
std::cout << (b->remove(406)) << std::endl;
b->printPretty();
std::cout << (b->insert(196)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
d->printPretty();
std::cout << (c->insert(391)) << std::endl;
*e=*a;
std::cout << (c->insert(311)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
*d=*c;
std::cout << (a->insert(95)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
std::cout << (b->insert(370)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
b->printPretty();
std::cout << (c->insert(111)) << std::endl;
std::cout << (c->insert(111)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
a->printPretty();
std::cout << (a->insert(95)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(111)) << std::endl;
std::cout << (c->remove(383)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
c->printPretty();
std::cout << (c->remove(391)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
*a=*b;
std::cout << (a->remove(370)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
a->printPretty();
std::cout << (a->insert(481)) << std::endl;
d->printPretty();
std::cout << (a->insert(271)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
std::cout << (e->remove(60)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (b->remove(481)) << std::endl;
c->printPretty();
std::cout << (e->remove(85)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
b->printPretty();
std::cout << (e->insert(111)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (b->insert(370)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
std::cout << (c->remove(381)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (b->insert(495)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (d->remove(90)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (d->insert(391)) << std::endl;
*b=*d;
e->printPretty();
a->printPretty();
std::cout << (d->insert(111)) << std::endl;
*b=*a;
*b=*c;
*d=*d;
*a=*e;
std::cout << (a->remove(180)) << std::endl;
e->printPretty();
std::cout << (b->insert(130)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->remove(311)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (e->remove(111)) << std::endl;
std::cout << (b->insert(240)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
a->printPretty();
b->printPretty();
*c=*d;
std::cout << (b->remove(240)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (e->insert(401)) << std::endl;
*d=*a;
std::cout << (d->remove(53)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (e->insert(244)) << std::endl;
a->printPretty();
std::cout << (e->remove(447)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
std::cout << (d->remove(196)) << std::endl;
std::cout << (b->insert(185)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (c->insert(391)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (c->remove(138)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
std::cout << (c->insert(335)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
*c=*e;
std::cout << (b->remove(194)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
a->printPretty();
std::cout << (a->insert(313)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
std::cout << (e->insert(25)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
e->printPretty();
std::cout << (c->insert(271)) << std::endl;
d->printPretty();
std::cout << (e->insert(430)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (b->insert(137)) << std::endl;
*d=*b;
std::cout << (c->remove(313)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
d->printPretty();
d->printPretty();
*d=*b;
std::cout << (a->remove(271)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
c->printPretty();
std::cout << (d->insert(406)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
std::cout << (a->remove(313)) << std::endl;
*d=*d;
c->printPretty();
*c=*a;
std::cout << (d->insert(254)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
e->printPretty();
c->printPretty();
b->printPretty();
std::cout << (c->remove(252)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (e->remove(286)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (d->insert(349)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
*e=*a;
*e=*e;
*b=*a;
std::cout << (d->remove(176)) << std::endl;
*b=*a;
e->printPretty();
*a=*a;
*b=*e;
std::cout << (b->insert(461)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (d->remove(30)) << std::endl;
*e=*d;
std::cout << (e->insert(137)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
e->printPretty();
std::cout << (a->insert(16)) << std::endl;
*a=*d;
std::cout << (d->insert(406)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
*b=*e;
std::cout << (e->remove(312)) << std::endl;
std::cout << (b->insert(67)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
std::cout << (e->insert(226)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
*a=*a;
std::cout << (a->remove(92)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
*a=*c;
std::cout << (a->remove(286)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
a->printPretty();
std::cout << (c->remove(420)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
std::cout << (a->insert(365)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
c->printPretty();
std::cout << (d->insert(349)) << std::endl;
*b=*a;
*e=*d;
std::cout << (a->remove(480)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
*c=*e;
*e=*e;
std::cout << (e->remove(310)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(365)) << std::endl;
std::cout << (e->remove(349)) << std::endl;
std::cout << (d->insert(349)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (d->insert(349)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
std::cout << (c->remove(349)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
*d=*e;
std::cout << (d->remove(360)) << std::endl;
*b=*a;
*a=*d;
*a=*a;
std::cout << (e->insert(127)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
a->printPretty();
std::cout << (a->insert(335)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
b->printPretty();
std::cout << (a->remove(444)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->insert(127)) << std::endl;
c->printPretty();
std::cout << (a->remove(220)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
c->printPretty();
*d=*d;
*a=*a;
a->printPretty();
std::cout << (b->insert(494)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
std::cout << (b->insert(453)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
e->printPretty();
std::cout << (b->insert(470)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
*d=*d;
std::cout << (b->insert(494)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (e->insert(363)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
*d=*a;
std::cout << (e->remove(327)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
*d=*d;
std::cout << (a->insert(22)) << std::endl;
b->printPretty();
std::cout << (b->insert(494)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (d->insert(335)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
*e=*d;
std::cout << (e->insert(206)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
std::cout << (d->remove(335)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
*d=*c;
std::cout << (d->insert(234)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (b->remove(217)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
b->printPretty();
std::cout << (c->insert(202)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
*e=*d;
*b=*c;
std::cout << (c->remove(70)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
*b=*b;
std::cout << (e->insert(7)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (e->insert(265)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
*a=*d;
c->printPretty();
a->printPretty();
std::cout << (c->insert(31)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (e->remove(265)) << std::endl;
*d=*e;
*e=*b;
std::cout << (c->remove(482)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (d->insert(7)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
e->printPretty();
std::cout << (b->remove(234)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
e->printPretty();
*d=*b;
c->printPretty();
std::cout << (c->remove(204)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
*b=*b;
std::cout << (e->remove(94)) << std::endl;
d->printPretty();
c->printPretty();
*b=*b;
*e=*d;
std::cout << (a->remove(243)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
*e=*a;
c->printPretty();
*a=*c;
a->printPretty();
d->printPretty();
std::cout << (c->remove(234)) << std::endl;
d->printPretty();
std::cout << (e->remove(179)) << std::endl;
b->printPretty();
std::cout << (a->remove(287)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
b->printPretty();
std::cout << (a->remove(359)) << std::endl;
std::cout << (e->remove(80)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
c->printPretty();
std::cout << (a->insert(488)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (a->insert(286)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
*d=*e;
*e=*e;
std::cout << (c->insert(236)) << std::endl;
std::cout << (e->remove(37)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
a->printPretty();
std::cout << (a->remove(31)) << std::endl;
*d=*c;
std::cout << (e->insert(483)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
*b=*d;
std::cout << (d->remove(260)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
b->printPretty();
std::cout << (c->insert(31)) << std::endl;
c->printPretty();
std::cout << (b->remove(248)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (b->insert(195)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (d->insert(248)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
e->printPretty();
*c=*d;
std::cout << (b->remove(161)) << std::endl;
a->printPretty();
std::cout << (e->remove(488)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
*d=*c;
std::cout << (d->remove(31)) << std::endl;
*e=*c;
std::cout << (a->remove(318)) << std::endl;
*e=*e;
std::cout << (c->remove(495)) << std::endl;
*c=*b;
std::cout << (c->remove(11)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
e->printPretty();
std::cout << (a->insert(442)) << std::endl;
*b=*a;
b->printPretty();
*c=*b;
a->printPretty();
std::cout << (a->remove(44)) << std::endl;
std::cout << (e->remove(125)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
*b=*a;
std::cout << (e->insert(454)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
c->printPretty();
std::cout << (e->insert(248)) << std::endl;
*d=*e;
*c=*a;
a->printPretty();
std::cout << (e->remove(365)) << std::endl;
std::cout << (c->remove(442)) << std::endl;
a->printPretty();
b->printPretty();
b->printPretty();
std::cout << (b->insert(442)) << std::endl;
std::cout << (d->insert(11)) << std::endl;
*b=*c;
std::cout << (a->insert(468)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
e->printPretty();
*b=*b;
std::cout << (a->remove(468)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
*d=*b;
std::cout << (e->insert(248)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
*d=*c;
*e=*a;
d->printPretty();
std::cout << (c->insert(488)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
a->printPretty();
std::cout << (a->remove(488)) << std::endl;
std::cout << (e->insert(442)) << std::endl;
e->printPretty();
std::cout << (d->insert(362)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
*a=*b;
c->printPretty();
*d=*d;
std::cout << (a->insert(181)) << std::endl;
b->printPretty();
std::cout << (c->insert(418)) << std::endl;
std::cout << (d->remove(352)) << std::endl;
*d=*e;
std::cout << (c->insert(488)) << std::endl;
*c=*d;
std::cout << (e->remove(282)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (c->insert(168)) << std::endl;
*e=*a;
std::cout << (c->insert(442)) << std::endl;
std::cout << (d->remove(403)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
e->printPretty();
std::cout << (c->remove(85)) << std::endl;
c->printPretty();
std::cout << (b->remove(53)) << std::endl;
b->printPretty();
std::cout << (a->insert(300)) << std::endl;
*c=*a;
std::cout << (b->remove(188)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(182)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
*b=*a;
*a=*a;
std::cout << (c->remove(300)) << std::endl;
d->printPretty();
std::cout << (d->insert(488)) << std::endl;
*b=*d;
b->printPretty();
*c=*c;
std::cout << (a->remove(407)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
*c=*b;
std::cout << (c->insert(205)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
*e=*d;
std::cout << (e->insert(396)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
*d=*b;
*e=*b;
std::cout << (c->remove(488)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
*e=*b;
std::cout << (e->remove(488)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
*d=*d;
std::cout << (e->insert(219)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
d->printPretty();
std::cout << (c->remove(303)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
b->printPretty();
std::cout << (a->remove(300)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
b->printPretty();
std::cout << (b->remove(35)) << std::endl;
e->printPretty();
std::cout << (b->insert(488)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
e->printPretty();
*c=*d;
std::cout << (e->insert(219)) << std::endl;
c->printPretty();
std::cout << (a->insert(182)) << std::endl;
b->printPretty();
std::cout << (b->insert(477)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (c->remove(422)) << std::endl;
a->printPretty();
std::cout << (c->insert(10)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (b->remove(477)) << std::endl;
std::cout << (c->remove(10)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (c->remove(83)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (e->insert(377)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
*d=*a;
std::cout << (e->remove(266)) << std::endl;
d->printPretty();
std::cout << (e->remove(319)) << std::endl;
a->printPretty();
std::cout << (d->insert(330)) << std::endl;
c->printPretty();
std::cout << (e->insert(192)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
d->printPretty();
*c=*e;
e->printPretty();
std::cout << (e->insert(228)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (c->insert(339)) << std::endl;
e->printPretty();
a->printPretty();
d->printPretty();
std::cout << (b->remove(69)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
c->printPretty();
std::cout << (a->insert(124)) << std::endl;
e->printPretty();
std::cout << (d->insert(377)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
c->printPretty();
std::cout << (c->remove(182)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (d->remove(377)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
*b=*c;
std::cout << (c->remove(129)) << std::endl;
*a=*a;
std::cout << (e->remove(57)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
*b=*b;
*c=*c;
std::cout << (d->remove(199)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->remove(66)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(330)) << std::endl;
*c=*c;
*c=*c;
std::cout << (b->insert(7)) << std::endl;
std::cout << (c->remove(66)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
b->printPretty();
std::cout << (b->insert(479)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
a->printPretty();
std::cout << (e->insert(159)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
std::cout << (b->remove(7)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
*b=*e;
std::cout << (e->insert(470)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
*b=*d;
std::cout << (d->insert(373)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
*c=*a;
std::cout << (d->insert(373)) << std::endl;
a->printPretty();
std::cout << (b->remove(182)) << std::endl;
*e=*e;
std::cout << (a->remove(299)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
*c=*e;
std::cout << (b->insert(499)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
*a=*c;
std::cout << (a->insert(75)) << std::endl;
return 0;
}
