#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(428)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
std::cout << (a->remove(428)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(441)) << std::endl;
b->printPretty();
a->printPretty();
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*b=*c;
std::cout << (e->insert(42)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
*d=*a;
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (b->remove(325)) << std::endl;
*d=*e;
*d=*d;
std::cout << (e->remove(239)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (e->insert(42)) << std::endl;
*c=*e;
a->printPretty();
*c=*c;
std::cout << (b->insert(456)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (c->remove(185)) << std::endl;
d->printPretty();
std::cout << (e->insert(369)) << std::endl;
e->printPretty();
std::cout << (e->remove(305)) << std::endl;
c->printPretty();
std::cout << (e->remove(86)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
*b=*c;
std::cout << (a->insert(250)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
*d=*a;
std::cout << (e->insert(107)) << std::endl;
*c=*d;
std::cout << (e->remove(13)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
*c=*c;
std::cout << (a->remove(339)) << std::endl;
*d=*b;
std::cout << (c->insert(283)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
*c=*d;
std::cout << (e->insert(246)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
*a=*a;
std::cout << (b->remove(436)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
d->printPretty();
std::cout << (e->remove(157)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
*d=*d;
std::cout << (e->remove(369)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (a->remove(265)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(265)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (e->insert(319)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
e->printPretty();
std::cout << (d->remove(229)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
a->printPretty();
*b=*d;
e->printPretty();
*c=*d;
a->printPretty();
std::cout << (a->insert(160)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
*d=*a;
std::cout << (c->insert(138)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
*a=*d;
std::cout << (c->insert(51)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
b->printPretty();
std::cout << (c->remove(270)) << std::endl;
std::cout << (d->remove(196)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->insert(364)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
std::cout << (a->remove(26)) << std::endl;
*d=*d;
std::cout << (b->remove(220)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
c->printPretty();
std::cout << (e->remove(19)) << std::endl;
d->printPretty();
std::cout << (d->remove(257)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
d->printPretty();
std::cout << (c->insert(320)) << std::endl;
*d=*d;
std::cout << (d->insert(38)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
*a=*a;
std::cout << (a->remove(91)) << std::endl;
c->printPretty();
std::cout << (d->remove(252)) << std::endl;
*c=*d;
b->printPretty();
*e=*b;
b->printPretty();
std::cout << (c->insert(62)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (d->insert(132)) << std::endl;
a->printPretty();
std::cout << (c->remove(360)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
*d=*a;
std::cout << (d->insert(162)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (e->insert(183)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (e->insert(21)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
a->printPretty();
std::cout << (a->remove(437)) << std::endl;
d->printPretty();
std::cout << (e->insert(183)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
b->printPretty();
std::cout << (e->remove(183)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (e->insert(21)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(8)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
*b=*b;
std::cout << (a->insert(192)) << std::endl;
b->printPretty();
std::cout << (c->insert(132)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
*a=*a;
std::cout << (a->insert(235)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
*b=*c;
*c=*c;
std::cout << (a->insert(67)) << std::endl;
std::cout << (d->insert(268)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
a->printPretty();
std::cout << (c->remove(380)) << std::endl;
std::cout << (d->insert(200)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
*b=*e;
std::cout << (b->remove(21)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
*b=*d;
std::cout << (e->remove(21)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
b->printPretty();
std::cout << (d->remove(200)) << std::endl;
a->printPretty();
std::cout << (a->insert(407)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (e->insert(5)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
d->printPretty();
std::cout << (a->remove(67)) << std::endl;
*b=*c;
std::cout << (b->remove(196)) << std::endl;
*d=*c;
std::cout << (d->insert(162)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (a->insert(407)) << std::endl;
*d=*a;
a->printPretty();
*a=*b;
std::cout << (d->remove(407)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
a->printPretty();
a->printPretty();
*e=*e;
std::cout << (a->insert(26)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (c->insert(89)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*c=*c;
std::cout << (e->insert(127)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->insert(420)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
*b=*c;
std::cout << (b->insert(89)) << std::endl;
*d=*e;
std::cout << (d->remove(464)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
c->printPretty();
std::cout << (c->remove(89)) << std::endl;
*c=*d;
std::cout << (b->insert(50)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
*e=*c;
std::cout << (c->remove(420)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
*d=*c;
std::cout << (e->insert(87)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
*c=*a;
std::cout << (b->insert(254)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (d->remove(150)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (a->remove(100)) << std::endl;
*a=*a;
std::cout << (d->insert(111)) << std::endl;
*e=*e;
std::cout << (d->insert(265)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
*a=*a;
std::cout << (b->insert(225)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (e->remove(406)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(128)) << std::endl;
std::cout << (a->insert(26)) << std::endl;
a->printPretty();
std::cout << (d->insert(392)) << std::endl;
*d=*d;
std::cout << (e->remove(158)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
d->printPretty();
std::cout << (e->remove(230)) << std::endl;
*e=*a;
std::cout << (a->insert(243)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
*b=*e;
std::cout << (a->remove(268)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (e->remove(402)) << std::endl;
std::cout << (a->insert(26)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
std::cout << (c->remove(26)) << std::endl;
std::cout << (b->insert(159)) << std::endl;
d->printPretty();
std::cout << (a->remove(171)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
*e=*c;
std::cout << (c->remove(268)) << std::endl;
c->printPretty();
b->printPretty();
e->printPretty();
std::cout << (b->remove(238)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
*b=*c;
*e=*a;
std::cout << (d->insert(312)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
d->printPretty();
std::cout << (c->insert(471)) << std::endl;
*b=*c;
e->printPretty();
std::cout << (a->insert(469)) << std::endl;
*c=*d;
std::cout << (a->remove(26)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
c->printPretty();
std::cout << (b->insert(385)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
*c=*b;
std::cout << (c->remove(472)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
c->printPretty();
std::cout << (d->insert(161)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->insert(408)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (a->insert(432)) << std::endl;
*e=*d;
std::cout << (b->insert(187)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
c->printPretty();
std::cout << (d->insert(142)) << std::endl;
std::cout << (e->remove(222)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (d->remove(203)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
a->printPretty();
std::cout << (b->insert(385)) << std::endl;
std::cout << (b->insert(455)) << std::endl;
*c=*c;
std::cout << (d->insert(127)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
d->printPretty();
std::cout << (e->insert(48)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
b->printPretty();
std::cout << (e->remove(306)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (a->remove(249)) << std::endl;
d->printPretty();
std::cout << (e->insert(23)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
*c=*c;
*d=*e;
std::cout << (e->remove(284)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
e->printPretty();
std::cout << (b->insert(234)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
*e=*e;
std::cout << (c->remove(48)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (d->insert(23)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
e->printPretty();
std::cout << (b->remove(130)) << std::endl;
d->printPretty();
std::cout << (d->insert(33)) << std::endl;
e->printPretty();
std::cout << (b->remove(399)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
*a=*e;
std::cout << (d->insert(48)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (e->remove(30)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
std::cout << (d->insert(48)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (a->remove(230)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
*e=*e;
*a=*a;
std::cout << (e->remove(417)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
a->printPretty();
*e=*c;
*a=*b;
std::cout << (a->remove(340)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (d->remove(12)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (c->remove(496)) << std::endl;
b->printPretty();
std::cout << (c->remove(7)) << std::endl;
*d=*a;
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->remove(471)) << std::endl;
d->printPretty();
std::cout << (e->insert(258)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
*e=*b;
*e=*e;
std::cout << (c->insert(106)) << std::endl;
e->printPretty();
std::cout << (a->insert(406)) << std::endl;
std::cout << (a->remove(455)) << std::endl;
e->printPretty();
std::cout << (a->insert(48)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
*c=*c;
*c=*c;
std::cout << (d->remove(489)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
std::cout << (d->insert(187)) << std::endl;
d->printPretty();
std::cout << (d->insert(122)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
std::cout << (c->remove(63)) << std::endl;
c->printPretty();
e->printPretty();
*c=*e;
*a=*d;
std::cout << (a->insert(210)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
*b=*a;
*a=*a;
std::cout << (d->insert(312)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(471)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
*e=*a;
std::cout << (d->insert(462)) << std::endl;
*e=*b;
*e=*e;
std::cout << (b->insert(482)) << std::endl;
a->printPretty();
std::cout << (d->remove(114)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (a->remove(430)) << std::endl;
*d=*d;
std::cout << (d->insert(439)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
*b=*c;
std::cout << (a->insert(122)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
*b=*d;
d->printPretty();
b->printPretty();
a->printPretty();
d->printPretty();
std::cout << (c->remove(48)) << std::endl;
*e=*e;
*c=*b;
*a=*a;
std::cout << (b->insert(469)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (a->insert(187)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
std::cout << (b->remove(217)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
b->printPretty();
std::cout << (a->remove(285)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
*d=*a;
*b=*b;
std::cout << (c->remove(74)) << std::endl;
*e=*c;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
d->printPretty();
std::cout << (a->insert(280)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
*c=*e;
std::cout << (d->insert(72)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
*b=*a;
std::cout << (c->insert(241)) << std::endl;
*a=*b;
*a=*d;
std::cout << (d->insert(98)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
std::cout << (d->insert(268)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
*a=*c;
std::cout << (b->insert(286)) << std::endl;
*e=*d;
std::cout << (c->remove(300)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
*d=*c;
*c=*b;
std::cout << (e->insert(187)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
*c=*b;
std::cout << (e->insert(51)) << std::endl;
std::cout << (b->remove(249)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (a->remove(455)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (e->remove(257)) << std::endl;
std::cout << (a->insert(472)) << std::endl;
std::cout << (e->insert(367)) << std::endl;
*e=*e;
std::cout << (e->insert(268)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
*e=*d;
std::cout << (a->remove(462)) << std::endl;
std::cout << (a->insert(363)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (a->insert(115)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
*c=*d;
std::cout << (e->insert(286)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
*b=*b;
std::cout << (c->remove(257)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
*e=*d;
*b=*c;
std::cout << (c->remove(8)) << std::endl;
b->printPretty();
std::cout << (c->insert(23)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (c->remove(196)) << std::endl;
std::cout << (e->remove(469)) << std::endl;
a->printPretty();
std::cout << (c->insert(274)) << std::endl;
*c=*d;
std::cout << (c->remove(187)) << std::endl;
*e=*c;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
d->printPretty();
std::cout << (d->remove(274)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (d->insert(270)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
d->printPretty();
std::cout << (c->remove(280)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (c->insert(210)) << std::endl;
std::cout << (e->insert(48)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
*a=*d;
std::cout << (a->insert(373)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
*d=*e;
a->printPretty();
b->printPretty();
std::cout << (d->insert(48)) << std::endl;
std::cout << (a->remove(446)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (e->insert(267)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
*d=*d;
std::cout << (d->insert(257)) << std::endl;
a->printPretty();
std::cout << (d->remove(280)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (a->insert(225)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (b->insert(469)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
*c=*a;
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
return 0;
}
