#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
*b=*a;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*b=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (c->remove(290)) << std::endl;
*b=*c;
std::cout << (b->remove(67)) << std::endl;
b->printPretty();
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
*e=*a;
*c=*e;
c->printPretty();
d->printPretty();
b->printPretty();
std::cout << (d->remove(262)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
*b=*d;
*b=*d;
std::cout << (e->insert(427)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
*d=*b;
std::cout << (c->remove(499)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
std::cout << (c->remove(165)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->insert(359)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
c->printPretty();
std::cout << (a->insert(406)) << std::endl;
*d=*b;
std::cout << (d->remove(112)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
*e=*b;
std::cout << (c->insert(317)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
c->printPretty();
std::cout << (c->remove(109)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (b->insert(460)) << std::endl;
std::cout << (d->remove(483)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
*a=*d;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
c->printPretty();
std::cout << (b->remove(460)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (c->insert(317)) << std::endl;
std::cout << (c->insert(317)) << std::endl;
*c=*e;
std::cout << (a->remove(427)) << std::endl;
e->printPretty();
std::cout << (d->insert(76)) << std::endl;
c->printPretty();
std::cout << (a->remove(171)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (b->insert(76)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
d->printPretty();
std::cout << (e->insert(358)) << std::endl;
std::cout << (e->insert(358)) << std::endl;
e->printPretty();
std::cout << (c->insert(317)) << std::endl;
*b=*c;
*d=*a;
std::cout << (a->insert(274)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (c->insert(459)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
*d=*d;
std::cout << (d->insert(199)) << std::endl;
c->printPretty();
c->printPretty();
*e=*a;
std::cout << (c->remove(212)) << std::endl;
e->printPretty();
std::cout << (c->remove(296)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (d->insert(199)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
d->printPretty();
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (e->insert(274)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
a->printPretty();
std::cout << (d->insert(406)) << std::endl;
*e=*a;
std::cout << (d->insert(218)) << std::endl;
e->printPretty();
e->printPretty();
a->printPretty();
*a=*d;
*e=*e;
std::cout << (c->insert(459)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->insert(459)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
d->printPretty();
std::cout << (b->remove(130)) << std::endl;
std::cout << (a->insert(199)) << std::endl;
e->printPretty();
a->printPretty();
b->printPretty();
std::cout << (b->remove(296)) << std::endl;
*a=*a;
std::cout << (a->insert(406)) << std::endl;
*c=*e;
*d=*d;
std::cout << (b->remove(459)) << std::endl;
*c=*b;
*b=*d;
std::cout << (a->insert(295)) << std::endl;
*c=*b;
std::cout << (a->insert(295)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (d->remove(303)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (a->insert(199)) << std::endl;
*e=*c;
std::cout << (e->insert(366)) << std::endl;
c->printPretty();
std::cout << (e->insert(406)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (d->remove(64)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(377)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
std::cout << (e->remove(366)) << std::endl;
d->printPretty();
std::cout << (d->insert(377)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
a->printPretty();
std::cout << (d->insert(398)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
e->printPretty();
std::cout << (d->insert(468)) << std::endl;
*b=*a;
std::cout << (c->insert(199)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->remove(218)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (c->insert(199)) << std::endl;
std::cout << (c->remove(17)) << std::endl;
std::cout << (d->remove(377)) << std::endl;
std::cout << (a->insert(43)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
*c=*e;
std::cout << (a->insert(218)) << std::endl;
e->printPretty();
std::cout << (d->remove(486)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (c->remove(227)) << std::endl;
*b=*b;
std::cout << (c->remove(482)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
*a=*c;
std::cout << (d->insert(48)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
*e=*d;
std::cout << (d->insert(406)) << std::endl;
std::cout << (e->insert(81)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (b->remove(269)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (b->insert(412)) << std::endl;
b->printPretty();
std::cout << (b->insert(412)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (d->remove(214)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
*a=*a;
*c=*e;
std::cout << (d->insert(368)) << std::endl;
d->printPretty();
d->printPretty();
e->printPretty();
std::cout << (a->remove(325)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
a->printPretty();
*b=*c;
*b=*d;
std::cout << (d->remove(227)) << std::endl;
std::cout << (d->insert(398)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
std::cout << (a->insert(187)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (e->insert(76)) << std::endl;
*e=*d;
std::cout << (c->insert(368)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (a->insert(405)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (b->insert(250)) << std::endl;
*e=*a;
b->printPretty();
*e=*b;
std::cout << (a->insert(31)) << std::endl;
*d=*b;
std::cout << (a->remove(345)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
d->printPretty();
std::cout << (a->remove(31)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
*c=*b;
*e=*a;
std::cout << (c->insert(368)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
*c=*e;
std::cout << (c->remove(472)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (c->insert(477)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->insert(19)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
e->printPretty();
std::cout << (b->remove(19)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
e->printPretty();
std::cout << (c->remove(375)) << std::endl;
std::cout << (c->insert(185)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
*e=*b;
std::cout << (d->remove(154)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
a->printPretty();
c->printPretty();
*d=*d;
std::cout << (b->insert(359)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
*a=*b;
std::cout << (a->remove(406)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
*d=*e;
*e=*d;
*e=*d;
a->printPretty();
std::cout << (b->insert(18)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
c->printPretty();
std::cout << (e->remove(368)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (a->remove(303)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
e->printPretty();
std::cout << (e->remove(39)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (c->insert(5)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
std::cout << (a->insert(413)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (e->insert(28)) << std::endl;
d->printPretty();
a->printPretty();
d->printPretty();
a->printPretty();
std::cout << (a->insert(492)) << std::endl;
b->printPretty();
std::cout << (c->remove(395)) << std::endl;
std::cout << (c->remove(468)) << std::endl;
std::cout << (a->remove(61)) << std::endl;
std::cout << (b->remove(393)) << std::endl;
e->printPretty();
a->printPretty();
*e=*e;
std::cout << (d->insert(218)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
e->printPretty();
std::cout << (a->insert(492)) << std::endl;
*a=*a;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
*e=*b;
std::cout << (a->insert(368)) << std::endl;
*a=*d;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->remove(61)) << std::endl;
*c=*e;
std::cout << (a->remove(42)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
e->printPretty();
std::cout << (b->insert(370)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (b->insert(170)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (d->insert(411)) << std::endl;
*b=*d;
std::cout << (a->remove(66)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
std::cout << (b->remove(335)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
a->printPretty();
std::cout << (d->insert(440)) << std::endl;
*a=*a;
*e=*d;
std::cout << (e->insert(406)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(154)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
std::cout << (b->insert(423)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
a->printPretty();
std::cout << (d->insert(28)) << std::endl;
*c=*d;
std::cout << (b->insert(395)) << std::endl;
b->printPretty();
std::cout << (b->insert(423)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
a->printPretty();
std::cout << (e->remove(406)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
std::cout << (c->remove(211)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
std::cout << (d->remove(440)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
*c=*c;
std::cout << (c->insert(335)) << std::endl;
*b=*e;
std::cout << (c->insert(4)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
std::cout << (b->insert(424)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
c->printPretty();
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (a->insert(315)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
*c=*e;
*d=*c;
std::cout << (a->insert(250)) << std::endl;
c->printPretty();
std::cout << (d->insert(469)) << std::endl;
std::cout << (e->insert(380)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (d->insert(203)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
std::cout << (c->insert(446)) << std::endl;
std::cout << (a->insert(315)) << std::endl;
*b=*b;
std::cout << (b->remove(411)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (b->insert(424)) << std::endl;
*e=*e;
std::cout << (d->insert(142)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->remove(4)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
d->printPretty();
std::cout << (b->insert(432)) << std::endl;
d->printPretty();
std::cout << (d->insert(340)) << std::endl;
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (e->insert(395)) << std::endl;
*a=*d;
std::cout << (b->remove(368)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
*c=*c;
*c=*c;
c->printPretty();
e->printPretty();
std::cout << (d->insert(142)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
*c=*d;
*d=*c;
std::cout << (d->insert(216)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (e->remove(151)) << std::endl;
*a=*e;
std::cout << (a->remove(24)) << std::endl;
*d=*b;
std::cout << (c->insert(251)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
*c=*c;
std::cout << (b->remove(326)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
d->printPretty();
std::cout << (e->remove(395)) << std::endl;
c->printPretty();
std::cout << (b->remove(326)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (a->insert(373)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
a->printPretty();
std::cout << (e->remove(492)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->remove(218)) << std::endl;
*c=*c;
std::cout << (b->insert(432)) << std::endl;
*a=*b;
std::cout << (d->insert(440)) << std::endl;
*a=*e;
e->printPretty();
*b=*d;
std::cout << (e->insert(129)) << std::endl;
d->printPretty();
std::cout << (e->remove(323)) << std::endl;
*a=*b;
std::cout << (c->remove(220)) << std::endl;
c->printPretty();
std::cout << (c->remove(4)) << std::endl;
std::cout << (c->insert(400)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (c->remove(436)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (d->remove(432)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
*c=*a;
std::cout << (a->remove(32)) << std::endl;
std::cout << (d->remove(440)) << std::endl;
std::cout << (c->insert(319)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
*b=*c;
std::cout << (b->remove(319)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (b->remove(446)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(306)) << std::endl;
std::cout << (d->insert(314)) << std::endl;
*c=*a;
*d=*e;
std::cout << (b->insert(310)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
*b=*b;
std::cout << (b->remove(432)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (d->insert(306)) << std::endl;
*c=*c;
std::cout << (a->insert(51)) << std::endl;
a->printPretty();
std::cout << (c->remove(58)) << std::endl;
e->printPretty();
a->printPretty();
*e=*e;
*b=*b;
d->printPretty();
std::cout << (b->insert(250)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
std::cout << (a->remove(237)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (d->remove(306)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
*e=*e;
std::cout << (e->insert(129)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (d->remove(411)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
d->printPretty();
std::cout << (b->remove(280)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
b->printPretty();
std::cout << (b->remove(137)) << std::endl;
*c=*b;
std::cout << (c->insert(226)) << std::endl;
*d=*c;
a->printPretty();
*d=*d;
std::cout << (d->insert(335)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
*a=*e;
std::cout << (e->insert(446)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (e->remove(381)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
d->printPretty();
std::cout << (d->insert(294)) << std::endl;
std::cout << (c->insert(25)) << std::endl;
b->printPretty();
*e=*c;
c->printPretty();
std::cout << (d->remove(335)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
c->printPretty();
std::cout << (e->insert(484)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (a->insert(99)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
a->printPretty();
*b=*a;
*b=*d;
std::cout << (d->insert(57)) << std::endl;
std::cout << (b->remove(424)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (d->insert(216)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
c->printPretty();
b->printPretty();
*d=*e;
std::cout << (d->remove(192)) << std::endl;
*d=*e;
std::cout << (c->insert(463)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
d->printPretty();
*d=*a;
*c=*d;
*c=*b;
std::cout << (d->insert(306)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
*d=*b;
*e=*b;
std::cout << (c->remove(250)) << std::endl;
*d=*a;
*a=*c;
std::cout << (c->insert(260)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
c->printPretty();
std::cout << (d->insert(250)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
*c=*d;
*c=*a;
std::cout << (b->insert(261)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (c->insert(165)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
b->printPretty();
std::cout << (a->remove(328)) << std::endl;
*d=*d;
std::cout << (c->remove(440)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(411)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
*c=*e;
std::cout << (a->insert(308)) << std::endl;
*c=*b;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(446)) << std::endl;
std::cout << (d->insert(308)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
d->printPretty();
std::cout << (a->insert(154)) << std::endl;
std::cout << (d->remove(411)) << std::endl;
d->printPretty();
std::cout << (a->remove(446)) << std::endl;
return 0;
}
