#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
a->printPretty();
std::cout << (a->insert(256)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(213)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
a->printPretty();
std::cout << (a->remove(280)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
std::cout << (a->insert(328)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
*a=*a;
std::cout << (b->remove(399)) << std::endl;
std::cout << (b->insert(491)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
e->printPretty();
std::cout << (a->insert(220)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
*b=*b;
std::cout << (a->insert(254)) << std::endl;
a->printPretty();
std::cout << (e->insert(128)) << std::endl;
*b=*c;
std::cout << (e->remove(491)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
b->printPretty();
std::cout << (a->remove(330)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (a->insert(314)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
d->printPretty();
std::cout << (e->remove(128)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
d->printPretty();
*b=*a;
c->printPretty();
d->printPretty();
*e=*e;
std::cout << (b->insert(495)) << std::endl;
*a=*e;
std::cout << (a->remove(220)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
*d=*e;
std::cout << (b->remove(104)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (b->insert(495)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (a->insert(314)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->insert(47)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
d->printPretty();
a->printPretty();
c->printPretty();
a->printPretty();
*b=*a;
std::cout << (a->insert(128)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
c->printPretty();
std::cout << (b->insert(442)) << std::endl;
std::cout << (a->insert(314)) << std::endl;
a->printPretty();
std::cout << (e->insert(47)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (e->insert(25)) << std::endl;
std::cout << (e->remove(305)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
std::cout << (a->insert(290)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
*d=*d;
*a=*c;
std::cout << (e->insert(145)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(59)) << std::endl;
*d=*b;
std::cout << (a->remove(207)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (a->insert(59)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
a->printPretty();
std::cout << (a->insert(161)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
*e=*a;
std::cout << (c->insert(161)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (c->remove(74)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (a->remove(59)) << std::endl;
std::cout << (e->insert(59)) << std::endl;
*c=*c;
std::cout << (a->insert(140)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (a->insert(407)) << std::endl;
std::cout << (e->remove(59)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
std::cout << (c->insert(232)) << std::endl;
c->printPretty();
std::cout << (e->insert(393)) << std::endl;
*e=*a;
std::cout << (d->insert(307)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
a->printPretty();
std::cout << (a->remove(140)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
*a=*c;
std::cout << (a->remove(301)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (b->insert(495)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
*e=*b;
*a=*c;
std::cout << (b->insert(7)) << std::endl;
*a=*c;
std::cout << (d->insert(189)) << std::endl;
a->printPretty();
std::cout << (d->insert(195)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
*b=*e;
std::cout << (a->insert(239)) << std::endl;
*b=*a;
*c=*e;
std::cout << (b->insert(239)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
*b=*e;
std::cout << (c->remove(495)) << std::endl;
d->printPretty();
std::cout << (a->insert(211)) << std::endl;
*b=*e;
*a=*e;
std::cout << (a->remove(7)) << std::endl;
*a=*d;
std::cout << (e->remove(495)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
e->printPretty();
std::cout << (d->remove(446)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*e=*d;
std::cout << (e->insert(149)) << std::endl;
*b=*c;
std::cout << (e->insert(495)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
d->printPretty();
std::cout << (d->remove(364)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->insert(4)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
*c=*d;
*a=*b;
d->printPretty();
e->printPretty();
std::cout << (c->remove(168)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (d->insert(144)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
e->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
*a=*a;
*a=*e;
d->printPretty();
d->printPretty();
std::cout << (c->remove(149)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (b->remove(260)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
a->printPretty();
std::cout << (b->remove(7)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (c->insert(372)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->remove(83)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
*b=*b;
std::cout << (e->insert(195)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
e->printPretty();
std::cout << (b->insert(56)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(309)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
*b=*d;
std::cout << (a->insert(392)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (d->remove(364)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(126)) << std::endl;
e->printPretty();
*b=*c;
a->printPretty();
*a=*e;
std::cout << (d->insert(364)) << std::endl;
*e=*d;
*c=*c;
std::cout << (e->insert(400)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (c->insert(307)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->remove(400)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
b->printPretty();
std::cout << (c->insert(95)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->insert(149)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
e->printPretty();
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
d->printPretty();
std::cout << (d->remove(120)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
a->printPretty();
std::cout << (c->remove(95)) << std::endl;
std::cout << (c->remove(396)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
c->printPretty();
std::cout << (a->remove(266)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
*c=*a;
std::cout << (b->insert(490)) << std::endl;
std::cout << (e->insert(117)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
*d=*d;
std::cout << (b->remove(434)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
*c=*e;
std::cout << (b->remove(38)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
*d=*d;
std::cout << (a->remove(149)) << std::endl;
d->printPretty();
std::cout << (c->insert(117)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
*b=*d;
*d=*e;
std::cout << (c->insert(41)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
e->printPretty();
std::cout << (d->insert(25)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (e->insert(263)) << std::endl;
*b=*e;
std::cout << (a->insert(332)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
*a=*b;
std::cout << (d->remove(205)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
std::cout << (b->remove(263)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (c->insert(41)) << std::endl;
a->printPretty();
std::cout << (c->insert(12)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
d->printPretty();
std::cout << (a->insert(372)) << std::endl;
std::cout << (b->insert(99)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (c->remove(195)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (e->remove(80)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
e->printPretty();
c->printPretty();
*a=*d;
std::cout << (d->remove(283)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
c->printPretty();
std::cout << (b->insert(450)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
std::cout << (c->insert(12)) << std::endl;
*d=*e;
std::cout << (b->insert(92)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
c->printPretty();
std::cout << (e->insert(117)) << std::endl;
*e=*c;
std::cout << (b->remove(99)) << std::endl;
a->printPretty();
std::cout << (b->remove(409)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
a->printPretty();
std::cout << (d->remove(64)) << std::endl;
*e=*d;
*b=*d;
std::cout << (a->remove(495)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
std::cout << (e->insert(495)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
e->printPretty();
std::cout << (c->insert(429)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(195)) << std::endl;
std::cout << (b->remove(433)) << std::endl;
std::cout << (c->insert(117)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
std::cout << (b->remove(26)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (c->remove(223)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
*e=*c;
std::cout << (a->remove(384)) << std::endl;
std::cout << (a->insert(244)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
d->printPretty();
std::cout << (d->insert(386)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (b->insert(372)) << std::endl;
e->printPretty();
std::cout << (e->remove(123)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
c->printPretty();
std::cout << (b->remove(381)) << std::endl;
std::cout << (c->insert(12)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (a->insert(346)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
std::cout << (b->remove(263)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
e->printPretty();
std::cout << (d->remove(7)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (c->insert(266)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
*c=*c;
std::cout << (d->remove(271)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (b->remove(41)) << std::endl;
*d=*e;
std::cout << (c->insert(41)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
c->printPretty();
std::cout << (e->remove(386)) << std::endl;
std::cout << (d->remove(303)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
d->printPretty();
std::cout << (c->insert(19)) << std::endl;
d->printPretty();
std::cout << (b->remove(307)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (a->insert(384)) << std::endl;
a->printPretty();
std::cout << (a->insert(406)) << std::endl;
std::cout << (e->remove(429)) << std::endl;
a->printPretty();
std::cout << (d->insert(444)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->remove(189)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
std::cout << (e->insert(337)) << std::endl;
*c=*b;
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
d->printPretty();
*e=*b;
*b=*c;
std::cout << (a->insert(25)) << std::endl;
std::cout << (b->insert(374)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->remove(374)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (e->insert(117)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
*d=*e;
*d=*d;
std::cout << (e->insert(495)) << std::endl;
e->printPretty();
std::cout << (e->insert(92)) << std::endl;
std::cout << (b->remove(495)) << std::endl;
*a=*d;
*e=*d;
std::cout << (a->insert(5)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
e->printPretty();
std::cout << (d->insert(350)) << std::endl;
std::cout << (d->remove(271)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
*c=*e;
c->printPretty();
*b=*e;
*b=*a;
std::cout << (b->remove(86)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
*b=*e;
*c=*a;
std::cout << (b->remove(266)) << std::endl;
std::cout << (a->insert(271)) << std::endl;
*c=*a;
std::cout << (a->insert(108)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
d->printPretty();
*d=*a;
e->printPretty();
e->printPretty();
std::cout << (e->insert(86)) << std::endl;
b->printPretty();
std::cout << (c->insert(251)) << std::endl;
a->printPretty();
a->printPretty();
*e=*d;
std::cout << (e->remove(371)) << std::endl;
std::cout << (b->insert(88)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
*e=*d;
std::cout << (b->remove(92)) << std::endl;
*a=*d;
std::cout << (a->insert(7)) << std::endl;
b->printPretty();
std::cout << (d->insert(400)) << std::endl;
b->printPretty();
std::cout << (d->insert(92)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (a->remove(495)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
*d=*d;
std::cout << (e->insert(495)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
d->printPretty();
std::cout << (b->remove(495)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
std::cout << (e->remove(475)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(5)) << std::endl;
*e=*c;
*e=*a;
*a=*e;
std::cout << (c->remove(232)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->insert(5)) << std::endl;
*c=*d;
*b=*b;
std::cout << (c->insert(495)) << std::endl;
d->printPretty();
*d=*b;
e->printPretty();
std::cout << (c->insert(466)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
*d=*c;
std::cout << (e->insert(271)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->insert(7)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
c->printPretty();
std::cout << (e->insert(7)) << std::endl;
std::cout << (d->remove(372)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
d->printPretty();
std::cout << (a->insert(86)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
c->printPretty();
std::cout << (a->remove(108)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
d->printPretty();
*c=*c;
e->printPretty();
e->printPretty();
std::cout << (a->insert(86)) << std::endl;
*c=*d;
*e=*a;
std::cout << (d->remove(254)) << std::endl;
a->printPretty();
*e=*b;
*d=*c;
*a=*e;
*e=*a;
std::cout << (b->remove(372)) << std::endl;
*a=*e;
std::cout << (d->insert(108)) << std::endl;
e->printPretty();
a->printPretty();
*d=*a;
std::cout << (b->insert(429)) << std::endl;
*d=*a;
*c=*e;
std::cout << (d->remove(14)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (a->insert(466)) << std::endl;
*d=*e;
*b=*c;
*c=*a;
std::cout << (d->remove(376)) << std::endl;
c->printPretty();
std::cout << (b->insert(86)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (c->insert(427)) << std::endl;
e->printPretty();
std::cout << (a->insert(271)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (d->remove(424)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (d->insert(7)) << std::endl;
*b=*a;
*e=*b;
b->printPretty();
std::cout << (a->remove(372)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
a->printPretty();
std::cout << (c->insert(142)) << std::endl;
*a=*d;
std::cout << (c->remove(117)) << std::endl;
*a=*b;
std::cout << (b->insert(7)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
*d=*c;
std::cout << (d->insert(74)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (a->insert(428)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
*e=*e;
std::cout << (d->insert(489)) << std::endl;
*e=*c;
std::cout << (a->insert(167)) << std::endl;
std::cout << (a->insert(16)) << std::endl;
*c=*b;
d->printPretty();
e->printPretty();
std::cout << (e->remove(427)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
*c=*e;
*b=*c;
*e=*e;
std::cout << (c->remove(139)) << std::endl;
b->printPretty();
*c=*a;
*a=*e;
d->printPretty();
std::cout << (a->remove(142)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->remove(7)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
*b=*a;
std::cout << (b->remove(88)) << std::endl;
a->printPretty();
d->printPretty();
d->printPretty();
std::cout << (c->insert(86)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (e->insert(398)) << std::endl;
std::cout << (e->insert(317)) << std::endl;
std::cout << (d->insert(316)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (b->insert(250)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
*a=*b;
*a=*d;
*b=*c;
std::cout << (b->insert(90)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (b->remove(368)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (a->insert(142)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
c->printPretty();
std::cout << (b->remove(7)) << std::endl;
c->printPretty();
std::cout << (e->insert(138)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
return 0;
}
