#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(232)) << std::endl;
std::cout << (a->insert(371)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(279)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (a->insert(371)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(105)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(405)) << std::endl;
std::cout << (c->insert(96)) << std::endl;
*b=*a;
*a=*c;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (c->insert(96)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
a->printPretty();
b->printPretty();
c->printPretty();
std::cout << (e->remove(452)) << std::endl;
std::cout << (c->insert(96)) << std::endl;
*c=*b;
std::cout << (a->remove(19)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
*c=*d;
*b=*e;
b->printPretty();
std::cout << (d->insert(33)) << std::endl;
std::cout << (b->insert(203)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (c->insert(28)) << std::endl;
*c=*d;
std::cout << (d->insert(33)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
*b=*a;
*d=*b;
*b=*e;
*a=*a;
std::cout << (d->insert(442)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
*d=*a;
std::cout << (e->remove(226)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
std::cout << (d->insert(432)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
e->printPretty();
std::cout << (d->insert(36)) << std::endl;
std::cout << (b->insert(67)) << std::endl;
std::cout << (b->remove(67)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
*b=*e;
std::cout << (d->remove(486)) << std::endl;
std::cout << (d->remove(432)) << std::endl;
b->printPretty();
b->printPretty();
*e=*c;
std::cout << (b->insert(50)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
b->printPretty();
std::cout << (c->remove(196)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
*b=*d;
*c=*b;
e->printPretty();
*d=*b;
std::cout << (b->insert(89)) << std::endl;
e->printPretty();
std::cout << (c->insert(104)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (b->insert(237)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
*e=*c;
c->printPretty();
*b=*c;
std::cout << (b->insert(104)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
d->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
std::cout << (a->insert(83)) << std::endl;
*c=*a;
*b=*d;
std::cout << (d->remove(80)) << std::endl;
*b=*b;
a->printPretty();
b->printPretty();
std::cout << (e->remove(36)) << std::endl;
e->printPretty();
d->printPretty();
*a=*c;
a->printPretty();
*e=*a;
std::cout << (e->remove(130)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
*b=*a;
*c=*d;
*b=*d;
*a=*c;
e->printPretty();
*c=*a;
d->printPretty();
c->printPretty();
std::cout << (e->remove(66)) << std::endl;
c->printPretty();
std::cout << (c->insert(495)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
*c=*a;
std::cout << (a->remove(400)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
*b=*b;
std::cout << (c->insert(68)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (d->insert(155)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(29)) << std::endl;
*b=*a;
std::cout << (d->insert(68)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
*a=*d;
*d=*a;
std::cout << (a->remove(311)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
*e=*d;
std::cout << (d->remove(104)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
*b=*b;
std::cout << (c->insert(68)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
c->printPretty();
*d=*e;
std::cout << (b->remove(94)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (b->insert(313)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
*a=*e;
std::cout << (c->insert(36)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
*d=*d;
std::cout << (a->insert(425)) << std::endl;
*c=*b;
std::cout << (e->remove(146)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
*e=*c;
std::cout << (c->remove(12)) << std::endl;
std::cout << (c->remove(104)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
b->printPretty();
std::cout << (a->insert(335)) << std::endl;
std::cout << (e->remove(313)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (e->remove(281)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (a->insert(203)) << std::endl;
*d=*e;
std::cout << (a->insert(6)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (c->remove(313)) << std::endl;
a->printPretty();
std::cout << (b->insert(465)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (e->insert(455)) << std::endl;
*c=*d;
std::cout << (a->remove(155)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
*c=*d;
std::cout << (b->insert(386)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (e->insert(144)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (d->remove(83)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
b->printPretty();
a->printPretty();
*a=*d;
*d=*e;
std::cout << (e->insert(144)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
*d=*e;
std::cout << (a->remove(360)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (b->remove(419)) << std::endl;
*d=*e;
e->printPretty();
a->printPretty();
*e=*d;
e->printPretty();
std::cout << (b->insert(36)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (a->insert(210)) << std::endl;
c->printPretty();
std::cout << (e->remove(381)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
d->printPretty();
e->printPretty();
*d=*d;
std::cout << (a->remove(305)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (d->insert(37)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
e->printPretty();
std::cout << (e->insert(420)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (d->insert(433)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
*c=*e;
std::cout << (a->insert(479)) << std::endl;
*d=*d;
*e=*d;
std::cout << (c->insert(466)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
*a=*a;
std::cout << (b->insert(325)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (b->insert(451)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
std::cout << (e->remove(37)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (d->insert(433)) << std::endl;
std::cout << (a->insert(191)) << std::endl;
*d=*b;
std::cout << (e->remove(455)) << std::endl;
*e=*d;
std::cout << (e->insert(447)) << std::endl;
std::cout << (d->remove(465)) << std::endl;
std::cout << (c->insert(210)) << std::endl;
b->printPretty();
std::cout << (d->remove(402)) << std::endl;
e->printPretty();
std::cout << (c->remove(479)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (c->remove(104)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
*e=*a;
d->printPretty();
e->printPretty();
std::cout << (e->insert(465)) << std::endl;
e->printPretty();
std::cout << (d->remove(330)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
*e=*b;
std::cout << (b->insert(113)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
e->printPretty();
std::cout << (a->remove(84)) << std::endl;
std::cout << (c->remove(220)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
a->printPretty();
std::cout << (d->remove(451)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*c=*c;
std::cout << (d->remove(429)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (d->insert(466)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(113)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
e->printPretty();
std::cout << (b->insert(439)) << std::endl;
c->printPretty();
std::cout << (b->insert(439)) << std::endl;
*b=*e;
std::cout << (d->remove(150)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (d->insert(466)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (a->insert(362)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
*c=*b;
*a=*a;
std::cout << (c->remove(105)) << std::endl;
b->printPretty();
std::cout << (a->insert(451)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(119)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
c->printPretty();
std::cout << (c->remove(428)) << std::endl;
c->printPretty();
std::cout << (a->remove(183)) << std::endl;
*c=*e;
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
*d=*e;
*b=*a;
std::cout << (c->insert(383)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
d->printPretty();
std::cout << (b->insert(413)) << std::endl;
std::cout << (c->insert(383)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
b->printPretty();
std::cout << (a->insert(447)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->insert(393)) << std::endl;
std::cout << (e->remove(423)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
d->printPretty();
*c=*c;
*e=*b;
std::cout << (e->insert(191)) << std::endl;
std::cout << (a->insert(101)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
*a=*a;
*e=*c;
std::cout << (b->insert(439)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (d->insert(61)) << std::endl;
*b=*a;
std::cout << (a->insert(386)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
c->printPretty();
*a=*d;
*a=*a;
d->printPretty();
a->printPretty();
std::cout << (d->insert(483)) << std::endl;
*b=*b;
std::cout << (b->insert(494)) << std::endl;
std::cout << (d->remove(83)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
d->printPretty();
std::cout << (e->remove(118)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
b->printPretty();
std::cout << (c->insert(446)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
e->printPretty();
std::cout << (d->insert(394)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(85)) << std::endl;
*d=*d;
std::cout << (c->insert(131)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (a->insert(212)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
d->printPretty();
std::cout << (e->insert(439)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
*c=*b;
std::cout << (c->insert(444)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (e->remove(350)) << std::endl;
*d=*b;
std::cout << (d->remove(147)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
*d=*d;
std::cout << (e->remove(451)) << std::endl;
*b=*a;
std::cout << (e->insert(194)) << std::endl;
*b=*b;
*a=*c;
std::cout << (c->remove(444)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
*d=*e;
*b=*c;
*e=*a;
std::cout << (d->insert(386)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
*a=*d;
std::cout << (d->remove(383)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
*c=*a;
*d=*d;
*b=*c;
std::cout << (c->insert(166)) << std::endl;
std::cout << (d->remove(418)) << std::endl;
e->printPretty();
std::cout << (c->insert(166)) << std::endl;
std::cout << (c->insert(344)) << std::endl;
std::cout << (d->insert(138)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->remove(194)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
*e=*d;
std::cout << (b->insert(318)) << std::endl;
*b=*b;
std::cout << (c->remove(274)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
*b=*c;
std::cout << (c->insert(383)) << std::endl;
c->printPretty();
std::cout << (d->insert(138)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
d->printPretty();
*c=*c;
*d=*c;
std::cout << (a->insert(163)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
*d=*b;
*c=*d;
std::cout << (d->remove(386)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
b->printPretty();
std::cout << (b->remove(344)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
*b=*a;
*c=*d;
std::cout << (c->remove(383)) << std::endl;
std::cout << (c->remove(83)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
*e=*b;
std::cout << (c->insert(466)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
d->printPretty();
std::cout << (d->remove(163)) << std::endl;
*b=*a;
std::cout << (b->remove(420)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (d->insert(105)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->remove(376)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
b->printPretty();
std::cout << (e->insert(166)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (c->remove(439)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
std::cout << (e->insert(324)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (a->insert(166)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
d->printPretty();
std::cout << (c->remove(233)) << std::endl;
*e=*a;
*e=*e;
std::cout << (b->insert(75)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (d->remove(194)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
*a=*b;
std::cout << (c->insert(23)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
*c=*b;
std::cout << (b->remove(137)) << std::endl;
std::cout << (d->remove(95)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (e->insert(386)) << std::endl;
std::cout << (c->insert(344)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (a->insert(58)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
*a=*c;
std::cout << (d->insert(15)) << std::endl;
c->printPretty();
std::cout << (c->remove(383)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
*a=*c;
*a=*a;
std::cout << (d->remove(195)) << std::endl;
std::cout << (a->remove(314)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
d->printPretty();
*a=*e;
*b=*a;
*a=*c;
std::cout << (b->insert(427)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (b->remove(427)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
a->printPretty();
std::cout << (a->insert(137)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
b->printPretty();
std::cout << (b->remove(367)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (b->remove(182)) << std::endl;
a->printPretty();
std::cout << (c->insert(314)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
d->printPretty();
std::cout << (e->insert(15)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
*a=*a;
std::cout << (e->insert(323)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
e->printPretty();
std::cout << (d->insert(439)) << std::endl;
*a=*b;
std::cout << (d->insert(105)) << std::endl;
*b=*a;
std::cout << (c->remove(89)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
*b=*c;
*b=*e;
std::cout << (a->insert(337)) << std::endl;
std::cout << (b->remove(285)) << std::endl;
std::cout << (c->insert(203)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
*b=*a;
std::cout << (e->remove(15)) << std::endl;
std::cout << (d->insert(105)) << std::endl;
a->printPretty();
std::cout << (b->remove(454)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (c->remove(314)) << std::endl;
*a=*d;
*a=*b;
std::cout << (a->remove(328)) << std::endl;
std::cout << (b->insert(437)) << std::endl;
*a=*d;
std::cout << (e->insert(447)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
std::cout << (b->insert(437)) << std::endl;
*c=*b;
*c=*c;
std::cout << (e->remove(383)) << std::endl;
a->printPretty();
std::cout << (b->remove(337)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
*c=*a;
std::cout << (b->insert(11)) << std::endl;
*c=*c;
*d=*e;
std::cout << (b->insert(330)) << std::endl;
b->printPretty();
std::cout << (e->remove(288)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (c->remove(455)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
*a=*c;
std::cout << (c->insert(229)) << std::endl;
d->printPretty();
std::cout << (a->remove(439)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
d->printPretty();
std::cout << (a->remove(297)) << std::endl;
*d=*d;
*b=*b;
b->printPretty();
std::cout << (a->remove(105)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
e->printPretty();
std::cout << (b->insert(330)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
a->printPretty();
std::cout << (c->remove(439)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (c->insert(254)) << std::endl;
d->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*b=*e;
*d=*a;
*d=*e;
*e=*e;
std::cout << (c->remove(105)) << std::endl;
b->printPretty();
*e=*b;
c->printPretty();
*e=*e;
std::cout << (d->remove(105)) << std::endl;
*b=*e;
std::cout << (e->insert(8)) << std::endl;
std::cout << (e->remove(370)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
return 0;
}
