#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (b->insert(247)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (a->remove(247)) << std::endl;
*a=*b;
std::cout << (c->insert(325)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (b->insert(373)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
c->printPretty();
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
d->printPretty();
std::cout << (e->insert(325)) << std::endl;
*d=*d;
std::cout << (c->remove(455)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
a->printPretty();
*d=*b;
a->printPretty();
std::cout << (b->remove(373)) << std::endl;
std::cout << (c->insert(427)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
*c=*c;
b->printPretty();
c->printPretty();
std::cout << (e->insert(383)) << std::endl;
a->printPretty();
*e=*a;
*d=*c;
std::cout << (b->remove(382)) << std::endl;
*b=*c;
std::cout << (b->insert(133)) << std::endl;
*c=*e;
std::cout << (b->remove(315)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (e->insert(25)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
e->printPretty();
std::cout << (b->remove(247)) << std::endl;
b->printPretty();
std::cout << (e->insert(376)) << std::endl;
std::cout << (b->remove(427)) << std::endl;
*b=*d;
std::cout << (b->insert(415)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
*a=*c;
*c=*b;
std::cout << (c->remove(214)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
e->printPretty();
std::cout << (a->insert(357)) << std::endl;
c->printPretty();
std::cout << (e->remove(258)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
*c=*a;
c->printPretty();
b->printPretty();
b->printPretty();
e->printPretty();
std::cout << (d->remove(247)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
c->printPretty();
d->printPretty();
*b=*e;
std::cout << (c->insert(476)) << std::endl;
b->printPretty();
*c=*c;
*e=*c;
std::cout << (a->insert(357)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(476)) << std::endl;
std::cout << (c->insert(221)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
*d=*c;
*b=*a;
std::cout << (d->remove(221)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*e=*e;
*e=*a;
*c=*b;
*a=*d;
std::cout << (d->remove(9)) << std::endl;
b->printPretty();
std::cout << (b->insert(357)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (c->remove(126)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
*d=*b;
std::cout << (d->remove(436)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
b->printPretty();
std::cout << (c->insert(436)) << std::endl;
std::cout << (e->insert(102)) << std::endl;
*a=*b;
std::cout << (b->insert(357)) << std::endl;
std::cout << (a->insert(196)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
d->printPretty();
std::cout << (b->insert(350)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
std::cout << (c->remove(211)) << std::endl;
*c=*c;
*e=*b;
std::cout << (c->remove(496)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
*e=*b;
std::cout << (d->remove(113)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (c->insert(357)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
*e=*a;
b->printPretty();
b->printPretty();
c->printPretty();
std::cout << (c->remove(211)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
b->printPretty();
std::cout << (e->insert(23)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
a->printPretty();
std::cout << (c->remove(312)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
*a=*c;
std::cout << (e->insert(236)) << std::endl;
*c=*b;
std::cout << (c->remove(363)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
b->printPretty();
std::cout << (a->insert(357)) << std::endl;
c->printPretty();
*d=*e;
a->printPretty();
c->printPretty();
c->printPretty();
std::cout << (b->insert(17)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
*b=*e;
std::cout << (b->remove(431)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (d->remove(23)) << std::endl;
std::cout << (e->insert(442)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (d->insert(462)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (a->remove(141)) << std::endl;
*e=*b;
std::cout << (d->remove(209)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
e->printPretty();
std::cout << (a->insert(357)) << std::endl;
d->printPretty();
std::cout << (c->remove(274)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
*c=*a;
b->printPretty();
*e=*e;
*e=*a;
*e=*d;
std::cout << (c->insert(268)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->insert(462)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
c->printPretty();
std::cout << (b->remove(189)) << std::endl;
c->printPretty();
std::cout << (d->remove(60)) << std::endl;
*a=*d;
*e=*b;
*d=*e;
*a=*a;
std::cout << (b->remove(238)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (c->remove(483)) << std::endl;
std::cout << (a->insert(326)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (c->remove(436)) << std::endl;
*b=*a;
std::cout << (e->insert(168)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (c->insert(268)) << std::endl;
std::cout << (a->remove(443)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
*a=*a;
*a=*d;
d->printPretty();
std::cout << (b->remove(159)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
*e=*d;
std::cout << (b->insert(306)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (d->insert(67)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (c->remove(268)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
a->printPretty();
std::cout << (d->remove(394)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
d->printPretty();
std::cout << (a->insert(320)) << std::endl;
*a=*a;
*e=*b;
std::cout << (c->remove(42)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (d->remove(67)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (d->remove(334)) << std::endl;
e->printPretty();
std::cout << (c->insert(371)) << std::endl;
a->printPretty();
b->printPretty();
*b=*a;
std::cout << (c->insert(183)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
d->printPretty();
*e=*d;
a->printPretty();
std::cout << (b->insert(129)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
d->printPretty();
std::cout << (b->insert(497)) << std::endl;
std::cout << (e->insert(163)) << std::endl;
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (b->remove(139)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
e->printPretty();
std::cout << (a->insert(320)) << std::endl;
std::cout << (b->remove(324)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
*c=*a;
std::cout << (b->insert(84)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
c->printPretty();
std::cout << (b->remove(320)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
*c=*c;
std::cout << (d->insert(60)) << std::endl;
c->printPretty();
d->printPretty();
*e=*d;
a->printPretty();
std::cout << (c->remove(320)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
std::cout << (d->insert(236)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
b->printPretty();
std::cout << (c->insert(312)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
*b=*e;
std::cout << (b->insert(251)) << std::endl;
*b=*a;
*e=*c;
*b=*a;
std::cout << (d->remove(475)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
a->printPretty();
std::cout << (b->remove(338)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
*b=*b;
std::cout << (e->remove(462)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
c->printPretty();
std::cout << (a->insert(60)) << std::endl;
*b=*a;
std::cout << (a->insert(459)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (c->remove(312)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (a->insert(23)) << std::endl;
c->printPretty();
std::cout << (c->insert(224)) << std::endl;
std::cout << (c->remove(23)) << std::endl;
std::cout << (c->remove(159)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
d->printPretty();
std::cout << (e->insert(262)) << std::endl;
*d=*c;
std::cout << (e->insert(60)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (a->insert(178)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
d->printPretty();
std::cout << (d->insert(224)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
d->printPretty();
std::cout << (d->insert(60)) << std::endl;
*d=*e;
d->printPretty();
b->printPretty();
std::cout << (e->insert(71)) << std::endl;
std::cout << (b->remove(269)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
e->printPretty();
std::cout << (e->insert(226)) << std::endl;
c->printPretty();
*d=*c;
e->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (d->remove(448)) << std::endl;
std::cout << (a->remove(364)) << std::endl;
std::cout << (a->insert(302)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
*c=*d;
*c=*a;
std::cout << (d->remove(237)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (c->remove(312)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
c->printPretty();
*a=*c;
*d=*e;
d->printPretty();
std::cout << (e->insert(60)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*c=*b;
std::cout << (e->insert(332)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
d->printPretty();
*b=*d;
c->printPretty();
*e=*a;
*c=*c;
*b=*d;
std::cout << (e->insert(375)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
b->printPretty();
std::cout << (a->insert(140)) << std::endl;
e->printPretty();
std::cout << (b->remove(56)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
std::cout << (d->insert(71)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
*e=*c;
std::cout << (e->remove(60)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
*e=*c;
std::cout << (d->insert(261)) << std::endl;
*a=*b;
*b=*a;
std::cout << (b->insert(236)) << std::endl;
std::cout << (b->remove(422)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
b->printPretty();
std::cout << (b->insert(116)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
c->printPretty();
std::cout << (d->remove(312)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
*c=*b;
std::cout << (a->remove(351)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
c->printPretty();
std::cout << (d->remove(269)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
*a=*e;
std::cout << (c->remove(477)) << std::endl;
std::cout << (a->insert(417)) << std::endl;
e->printPretty();
std::cout << (b->remove(236)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (c->insert(236)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
*b=*d;
std::cout << (c->insert(262)) << std::endl;
std::cout << (c->remove(262)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (b->insert(71)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (e->remove(320)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
e->printPretty();
std::cout << (d->remove(459)) << std::endl;
std::cout << (d->insert(236)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (c->insert(291)) << std::endl;
std::cout << (d->remove(23)) << std::endl;
*e=*b;
*d=*a;
*a=*e;
*e=*b;
std::cout << (e->remove(459)) << std::endl;
a->printPretty();
std::cout << (b->remove(60)) << std::endl;
std::cout << (c->insert(490)) << std::endl;
*d=*c;
*c=*d;
std::cout << (a->insert(236)) << std::endl;
std::cout << (e->remove(60)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
e->printPretty();
std::cout << (a->remove(153)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
c->printPretty();
d->printPretty();
b->printPretty();
std::cout << (a->remove(488)) << std::endl;
*a=*e;
std::cout << (e->insert(320)) << std::endl;
std::cout << (e->remove(236)) << std::endl;
*c=*d;
std::cout << (e->insert(87)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(224)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
b->printPretty();
std::cout << (e->insert(224)) << std::endl;
a->printPretty();
std::cout << (a->remove(224)) << std::endl;
std::cout << (d->remove(334)) << std::endl;
*d=*b;
std::cout << (e->remove(151)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
d->printPretty();
std::cout << (c->insert(33)) << std::endl;
a->printPretty();
std::cout << (a->insert(71)) << std::endl;
std::cout << (d->insert(95)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
*c=*c;
std::cout << (c->insert(205)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (a->insert(371)) << std::endl;
*e=*c;
std::cout << (c->insert(291)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
c->printPretty();
std::cout << (c->insert(459)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
*a=*e;
*a=*b;
*d=*c;
std::cout << (a->remove(94)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
e->printPretty();
std::cout << (b->insert(181)) << std::endl;
std::cout << (a->remove(23)) << std::endl;
*b=*c;
std::cout << (b->remove(263)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
a->printPretty();
std::cout << (e->insert(56)) << std::endl;
*c=*e;
std::cout << (e->remove(149)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
b->printPretty();
*a=*c;
*c=*a;
std::cout << (a->insert(289)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
d->printPretty();
*e=*d;
a->printPretty();
std::cout << (d->remove(426)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
std::cout << (c->insert(459)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
a->printPretty();
std::cout << (e->insert(365)) << std::endl;
*b=*e;
std::cout << (c->insert(459)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
b->printPretty();
std::cout << (e->remove(138)) << std::endl;
*d=*d;
std::cout << (a->remove(173)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
*b=*e;
*d=*e;
b->printPretty();
std::cout << (e->remove(173)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (e->insert(224)) << std::endl;
std::cout << (d->insert(205)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
c->printPretty();
std::cout << (b->remove(357)) << std::endl;
std::cout << (c->remove(417)) << std::endl;
d->printPretty();
a->printPretty();
b->printPretty();
std::cout << (d->insert(443)) << std::endl;
*c=*c;
std::cout << (c->remove(443)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (a->remove(443)) << std::endl;
e->printPretty();
std::cout << (b->insert(205)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
e->printPretty();
*a=*b;
*e=*b;
std::cout << (b->insert(336)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
e->printPretty();
std::cout << (d->insert(9)) << std::endl;
*a=*b;
*e=*b;
std::cout << (e->insert(33)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
*c=*b;
std::cout << (b->insert(193)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
*c=*d;
std::cout << (d->insert(102)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (c->remove(247)) << std::endl;
b->printPretty();
std::cout << (a->remove(291)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
d->printPretty();
std::cout << (b->remove(459)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
*d=*a;
std::cout << (e->insert(30)) << std::endl;
*c=*c;
std::cout << (a->remove(358)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
std::cout << (d->insert(336)) << std::endl;
c->printPretty();
std::cout << (d->remove(56)) << std::endl;
c->printPretty();
std::cout << (a->insert(56)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
*e=*e;
std::cout << (c->insert(328)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
*b=*c;
std::cout << (a->insert(340)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (b->remove(263)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
e->printPretty();
std::cout << (a->insert(267)) << std::endl;
e->printPretty();
std::cout << (b->remove(449)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
*b=*a;
std::cout << (e->remove(280)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
b->printPretty();
std::cout << (c->remove(361)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
c->printPretty();
std::cout << (e->insert(453)) << std::endl;
*b=*d;
std::cout << (a->remove(241)) << std::endl;
std::cout << (e->remove(304)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
*e=*b;
std::cout << (c->insert(289)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
b->printPretty();
std::cout << (d->insert(443)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
a->printPretty();
std::cout << (b->insert(47)) << std::endl;
*b=*b;
std::cout << (b->remove(443)) << std::endl;
d->printPretty();
std::cout << (b->insert(201)) << std::endl;
std::cout << (c->remove(291)) << std::endl;
return 0;
}
