#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(7)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
c->printPretty();
std::cout << (a->remove(7)) << std::endl;
*b=*c;
std::cout << (b->remove(57)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
*b=*b;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(481)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*e=*e;
std::cout << (c->insert(15)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
*b=*b;
*a=*a;
d->printPretty();
std::cout << (c->remove(300)) << std::endl;
d->printPretty();
std::cout << (d->remove(226)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
d->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (c->remove(15)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
d->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(389)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
*a=*d;
std::cout << (e->insert(492)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (a->insert(234)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->remove(234)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
e->printPretty();
std::cout << (d->remove(168)) << std::endl;
*a=*b;
std::cout << (d->insert(242)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (c->insert(136)) << std::endl;
*e=*c;
std::cout << (b->remove(184)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
*b=*b;
e->printPretty();
b->printPretty();
std::cout << (b->remove(291)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (b->insert(122)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
*b=*c;
std::cout << (b->insert(94)) << std::endl;
std::cout << (c->remove(136)) << std::endl;
std::cout << (d->remove(366)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
b->printPretty();
std::cout << (a->remove(480)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
b->printPretty();
std::cout << (e->remove(342)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
*c=*e;
std::cout << (a->remove(184)) << std::endl;
std::cout << (b->insert(136)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
*c=*b;
std::cout << (b->insert(136)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(433)) << std::endl;
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (c->remove(65)) << std::endl;
b->printPretty();
*c=*e;
e->printPretty();
std::cout << (b->insert(94)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
*c=*d;
d->printPretty();
std::cout << (a->remove(321)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
std::cout << (a->remove(291)) << std::endl;
b->printPretty();
std::cout << (b->insert(374)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
*c=*a;
std::cout << (c->remove(116)) << std::endl;
e->printPretty();
e->printPretty();
*b=*e;
std::cout << (c->insert(128)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(272)) << std::endl;
c->printPretty();
std::cout << (d->insert(232)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (e->remove(272)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
*a=*c;
std::cout << (c->insert(255)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (a->insert(353)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
*c=*b;
std::cout << (a->insert(331)) << std::endl;
c->printPretty();
std::cout << (c->remove(272)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
*c=*b;
std::cout << (e->insert(85)) << std::endl;
*e=*d;
std::cout << (d->insert(97)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->remove(374)) << std::endl;
*b=*a;
std::cout << (d->insert(403)) << std::endl;
*b=*e;
std::cout << (b->remove(340)) << std::endl;
std::cout << (e->remove(200)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (c->remove(272)) << std::endl;
std::cout << (a->insert(307)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
*a=*a;
std::cout << (d->insert(53)) << std::endl;
b->printPretty();
std::cout << (d->remove(403)) << std::endl;
a->printPretty();
e->printPretty();
*d=*e;
std::cout << (e->insert(266)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
a->printPretty();
std::cout << (e->insert(353)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(403)) << std::endl;
std::cout << (d->remove(403)) << std::endl;
*e=*d;
*a=*d;
std::cout << (e->remove(389)) << std::endl;
a->printPretty();
*a=*a;
*e=*c;
*b=*a;
*a=*a;
*a=*d;
std::cout << (c->insert(209)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (b->insert(286)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
*c=*b;
*a=*a;
std::cout << (c->remove(361)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
*e=*a;
std::cout << (d->remove(259)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
b->printPretty();
std::cout << (b->insert(484)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
*d=*b;
std::cout << (b->insert(225)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
std::cout << (c->remove(232)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
*b=*d;
std::cout << (b->remove(484)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(209)) << std::endl;
*d=*c;
*c=*e;
d->printPretty();
*a=*a;
std::cout << (c->remove(467)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
d->printPretty();
std::cout << (a->insert(222)) << std::endl;
std::cout << (a->remove(334)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
b->printPretty();
std::cout << (a->insert(191)) << std::endl;
*c=*a;
std::cout << (c->insert(191)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
*e=*d;
std::cout << (a->insert(191)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
*d=*d;
std::cout << (e->remove(450)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
a->printPretty();
d->printPretty();
*d=*e;
std::cout << (c->insert(4)) << std::endl;
*b=*c;
*a=*a;
e->printPretty();
*c=*a;
std::cout << (a->insert(191)) << std::endl;
*b=*e;
*a=*e;
*a=*d;
e->printPretty();
std::cout << (e->insert(258)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (c->insert(328)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
c->printPretty();
std::cout << (e->insert(484)) << std::endl;
std::cout << (d->remove(88)) << std::endl;
std::cout << (a->insert(320)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
e->printPretty();
*e=*e;
b->printPretty();
std::cout << (e->insert(273)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
b->printPretty();
std::cout << (a->remove(72)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (b->remove(97)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
b->printPretty();
*a=*e;
d->printPretty();
std::cout << (e->insert(53)) << std::endl;
a->printPretty();
std::cout << (c->insert(261)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (b->remove(273)) << std::endl;
*e=*e;
std::cout << (a->remove(271)) << std::endl;
*b=*b;
std::cout << (b->remove(152)) << std::endl;
std::cout << (c->remove(87)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
*b=*a;
std::cout << (e->remove(53)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
*c=*a;
std::cout << (e->remove(390)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
*b=*a;
std::cout << (a->insert(491)) << std::endl;
*a=*b;
std::cout << (a->remove(54)) << std::endl;
std::cout << (d->remove(95)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
std::cout << (a->insert(363)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (e->remove(329)) << std::endl;
std::cout << (e->remove(441)) << std::endl;
std::cout << (e->insert(477)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
*d=*a;
std::cout << (e->insert(386)) << std::endl;
d->printPretty();
std::cout << (b->remove(344)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
*c=*a;
std::cout << (c->remove(273)) << std::endl;
std::cout << (b->insert(290)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (d->remove(429)) << std::endl;
*e=*e;
std::cout << (c->remove(484)) << std::endl;
std::cout << (b->insert(290)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (d->insert(363)) << std::endl;
*e=*d;
a->printPretty();
*b=*d;
std::cout << (e->insert(363)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
*c=*a;
std::cout << (b->insert(363)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->insert(258)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (e->insert(274)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
*b=*b;
*b=*e;
std::cout << (c->insert(273)) << std::endl;
std::cout << (c->insert(451)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
std::cout << (c->insert(30)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
a->printPretty();
std::cout << (b->remove(351)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (c->insert(181)) << std::endl;
std::cout << (a->remove(273)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
std::cout << (a->insert(361)) << std::endl;
a->printPretty();
a->printPretty();
*d=*c;
std::cout << (d->remove(407)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (b->remove(1)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
e->printPretty();
std::cout << (b->remove(392)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
e->printPretty();
*e=*c;
d->printPretty();
std::cout << (d->insert(297)) << std::endl;
std::cout << (c->insert(181)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(258)) << std::endl;
*d=*a;
std::cout << (b->remove(279)) << std::endl;
std::cout << (c->remove(181)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(273)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
*d=*d;
std::cout << (e->remove(406)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
std::cout << (a->insert(405)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
e->printPretty();
std::cout << (c->remove(173)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
*e=*e;
std::cout << (b->remove(274)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
*a=*c;
*a=*d;
*d=*b;
b->printPretty();
std::cout << (a->remove(70)) << std::endl;
*a=*c;
std::cout << (c->remove(476)) << std::endl;
d->printPretty();
e->printPretty();
*b=*d;
std::cout << (c->remove(484)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
c->printPretty();
std::cout << (d->insert(201)) << std::endl;
*e=*e;
std::cout << (b->remove(413)) << std::endl;
*a=*d;
std::cout << (e->remove(181)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
e->printPretty();
std::cout << (e->insert(166)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
a->printPretty();
std::cout << (e->insert(473)) << std::endl;
d->printPretty();
std::cout << (c->insert(182)) << std::endl;
*d=*b;
std::cout << (e->remove(30)) << std::endl;
std::cout << (b->remove(422)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
std::cout << (e->remove(268)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
a->printPretty();
*c=*e;
*b=*b;
std::cout << (b->remove(140)) << std::endl;
std::cout << (b->remove(201)) << std::endl;
d->printPretty();
std::cout << (a->insert(140)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
a->printPretty();
b->printPretty();
a->printPretty();
std::cout << (d->insert(460)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(449)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
d->printPretty();
std::cout << (a->remove(140)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
e->printPretty();
std::cout << (c->insert(484)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(413)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
e->printPretty();
std::cout << (d->insert(108)) << std::endl;
b->printPretty();
std::cout << (d->remove(460)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
std::cout << (b->insert(484)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (e->insert(261)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->insert(140)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (a->remove(201)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
*a=*e;
std::cout << (b->insert(16)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
*d=*d;
*a=*e;
std::cout << (b->insert(386)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
c->printPretty();
std::cout << (b->insert(225)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
a->printPretty();
std::cout << (c->remove(425)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (a->insert(261)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
*a=*c;
std::cout << (e->remove(454)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
*d=*d;
std::cout << (d->insert(100)) << std::endl;
std::cout << (b->insert(215)) << std::endl;
*e=*b;
std::cout << (b->remove(215)) << std::endl;
std::cout << (d->remove(141)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(484)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
b->printPretty();
d->printPretty();
d->printPretty();
std::cout << (b->insert(476)) << std::endl;
*b=*a;
std::cout << (e->remove(264)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
d->printPretty();
std::cout << (a->remove(267)) << std::endl;
*b=*e;
std::cout << (b->remove(143)) << std::endl;
b->printPretty();
std::cout << (e->insert(409)) << std::endl;
*b=*d;
std::cout << (b->remove(239)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
e->printPretty();
std::cout << (b->insert(125)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
*e=*c;
std::cout << (e->remove(59)) << std::endl;
*a=*e;
std::cout << (b->remove(100)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
d->printPretty();
std::cout << (d->insert(91)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
*b=*a;
e->printPretty();
*a=*a;
std::cout << (c->remove(409)) << std::endl;
d->printPretty();
*c=*b;
d->printPretty();
std::cout << (c->remove(231)) << std::endl;
*a=*b;
std::cout << (a->insert(166)) << std::endl;
*d=*d;
*d=*c;
c->printPretty();
e->printPretty();
e->printPretty();
std::cout << (b->remove(439)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
std::cout << (a->remove(435)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
d->printPretty();
std::cout << (b->remove(166)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
d->printPretty();
std::cout << (d->remove(166)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
std::cout << (c->insert(89)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (d->remove(203)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
*a=*d;
std::cout << (d->insert(495)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(304)) << std::endl;
std::cout << (e->remove(186)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
*b=*e;
std::cout << (d->remove(495)) << std::endl;
std::cout << (c->insert(384)) << std::endl;
return 0;
}
