#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(491)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (a->remove(491)) << std::endl;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->insert(471)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(231)) << std::endl;
c->printPretty();
std::cout << (c->remove(9)) << std::endl;
b->printPretty();
std::cout << (a->remove(463)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
*a=*c;
*c=*b;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (e->insert(23)) << std::endl;
b->printPretty();
std::cout << (b->remove(471)) << std::endl;
std::cout << (e->insert(243)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
std::cout << (e->insert(263)) << std::endl;
c->printPretty();
std::cout << (e->insert(402)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(263)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
d->printPretty();
std::cout << (a->insert(127)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
*d=*b;
std::cout << (b->insert(39)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
std::cout << (c->insert(76)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
*d=*e;
std::cout << (b->insert(489)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (b->insert(191)) << std::endl;
*a=*a;
std::cout << (c->insert(218)) << std::endl;
*d=*c;
std::cout << (c->insert(76)) << std::endl;
std::cout << (d->remove(423)) << std::endl;
std::cout << (b->insert(191)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (c->remove(263)) << std::endl;
std::cout << (a->insert(355)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (a->insert(411)) << std::endl;
a->printPretty();
std::cout << (e->insert(402)) << std::endl;
std::cout << (a->remove(355)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
*b=*c;
std::cout << (c->remove(23)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
*b=*a;
std::cout << (a->insert(15)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (e->insert(59)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
*b=*a;
std::cout << (a->remove(145)) << std::endl;
std::cout << (b->remove(398)) << std::endl;
a->printPretty();
std::cout << (e->insert(243)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
*b=*b;
c->printPretty();
*b=*a;
std::cout << (a->insert(403)) << std::endl;
e->printPretty();
std::cout << (e->remove(243)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
*e=*d;
std::cout << (a->remove(127)) << std::endl;
*c=*b;
*c=*e;
a->printPretty();
std::cout << (c->remove(218)) << std::endl;
*d=*b;
*d=*e;
std::cout << (a->remove(223)) << std::endl;
*a=*a;
std::cout << (d->remove(76)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (c->insert(448)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
std::cout << (c->remove(16)) << std::endl;
*e=*b;
b->printPretty();
a->printPretty();
std::cout << (b->insert(306)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
*c=*e;
std::cout << (c->remove(235)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
std::cout << (e->insert(282)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
*b=*d;
*a=*c;
std::cout << (d->remove(285)) << std::endl;
*a=*a;
std::cout << (c->remove(93)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
*d=*d;
*e=*e;
std::cout << (a->insert(377)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
e->printPretty();
std::cout << (b->insert(285)) << std::endl;
e->printPretty();
std::cout << (b->remove(285)) << std::endl;
*c=*b;
std::cout << (c->insert(218)) << std::endl;
d->printPretty();
*e=*c;
b->printPretty();
*e=*e;
c->printPretty();
std::cout << (d->remove(300)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
std::cout << (e->insert(51)) << std::endl;
*e=*d;
std::cout << (c->insert(300)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (c->remove(127)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (e->insert(216)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
a->printPretty();
std::cout << (d->remove(456)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (e->remove(216)) << std::endl;
c->printPretty();
std::cout << (b->insert(170)) << std::endl;
*b=*a;
std::cout << (e->remove(51)) << std::endl;
a->printPretty();
std::cout << (b->insert(218)) << std::endl;
*c=*d;
*a=*b;
std::cout << (e->insert(400)) << std::endl;
a->printPretty();
std::cout << (d->insert(480)) << std::endl;
std::cout << (c->remove(97)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (a->remove(187)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
*b=*d;
std::cout << (a->remove(300)) << std::endl;
a->printPretty();
a->printPretty();
*d=*d;
std::cout << (a->insert(218)) << std::endl;
b->printPretty();
std::cout << (c->remove(50)) << std::endl;
d->printPretty();
std::cout << (d->remove(477)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (e->insert(166)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
*d=*e;
a->printPretty();
*c=*a;
d->printPretty();
e->printPretty();
std::cout << (a->insert(341)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
*d=*e;
std::cout << (c->remove(218)) << std::endl;
std::cout << (d->insert(166)) << std::endl;
std::cout << (b->insert(249)) << std::endl;
d->printPretty();
std::cout << (b->insert(498)) << std::endl;
std::cout << (b->insert(249)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
c->printPretty();
std::cout << (d->insert(92)) << std::endl;
std::cout << (a->remove(334)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
*c=*b;
e->printPretty();
*b=*e;
c->printPretty();
*c=*e;
std::cout << (e->insert(166)) << std::endl;
std::cout << (a->insert(71)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
*c=*b;
std::cout << (c->remove(166)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
*d=*c;
std::cout << (b->insert(418)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (a->remove(71)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
*e=*d;
std::cout << (b->remove(295)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
*a=*e;
std::cout << (d->remove(24)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
b->printPretty();
std::cout << (b->insert(141)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->remove(418)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (d->remove(365)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (c->insert(30)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(159)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
*a=*b;
std::cout << (a->remove(361)) << std::endl;
*b=*b;
std::cout << (a->remove(244)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
c->printPretty();
*d=*b;
*d=*a;
*b=*a;
std::cout << (c->insert(82)) << std::endl;
e->printPretty();
a->printPretty();
d->printPretty();
std::cout << (b->remove(190)) << std::endl;
d->printPretty();
std::cout << (c->insert(82)) << std::endl;
*e=*c;
*d=*d;
*c=*e;
std::cout << (b->remove(43)) << std::endl;
c->printPretty();
std::cout << (e->remove(24)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
*e=*e;
*c=*b;
*a=*d;
std::cout << (c->insert(443)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
*e=*b;
*a=*d;
*a=*e;
*c=*b;
std::cout << (d->remove(465)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
*e=*c;
std::cout << (a->remove(91)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (b->insert(27)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
*e=*c;
std::cout << (e->insert(441)) << std::endl;
std::cout << (d->remove(267)) << std::endl;
*d=*c;
std::cout << (b->remove(28)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
*e=*e;
std::cout << (e->remove(441)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
*d=*d;
std::cout << (e->remove(182)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
std::cout << (d->remove(84)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
d->printPretty();
std::cout << (d->remove(469)) << std::endl;
std::cout << (d->remove(122)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (a->remove(203)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(425)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (c->insert(275)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
*a=*a;
std::cout << (e->remove(42)) << std::endl;
*d=*d;
std::cout << (c->insert(366)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
b->printPretty();
*a=*c;
b->printPretty();
e->printPretty();
std::cout << (a->insert(366)) << std::endl;
b->printPretty();
std::cout << (d->remove(412)) << std::endl;
*e=*b;
std::cout << (a->insert(14)) << std::endl;
std::cout << (b->remove(432)) << std::endl;
a->printPretty();
std::cout << (a->remove(366)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
e->printPretty();
std::cout << (c->insert(344)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
*c=*c;
std::cout << (b->remove(279)) << std::endl;
*a=*e;
*d=*b;
std::cout << (b->insert(425)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (b->remove(240)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (d->remove(81)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
*c=*e;
std::cout << (d->remove(426)) << std::endl;
b->printPretty();
std::cout << (d->insert(410)) << std::endl;
b->printPretty();
std::cout << (b->insert(425)) << std::endl;
*e=*b;
std::cout << (a->insert(469)) << std::endl;
d->printPretty();
std::cout << (a->insert(469)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
*e=*e;
e->printPretty();
*b=*d;
e->printPretty();
std::cout << (b->remove(174)) << std::endl;
e->printPretty();
d->printPretty();
*a=*c;
std::cout << (e->remove(425)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (a->insert(424)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
*c=*d;
std::cout << (c->remove(367)) << std::endl;
c->printPretty();
std::cout << (a->insert(424)) << std::endl;
*d=*a;
std::cout << (b->remove(238)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
std::cout << (a->remove(210)) << std::endl;
c->printPretty();
std::cout << (c->remove(410)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
*e=*b;
std::cout << (b->remove(487)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
*d=*e;
*e=*c;
*d=*d;
std::cout << (c->remove(52)) << std::endl;
c->printPretty();
std::cout << (e->remove(47)) << std::endl;
b->printPretty();
std::cout << (d->insert(410)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
b->printPretty();
*a=*c;
c->printPretty();
e->printPretty();
std::cout << (e->remove(120)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
*e=*d;
std::cout << (a->remove(47)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
e->printPretty();
std::cout << (e->remove(109)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
a->printPretty();
std::cout << (b->remove(410)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
*d=*e;
std::cout << (b->remove(454)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->insert(425)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
b->printPretty();
std::cout << (b->remove(394)) << std::endl;
*e=*e;
std::cout << (a->insert(483)) << std::endl;
*d=*b;
std::cout << (a->insert(378)) << std::endl;
*b=*e;
std::cout << (e->remove(109)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (a->remove(141)) << std::endl;
*a=*d;
*c=*b;
std::cout << (e->insert(2)) << std::endl;
std::cout << (d->insert(159)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
*a=*d;
*e=*a;
std::cout << (b->insert(425)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (c->insert(270)) << std::endl;
e->printPretty();
std::cout << (b->insert(425)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (e->remove(159)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
e->printPretty();
std::cout << (a->remove(237)) << std::endl;
*b=*d;
*c=*a;
*c=*a;
std::cout << (e->remove(245)) << std::endl;
b->printPretty();
std::cout << (c->insert(159)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
*c=*d;
std::cout << (e->remove(233)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (a->remove(159)) << std::endl;
a->printPretty();
std::cout << (a->insert(157)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
std::cout << (a->insert(286)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*b=*d;
*d=*b;
std::cout << (c->remove(469)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
std::cout << (e->insert(243)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
std::cout << (e->remove(45)) << std::endl;
*a=*e;
std::cout << (a->insert(404)) << std::endl;
std::cout << (a->remove(18)) << std::endl;
std::cout << (c->insert(303)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
*c=*b;
std::cout << (d->insert(133)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
*e=*c;
std::cout << (b->remove(467)) << std::endl;
*b=*b;
c->printPretty();
c->printPretty();
std::cout << (d->remove(390)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (c->insert(132)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (b->remove(202)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->remove(183)) << std::endl;
d->printPretty();
std::cout << (b->insert(378)) << std::endl;
c->printPretty();
std::cout << (a->remove(243)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
c->printPretty();
std::cout << (b->remove(185)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
*c=*e;
b->printPretty();
e->printPretty();
*b=*c;
std::cout << (a->remove(171)) << std::endl;
std::cout << (c->remove(230)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
*c=*e;
*e=*c;
std::cout << (d->insert(164)) << std::endl;
*d=*c;
*c=*a;
std::cout << (a->remove(128)) << std::endl;
*b=*e;
b->printPretty();
*b=*e;
e->printPretty();
std::cout << (d->insert(297)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
c->printPretty();
*c=*b;
*d=*b;
std::cout << (b->remove(4)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
std::cout << (c->insert(365)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (d->insert(458)) << std::endl;
d->printPretty();
std::cout << (a->insert(69)) << std::endl;
*b=*d;
std::cout << (d->insert(52)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (b->insert(458)) << std::endl;
c->printPretty();
std::cout << (c->insert(365)) << std::endl;
std::cout << (d->insert(458)) << std::endl;
*e=*a;
std::cout << (b->insert(314)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (e->remove(433)) << std::endl;
*e=*a;
std::cout << (b->insert(314)) << std::endl;
std::cout << (e->insert(274)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
a->printPretty();
std::cout << (a->remove(292)) << std::endl;
e->printPretty();
std::cout << (e->remove(69)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
b->printPretty();
std::cout << (a->insert(494)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
return 0;
}
