#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(351)) << std::endl;
std::cout << (a->remove(340)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (a->insert(271)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->insert(271)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
*a=*b;
std::cout << (b->remove(271)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(197)) << std::endl;
b->printPretty();
std::cout << (d->insert(206)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*d=*b;
*c=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (a->remove(115)) << std::endl;
*c=*d;
std::cout << (c->insert(351)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (a->remove(6)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
c->printPretty();
std::cout << (d->remove(3)) << std::endl;
*b=*d;
std::cout << (b->insert(197)) << std::endl;
*e=*e;
std::cout << (c->insert(197)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
b->printPretty();
std::cout << (d->remove(43)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
*c=*e;
e->printPretty();
e->printPretty();
std::cout << (e->insert(10)) << std::endl;
std::cout << (d->remove(351)) << std::endl;
std::cout << (d->remove(367)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
std::cout << (d->remove(347)) << std::endl;
*e=*e;
std::cout << (e->remove(93)) << std::endl;
std::cout << (e->remove(197)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
*d=*a;
std::cout << (d->insert(3)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
*e=*b;
*e=*c;
std::cout << (a->insert(153)) << std::endl;
*b=*b;
*c=*b;
std::cout << (c->insert(376)) << std::endl;
c->printPretty();
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
*c=*d;
std::cout << (d->remove(264)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
std::cout << (d->remove(30)) << std::endl;
*c=*b;
*e=*e;
std::cout << (e->insert(197)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
d->printPretty();
std::cout << (b->insert(265)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
*c=*b;
std::cout << (e->insert(197)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (e->remove(319)) << std::endl;
std::cout << (e->remove(310)) << std::endl;
e->printPretty();
std::cout << (a->remove(49)) << std::endl;
c->printPretty();
d->printPretty();
*e=*c;
a->printPretty();
d->printPretty();
std::cout << (a->insert(153)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (d->remove(137)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (a->remove(351)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
*e=*e;
std::cout << (e->insert(112)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
*c=*b;
std::cout << (c->insert(494)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
std::cout << (c->insert(232)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (a->insert(232)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
*e=*e;
std::cout << (a->insert(284)) << std::endl;
std::cout << (d->remove(316)) << std::endl;
std::cout << (a->insert(148)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
std::cout << (b->remove(221)) << std::endl;
*c=*c;
std::cout << (c->insert(6)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (b->remove(6)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
c->printPretty();
std::cout << (d->insert(351)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (d->insert(271)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
std::cout << (d->remove(271)) << std::endl;
*e=*e;
std::cout << (d->remove(6)) << std::endl;
c->printPretty();
std::cout << (a->remove(178)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (d->insert(263)) << std::endl;
*d=*e;
*b=*e;
*a=*b;
std::cout << (b->remove(370)) << std::endl;
*d=*c;
std::cout << (a->remove(318)) << std::endl;
*d=*a;
a->printPretty();
c->printPretty();
c->printPretty();
std::cout << (a->remove(340)) << std::endl;
a->printPretty();
*c=*b;
*e=*c;
e->printPretty();
std::cout << (e->remove(192)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (d->remove(126)) << std::endl;
d->printPretty();
std::cout << (d->insert(446)) << std::endl;
*b=*d;
std::cout << (b->insert(446)) << std::endl;
c->printPretty();
std::cout << (d->remove(43)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (b->remove(323)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
c->printPretty();
*e=*b;
*a=*c;
std::cout << (d->insert(446)) << std::endl;
std::cout << (d->insert(218)) << std::endl;
b->printPretty();
std::cout << (b->insert(467)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
e->printPretty();
std::cout << (b->remove(232)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
e->printPretty();
std::cout << (c->insert(341)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
c->printPretty();
std::cout << (d->insert(431)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (c->remove(248)) << std::endl;
a->printPretty();
std::cout << (c->insert(341)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(283)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
*d=*b;
std::cout << (b->remove(5)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
b->printPretty();
std::cout << (b->insert(82)) << std::endl;
*b=*d;
*e=*c;
std::cout << (a->remove(228)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (d->insert(341)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
*d=*c;
*c=*c;
std::cout << (c->insert(348)) << std::endl;
*d=*a;
std::cout << (e->remove(321)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
e->printPretty();
std::cout << (b->insert(448)) << std::endl;
a->printPretty();
std::cout << (c->insert(348)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
std::cout << (c->insert(348)) << std::endl;
d->printPretty();
std::cout << (c->remove(341)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
std::cout << (e->remove(496)) << std::endl;
*c=*e;
*a=*e;
std::cout << (b->insert(88)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (c->insert(383)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
*b=*a;
std::cout << (a->remove(278)) << std::endl;
*c=*d;
*b=*e;
*e=*a;
std::cout << (c->insert(42)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
*b=*d;
std::cout << (e->remove(78)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
*e=*a;
*a=*e;
std::cout << (e->remove(364)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(42)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
*c=*d;
std::cout << (b->remove(173)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
a->printPretty();
std::cout << (d->remove(124)) << std::endl;
*d=*e;
c->printPretty();
c->printPretty();
std::cout << (b->insert(429)) << std::endl;
e->printPretty();
std::cout << (d->remove(155)) << std::endl;
*d=*a;
std::cout << (b->insert(124)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
*b=*e;
std::cout << (c->remove(412)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
a->printPretty();
std::cout << (c->insert(351)) << std::endl;
*c=*e;
std::cout << (d->insert(155)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
*c=*a;
*c=*d;
*c=*b;
std::cout << (d->insert(155)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
c->printPretty();
*e=*b;
*e=*a;
d->printPretty();
std::cout << (d->insert(155)) << std::endl;
std::cout << (b->insert(392)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
*c=*e;
std::cout << (e->insert(392)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (b->remove(392)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (c->remove(280)) << std::endl;
std::cout << (d->insert(456)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
c->printPretty();
std::cout << (c->insert(92)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (c->insert(155)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
*e=*d;
std::cout << (d->remove(460)) << std::endl;
*d=*a;
*e=*c;
std::cout << (c->remove(155)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->insert(21)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->insert(155)) << std::endl;
*d=*c;
std::cout << (e->remove(199)) << std::endl;
*d=*a;
std::cout << (a->remove(21)) << std::endl;
a->printPretty();
*a=*a;
a->printPretty();
d->printPretty();
std::cout << (b->insert(155)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
*c=*b;
std::cout << (d->insert(430)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (e->insert(389)) << std::endl;
*c=*d;
std::cout << (e->insert(389)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
d->printPretty();
std::cout << (d->insert(186)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (d->insert(155)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
e->printPretty();
std::cout << (e->remove(155)) << std::endl;
c->printPretty();
std::cout << (c->remove(478)) << std::endl;
std::cout << (d->remove(205)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(475)) << std::endl;
d->printPretty();
std::cout << (b->insert(422)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
c->printPretty();
std::cout << (b->remove(155)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
a->printPretty();
std::cout << (e->insert(186)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (b->remove(168)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
std::cout << (b->insert(126)) << std::endl;
std::cout << (b->remove(452)) << std::endl;
*a=*d;
std::cout << (c->insert(475)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (b->insert(157)) << std::endl;
*b=*c;
a->printPretty();
e->printPretty();
std::cout << (d->insert(186)) << std::endl;
std::cout << (a->insert(21)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
*c=*d;
std::cout << (c->remove(155)) << std::endl;
c->printPretty();
std::cout << (a->remove(379)) << std::endl;
e->printPretty();
std::cout << (d->insert(148)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
c->printPretty();
*e=*c;
d->printPretty();
*d=*d;
std::cout << (e->remove(21)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
c->printPretty();
std::cout << (b->remove(332)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
e->printPretty();
std::cout << (b->remove(155)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
e->printPretty();
std::cout << (d->insert(463)) << std::endl;
*b=*e;
*d=*a;
std::cout << (e->remove(378)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
std::cout << (e->remove(186)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
std::cout << (c->remove(103)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
a->printPretty();
std::cout << (a->remove(214)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
b->printPretty();
std::cout << (e->remove(146)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
*d=*e;
std::cout << (e->remove(136)) << std::endl;
std::cout << (d->insert(136)) << std::endl;
std::cout << (a->insert(191)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (a->insert(317)) << std::endl;
b->printPretty();
std::cout << (a->remove(126)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
*c=*e;
std::cout << (c->insert(25)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
*d=*a;
std::cout << (c->insert(433)) << std::endl;
*c=*b;
std::cout << (a->remove(151)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
a->printPretty();
std::cout << (d->remove(317)) << std::endl;
c->printPretty();
std::cout << (d->insert(417)) << std::endl;
c->printPretty();
std::cout << (a->insert(317)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (d->remove(324)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (d->insert(187)) << std::endl;
*a=*c;
std::cout << (e->remove(108)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
b->printPretty();
std::cout << (c->remove(50)) << std::endl;
c->printPretty();
std::cout << (a->remove(344)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
*d=*d;
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
*d=*c;
std::cout << (d->insert(186)) << std::endl;
std::cout << (a->remove(349)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (e->insert(194)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
*e=*c;
std::cout << (a->insert(409)) << std::endl;
std::cout << (d->remove(118)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (d->insert(391)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
c->printPretty();
std::cout << (e->insert(172)) << std::endl;
*c=*c;
std::cout << (a->insert(393)) << std::endl;
std::cout << (b->remove(403)) << std::endl;
c->printPretty();
std::cout << (c->insert(85)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
a->printPretty();
std::cout << (a->insert(117)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (e->remove(306)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
*d=*a;
std::cout << (b->remove(362)) << std::endl;
*c=*c;
*b=*a;
std::cout << (a->insert(322)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
*c=*b;
a->printPretty();
*a=*a;
std::cout << (b->insert(260)) << std::endl;
c->printPretty();
std::cout << (e->insert(233)) << std::endl;
a->printPretty();
*b=*a;
b->printPretty();
std::cout << (a->insert(393)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
a->printPretty();
*a=*a;
c->printPretty();
std::cout << (a->insert(409)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
d->printPretty();
std::cout << (c->insert(434)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
*c=*d;
*e=*d;
c->printPretty();
c->printPretty();
*c=*c;
b->printPretty();
std::cout << (b->insert(322)) << std::endl;
b->printPretty();
a->printPretty();
*b=*c;
std::cout << (c->remove(260)) << std::endl;
e->printPretty();
*c=*b;
*c=*a;
std::cout << (e->insert(35)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
a->printPretty();
std::cout << (b->remove(117)) << std::endl;
*e=*e;
std::cout << (e->remove(290)) << std::endl;
b->printPretty();
std::cout << (c->remove(260)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
*d=*e;
std::cout << (d->remove(163)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (c->insert(117)) << std::endl;
c->printPretty();
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
d->printPretty();
std::cout << (d->insert(348)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (d->insert(194)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(35)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (d->insert(241)) << std::endl;
*c=*d;
std::cout << (b->insert(425)) << std::endl;
*b=*a;
std::cout << (c->insert(393)) << std::endl;
e->printPretty();
std::cout << (e->insert(459)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (c->insert(109)) << std::endl;
*a=*e;
std::cout << (d->remove(194)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
*c=*a;
std::cout << (b->remove(409)) << std::endl;
b->printPretty();
std::cout << (a->insert(18)) << std::endl;
std::cout << (a->insert(240)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (e->remove(117)) << std::endl;
std::cout << (b->remove(393)) << std::endl;
std::cout << (d->remove(348)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
*e=*e;
std::cout << (a->remove(111)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
std::cout << (e->remove(393)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
*c=*a;
std::cout << (d->remove(327)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
*e=*c;
std::cout << (e->insert(387)) << std::endl;
*d=*d;
std::cout << (e->remove(19)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
a->printPretty();
*c=*c;
*e=*d;
std::cout << (e->remove(241)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
d->printPretty();
std::cout << (e->remove(236)) << std::endl;
d->printPretty();
std::cout << (c->remove(451)) << std::endl;
*c=*a;
std::cout << (b->remove(459)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(271)) << std::endl;
*c=*d;
std::cout << (b->insert(117)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
b->printPretty();
std::cout << (c->remove(35)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
*b=*e;
std::cout << (c->remove(117)) << std::endl;
std::cout << (b->remove(393)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
*d=*d;
std::cout << (e->insert(393)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
*d=*e;
std::cout << (b->insert(456)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (b->remove(143)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
d->printPretty();
std::cout << (e->insert(227)) << std::endl;
return 0;
}
