#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(22)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (a->remove(264)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (a->remove(428)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (a->remove(241)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (a->remove(4)) << std::endl;
b->printPretty();
std::cout << (a->insert(158)) << std::endl;
a->printPretty();
std::cout << (b->remove(93)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (e->remove(261)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
*d=*d;
std::cout << (b->insert(47)) << std::endl;
std::cout << (c->remove(104)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
a->printPretty();
std::cout << (d->remove(92)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(166)) << std::endl;
d->printPretty();
std::cout << (c->remove(47)) << std::endl;
b->printPretty();
std::cout << (b->insert(166)) << std::endl;
*a=*d;
*a=*b;
std::cout << (d->insert(112)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
*e=*a;
*c=*e;
std::cout << (d->insert(112)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
d->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->remove(115)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
d->printPretty();
std::cout << (d->remove(112)) << std::endl;
*c=*b;
std::cout << (e->insert(106)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
b->printPretty();
std::cout << (a->insert(253)) << std::endl;
*c=*d;
std::cout << (c->insert(59)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
b->printPretty();
*d=*e;
d->printPretty();
std::cout << (c->insert(59)) << std::endl;
*a=*e;
std::cout << (e->remove(160)) << std::endl;
*c=*a;
std::cout << (a->insert(231)) << std::endl;
*e=*d;
std::cout << (c->insert(446)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (c->insert(231)) << std::endl;
std::cout << (c->insert(446)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
std::cout << (b->remove(496)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
*b=*b;
std::cout << (c->insert(136)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
*a=*e;
*b=*e;
std::cout << (b->insert(231)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->insert(231)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
std::cout << (c->insert(446)) << std::endl;
std::cout << (c->insert(231)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (e->remove(231)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
*e=*e;
*c=*e;
std::cout << (c->insert(216)) << std::endl;
b->printPretty();
std::cout << (c->remove(216)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
*c=*e;
std::cout << (d->insert(216)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
*c=*b;
std::cout << (e->insert(494)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (e->remove(494)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
*e=*c;
d->printPretty();
b->printPretty();
std::cout << (e->remove(495)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
*a=*c;
std::cout << (d->remove(231)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
d->printPretty();
a->printPretty();
*b=*b;
std::cout << (a->remove(499)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
*b=*b;
std::cout << (a->insert(482)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->remove(158)) << std::endl;
d->printPretty();
std::cout << (d->insert(216)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (e->remove(347)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
b->printPretty();
std::cout << (d->remove(228)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
*d=*c;
std::cout << (c->insert(186)) << std::endl;
std::cout << (d->remove(499)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
*c=*a;
std::cout << (e->remove(353)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (a->remove(336)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
*e=*c;
*d=*a;
e->printPretty();
std::cout << (a->insert(95)) << std::endl;
*e=*b;
std::cout << (c->remove(273)) << std::endl;
e->printPretty();
std::cout << (e->insert(302)) << std::endl;
*e=*e;
std::cout << (d->remove(56)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(302)) << std::endl;
b->printPretty();
std::cout << (c->remove(221)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
d->printPretty();
std::cout << (a->remove(13)) << std::endl;
c->printPretty();
std::cout << (d->remove(34)) << std::endl;
*d=*e;
b->printPretty();
d->printPretty();
std::cout << (a->insert(95)) << std::endl;
*e=*a;
std::cout << (d->insert(19)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (b->remove(27)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
e->printPretty();
std::cout << (d->remove(218)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
std::cout << (a->insert(52)) << std::endl;
a->printPretty();
std::cout << (d->remove(221)) << std::endl;
*b=*c;
a->printPretty();
d->printPretty();
std::cout << (c->insert(454)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
*c=*d;
c->printPretty();
c->printPretty();
std::cout << (d->insert(172)) << std::endl;
*d=*c;
std::cout << (d->remove(106)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
b->printPretty();
*d=*e;
e->printPretty();
*c=*b;
std::cout << (e->remove(421)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
*c=*c;
*d=*c;
*e=*b;
std::cout << (b->remove(110)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->insert(421)) << std::endl;
c->printPretty();
std::cout << (a->insert(52)) << std::endl;
std::cout << (c->remove(421)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
a->printPretty();
std::cout << (a->insert(52)) << std::endl;
e->printPretty();
std::cout << (d->insert(57)) << std::endl;
*d=*a;
std::cout << (d->insert(95)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(99)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (b->remove(121)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
*b=*c;
std::cout << (b->insert(154)) << std::endl;
*a=*e;
std::cout << (d->insert(27)) << std::endl;
*a=*a;
std::cout << (d->insert(95)) << std::endl;
*e=*b;
*b=*c;
std::cout << (b->remove(154)) << std::endl;
std::cout << (d->insert(107)) << std::endl;
std::cout << (d->insert(480)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
e->printPretty();
std::cout << (e->remove(154)) << std::endl;
c->printPretty();
std::cout << (d->remove(158)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
*b=*d;
std::cout << (d->remove(130)) << std::endl;
*b=*d;
std::cout << (b->remove(371)) << std::endl;
*d=*a;
std::cout << (c->insert(128)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
*e=*d;
std::cout << (e->insert(52)) << std::endl;
std::cout << (d->remove(150)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
*d=*b;
*d=*b;
std::cout << (b->insert(95)) << std::endl;
*d=*a;
std::cout << (b->remove(2)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
a->printPretty();
*e=*a;
e->printPretty();
std::cout << (a->remove(52)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
*a=*a;
std::cout << (c->remove(455)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (b->insert(107)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
*d=*a;
*c=*a;
std::cout << (c->remove(480)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
*c=*d;
std::cout << (d->remove(289)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (e->remove(27)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(480)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
a->printPretty();
std::cout << (d->remove(54)) << std::endl;
c->printPretty();
std::cout << (b->remove(480)) << std::endl;
std::cout << (b->remove(487)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
*a=*d;
std::cout << (a->remove(182)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
d->printPretty();
e->printPretty();
*e=*d;
std::cout << (e->remove(480)) << std::endl;
e->printPretty();
*b=*b;
std::cout << (e->insert(410)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->insert(482)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
*c=*e;
std::cout << (e->remove(40)) << std::endl;
std::cout << (a->remove(480)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
a->printPretty();
std::cout << (c->insert(392)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
*c=*b;
std::cout << (b->remove(482)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
d->printPretty();
std::cout << (a->remove(376)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (d->remove(27)) << std::endl;
*c=*a;
*a=*b;
e->printPretty();
std::cout << (c->insert(487)) << std::endl;
std::cout << (d->insert(345)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
e->printPretty();
std::cout << (e->insert(179)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
std::cout << (d->insert(345)) << std::endl;
std::cout << (b->remove(487)) << std::endl;
c->printPretty();
std::cout << (d->remove(390)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
d->printPretty();
std::cout << (e->insert(27)) << std::endl;
*b=*a;
std::cout << (d->remove(345)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
*e=*b;
std::cout << (c->remove(184)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
c->printPretty();
std::cout << (e->insert(479)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
std::cout << (a->insert(59)) << std::endl;
d->printPretty();
std::cout << (b->remove(364)) << std::endl;
*e=*c;
std::cout << (d->remove(266)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
*e=*b;
std::cout << (e->insert(479)) << std::endl;
*a=*d;
std::cout << (a->remove(35)) << std::endl;
d->printPretty();
std::cout << (e->insert(51)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
*b=*b;
std::cout << (d->remove(296)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
e->printPretty();
std::cout << (b->insert(448)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
std::cout << (e->remove(474)) << std::endl;
*c=*b;
std::cout << (b->remove(430)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
*b=*d;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
*c=*c;
std::cout << (d->remove(86)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
e->printPretty();
std::cout << (a->insert(185)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
*e=*c;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
b->printPretty();
std::cout << (e->remove(479)) << std::endl;
*b=*b;
std::cout << (e->insert(82)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
*c=*b;
std::cout << (e->insert(82)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
e->printPretty();
a->printPretty();
*e=*b;
d->printPretty();
std::cout << (a->insert(452)) << std::endl;
*a=*e;
*b=*c;
c->printPretty();
e->printPretty();
std::cout << (a->remove(147)) << std::endl;
*e=*a;
*e=*e;
std::cout << (d->insert(158)) << std::endl;
std::cout << (e->remove(381)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->insert(404)) << std::endl;
*c=*e;
*a=*b;
std::cout << (a->remove(257)) << std::endl;
*b=*a;
std::cout << (a->insert(404)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (c->remove(408)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
*d=*a;
std::cout << (a->remove(433)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (a->insert(404)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->insert(448)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
*e=*b;
*a=*e;
std::cout << (a->remove(140)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
e->printPretty();
a->printPretty();
b->printPretty();
*d=*b;
std::cout << (d->insert(33)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
std::cout << (e->insert(448)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
*e=*d;
std::cout << (c->remove(294)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
a->printPretty();
std::cout << (c->insert(390)) << std::endl;
b->printPretty();
*a=*a;
a->printPretty();
std::cout << (a->insert(382)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (d->insert(404)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (b->insert(271)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
std::cout << (a->remove(275)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
*c=*c;
std::cout << (e->remove(33)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
*a=*d;
std::cout << (d->insert(152)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
*d=*e;
c->printPretty();
std::cout << (c->insert(207)) << std::endl;
d->printPretty();
d->printPretty();
*e=*c;
*b=*d;
c->printPretty();
*b=*e;
std::cout << (d->remove(241)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (a->remove(152)) << std::endl;
c->printPretty();
std::cout << (c->insert(362)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (b->insert(288)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(448)) << std::endl;
a->printPretty();
std::cout << (a->remove(432)) << std::endl;
std::cout << (c->remove(390)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
c->printPretty();
std::cout << (c->insert(482)) << std::endl;
*b=*c;
*e=*a;
std::cout << (b->insert(103)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
*d=*d;
std::cout << (c->insert(448)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
std::cout << (c->insert(353)) << std::endl;
d->printPretty();
std::cout << (a->insert(75)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (d->insert(376)) << std::endl;
std::cout << (d->insert(167)) << std::endl;
std::cout << (a->remove(130)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
e->printPretty();
std::cout << (b->remove(198)) << std::endl;
std::cout << (c->remove(448)) << std::endl;
e->printPretty();
*e=*d;
b->printPretty();
std::cout << (b->insert(447)) << std::endl;
*e=*a;
std::cout << (c->insert(307)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (b->remove(482)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (b->remove(103)) << std::endl;
std::cout << (c->remove(353)) << std::endl;
b->printPretty();
*a=*d;
*d=*e;
std::cout << (c->remove(253)) << std::endl;
*e=*d;
*d=*e;
std::cout << (b->remove(447)) << std::endl;
std::cout << (e->insert(410)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (d->remove(48)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->insert(162)) << std::endl;
*c=*d;
std::cout << (b->remove(89)) << std::endl;
e->printPretty();
std::cout << (e->insert(290)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (c->remove(255)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
std::cout << (e->insert(490)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
a->printPretty();
std::cout << (a->remove(379)) << std::endl;
std::cout << (a->remove(376)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
*b=*b;
std::cout << (c->remove(290)) << std::endl;
*e=*e;
std::cout << (e->insert(410)) << std::endl;
std::cout << (e->remove(490)) << std::endl;
*a=*c;
std::cout << (c->insert(384)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (b->insert(460)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->remove(211)) << std::endl;
a->printPretty();
std::cout << (b->remove(199)) << std::endl;
d->printPretty();
std::cout << (b->insert(207)) << std::endl;
*a=*e;
return 0;
}
