#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->remove(91)) << std::endl;
a->printPretty();
*d=*b;
*b=*a;
d->printPretty();
*d=*d;
*c=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (b->remove(325)) << std::endl;
*c=*e;
std::cout << (b->insert(456)) << std::endl;
std::cout << (e->remove(45)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
*c=*c;
std::cout << (b->remove(456)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
*b=*b;
*d=*c;
*d=*d;
std::cout << (e->remove(318)) << std::endl;
std::cout << (b->insert(346)) << std::endl;
c->printPretty();
std::cout << (e->remove(34)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
d->printPretty();
std::cout << (d->remove(40)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
c->printPretty();
std::cout << (c->insert(315)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
*e=*a;
*c=*e;
*e=*d;
std::cout << (b->remove(256)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
*e=*e;
*d=*e;
*e=*d;
std::cout << (b->remove(346)) << std::endl;
c->printPretty();
std::cout << (a->remove(129)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (d->remove(280)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
*d=*a;
*b=*a;
b->printPretty();
std::cout << (d->remove(499)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (a->insert(199)) << std::endl;
*c=*b;
std::cout << (a->insert(199)) << std::endl;
*e=*a;
std::cout << (d->remove(70)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
e->printPretty();
std::cout << (b->insert(134)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (d->insert(372)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
*a=*d;
std::cout << (b->remove(322)) << std::endl;
*c=*b;
std::cout << (a->remove(499)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
*b=*e;
std::cout << (b->remove(105)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (d->remove(304)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (a->insert(199)) << std::endl;
a->printPretty();
std::cout << (c->insert(377)) << std::endl;
std::cout << (d->remove(372)) << std::endl;
*a=*c;
std::cout << (b->remove(86)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
a->printPretty();
std::cout << (b->insert(310)) << std::endl;
std::cout << (a->remove(377)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (e->insert(199)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
c->printPretty();
std::cout << (c->insert(376)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (d->remove(175)) << std::endl;
std::cout << (c->remove(83)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
a->printPretty();
std::cout << (c->remove(377)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
std::cout << (d->remove(43)) << std::endl;
*a=*d;
std::cout << (e->remove(292)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (c->insert(198)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
d->printPretty();
std::cout << (a->insert(186)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
*a=*e;
c->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->remove(376)) << std::endl;
std::cout << (a->insert(215)) << std::endl;
*a=*b;
std::cout << (c->remove(10)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
c->printPretty();
std::cout << (a->remove(439)) << std::endl;
*c=*c;
std::cout << (e->insert(207)) << std::endl;
std::cout << (b->remove(15)) << std::endl;
std::cout << (e->remove(317)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
*c=*e;
std::cout << (a->insert(476)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
std::cout << (c->insert(58)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
*d=*e;
std::cout << (a->insert(76)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
e->printPretty();
std::cout << (d->remove(242)) << std::endl;
*a=*b;
*c=*e;
std::cout << (b->insert(366)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
std::cout << (d->remove(335)) << std::endl;
std::cout << (a->insert(439)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
d->printPretty();
e->printPretty();
a->printPretty();
*a=*b;
*d=*d;
std::cout << (c->remove(47)) << std::endl;
e->printPretty();
std::cout << (d->remove(184)) << std::endl;
std::cout << (b->remove(366)) << std::endl;
b->printPretty();
std::cout << (a->insert(439)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
e->printPretty();
std::cout << (a->insert(190)) << std::endl;
c->printPretty();
std::cout << (b->remove(344)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (c->insert(33)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (d->insert(454)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
e->printPretty();
std::cout << (b->remove(462)) << std::endl;
*e=*e;
std::cout << (c->remove(33)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
d->printPretty();
std::cout << (c->remove(220)) << std::endl;
*d=*c;
*c=*d;
*e=*e;
*e=*c;
std::cout << (d->remove(42)) << std::endl;
*e=*e;
d->printPretty();
*c=*a;
a->printPretty();
std::cout << (d->remove(484)) << std::endl;
d->printPretty();
std::cout << (b->remove(335)) << std::endl;
d->printPretty();
e->printPretty();
*a=*b;
d->printPretty();
*a=*e;
std::cout << (b->insert(466)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (a->insert(320)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
c->printPretty();
std::cout << (b->insert(466)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
c->printPretty();
std::cout << (e->remove(220)) << std::endl;
*c=*a;
std::cout << (c->insert(320)) << std::endl;
b->printPretty();
std::cout << (a->remove(320)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (b->remove(70)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
*a=*a;
*a=*e;
std::cout << (d->remove(138)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
c->printPretty();
*b=*d;
*e=*a;
std::cout << (b->remove(492)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
*a=*a;
*b=*a;
b->printPretty();
std::cout << (e->insert(234)) << std::endl;
*c=*e;
std::cout << (a->remove(373)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
*a=*d;
std::cout << (c->remove(204)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
*a=*b;
*e=*a;
std::cout << (c->remove(350)) << std::endl;
a->printPretty();
std::cout << (c->insert(440)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
a->printPretty();
std::cout << (e->remove(87)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (d->insert(431)) << std::endl;
b->printPretty();
std::cout << (c->remove(464)) << std::endl;
e->printPretty();
std::cout << (b->remove(390)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
d->printPretty();
std::cout << (b->remove(247)) << std::endl;
*b=*e;
*a=*e;
std::cout << (c->insert(16)) << std::endl;
*a=*c;
std::cout << (e->remove(456)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
d->printPretty();
*e=*b;
*c=*e;
e->printPretty();
std::cout << (b->remove(48)) << std::endl;
*d=*c;
std::cout << (c->insert(288)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->remove(463)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
b->printPretty();
std::cout << (c->remove(66)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (a->insert(440)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (b->insert(175)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
*d=*e;
e->printPretty();
b->printPretty();
std::cout << (c->remove(499)) << std::endl;
d->printPretty();
std::cout << (c->insert(19)) << std::endl;
std::cout << (d->remove(88)) << std::endl;
*c=*b;
std::cout << (a->insert(213)) << std::endl;
std::cout << (e->remove(311)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (a->remove(464)) << std::endl;
*a=*a;
std::cout << (a->insert(213)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (e->insert(440)) << std::endl;
*b=*b;
*d=*c;
d->printPretty();
*c=*c;
std::cout << (e->remove(283)) << std::endl;
std::cout << (e->remove(440)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
*b=*e;
std::cout << (b->remove(424)) << std::endl;
*c=*d;
std::cout << (b->insert(181)) << std::endl;
b->printPretty();
std::cout << (a->insert(440)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
*c=*b;
std::cout << (c->remove(171)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
a->printPretty();
d->printPretty();
*d=*b;
std::cout << (a->remove(367)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->remove(440)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
*d=*c;
std::cout << (d->insert(181)) << std::endl;
*d=*b;
*e=*b;
std::cout << (c->remove(369)) << std::endl;
d->printPretty();
std::cout << (e->remove(335)) << std::endl;
a->printPretty();
std::cout << (c->remove(181)) << std::endl;
*a=*c;
*c=*b;
a->printPretty();
std::cout << (a->insert(498)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
*b=*b;
std::cout << (e->remove(472)) << std::endl;
b->printPretty();
*a=*e;
*a=*a;
*e=*b;
std::cout << (d->insert(81)) << std::endl;
d->printPretty();
std::cout << (a->remove(353)) << std::endl;
c->printPretty();
std::cout << (a->insert(403)) << std::endl;
std::cout << (d->insert(378)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (d->insert(81)) << std::endl;
*a=*a;
std::cout << (d->remove(30)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (a->insert(28)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
*e=*b;
c->printPretty();
*d=*b;
std::cout << (e->remove(403)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
d->printPretty();
std::cout << (d->insert(403)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
a->printPretty();
std::cout << (a->insert(28)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
*e=*e;
*a=*e;
c->printPretty();
std::cout << (b->insert(286)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
e->printPretty();
std::cout << (a->insert(346)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
*e=*d;
std::cout << (c->remove(218)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
*a=*b;
std::cout << (e->remove(472)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
*d=*a;
std::cout << (b->remove(406)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (e->remove(403)) << std::endl;
std::cout << (d->remove(356)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (e->remove(362)) << std::endl;
*c=*e;
c->printPretty();
*d=*d;
std::cout << (a->remove(403)) << std::endl;
c->printPretty();
std::cout << (b->remove(403)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
e->printPretty();
*c=*c;
d->printPretty();
*a=*e;
std::cout << (c->insert(496)) << std::endl;
*e=*a;
std::cout << (d->insert(49)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
b->printPretty();
std::cout << (d->insert(168)) << std::endl;
std::cout << (d->remove(275)) << std::endl;
*b=*b;
std::cout << (d->insert(373)) << std::endl;
std::cout << (b->remove(15)) << std::endl;
*d=*e;
std::cout << (d->remove(54)) << std::endl;
*a=*c;
std::cout << (d->remove(273)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
std::cout << (a->insert(54)) << std::endl;
std::cout << (d->insert(345)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
*a=*c;
std::cout << (c->remove(387)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
*e=*e;
a->printPretty();
*d=*a;
std::cout << (a->remove(24)) << std::endl;
*d=*a;
*b=*a;
std::cout << (a->insert(102)) << std::endl;
d->printPretty();
std::cout << (e->remove(180)) << std::endl;
*e=*d;
std::cout << (e->remove(376)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
std::cout << (c->insert(12)) << std::endl;
e->printPretty();
std::cout << (a->insert(416)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
a->printPretty();
std::cout << (b->remove(205)) << std::endl;
*e=*c;
*c=*b;
std::cout << (d->insert(246)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
d->printPretty();
std::cout << (a->insert(416)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
std::cout << (c->insert(496)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
*d=*a;
std::cout << (d->insert(280)) << std::endl;
std::cout << (a->remove(54)) << std::endl;
c->printPretty();
std::cout << (d->insert(42)) << std::endl;
std::cout << (a->remove(172)) << std::endl;
*c=*d;
*e=*c;
a->printPretty();
std::cout << (c->remove(133)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
*e=*b;
std::cout << (d->insert(42)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (c->insert(429)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*b=*b;
std::cout << (c->insert(429)) << std::endl;
*a=*a;
std::cout << (b->remove(225)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
std::cout << (d->remove(74)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
*a=*b;
std::cout << (c->insert(454)) << std::endl;
a->printPretty();
std::cout << (a->insert(496)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (c->remove(454)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
*a=*b;
std::cout << (e->insert(434)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
*e=*a;
std::cout << (c->insert(446)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (a->insert(56)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
a->printPretty();
std::cout << (d->remove(86)) << std::endl;
a->printPretty();
std::cout << (d->insert(56)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (c->remove(33)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->remove(467)) << std::endl;
*e=*a;
std::cout << (e->insert(222)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*e=*d;
*c=*c;
std::cout << (a->remove(97)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
a->printPretty();
std::cout << (e->remove(102)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
std::cout << (a->remove(56)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
c->printPretty();
a->printPretty();
d->printPretty();
std::cout << (d->remove(437)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
b->printPretty();
std::cout << (c->remove(472)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
a->printPretty();
std::cout << (d->insert(416)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*a=*e;
*a=*c;
e->printPretty();
*c=*e;
std::cout << (b->insert(496)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
e->printPretty();
std::cout << (c->insert(203)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (d->remove(71)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (b->remove(7)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
a->printPretty();
*b=*e;
*a=*a;
e->printPretty();
std::cout << (a->remove(457)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
*e=*d;
std::cout << (b->remove(137)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
e->printPretty();
std::cout << (e->remove(139)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
std::cout << (c->insert(348)) << std::endl;
*a=*d;
std::cout << (e->insert(416)) << std::endl;
std::cout << (d->insert(449)) << std::endl;
d->printPretty();
return 0;
}
