#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(33)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (d->remove(322)) << std::endl;
*b=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
e->printPretty();
*c=*e;
std::cout << (a->insert(295)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(295)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
a->printPretty();
e->printPretty();
*b=*c;
a->printPretty();
std::cout << (c->insert(74)) << std::endl;
std::cout << (a->insert(472)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (b->insert(369)) << std::endl;
e->printPretty();
std::cout << (d->insert(435)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
*c=*e;
std::cout << (b->insert(438)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
d->printPretty();
std::cout << (e->insert(107)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
a->printPretty();
std::cout << (b->remove(429)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (c->insert(329)) << std::endl;
c->printPretty();
std::cout << (a->remove(413)) << std::endl;
std::cout << (a->remove(285)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
*c=*a;
std::cout << (c->insert(8)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
*e=*a;
*e=*d;
*a=*a;
std::cout << (c->insert(8)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (a->remove(8)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
std::cout << (d->remove(334)) << std::endl;
std::cout << (d->insert(177)) << std::endl;
std::cout << (e->insert(401)) << std::endl;
c->printPretty();
std::cout << (a->remove(161)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (d->remove(177)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->remove(442)) << std::endl;
std::cout << (c->insert(303)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
e->printPretty();
std::cout << (c->remove(287)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (b->remove(249)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
e->printPretty();
std::cout << (e->remove(442)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
*c=*b;
std::cout << (a->remove(103)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->insert(228)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
a->printPretty();
std::cout << (e->remove(82)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(92)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
*a=*d;
*d=*e;
std::cout << (e->insert(171)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (b->insert(268)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
*b=*e;
std::cout << (a->insert(222)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
std::cout << (d->remove(41)) << std::endl;
*c=*c;
*b=*d;
std::cout << (d->remove(153)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
*d=*b;
std::cout << (b->insert(154)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
b->printPretty();
std::cout << (d->insert(444)) << std::endl;
a->printPretty();
std::cout << (a->remove(222)) << std::endl;
*b=*c;
std::cout << (c->remove(295)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
b->printPretty();
std::cout << (c->insert(369)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
c->printPretty();
std::cout << (d->insert(153)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->remove(153)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (e->insert(448)) << std::endl;
c->printPretty();
*b=*a;
*a=*d;
std::cout << (e->remove(448)) << std::endl;
d->printPretty();
std::cout << (d->insert(97)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (d->remove(205)) << std::endl;
*e=*c;
std::cout << (c->remove(435)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (a->insert(418)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (d->insert(369)) << std::endl;
std::cout << (a->remove(488)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
c->printPretty();
std::cout << (b->insert(79)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
std::cout << (d->remove(141)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (c->insert(427)) << std::endl;
*e=*a;
std::cout << (e->remove(487)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
*c=*b;
std::cout << (b->insert(79)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
std::cout << (d->insert(405)) << std::endl;
std::cout << (c->insert(353)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
*d=*d;
a->printPretty();
b->printPretty();
*e=*e;
b->printPretty();
e->printPretty();
std::cout << (c->insert(333)) << std::endl;
c->printPretty();
std::cout << (b->remove(27)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
*b=*d;
std::cout << (e->insert(79)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->remove(345)) << std::endl;
d->printPretty();
std::cout << (a->remove(461)) << std::endl;
a->printPretty();
*c=*e;
*a=*c;
std::cout << (b->remove(12)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
*a=*a;
std::cout << (d->insert(129)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
c->printPretty();
std::cout << (d->remove(129)) << std::endl;
std::cout << (a->insert(59)) << std::endl;
c->printPretty();
*d=*d;
d->printPretty();
std::cout << (c->remove(423)) << std::endl;
std::cout << (b->insert(183)) << std::endl;
*e=*a;
std::cout << (a->insert(79)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (a->insert(59)) << std::endl;
*b=*d;
*d=*d;
*b=*e;
*e=*c;
std::cout << (b->remove(320)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
a->printPretty();
std::cout << (c->insert(135)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
std::cout << (d->remove(499)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
*d=*d;
std::cout << (a->remove(59)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (a->insert(79)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (e->remove(79)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (c->remove(79)) << std::endl;
*b=*e;
std::cout << (d->remove(459)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
*a=*e;
std::cout << (b->remove(135)) << std::endl;
std::cout << (c->remove(135)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
*b=*b;
*d=*e;
std::cout << (d->insert(135)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
*c=*a;
*a=*d;
std::cout << (d->insert(344)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (c->remove(135)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (d->remove(136)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
*b=*c;
std::cout << (d->insert(276)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(9)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
d->printPretty();
e->printPretty();
*e=*c;
std::cout << (d->insert(101)) << std::endl;
std::cout << (e->insert(488)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
d->printPretty();
std::cout << (a->insert(206)) << std::endl;
*a=*b;
std::cout << (b->remove(7)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
e->printPretty();
std::cout << (c->remove(298)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (c->remove(47)) << std::endl;
a->printPretty();
std::cout << (c->insert(472)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (a->insert(98)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
*a=*b;
*d=*c;
std::cout << (c->remove(472)) << std::endl;
std::cout << (e->insert(488)) << std::endl;
*e=*a;
*b=*e;
*a=*b;
d->printPretty();
*a=*a;
std::cout << (c->remove(158)) << std::endl;
*c=*e;
std::cout << (e->insert(106)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(495)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->remove(427)) << std::endl;
*c=*e;
std::cout << (c->insert(91)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
*c=*e;
std::cout << (a->remove(61)) << std::endl;
*e=*c;
std::cout << (c->insert(106)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
std::cout << (e->remove(314)) << std::endl;
e->printPretty();
std::cout << (b->insert(269)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
*c=*b;
std::cout << (e->remove(425)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
c->printPretty();
std::cout << (b->insert(269)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
*b=*a;
*d=*d;
d->printPretty();
std::cout << (e->remove(364)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (c->insert(66)) << std::endl;
b->printPretty();
std::cout << (a->remove(485)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
*e=*a;
std::cout << (d->insert(415)) << std::endl;
d->printPretty();
*a=*a;
c->printPretty();
b->printPretty();
std::cout << (d->remove(472)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
*b=*b;
*e=*c;
std::cout << (b->remove(311)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(123)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
std::cout << (d->insert(67)) << std::endl;
std::cout << (d->insert(340)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (d->insert(209)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
std::cout << (d->remove(30)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (a->remove(123)) << std::endl;
std::cout << (d->insert(209)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
b->printPretty();
*c=*d;
*d=*d;
std::cout << (c->insert(340)) << std::endl;
*b=*a;
std::cout << (b->remove(295)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
*d=*c;
*b=*d;
b->printPretty();
*c=*d;
*d=*c;
std::cout << (b->insert(209)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*a=*a;
std::cout << (d->insert(444)) << std::endl;
*a=*e;
std::cout << (d->insert(444)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
*c=*b;
std::cout << (a->insert(494)) << std::endl;
d->printPretty();
std::cout << (a->remove(494)) << std::endl;
*a=*e;
std::cout << (a->insert(12)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
*a=*e;
std::cout << (a->insert(494)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
std::cout << (c->insert(67)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
*c=*e;
std::cout << (b->insert(318)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->insert(340)) << std::endl;
std::cout << (d->insert(340)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
b->printPretty();
std::cout << (e->insert(198)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (d->remove(340)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
*c=*c;
std::cout << (c->insert(494)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
e->printPretty();
std::cout << (d->remove(6)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
*d=*c;
*d=*b;
std::cout << (d->remove(380)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(318)) << std::endl;
c->printPretty();
std::cout << (c->insert(494)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(442)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (d->remove(67)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (c->insert(237)) << std::endl;
*e=*a;
std::cout << (e->insert(325)) << std::endl;
std::cout << (b->remove(370)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
d->printPretty();
std::cout << (d->remove(33)) << std::endl;
std::cout << (d->insert(318)) << std::endl;
std::cout << (d->insert(318)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
d->printPretty();
std::cout << (c->insert(439)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (c->remove(66)) << std::endl;
*a=*b;
*e=*b;
std::cout << (a->insert(299)) << std::endl;
*a=*b;
std::cout << (d->insert(74)) << std::endl;
*d=*b;
*d=*b;
std::cout << (d->remove(67)) << std::endl;
std::cout << (d->insert(433)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
d->printPretty();
std::cout << (b->remove(219)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (a->insert(67)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
*a=*e;
std::cout << (b->remove(255)) << std::endl;
*b=*c;
std::cout << (d->insert(33)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
*d=*e;
*c=*d;
std::cout << (c->remove(67)) << std::endl;
*e=*e;
std::cout << (c->remove(433)) << std::endl;
e->printPretty();
std::cout << (a->insert(67)) << std::endl;
a->printPretty();
std::cout << (d->remove(316)) << std::endl;
b->printPretty();
std::cout << (e->remove(345)) << std::endl;
*d=*e;
c->printPretty();
std::cout << (e->insert(156)) << std::endl;
*d=*e;
std::cout << (c->insert(497)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
a->printPretty();
std::cout << (e->remove(67)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
*d=*b;
std::cout << (a->remove(67)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
*d=*b;
std::cout << (e->remove(118)) << std::endl;
e->printPretty();
std::cout << (e->insert(156)) << std::endl;
c->printPretty();
std::cout << (b->insert(123)) << std::endl;
std::cout << (b->insert(123)) << std::endl;
b->printPretty();
std::cout << (c->insert(289)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (b->insert(123)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
std::cout << (a->insert(482)) << std::endl;
*e=*e;
std::cout << (c->remove(289)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
*e=*a;
std::cout << (d->remove(396)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
d->printPretty();
std::cout << (e->remove(482)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
*b=*e;
std::cout << (d->remove(494)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (d->remove(376)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
c->printPretty();
std::cout << (a->insert(174)) << std::endl;
*e=*e;
*b=*e;
std::cout << (d->insert(78)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->insert(174)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (e->insert(163)) << std::endl;
b->printPretty();
c->printPretty();
c->printPretty();
e->printPretty();
std::cout << (d->remove(80)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
*b=*b;
std::cout << (c->insert(43)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(457)) << std::endl;
std::cout << (c->insert(429)) << std::endl;
std::cout << (b->remove(232)) << std::endl;
std::cout << (e->insert(64)) << std::endl;
c->printPretty();
d->printPretty();
e->printPretty();
c->printPretty();
std::cout << (e->insert(129)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
*c=*a;
*a=*a;
std::cout << (a->remove(65)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (a->remove(73)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->insert(323)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (c->insert(456)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (a->insert(342)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
*b=*c;
*e=*a;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (d->insert(456)) << std::endl;
*b=*a;
std::cout << (e->remove(1)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
std::cout << (c->insert(456)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (c->insert(352)) << std::endl;
*d=*b;
std::cout << (b->remove(174)) << std::endl;
std::cout << (c->remove(100)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
d->printPretty();
std::cout << (c->remove(458)) << std::endl;
b->printPretty();
std::cout << (e->insert(478)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (a->remove(342)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
*d=*a;
std::cout << (b->remove(1)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
c->printPretty();
e->printPretty();
*d=*b;
std::cout << (c->insert(457)) << std::endl;
*b=*c;
b->printPretty();
*b=*e;
std::cout << (c->remove(456)) << std::endl;
*a=*d;
std::cout << (d->insert(413)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
std::cout << (a->insert(321)) << std::endl;
std::cout << (b->insert(342)) << std::endl;
c->printPretty();
return 0;
}
