#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(304)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(275)) << std::endl;
*a=*b;
*a=*b;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
a->printPretty();
*c=*a;
std::cout << (b->insert(388)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->remove(487)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
e->printPretty();
std::cout << (b->insert(490)) << std::endl;
std::cout << (a->insert(168)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->insert(191)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
d->printPretty();
std::cout << (b->remove(181)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
*d=*a;
std::cout << (d->insert(373)) << std::endl;
std::cout << (d->insert(221)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (a->remove(168)) << std::endl;
b->printPretty();
std::cout << (d->remove(221)) << std::endl;
*e=*b;
*c=*b;
a->printPretty();
d->printPretty();
*d=*d;
std::cout << (c->insert(368)) << std::endl;
std::cout << (a->insert(296)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (a->insert(296)) << std::endl;
std::cout << (b->remove(388)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (d->insert(321)) << std::endl;
std::cout << (a->remove(303)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (a->insert(296)) << std::endl;
*b=*c;
std::cout << (e->remove(368)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
std::cout << (a->remove(500)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (b->remove(191)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
*e=*b;
std::cout << (e->remove(104)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
a->printPretty();
std::cout << (d->insert(65)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
std::cout << (b->remove(189)) << std::endl;
*b=*a;
*d=*b;
std::cout << (d->insert(299)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
d->printPretty();
std::cout << (a->remove(220)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
*d=*a;
std::cout << (a->insert(48)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
b->printPretty();
std::cout << (e->insert(385)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
c->printPretty();
std::cout << (e->remove(385)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
*e=*a;
std::cout << (b->insert(349)) << std::endl;
*b=*e;
std::cout << (c->insert(490)) << std::endl;
std::cout << (c->remove(191)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
*b=*c;
std::cout << (c->insert(41)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
a->printPretty();
std::cout << (c->remove(185)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
std::cout << (e->insert(191)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
*b=*a;
*b=*b;
std::cout << (a->remove(467)) << std::endl;
*a=*c;
std::cout << (c->remove(490)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (e->remove(191)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
e->printPretty();
std::cout << (a->insert(391)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
*a=*c;
std::cout << (e->insert(217)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
std::cout << (c->remove(104)) << std::endl;
*d=*d;
std::cout << (c->insert(40)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
b->printPretty();
std::cout << (d->insert(247)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
*e=*e;
std::cout << (c->remove(205)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (b->remove(28)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(492)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (d->remove(414)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->insert(480)) << std::endl;
e->printPretty();
std::cout << (e->insert(299)) << std::endl;
std::cout << (e->remove(45)) << std::endl;
*c=*a;
*d=*b;
std::cout << (e->insert(297)) << std::endl;
*b=*e;
std::cout << (d->remove(240)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
c->printPretty();
std::cout << (c->remove(40)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
*a=*c;
std::cout << (c->insert(41)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
*a=*a;
std::cout << (b->insert(48)) << std::endl;
a->printPretty();
std::cout << (d->remove(211)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
*a=*e;
std::cout << (d->remove(40)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (e->remove(299)) << std::endl;
*c=*a;
std::cout << (a->remove(299)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
d->printPretty();
std::cout << (a->remove(97)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
a->printPretty();
std::cout << (a->remove(48)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
std::cout << (e->insert(297)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(48)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
*d=*c;
d->printPretty();
e->printPretty();
*a=*d;
c->printPretty();
std::cout << (e->remove(243)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
*c=*b;
std::cout << (c->remove(401)) << std::endl;
*d=*b;
*b=*b;
std::cout << (b->remove(217)) << std::endl;
*e=*d;
std::cout << (d->remove(299)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
a->printPretty();
d->printPretty();
*d=*b;
std::cout << (d->insert(299)) << std::endl;
*d=*e;
std::cout << (b->remove(299)) << std::endl;
std::cout << (e->insert(273)) << std::endl;
a->printPretty();
std::cout << (b->remove(34)) << std::endl;
*d=*d;
std::cout << (b->remove(297)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (d->remove(57)) << std::endl;
*a=*d;
std::cout << (d->remove(217)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (e->remove(200)) << std::endl;
d->printPretty();
std::cout << (c->insert(297)) << std::endl;
*a=*c;
*c=*e;
std::cout << (e->insert(217)) << std::endl;
*b=*e;
std::cout << (a->remove(217)) << std::endl;
b->printPretty();
std::cout << (c->insert(75)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (a->insert(185)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
*e=*d;
*a=*c;
std::cout << (e->remove(299)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
*a=*c;
std::cout << (c->insert(100)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (b->remove(297)) << std::endl;
c->printPretty();
std::cout << (b->insert(24)) << std::endl;
std::cout << (a->insert(31)) << std::endl;
*e=*e;
std::cout << (c->remove(386)) << std::endl;
b->printPretty();
std::cout << (d->remove(35)) << std::endl;
std::cout << (d->remove(366)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(297)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (a->insert(400)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (c->insert(324)) << std::endl;
*a=*e;
*c=*d;
*d=*d;
std::cout << (d->remove(297)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->insert(378)) << std::endl;
a->printPretty();
std::cout << (c->remove(297)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (a->remove(378)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
*b=*c;
std::cout << (c->remove(279)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
*b=*b;
*c=*b;
a->printPretty();
std::cout << (d->insert(60)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
e->printPretty();
std::cout << (b->insert(425)) << std::endl;
c->printPretty();
std::cout << (c->insert(157)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
e->printPretty();
std::cout << (b->remove(408)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
*a=*b;
std::cout << (d->insert(455)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
*b=*c;
std::cout << (b->insert(157)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
*b=*e;
std::cout << (d->remove(455)) << std::endl;
*a=*c;
*a=*a;
b->printPretty();
std::cout << (a->remove(195)) << std::endl;
*e=*c;
std::cout << (c->insert(292)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
b->printPretty();
*b=*b;
d->printPretty();
*c=*d;
std::cout << (b->remove(189)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
*c=*a;
std::cout << (c->insert(277)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
*b=*d;
*d=*c;
std::cout << (c->remove(153)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*c=*b;
*a=*d;
std::cout << (b->remove(197)) << std::endl;
std::cout << (a->remove(494)) << std::endl;
*c=*a;
std::cout << (a->remove(277)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
a->printPretty();
*b=*c;
*c=*d;
std::cout << (b->insert(277)) << std::endl;
b->printPretty();
*b=*d;
d->printPretty();
d->printPretty();
std::cout << (d->insert(277)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
*e=*d;
std::cout << (a->insert(219)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(85)) << std::endl;
*d=*b;
std::cout << (e->insert(127)) << std::endl;
*d=*c;
std::cout << (c->insert(128)) << std::endl;
*d=*e;
b->printPretty();
*a=*b;
d->printPretty();
std::cout << (d->remove(265)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(181)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
*d=*e;
std::cout << (c->insert(494)) << std::endl;
*b=*c;
std::cout << (c->insert(128)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
*c=*d;
std::cout << (c->insert(277)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (e->insert(187)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
*b=*a;
std::cout << (a->insert(494)) << std::endl;
a->printPretty();
*e=*b;
b->printPretty();
c->printPretty();
std::cout << (d->remove(494)) << std::endl;
*a=*b;
std::cout << (a->remove(468)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
*b=*a;
std::cout << (e->insert(335)) << std::endl;
b->printPretty();
c->printPretty();
c->printPretty();
*d=*c;
std::cout << (c->remove(351)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
a->printPretty();
std::cout << (a->insert(494)) << std::endl;
std::cout << (d->insert(219)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (b->insert(257)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
*a=*d;
*d=*d;
std::cout << (d->insert(277)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
*b=*b;
*b=*a;
std::cout << (c->remove(97)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->remove(381)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (e->remove(423)) << std::endl;
b->printPretty();
std::cout << (a->insert(367)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (b->remove(453)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->remove(350)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (e->remove(269)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
*a=*d;
*c=*a;
std::cout << (a->insert(127)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(477)) << std::endl;
e->printPretty();
std::cout << (a->remove(43)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (e->insert(176)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
e->printPretty();
std::cout << (e->insert(277)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
*a=*d;
std::cout << (a->insert(64)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->insert(89)) << std::endl;
std::cout << (a->insert(349)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
*a=*b;
std::cout << (e->insert(277)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (e->remove(494)) << std::endl;
e->printPretty();
d->printPretty();
*b=*e;
std::cout << (a->remove(470)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
e->printPretty();
std::cout << (d->insert(277)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
*b=*e;
a->printPretty();
*e=*a;
std::cout << (b->remove(245)) << std::endl;
c->printPretty();
std::cout << (d->insert(415)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (c->insert(123)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
*a=*a;
std::cout << (a->remove(127)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
b->printPretty();
std::cout << (d->remove(127)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
b->printPretty();
*c=*d;
*b=*b;
std::cout << (b->remove(309)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
std::cout << (d->insert(135)) << std::endl;
e->printPretty();
std::cout << (c->insert(432)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->insert(198)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
*c=*b;
std::cout << (c->remove(227)) << std::endl;
std::cout << (e->remove(94)) << std::endl;
std::cout << (e->remove(306)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (e->insert(153)) << std::endl;
*d=*a;
*e=*e;
*e=*e;
std::cout << (b->remove(43)) << std::endl;
std::cout << (e->insert(256)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (e->remove(99)) << std::endl;
e->printPretty();
std::cout << (a->insert(315)) << std::endl;
std::cout << (b->remove(325)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (c->insert(469)) << std::endl;
e->printPretty();
std::cout << (c->insert(5)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
*b=*a;
*c=*b;
std::cout << (d->insert(101)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
std::cout << (e->remove(227)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
*a=*b;
std::cout << (d->remove(196)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
a->printPretty();
std::cout << (e->remove(256)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
*b=*e;
std::cout << (c->insert(47)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
*d=*c;
std::cout << (b->remove(192)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
*d=*e;
std::cout << (b->remove(53)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
*d=*a;
std::cout << (b->remove(248)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (c->remove(330)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
*b=*d;
std::cout << (e->insert(404)) << std::endl;
std::cout << (a->insert(417)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
*c=*d;
*a=*e;
std::cout << (e->insert(159)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
d->printPretty();
std::cout << (b->remove(299)) << std::endl;
*a=*c;
std::cout << (e->remove(159)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (b->insert(334)) << std::endl;
c->printPretty();
std::cout << (b->remove(196)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
e->printPretty();
std::cout << (b->insert(478)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
c->printPretty();
std::cout << (e->insert(345)) << std::endl;
*b=*d;
std::cout << (a->remove(236)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
*c=*a;
std::cout << (e->insert(298)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (a->remove(402)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
*b=*c;
std::cout << (d->insert(36)) << std::endl;
e->printPretty();
c->printPretty();
*e=*c;
std::cout << (d->remove(36)) << std::endl;
*c=*b;
*a=*b;
*c=*c;
a->printPretty();
std::cout << (b->insert(227)) << std::endl;
d->printPretty();
c->printPretty();
b->printPretty();
std::cout << (b->remove(227)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
c->printPretty();
std::cout << (c->remove(222)) << std::endl;
c->printPretty();
std::cout << (d->insert(247)) << std::endl;
std::cout << (d->remove(247)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (c->insert(387)) << std::endl;
e->printPretty();
std::cout << (a->remove(410)) << std::endl;
std::cout << (b->remove(392)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
d->printPretty();
std::cout << (a->remove(179)) << std::endl;
*c=*b;
std::cout << (d->insert(76)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
e->printPretty();
std::cout << (e->insert(10)) << std::endl;
a->printPretty();
std::cout << (c->remove(56)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
return 0;
}
