#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
*a=*b;
std::cout << (a->insert(127)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (a->insert(355)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
std::cout << (a->insert(176)) << std::endl;
*b=*a;
std::cout << (b->insert(483)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->remove(474)) << std::endl;
a->printPretty();
std::cout << (b->insert(75)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->remove(75)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->remove(176)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
a->printPretty();
e->printPretty();
std::cout << (b->insert(160)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
b->printPretty();
std::cout << (b->insert(82)) << std::endl;
*d=*a;
std::cout << (d->insert(127)) << std::endl;
std::cout << (b->remove(355)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
std::cout << (a->remove(58)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (b->insert(200)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
d->printPretty();
std::cout << (a->insert(127)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (a->insert(160)) << std::endl;
std::cout << (a->insert(400)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
*b=*b;
std::cout << (b->insert(417)) << std::endl;
std::cout << (a->remove(355)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->remove(376)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
*d=*d;
std::cout << (b->insert(386)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (b->remove(500)) << std::endl;
c->printPretty();
std::cout << (d->insert(264)) << std::endl;
c->printPretty();
std::cout << (c->insert(343)) << std::endl;
std::cout << (a->remove(100)) << std::endl;
*a=*d;
*c=*c;
b->printPretty();
a->printPretty();
std::cout << (d->insert(394)) << std::endl;
std::cout << (d->remove(315)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
*d=*d;
std::cout << (b->insert(134)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
a->printPretty();
std::cout << (c->insert(343)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
c->printPretty();
std::cout << (e->remove(206)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
b->printPretty();
std::cout << (a->insert(481)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
*a=*a;
*c=*d;
std::cout << (d->insert(471)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (c->insert(157)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
c->printPretty();
std::cout << (a->remove(82)) << std::endl;
c->printPretty();
std::cout << (c->insert(491)) << std::endl;
b->printPretty();
std::cout << (a->insert(333)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (c->remove(174)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (d->remove(151)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
std::cout << (b->remove(408)) << std::endl;
*a=*b;
std::cout << (c->remove(137)) << std::endl;
*a=*b;
std::cout << (d->remove(471)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (e->insert(390)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
*a=*d;
e->printPretty();
a->printPretty();
std::cout << (e->remove(390)) << std::endl;
std::cout << (b->remove(82)) << std::endl;
a->printPretty();
std::cout << (b->remove(417)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (c->insert(400)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
b->printPretty();
std::cout << (a->insert(388)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
d->printPretty();
std::cout << (b->remove(176)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
std::cout << (a->remove(264)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
*a=*c;
*e=*a;
std::cout << (c->insert(379)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (e->insert(476)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
std::cout << (c->remove(420)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
a->printPretty();
std::cout << (d->insert(157)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
*c=*e;
std::cout << (a->remove(171)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (c->insert(98)) << std::endl;
a->printPretty();
std::cout << (e->insert(186)) << std::endl;
std::cout << (a->insert(200)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
*a=*b;
std::cout << (b->insert(450)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (e->remove(491)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
*e=*e;
std::cout << (c->remove(148)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (a->remove(127)) << std::endl;
std::cout << (a->insert(207)) << std::endl;
*d=*c;
std::cout << (b->insert(464)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
std::cout << (a->insert(207)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (a->insert(386)) << std::endl;
std::cout << (e->insert(400)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
*d=*e;
std::cout << (c->remove(469)) << std::endl;
*e=*a;
std::cout << (e->insert(386)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
*a=*d;
*d=*a;
std::cout << (a->insert(186)) << std::endl;
*e=*c;
std::cout << (d->remove(271)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (d->remove(455)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (e->insert(259)) << std::endl;
std::cout << (c->insert(400)) << std::endl;
b->printPretty();
*d=*b;
a->printPretty();
std::cout << (b->remove(65)) << std::endl;
*d=*d;
*b=*b;
std::cout << (e->remove(448)) << std::endl;
*a=*d;
std::cout << (a->remove(247)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
*d=*e;
std::cout << (e->insert(352)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (b->remove(186)) << std::endl;
*c=*d;
std::cout << (d->insert(374)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
a->printPretty();
std::cout << (d->remove(400)) << std::endl;
std::cout << (a->insert(65)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (a->remove(400)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
e->printPretty();
std::cout << (a->remove(319)) << std::endl;
*b=*e;
std::cout << (c->insert(191)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
*d=*b;
std::cout << (d->insert(24)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
*c=*a;
std::cout << (a->insert(473)) << std::endl;
std::cout << (d->insert(491)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
*d=*d;
std::cout << (a->insert(29)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (d->insert(354)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
a->printPretty();
std::cout << (c->remove(202)) << std::endl;
*d=*e;
std::cout << (d->remove(11)) << std::endl;
std::cout << (d->remove(67)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->insert(263)) << std::endl;
*c=*a;
std::cout << (b->insert(191)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (b->remove(395)) << std::endl;
*c=*c;
*c=*d;
std::cout << (c->insert(408)) << std::endl;
*a=*a;
*b=*d;
std::cout << (a->insert(169)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (c->remove(376)) << std::endl;
std::cout << (a->remove(144)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (a->remove(300)) << std::endl;
d->printPretty();
std::cout << (c->insert(473)) << std::endl;
d->printPretty();
std::cout << (d->remove(408)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
e->printPretty();
std::cout << (c->insert(92)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (b->insert(64)) << std::endl;
std::cout << (b->remove(192)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
*a=*a;
std::cout << (e->insert(100)) << std::endl;
*c=*d;
*c=*c;
std::cout << (a->insert(76)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (a->insert(169)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (c->insert(185)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
*c=*d;
std::cout << (e->insert(380)) << std::endl;
std::cout << (a->insert(247)) << std::endl;
*e=*a;
std::cout << (a->remove(52)) << std::endl;
a->printPretty();
std::cout << (d->insert(191)) << std::endl;
e->printPretty();
std::cout << (c->insert(461)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (a->insert(247)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
*e=*d;
std::cout << (e->remove(473)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
c->printPretty();
std::cout << (c->remove(77)) << std::endl;
*b=*e;
*e=*c;
std::cout << (b->insert(482)) << std::endl;
std::cout << (d->remove(65)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (a->insert(337)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->insert(473)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
c->printPretty();
std::cout << (c->remove(29)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
e->printPretty();
std::cout << (d->remove(464)) << std::endl;
*e=*b;
std::cout << (e->insert(247)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->insert(43)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
std::cout << (e->remove(416)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (d->remove(31)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
c->printPretty();
std::cout << (b->remove(37)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
d->printPretty();
std::cout << (e->insert(386)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
*a=*d;
std::cout << (c->insert(148)) << std::endl;
*a=*e;
std::cout << (b->insert(474)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (d->insert(79)) << std::endl;
*a=*c;
std::cout << (c->remove(464)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(478)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (c->remove(79)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (b->remove(474)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
*a=*d;
std::cout << (a->insert(38)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
c->printPretty();
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (e->remove(42)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
b->printPretty();
std::cout << (e->remove(169)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (a->insert(473)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (c->remove(359)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(247)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->remove(358)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
b->printPretty();
std::cout << (b->insert(79)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
d->printPretty();
std::cout << (b->remove(117)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (c->remove(79)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (e->remove(386)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
*b=*a;
std::cout << (b->insert(439)) << std::endl;
c->printPretty();
std::cout << (d->insert(399)) << std::endl;
d->printPretty();
std::cout << (b->insert(148)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
c->printPretty();
std::cout << (d->remove(77)) << std::endl;
b->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->remove(112)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (c->remove(148)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
*d=*d;
std::cout << (d->remove(235)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (c->insert(222)) << std::endl;
d->printPretty();
std::cout << (d->remove(139)) << std::endl;
std::cout << (e->remove(469)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
*d=*e;
std::cout << (b->remove(439)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
d->printPretty();
std::cout << (b->remove(233)) << std::endl;
*b=*b;
std::cout << (b->remove(378)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
std::cout << (a->insert(144)) << std::endl;
*b=*d;
std::cout << (c->insert(407)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->insert(86)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
e->printPretty();
std::cout << (b->insert(357)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
d->printPretty();
std::cout << (d->remove(328)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
*b=*a;
*a=*e;
std::cout << (a->insert(26)) << std::endl;
*d=*a;
std::cout << (d->insert(388)) << std::endl;
*e=*e;
std::cout << (c->insert(176)) << std::endl;
*d=*c;
*b=*e;
std::cout << (c->remove(14)) << std::endl;
std::cout << (a->insert(26)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
*a=*c;
std::cout << (e->insert(264)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (b->remove(224)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
*c=*d;
std::cout << (c->insert(473)) << std::endl;
a->printPretty();
std::cout << (a->insert(148)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->remove(264)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->insert(97)) << std::endl;
*d=*e;
std::cout << (b->remove(109)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (b->remove(247)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
b->printPretty();
e->printPretty();
*e=*e;
std::cout << (b->remove(416)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
*a=*e;
*b=*a;
std::cout << (c->remove(13)) << std::endl;
b->printPretty();
*e=*d;
*e=*d;
*c=*e;
std::cout << (c->remove(247)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
e->printPretty();
std::cout << (a->remove(254)) << std::endl;
a->printPretty();
std::cout << (d->insert(357)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
*c=*c;
a->printPretty();
b->printPretty();
std::cout << (a->insert(433)) << std::endl;
*d=*b;
std::cout << (b->insert(264)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (c->remove(374)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (a->remove(288)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (b->remove(113)) << std::endl;
b->printPretty();
std::cout << (a->remove(399)) << std::endl;
a->printPretty();
std::cout << (d->insert(408)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
b->printPretty();
std::cout << (d->remove(284)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
*c=*d;
std::cout << (b->remove(148)) << std::endl;
*b=*e;
std::cout << (d->remove(264)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
d->printPretty();
e->printPretty();
*e=*a;
*e=*a;
std::cout << (a->remove(433)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
*a=*b;
*d=*e;
std::cout << (c->insert(264)) << std::endl;
std::cout << (b->remove(113)) << std::endl;
*c=*d;
std::cout << (b->insert(357)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->insert(433)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
*e=*a;
std::cout << (e->insert(74)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
e->printPretty();
std::cout << (c->insert(113)) << std::endl;
a->printPretty();
std::cout << (d->remove(34)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
*d=*b;
std::cout << (a->remove(212)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
std::cout << (b->remove(358)) << std::endl;
std::cout << (b->insert(292)) << std::endl;
d->printPretty();
*b=*d;
d->printPretty();
std::cout << (d->insert(61)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
*c=*c;
std::cout << (a->insert(467)) << std::endl;
*d=*a;
*e=*c;
d->printPretty();
b->printPretty();
std::cout << (a->remove(458)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(37)) << std::endl;
*d=*c;
*c=*b;
std::cout << (d->remove(86)) << std::endl;
std::cout << (d->insert(248)) << std::endl;
std::cout << (a->insert(405)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->remove(34)) << std::endl;
std::cout << (b->remove(187)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(445)) << std::endl;
*a=*d;
std::cout << (a->remove(298)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
*b=*d;
std::cout << (b->remove(264)) << std::endl;
*b=*a;
std::cout << (c->insert(139)) << std::endl;
*a=*c;
std::cout << (a->insert(269)) << std::endl;
std::cout << (c->insert(34)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
a->printPretty();
std::cout << (e->remove(143)) << std::endl;
*a=*c;
std::cout << (c->remove(455)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
b->printPretty();
std::cout << (d->insert(34)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
std::cout << (d->insert(278)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
std::cout << (d->insert(278)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
*b=*b;
std::cout << (c->remove(264)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (b->insert(408)) << std::endl;
b->printPretty();
std::cout << (d->remove(283)) << std::endl;
d->printPretty();
return 0;
}
